### PR TITLE
CONTRIBUTING.md missing at that place

### PR DESCRIPTION
**Pull request by PallHaraldsson**
I'm NOT sure it's best to point to this specific file (and not e.g. copy it to the place that was pointed to). Also problematic if forked (possible to have a relative path?) See here: https://github.com/dashpay/dash/pull/840#issuecomment-222540862
[skip ci]

### CODE REVIEW

**Comment by UdjinM6** [comment]
Thanks!
However there is `v0.12.1.1` tag is wrong and I guess was created by an accident. Should be `v0.12.1.x`. Please update url there.

PS. Also please note that we don't accept PRs to master. I changed base to `v0.12.0.x` for this one but just be aware next time. ;)

**Comment by PallHaraldsson** [comment]
@UdjinM6 I think you asked for the next commit (and not to v0.13.0.x). I'm not sure there will be a next time.. I just happened to stumble on this repo, I mostly to PRs to Julia (and then master, didn't think you should/could in some cases do otherwise [through GitHub]).

**Comment by UdjinM6** [comment]
Thanks!

yep, notes about v0.13 was for @schinzelh only, sorry for confusion :)

**Comment by schinzelh** [comment]
Yeah, you can drop the 0.13.0.0 tag - not sure on the 0.13.0.x branch though - i guess it got deprecated by 0.12.1/0.12.2

ping @evan82

**Pull request merged**
