### PR TITLE
docs: update license year range to 2024

### PR DESCRIPTION
**Pull request by knst**
## What was done?
Happy new year and happy new lunar year!
2024 is here and 20.1 is coming.

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Should run https://github.com/dashpay/dash/blob/develop/contrib/devtools/copyright_header.py as well

**Comment by PastaPastaPasta** [comment]
Removed "backport candidate" as that is (currently) for v20.0.5 theoretically; not v20.1; develop is stull v20.1

**Comment by knst** [comment]
> Removed "backport candidate" as that is (currently) for v20.0.5 theoretically; not v20.1; develop is still v20.1

I added a label for possible v20.0.5 if any between release would be done

**Comment by PastaPastaPasta** [comment]
> > Removed "backport candidate" as that is (currently) for v20.0.5 theoretically; not v20.1; develop is still v20.1
> 
> I added a label for possible v20.0.5 if any between release would be done

hmmm yeah; but I don't think this is worth backporting even if we do need v20.0.5, unless you want to do a new PR that runs the copyright bump instead of in this PR

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Comment by knst** [comment]
> unless you want to do a new PR that runs the copyright bump instead of in this PR

https://github.com/dashpay/dash/pull/5892

A notice for next year: copyright year for sources should be bumped at the end of year next time; license year is preferred to bump after NY

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
