### PR TITLE
Backport spellcheck

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Pls see https://github.com/UdjinM6/dash/commits/pr4276

**Comment by PastaPastaPasta** [comment]
Cherry picked all... https://github.com/dashpay/dash/pull/4276/commits/699038589deec32d4c7f73faf39e8f96ef41f2ad slightly concerns me. Are these all in dash specific code or will this cause conflicts?

**Comment by UdjinM6** [comment]
> Cherry picked all... [6990385](https://github.com/dashpay/dash/commit/699038589deec32d4c7f73faf39e8f96ef41f2ad) slightly concerns me. Are these all in dash specific code or will this cause conflicts? (also rebased on develop)

I just ran the script locally and fixed most of them. Some are not Dash related, that's true but it should be trivial to resolve potential merge conflicts I think ( /hope 😇 )

**Comment by PastaPastaPasta** [comment]
Yeah, I figured that's what you did.... 

I guess that should be fine...

**Review by UdjinM6 — DISMISSED** [review]
LGTM, utACK

**Comment by PastaPastaPasta** [comment]
rebased

**Review by UdjinM6 — APPROVED** [review]
re-utACK

**Pull request merged**
