### PR TITLE
Change default datadir

### PR DESCRIPTION
**Pull request by UdjinM6**
Change default datadir from `Dash(Win,Mac)/.dash(Linux)` to `DashCore(Win,Mac)/.dashcore(Linux)` as discussed in #898 
Changing package/dist name/user/settings will probably follow next in another PR (could blow up things, will require a lot more attention imo).

### CODE REVIEW

**Comment by crowning-** [comment]
Why .dashcore and not .DashCore on Linux?

**Comment by schinzelh** [comment]
I hate camelcase in directory names :-)

**Comment by crowning-** [comment]
But having it the same for all OS will reduce the number of support questions.

Either all lowercase or all CamelCase IMO.

**Comment by UdjinM6** [comment]
IMO it's common practice to have all lowercase on Unix/Linux systems (few exceptions on recent Ubuntu's though) and to have CamelCase on Windows and Mac. I would stick with that.

**Comment by crowning-** [comment]
Okay, make it .dashcore for Unix, and send me a beer for each time someone's gonna doin git wrong :beer:

**Pull request merged**
