### PR TITLE
Update default private send mixing from 2 to 4

### PR DESCRIPTION
**Pull request by PaulieD**

### CODE REVIEW

**Comment by akijuh** [comment]
I think also 
**DEFAULT_PRIVATESEND_MULTISESSION**  = false; 
should be enabled by default.

@UdjinM6

**Comment by akijuh** [comment]
@PaulieD None, but its mandatory for mixing speed.

**Comment by UdjinM6** [comment]
I think it's ok to bump this in 12.3. @codablock @nmarley  ?

@akijuh re DEFAULT_PRIVATESEND_MULTISESSION: it's `false` for _normal_ users due to the speed it consumes keys from keypool. There is a GUI message which gives some info how to enable this mode and a warning. I wouldn't turn this ON by default until we have proper HD wallet implementation.

@PaulieD you need to rebase this on top of `develop`, force push and switch the branch to `develop` as well in github GUI.

**Comment by akijuh** [comment]
@UdjinM6  It is ok to me, but i bet most users do not touch settings, and wallet also will generate more keys if needed.

**Comment by PaulieD** [comment]
Rebased https://github.com/dashpay/dash/pull/2066

**Comment by nmarley** [comment]
@UdjinM6 I would prefer not to merge this in 12.3 TBH. You probably know the effects this will have better than anyone else, but I don't like slipping in non-fixes (e.g. features/improvements) that haven't been well-tested and since we've already set a freeze.

I also don't think there's been enough discussion to warrant this -- there could be others who don't agree w/this logic (I personally don't think this is a valid change).

**Comment by PaulieD** [comment]
I believe it is now rebased properly. Please inform me if there is any more I need to do @UdjinM6 @nmarley

**Comment by nmarley** [comment]
@PaulieD Looks like your "patch-2" branch is still based off master. I'm not sure what tools you use, but if you use the command line, something like:

```
git checkout patch-2
git rebase develop
git push --force origin patch-2
```

... should do it (depending on if you have other changes, you might need to do a `git stash` first.

**Comment by UdjinM6** [comment]
@akijuh yes, wallet will generate new keys but the point is that this is pointless if user has no backup strategy - if anything goes wrong old autobackups are going to be overwritten rather quickly, so I'd prefer to make it explicitly clear and require user to manually switch to this mode. Again, this shouldn't be an issue with HD wallets (they can be recovered from seed at any state) but we are not there yet.

@nmarley `DEFAULT_PRIVATESEND_ROUNDS` will only affect initial settings for new users and they can always tweak it back down to `MIN_PRIVATESEND_ROUNDS` (2) from settings, so this _should_ be safe. But I agree, let's make no exceptions and postpone this one too.

**Comment by PaulieD** [comment]
In an attempt to resolve the conflicts, I merged develop branch into my patch branch, however that now means this pr has over 1000 commits attached to it. My apologies, still getting the hang of this stuff. If anyone has any advice of how to handle this, keeping in mind this was done through github.com and not the cli. The easy alternative I can think of is creating a second PR which was always based on the develop branch.

**Comment by nmarley** [comment]
> I'm unsure how to rebase outside of cli.

Just git clone your repo and switch to the branch. Honestly just do this (you need to have your SSH key setup on Github):

```
git clone https://github.com/PaulieD/dash.git && cd dash
git checkout -b patch-2 develop
# make your 1-line change here
git push -f origin patch-2
```

**Comment by PaulieD** [comment]
@nmarley you are completely right. I need to learn about git more. I've added that to the million and one things to do XD.

The line `git checkout -b patch-2 develop` is giving a fatal error. Saying that patch-2 has already been created. Sorry about my lack of ability in regards to git. Learning something new everyday.

**Comment by nmarley** [comment]
No worries @PaulieD , this is something that can be fixed. Give me a few hours and I can record a screen cast to show you what I mean.

update: Well... never mind. Looks like you deleted your original repo. :/

**Comment by nmarley** [comment]
Sorry, this is a mess now. I'm closing this.

**Pull request closed without merging**
