### PR TITLE
V0.12.1.x - dashified the about icons

### PR DESCRIPTION
**Pull request by taw00**
Swapped out some icons. For example, open dash-qt, go to "help" and "about dash" and note the "bitcoin" icon there now. This fixes that.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Nicely spotted, thanks!

Can you squash commits into one and push the clean one (-f) again pls?

**Comment by taw00** [comment]
Googling. Not sure how to do that. Standby.

**Comment by taw00** [comment]
Eegad... my repo is all hosed now. Hmm.

**Comment by taw00** [comment]
Fixed... with @moocowmoo's help cuz I am git-challenged.

**Comment by UdjinM6** [comment]
Looks good now, ACK a9a9c9a :)

**Comment by crowning-** [comment]
Unfortunately this change will (most probably) be superseeded by https://github.com/crowning-/dash/tree/UI_Icons because of https://github.com/dashpay/dash/pull/762.

Those black/transparent icons introduced by the Bitcoin-devs are almost invisible on some Linux flavors, and don't look good on other operating systems depending on the OS-version and/or chosen UI-theme of the operating system. No idea why they did this, especially why they did this only for a couple of icons and not ALL of them. Makes the look quite inconsistent.

I will create a pull request later today (with screenshots of the results) when my testing for OSX is done. We can discuss things there...

**Comment by UdjinM6** [comment]
I agree with @crowning- - black icons look weird on default ubuntu scheme :( If I broke smth while Iwas merging bitcoin source and icons actually look good on linux for bitcoin - please, let me know. Otherwise I would prefer #764 over this one.

**Comment by evan82** [comment]
Closing due to duplication with #764

**Pull request closed without merging**
