### PR TITLE
fix: improved reliability of functional tests that activates dip24

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Functional tests in CI and locally often fails without a good reason (pretty randomly)

## What was done?
It was re-implemented `get_recovered_sig` and updated `create_raw_tx` for better selection/change output.

## How Has This Been Tested?
Run functional times with bug amount of parrallel jobs:
```
test/functional/test_runner.py -j 20 feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py  feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py
```
Without these changes usually 2-3 instance fails.
With these changes all failures happened only for `p2p_addrv2_relay.py` and `mempool_unbroadcast.py`. Beside feature_llmq_is_conflicts.py improved stability of `interface_zmq_dash.py` also.

## Breaking Changes
No breaking changes

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by knst** [comment]
```
> feature_llmq_hpmn.py                  | ✖ Failed  | 1802 s
```

seems it didn't help

**Comment by PastaPastaPasta** [comment]
No thoughts 🤷 I don't see why this changes anything. Up to Udjin

**Comment by UdjinM6** [comment]
Running `./test/functional/test_runner.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py`:
develop:
```
feature_llmq_is_cl_conflicts.py | ✓ Passed  | 192 s
feature_llmq_is_cl_conflicts.py | ✓ Passed  | 199 s
feature_llmq_is_cl_conflicts.py | ✓ Passed  | 200 s
feature_llmq_is_cl_conflicts.py | ✓ Passed  | 207 s

ALL                             | ✓ Passed  | 798 s (accumulated) 
Runtime: 207 s

```
this PR:
```
feature_llmq_is_cl_conflicts.py | ✓ Passed  | 194 s
feature_llmq_is_cl_conflicts.py | ✓ Passed  | 199 s
feature_llmq_is_cl_conflicts.py | ✓ Passed  | 201 s
feature_llmq_is_cl_conflicts.py | ✓ Passed  | 202 s

ALL                             | ✓ Passed  | 796 s (accumulated) 
Runtime: 202 s
```

Basically, no difference. Also, I agree with @PastaPastaPasta , this patch _shouldn't_ affect tests behaviour after `Activated DIP0024 at height:xxx`. But if it _does_ for you then smth could be actually broken and needs to be fixed, not skipped. Or maybe you just need to lower `-j` - you could be triggering OOM-killer or smth.

**Comment by knst** [comment]
> But if it does for you then smth could be actually broken and needs to be fixed, not skipped. Or maybe you just need to lower -j - you could be triggering OOM-killer or smth.

Probably you are right about an under-lying issue, but I can't figure out what's a reason. I have 2 testing environment laptop (40Gb ram + 16 cores) and PC (32Gb RAM + 24 cores) and problem reproduced in laptop with bigger amount of RAM but smaller amount of CPU. So, I assume, that it's not OOM-killer but probably something else.

 - This PR:
```
$ git checkout c16fa61
$ test/functional/test_runner.py -j 20 feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py  feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py
<all 20 succeed>
```
 - A commit from develop:
```
$ git checkout 74fabcb1b9e5133b579717acace175338e729130
$ test/functional/test_runner.py -j 20 feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py  feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py feature_llmq_is_cl_conflicts.py
1st failure:
2023-04-17T11:47:06.620000Z TestFramework (INFO): Wait for dip0024 activation
2023-04-17T11:47:51.467000Z TestFramework (INFO): Activated DIP0024 at height:902
2023-04-17T11:48:02.043000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 148, in main
    self.run_test()
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_is_cl_conflicts.py", line 78, in run_test
    self.test_chainlock_overrides_islock_overrides_nonchainlock(False)
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_is_cl_conflicts.py", line 214, in test_chainlock_overrides_islock_overrides_nonchainlock
    islock = self.create_islock(rawtx2, deterministic)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 1469, in create_islock
    rec_sig = self.get_recovered_sig(request_id, message_hash, node=quorum_member.node, llmq_type=llmq_type)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 1915, in get_recovered_sig
    assert False
AssertionError
-------------
2nd failure:
2023-04-17T11:46:29.080000Z TestFramework (INFO): New quorum: height=216, quorumHash=496bbebef32e4e38fa71c48acfafaa1d5ccde556da7ddc7ed4717e42e78b64dc, quorumIndex=0, minedBlock=6d6f86b6be658de1b021812d9fa6467502bb097673fdcefd25992424d6e7e770
2023-04-17T11:46:43.153000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 148, in main
    self.run_test()
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_is_cl_conflicts.py", line 74, in run_test
    self.test_chainlock_overrides_islock(True, True)
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_is_cl_conflicts.py", line 91, in test_chainlock_overrides_islock
    rawtx1 = self.create_raw_tx(self.nodes[0], self.nodes[0], 1, 1, 100)['hex']
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 1434, in create_raw_tx
    rawtx = node_from.createrawtransaction(inputs, outputs)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Amount out of range (-3)
2023-04-17T11:46:43.654000Z TestFramework (INFO): Stopping nodes
------------
3rd failure:
2023-04-17T11:47:52.668000Z TestFramework (INFO): Activated DIP0024 at height:902
2023-04-17T11:48:03.120000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 148, in main
    self.run_test()
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_is_cl_conflicts.py", line 78, in run_test
    self.test_chainlock_overrides_islock_overrides_nonchainlock(False)
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_is_cl_conflicts.py", line 214, in test_chainlock_overrides_islock_overrides_nonchainlock
    islock = self.create_islock(rawtx2, deterministic)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 1469, in create_islock
    rec_sig = self.get_recovered_sig(request_id, message_hash, node=quorum_member.node, llmq_type=llmq_type)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 1915, in get_recovered_sig
    assert False
AssertionError
2023-04-17T11:48:03.621000Z TestFramework (INFO): Stopping nodes

<total failed 3/20>
```

**Comment by UdjinM6** [comment]
I can't reproduce any failures even with `-j 40` 🤷‍♂️ 

@knst pls try running it with db38a232 and ba250184

**Comment by knst** [comment]
@UdjinM6 I re-wrote `get_recovered_sig`, please, help to review it.

With your changes fr selection/change output and the new `get_recovered_sig` it works more reliable at my laptop now.

**Comment by UdjinM6** [comment]
pls see 896f0763d8

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
