### PR TITLE
Backport remaining "candidates" from develop to v0.15.x

### PR DESCRIPTION
**Pull request by UdjinM6**
And update release notes once again.

### CODE REVIEW

**Comment by codablock** [comment]
@UdjinM6 you want to reuse this PR to bring in the new backport candidates as well?

**Comment by UdjinM6** [comment]
@codablock Yep, will add them once they are merged.

**Comment by UdjinM6** [comment]
Oooops, I just force-pushed it to trigger Travis build again 🙈

**Comment by UdjinM6** [comment]
FYI: Removed `backport-candidate-15.x` label from corresponding PRs.

**Pull request merged**
