### PR TITLE
Update immer to ed9bdae5ad174bd6248383cce8c5c135fec7ff82

### PR DESCRIPTION
**Pull request by UdjinM6**
Had a report that dashd crashes on FreeBSD due to a bug in immer. Bumping it to latest master fixes the issue.

This should be backported to 0.13.

EDIT: fyi, here is the script to build Dash Core on FreeBSD https://gist.github.com/UdjinM6/9242ab97fb819b77d07fbcbdcc074969 might be a good start for corresponding doc update ;)

### CODE REVIEW

**Comment by codablock** [comment]
Cool, someone (maybe the same person) reported the same issue to me. Will review the changes on Monday.

For the backporting to v13, I'd suggest to only backport https://github.com/arximboldi/immer/commit/dcb9823835f4c9019ceeb8461e39b7752caf77ae instead of directly going to master, as I feel the risk of this would otherwise be too high so shortly before release.

**Comment by UdjinM6** [comment]
This one https://github.com/arximboldi/immer/commit/c89819df92191d6969a6a22c88c72943b8e25016 looks like a good candidate though. At least bumping to it fixes the issue too and changes seems to be pretty small, see #2626

**Comment by MrDefacto** [comment]
I can confirm that this commit resolves issue that i've reported. GJ

**Comment by UdjinM6** [comment]
Will be superseded by #2630 , closing.

**Pull request closed without merging**
