### PR TITLE
rpc: Serialize in getblock without cs_main

### PR DESCRIPTION
**Pull request by IntegralTeam**
Backported from bitcoin
- https://github.com/bitcoin/bitcoin/pull/15932
- https://github.com/bitcoin/bitcoin/pull/12151

### CODE REVIEW

**Comment by UdjinM6** [comment]
Thanks for submitting. This could be helpful (the less `cs_main` there are the better) however I see at least a couple of issues with these backports:
1. They are incomplete (not all commits are included);
2. Some intermediary PRs are missing it seems.

This means that we'll get merge conflicts in other backports if we try to catchup with recent bitcoin releases after merging this one and I'm not sure if this fix is that critical to ignore these issues.

**Comment by PastaPastaPasta** [comment]
NACK w/o sufficient reason to backport these out of order. I'll get there eventually in my backporting

**Comment by fanatid** [comment]
@PastaPastaPasta can you say approximate version of dash where this PRs will be backported? ETA for this version? Thanks!

**Comment by PastaPastaPasta** [comment]
I'm currently about half way done with backporting 0.15, after that will be 0.16. Those PRs are neither in 0.15 or 0.16 so it will likely be a decent while. Is there any reason why you want them in so bad? if there is a good reason it might make sense to backport out of order

**Comment by fanatid** [comment]
There is no big reason for out of order backport since dash blocks/database smaller compare to bitcoin, but it would be nice to have this feature for service on which I work.

**Pull request closed without merging**
