### PR TITLE
backport: Merge bitcoin#22860

### PR DESCRIPTION
**Pull request by vijaydasmp**
bitcoin backports

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 , requesting for review

**Review by UdjinM6 — APPROVED** [review]
utACK e352a43d0fa2eee3e29da651add9975e89d1f0de

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta , requesting review

**Comment by vijaydasmp** [comment]
Hello @knst , requestibg review

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta , requesting review

**Comment by UdjinM6** [comment]
Needs rebase to fix `Check Merge Fast-Forward Only`

**Pull request merged**
