### PR TITLE
Fix qt crash

### PR DESCRIPTION
**Pull request by UdjinM6**
Fixes `dash-qt --version` (`--help` etc) crash (`Segmentation fault: 11`)

### CODE REVIEW

**Comment by UdjinM6** [comment]
>  why optionsModel would be NULL in the first place

because `--version` returns right away, in never gets to `app.createOptionsModel()` in `main` (it simply doesn't have to).

**Comment by schinzelh** [comment]
Hmm, I wonder if this bug still exists in bitcoin-qt

**Comment by UdjinM6** [comment]
>Hmm, I wonder if this bug still exists in bitcoin-qt

most likely no https://github.com/dashpay/dash/commit/26c471df6be8a4cd106bcf5f806b29d653fc834d#diff-090c60fbf60da129ccb2db498a393f04R364 :)

**Comment by schinzelh** [comment]
So we gonna merge Bitcoin 13.1 into Dash 12.1? :trollface:

**Comment by UdjinM6** [comment]
> So we gonna merge Bitcoin 13.1 into Dash 12.1?

You should probably follow link I provided in the post above before making assumptions that this could be fixed by merging bitcoin 13.1 ;)

**Comment by tgflynn** [comment]
@schinzelh Let's get 12.1 to mainnet first.

**Comment by tgflynn** [comment]
After looking at the full code it looks like you should still crash on line 379 if optionsModel is NULL.

**Comment by UdjinM6** [comment]
nope, `delete NULL` is safe

**Comment by tgflynn** [comment]
Huh, I didn't know that, always thought delete NULL would segfault (and I've been writing C++ code for about 18 years).

**Pull request merged**
