### PR TITLE
rpc: Do not require a privkey corresponding to ownerAddress in `protx register_*` to be known by the wallet

### PR DESCRIPTION
**Pull request by UdjinM6**
This requirement was introduced in the initial implementation when we were signing protx payload with the owner key (#2246). This was changed later when we implemented external collateral references (#2366). The owner key is not used for anything in ProTxReg but to get CKeyID since then which we can do by simply decoding an address instead. This simplifies masternode registration process by letting an Operator to issue `protx register_prepare` on its own instead of asking an Owner. An Owner still have to sign the message provided by an Operator with his collateral address to prove collateral ownership (and authorize masternode registration).

Note: `protx register_*` rpc will no longer accept privkeys for `ownerAddress` param. Some 3-rd party software like DMT might need to be patched to work correctly with nodes running with this fix.

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
General concept ACK, but is it good to introduce that breaking behavior of not allowing privatekeys to be used?

**Comment by UdjinM6** [comment]
I think it's fine for a major version to introduce breaking changes and discouraging the usage of plaintext privkeys when it's not really needed is the right thing to do too.

**Comment by PastaPastaPasta** [comment]
> I think it's fine for a major version to introduce breaking changes and discouraging the usage of plaintext privkeys when it's not really needed is the right thing to do too.

@bertrand256 would this be breaking for you? 

Generally, I lean towards breaking rpc changes should have 1 major version of gap / deprecation to allow people to migrate without problems

**Comment by Bertrand256** [comment]
@PastaPastaPasta Yes, it will require adjustments in DMT code, but this is not a big problem.
Imho, the change is ok - I'm also inclined to eliminate private key transfers whenever possible.

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
it'd be nice if there was a test for this

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
