### PR TITLE
Ensure generatetoaddress works on RegTest only.

### PR DESCRIPTION
**Pull request by Duality-CDOO**

### CODE REVIEW

**Comment by UdjinM6** [comment]
Why?

**Comment by UdjinM6** [comment]
Yes. _Most likely_ you won't find any blocks though, but in general it works just fine :)

**Comment by Duality-CDOO** [comment]
@UdjinM6 Not at our end, the wallet freaked out and crashed. Wouldn't it be better to simply add that check and RPCError message?

**Comment by UdjinM6** [comment]
Are we talking about Dash Core wallet or about some fork? Cause I tried to reproduce it few times now and it doesn't crash. If it's Dash Core - pls provide the crash log/gdb backtrace, if it's not - I bet the issue is not the RPC itself and you should probably dig deeper and fix the underlying issue.

**Comment by Duality-CDOO** [comment]
@UdjinM6 Standby, I will talk with my developer and investigate.

**Comment by UdjinM6** [comment]
Given the silence here and the fact that I can't reproduce it, I guess the issue is identified to be non-Dash-related :) Closing.

**Pull request closed without merging**
