### PR TITLE
Migration fixes

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by tgflynn** [comment]
So if I understand correctly this adds a new setting: strDataDirDefault so there are now 2 settings: strDataDir and strDataDirDefault ?  Seems a bit overly complex to me.

Also I don't see how the user can change strDataDirDefault.

Maybe I'm misunderstanding this.

**Comment by UdjinM6** [comment]
Yep, strDataDirDefault is for internal use only, user can't change this.

So the idea is this: user can select whichever folder he likes and this is stored in strDataDir but we also store default path in strDataDirDefault, so that when the new (qt) wallet version is out an it expects another folder to be default we were able to detect this and ask user to select a folder (preferably to create a new one, not to select the same but that's is out of scope of this PR).

**Comment by tgflynn** [comment]
So if the user does set an alternate datadir he's going to have to reenter it every time dash-qt starts up ?

I would think it would be better to do something only on initial migration.

**Comment by UdjinM6** [comment]
>So if the user does set an alternate datadir he's going to have to reenter it every time dash-qt starts up ?

No... User can only set `strDataDir`, and we set `strDataDirDefault` automatically at the same time user picks (new/alternative) datadir https://github.com/dashpay/dash/pull/1247/files#diff-687e4cf035e297458699055f64b2a585R204. Mismatch №3 (`/* 3) Check to see if default datadir is the one we expect */`) will only happen when saved settings (`strDataDirDefault`) do not match our internal expectation (`getDefaultDataDirectory()`) which can only happen on migration.

**Comment by tgflynn** [comment]
But I don't see where strDataDirDefault ever gets set to anything other than dataDirDefaultCurrent.

So it seems like strDataDirDefault will always be the standard default and if dataDir was changed there will always be a mismatch causing the user to be asked.

**Comment by tgflynn** [comment]
utACK

**Pull request merged**
