### PR TITLE
backport: trivial 2024 10 23 pr5

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
Batch of trivial backports

## What was done?
See commits

## How Has This Been Tested?
built locally; large combined merge passed tests locally

## Breaking Changes
Should be none

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by knst — APPROVED** [review]
LGTM f76ae87cbc9c017e4684c8fdaa039f60ec0f554d but let's wait CI

**Comment by UdjinM6** [comment]
I must be missing smth but.... isn't this PR identical to #6348??

**Comment by PastaPastaPasta** [comment]
Seems like it 😂 One fewer PR!

**Comment by PastaPastaPasta** [comment]
closing in favor of https://github.com/dashpay/dash/pull/6348

**Pull request closed without merging**
