### PR TITLE
fix: ignore triggers from the past when voting

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
we should not vote on triggers from the past

## How Has This Been Tested?
n/a

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge; are there any ideas on how we can create a test for this?

**Comment by knst** [comment]
> there any ideas on how we can create a test for this?

Functional tests have a feature "check a string in logs". So, we can make some triggers to expire; after that assert that logs doesn't have this substring: `CGovernanceManager::%s Voting NO-FUNDING` - it appears in logs only if trigger is not expired with current implementation.

This feature `assert_debug_log` is used [here](https://github.com/dashpay/dash/blob/master/test/functional/p2p_invalid_messages.py#L182) and [here](https://github.com/dashpay/dash/blob/master/test/functional/wallet_dump.py#L195-L196) for example

**Comment by knst** [comment]
p.s. `assert_debug_log` can works in 2 modes: expected logs and unexpected logs; both arguments are arrays.
Here's a signature:
```
    def assert_debug_log(self, expected_msgs, unexpected_msgs=None, timeout=2):
```

**Comment by UdjinM6** [comment]
> > there any ideas on how we can create a test for this?
> 
> Functional tests have a feature "check a string in logs". So, we can make some triggers to expire; after that assert that logs doesn't have this substring: `CGovernanceManager::%s Voting NO-FUNDING` - it appears in logs only if trigger is not expired with current implementation.
> 
> This feature `assert_debug_log` is used [here](https://github.com/dashpay/dash/blob/master/test/functional/p2p_invalid_messages.py#L182) and [here](https://github.com/dashpay/dash/blob/master/test/functional/wallet_dump.py#L195-L196) for example

Good idea! 👍

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Review by knst — APPROVED** [review]
utACK

**Pull request merged**
