### PR TITLE
fix: coin selection with `include_unsafe` option should respect `nCoinType`

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
The issue was introduced in #6074 via https://github.com/dashpay/dash/commit/69c5aa89479af20c2bdb0c02191617140efdae5e

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by PastaPastaPasta — APPROVED** [review]
utACK e5114da32536f977e69f6a0d531c3ca45dafdf07

**Review by knst — APPROVED** [review]
LGTM e5114da32536f977e69f6a0d531c3ca45dafdf07

thought, strange that it is not caught by functional tests

**Review by kwvg — APPROVED** [review]
utACK e5114da32536f977e69f6a0d531c3ca45dafdf07

**Comment by PastaPastaPasta** [comment]
back ported in https://github.com/dashpay/dash/pull/6447

**Pull request merged**
