### PR TITLE
backport: merge bitcoin#19525, #20434, #22244, #20476, #19667, #22320, #18676, #19375, #21991, #20421, partial #23511 (auxiliary backports: part 8)

### PR DESCRIPTION
**Pull request by kittywhiskers**
# What was done?
Backports, see commit titles for more information

## How Has This Been Tested?
`make check`

## Breaking Changes
None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
NACK

bitcoin can do 22930 because they switched to guix and downgraded glibc in 22365
running dashd produced via gitian build using this branch results in 
```
./dashcore-3abf7af8a21f/bin/dashd: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./dashcore-3abf7af8a21f/bin/dashd)
```
on 18.04/bionic

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
re-req when you need me to review :D

**Review by UdjinM6 — CHANGES_REQUESTED** [review]

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
