### PR TITLE
fix tab text truncation

### PR DESCRIPTION
**Pull request by UdjinM6**
Should fix an issue reported there https://github.com/dashpay/dash/pull/778#issuecomment-220550343 by simply making toolbar tabs/buttons wider.

### CODE REVIEW

**Comment by akijuh** [comment]
This is not only light theme fault, its also in the blue theme.
Transactions tab first left column is now too wide and therefore columns are misaligned.

firstcol

**Comment by UdjinM6** [comment]
@akijuh that is not the same problem as this PR. Please report new issues in https://github.com/dashpay/dash/issues so that evreyone was aware instead of reporting in already merged PRs. Thanks!

**Comment by akijuh** [comment]
Ok, i am new with github...

**Comment by UdjinM6** [comment]
@akijuh np :)

**Pull request merged**
