### PR TITLE
v17: Update CLIENT_VERSION_IS_RELEASE in configure.ac

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
I think this should be done to this branch. Let me know if it should actually be done elsewhere

### CODE REVIEW

**Review by xdustinface — DISMISSED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
utACK to merge after #4157

**Pull request merged**
