### PR TITLE
Fix nDelayGetHeadersTime (int64_t max == never delay)

### PR DESCRIPTION
**Pull request by UdjinM6**
Imo it makes a bit more sense to have it this way.

### CODE REVIEW

**Comment by codablock** [comment]
Doesn't this cause integer overflows?

**Comment by UdjinM6** [comment]
Hmm... How exactly?

**Comment by codablock** [comment]
Ah sorry, int64_t is signed, so it won't overflow but result in a negative value when something like `GetAdjustedTime() - chainparams.DelayGetHeadersTime()` is being calculated. It will do the correct thing, but I'm not sure if I like this as it is not immediately obvious that you're dealing with negative values here.

**Comment by UdjinM6** [comment]
Rewrote conditions, hopefully it's now easier to grasp what's going on there

**Pull request merged**
