### PR TITLE
Backports 0.17 pr18

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Linter added in this PR fails, will take a look tomorrow

### CODE REVIEW

**Comment by UdjinM6** [comment]
Tried to fix linter errors and ended up with this https://github.com/UdjinM6/dash/commits/pr3636 so far. Was able to run it on mac with 0 linter errors, tests pass locally too but I'm not 100% sure about shellcheck fixes yet, waiting for travis/gitlab.

**Comment by PastaPastaPasta** [comment]
Cherry-picked, the commits looks good overall, however lint-all.sh is still failing for me locally

```
./test/lint/lint-all.sh 

In ci/build_src.sh line 41:
test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
                     ^-- SC2015: Note that A && B || C is not if-then-else. C may run when A is true.


In ci/test_integrationtests.sh line 9:
PASS_ARGS="$@"
          ^--^ SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.


In ci/test_integrationtests.sh line 45:
  for d in $(ls testdatadirs/$BASEDIR | grep -v '^cache$'); do
             ^-- SC2010: Don't use ls | grep. Use a glob or a for loop with a condition to allow non-alphanumeric filenames.


In contrib/macdeploy/detached-sig-create.sh line 17:
if [ ! -n "$1" ]; then
     ^-- SC2236: Use -z instead of ! -n.


In contrib/qos/tc.sh line 34:
if [ ! -z "${LOCALNET_V6}" ] ; then
     ^-- SC2236: Use -n instead of ! -z.


In contrib/qos/tc.sh line 57:
if [ ! -z "${LOCALNET_V6}" ] ; then
     ^-- SC2236: Use -n instead of ! -z.


In contrib/verify-commits/verify-commits.sh line 101:
				HASH=$(git cat-file blob "$CURRENT_COMMIT":"$FILE" | shasum -a 512 | { read FIRST OTHER; echo $FIRST; } )
                                                                                                                  ^---^ SC2034: OTHER appears unused. Verify use (or export if used externally).


In contrib/windeploy/detached-sig-create.sh line 11:
if [ ! -n "$1" ]; then
     ^-- SC2236: Use -z instead of ! -n.


In docker/build-docker.sh line 6:
cd $DIR/..
^--------^ SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.

Did you mean: 
cd $DIR/.. || exit


In docker/push-docker.sh line 6:
cd $DIR/..
^--------^ SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.

Did you mean: 
cd $DIR/.. || exit


In test/lint/git-subtree-check.sh line 22:
	while read a b junk; do
                       ^--^ SC2034: junk appears unused. Verify use (or export if used externally).


In test/lint/git-subtree-check.sh line 52:
old=$1
^-^ SC2034: old appears unused. Verify use (or export if used externally).

For more information:
  https://www.shellcheck.net/wiki/SC2010 -- Don't use ls | grep. Use a glob o...
  https://www.shellcheck.net/wiki/SC2034 -- OTHER appears unused. Verify use ...
  https://www.shellcheck.net/wiki/SC2124 -- Assigning an array to a string! A...
^---- failure generated from ./test/lint/lint-shell.sh
```

**Comment by UdjinM6** [comment]
You missed the last one - 682c6b843e85fe0b524b22b504d4c122966207e5

**Comment by PastaPastaPasta** [comment]
Yeah... That helps, looks good

**Comment by PastaPastaPasta** [comment]
I'm not sure why CI isn't happy... Tests are passing, yet it's coming back red

**Comment by UdjinM6** [comment]
Pls see d394166d4963ffcca578e3a9384aae6dc447599d

**Comment by PastaPastaPasta** [comment]
Cherry-picked

**Pull request merged**
