### PR TITLE
backport: CWallet refactoring: bitcoin#14588 #16026 #16786 #17261 #18026 #18067 #18115 #18241, #19982 fixes for #17260, #16301, #16426, redo #20033, #19845

### PR DESCRIPTION
**Pull request by knst**
That is final batch of backports related to CWallet refactorings.

Prior work is here: https://github.com/dashpay/dash/pull/5111

## Issue being fixed or feature implemented
https://github.com/dashpay/dash-issues/issues/54

## What was done?
Were made next backports:
- bitcoin#18115
- bitcoin#18241
- bitcoin#18067
- bitcoin#18026
- bitcoin#17261
- bitcoin#14588
- bitcoin#16786
- bitcoin#16026
- bitcoin#19982

Beside that were follow-up fixes:
 - bitcoin#17260
 - bitcoin#16301
 - bitcoin#16426

Backport bitcoin-17261 is very big, for easier review here's un-squashed commits: https://github.com/knst/dash/tree/bc-bp-cwallet-6-17261

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
Should not be breaking changes

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by UdjinM6** [comment]
LGTM, will try to test it a bit before ACK-ing.

NOTE:
91b1720 -> merge 19845
4096408 -> merge 20033

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see 1272ea3c05cb13a0c9b37f55ae192da7890d3843 and 66cbe6e0bc79f46ba3b4c7fcb2221e88ef3103d4

**Review by UdjinM6 — APPROVED** [review]
LGTM, lightly tested ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
