### PR TITLE
chainlocks: Fix potential deadlock

### PR DESCRIPTION
**Pull request by UdjinM6**
Should fix this:
```
Previous lock order was:
 pnode->cs_sendProcessing  net.cpp:2854
 cs_main  net_processing.cpp:3946 (TRY)
 mempool.cs  net_processing.cpp:4183
 (1) pto->cs_inventory  net_processing.cpp:4183
 pto->cs_filter  net_processing.cpp:4233
 (2) cs  llmq/quorums_chainlocks.cpp:87
Current lock order is:
 cs_main  llmq/quorums_chainlocks.cpp:138
 (2) cs  llmq/quorums_chainlocks.cpp:138
 cs_vNodes  net.cpp:3662
 (1) cs_inventory  ./net.h:1085
```

### CODE REVIEW

**Review by xdustinface — COMMENTED** [review]
Couldn't we then also move `InternalHasConflictingChainLock` up into the other `LOCK(cs)` scope (without negative side effects?) like in 5b520c388d2b5147cc730855213e1c393d73d7f9?

**Comment by UdjinM6** [comment]
I guess 5b520c3 makes sense. Just not in this PR :)

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
