### PR TITLE
Fix two translation build issues

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
utACK

**Comment by UdjinM6** [comment]
Just realised that I cherry-picked an individual commit instead of the merge one hence there was no `merge #xxx` in its title 🙈 Fixed (tweaked the title manually, no code changes).

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
