### PR TITLE
fix: Exclude SCRIPT_ENABLE_DIP0020_OPCODES from flags in mempool checks while DIP0020 is not activated yet

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
Should fix the crash reported in #6256

## Breaking Changes
n/a, only affects txes prior to DIP0020 activation

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by knst — APPROVED** [review]
Concept ACK but let me think a bit about possible corner cases

**Comment by UdjinM6** [comment]
> @UdjinM6 let's add tests from 6298 ?

Let's maybe merge #6298 first instead and then rebase this one?

**Comment by UdjinM6** [comment]
No, it's #6256 which breaks tests with crashes. #6298 simply adds a p2p part to it, shouldn't break anything. Check CI: https://gitlab.com/dashpay/dash/-/pipelines/1477542913.

**Review by knst — CHANGES_REQUESTED** [review]
Consider https://github.com/dashpay/dash/pull/6299 instead

**Comment by UdjinM6** [comment]
closing in fav of #6302

**Pull request closed without merging**
