### PR TITLE
Backports 0.18 pr2

### PR DESCRIPTION
**Pull request by Munkybooty**

### CODE REVIEW

**Comment by UdjinM6** [comment]
13899 should be dropped (it was merged in https://github.com/dashpay/dash/pull/4196) + pls see b774f74847049c5dfc00b7895f42fd4c7028b215 and 8aefd624d0944924e7310a753b1f980e59eeeed1

**Review by UdjinM6 — COMMENTED** [review]
still missing 8aefd62

**Review by UdjinM6 — APPROVED** [review]
👍 

utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
