### PR TITLE
clean up a bit

### PR DESCRIPTION
**Pull request by UdjinM6**
Changes:
- remove `._str()` from `LogPrintf`s
- a bit more verbose votes debug output
- trivial change: https://github.com/dashpay/dash/compare/v0.12.1.x...UdjinM6:cleanup_?expand=1#diff-568a69d65983b416159f2a6f562c84f4R1322
- fix comments and tabs/spaces

### CODE REVIEW

**Comment by evan82** [comment]
rebase pls?

**Comment by UdjinM6** [comment]
done :)

**Comment by UdjinM6** [comment]
Since it's still open I added more bitcoin -> dash transitions here ;)

**Comment by schinzelh** [comment]
Merged, thanks!

**Pull request closed without merging**
