### PR TITLE
Backports 0.17 pr5

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
rebased on develop, not dependant on pr3 or pr4

**Comment by PastaPastaPasta** [comment]
contrib/devtools/lint-python.sh is casting a bit too wide of a net. It shouldn't be triggering (imo) on the remaining things present. TIme to ask @UdjinM6 for help :)

**Comment by UdjinM6** [comment]
Pls see https://github.com/UdjinM6/dash/commits/pr3530

Few notes on that ^^^:
- 265ac192b7007beb109076d0482dd53acebca39a - 11789 backport was  missing quite a few things
- e280d60f0a439a357c104b22c1a6fa6666aaf5c8 - fixes F401 issues
- 88c5e4828ac9c2cbadee50c789154210e30354b8 - there is a fix in bitcoin for the same issue https://github.com/bitcoin/bitcoin/pull/16124 but it requires much more backporting, proposing a much simpler fix for now
- 4c895da3ede356552251b7f0fb31da189f6017cd - https://github.com/bitcoin/bitcoin/pull/15257 will drop W504 and fix W605. E741 was never fixed. IMO keeping them in the list is a good reminder that some backports are missing, so I added them back (but they are disabled).

**Comment by PastaPastaPasta** [comment]
Looks good. Cherry-picked, once reviewed I can squash

**Comment by PastaPastaPasta** [comment]
Rebased on develop (mostly to rebase pr6 and my working branch)

**Comment by UdjinM6** [comment]
I _think_ we also need https://github.com/bitcoin/bitcoin/pull/12710 to fix tests after 12437.

**Comment by PastaPastaPasta** [comment]
cherry-picked. Cherry-pick was clean

**Comment by PastaPastaPasta** [comment]
Ok, squashed. Sadly squashing did some weird things initally, caused some commits already merged to show up on the PR. Tried dropping those commits, which resulted in an unclean force push, I then rebased on develop and force pushed again, if you combine the two force pushes here (https://github.com/dashpay/dash/compare/bcc1054700a05cd7028d7729c7276f63b6e249be..3d252a72b217786a6f7ba3435ddc0657d7092489) the combined force pushes are clean

**Pull request merged**
