### PR TITLE
[18.x] backport: backports for rc5 and bump

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by UdjinM6** [comment]
Missing #4843, #4846 and #4854 (see https://github.com/dashpay/dash/pulls?q=is%3Apr+is%3Aclosed+label%3Abackport-candidate-18.x). Also, ideally, [3636ec0](https://github.com/dashpay/dash/pull/4856/commits/3636ec023f83ea1888703d47ebda1e695f68ef6a) should be done on develop first and then backported.

**Comment by PastaPastaPasta** [comment]
Cherry picked 4854, and dropped copyright, the other two have conflicting changes and maybe @knst can create a backport PR with his commits

**Comment by UdjinM6** [comment]
1233977a0fb15fa69cf2bb87b88a8d91e0f23ac2 and db91e4f8e9e90472b9b8619c4f4fababb6950996 should do it I think

**Comment by PastaPastaPasta** [comment]
Okay @UdjinM6 please review

**Review by QuantumExplorer — APPROVED** [review]
Approved because these are just cherry picked commits.

**Review by UdjinM6 — APPROVED** [review]
ACK

**Comment by knst** [comment]
Strange, seems as zlib 1.2.11 is not available by link anymore (404 error).

I tried to build with 1.2.12 and it works on Kubuntu 22.04 fine.

diff --git a/depends/packages/zlib.mk b/depends/packages/zlib.mk
index acb02020a8..66cb8aa7a0 100644
--- a/depends/packages/zlib.mk
+++ b/depends/packages/zlib.mk
@@ -1,8 +1,8 @@
 package=zlib
-$(package)_version=1.2.11
+$(package)_version=1.2.12
 $(package)_download_path=https://www.zlib.net
 $(package)_file_name=$(package)-$($(package)_version).tar.gz
-$(package)_sha256_hash=c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
+$(package)_sha256_hash=91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9

**Comment by UdjinM6** [comment]
@knst Hmm, right. So I guess it worked for me locally cause I have zlib downloaded already and it works for gitian cause it uses `https://bitcoincore.org/depends-sources/` as a fallback for all dependencies (i.e. `https://bitcoincore.org/depends-sources/zlib-1.2.11.tar.gz` for zlib).  Pls create a PR with your patch and `v18.x` as a base branch.

**Comment by knst** [comment]
https://github.com/dashpay/dash/pull/4858

**Pull request merged**
