### PR TITLE
refactor: replace util::Ref with CoreContext (std::variant)

### PR DESCRIPTION
**Pull request by kittywhiskers**
## Issue being fixed or feature implemented

replacing util::Ref with std::any as bitcoin did caused triggered a bug in the compiler on ubuntu 20.04, additionally, using std::any should be avoided due to the general lack of type safety.

## What was done?

This PR instead replaces util::Ref with a new std::variant called CoreContext. This CoreContext can be either nothing (std::nullopt_t) or any of the contexts as defined here https://github.com/dashpay/dash/pull/5055/files#diff-0b11759ffdecd88f727e460c2490c86bce5dfe0ee92f8df9dab0d37d57d235ffR16-R20

## How Has This Been Tested?

make check, functional tests

## Breaking Changes

shouldn't be any breaking changes

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see 605c7452f9efe9bfb01cade63cfedb1b0adf0f4e (should fix test failures + drop unrelated changes)

**Comment by UdjinM6** [comment]
pls see e588002d0f for some suggestions

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
