### PR TITLE
llmq: Some refactoring in CChainLocksHandler::ProcessNewChainLock

### PR DESCRIPTION
**Pull request by xdustinface**

### CODE REVIEW

**Comment by UdjinM6** [comment]
cc1b476 really made me think if it actually makes any sense to have _both_ `(!bestChainLock.IsNull() && clsig.nHeight <= bestChainLock.nHeight)` and `InternalHasConflictingChainLock` here at all (#3978 is a side effect of that 🙂 ) cause it seems like `InternalHasConflictingChainLock` will always be `false` in this combination, no?

**Comment by UdjinM6** [comment]
Ping 👀  Any thoughts on dropping `InternalHasConflictingChainLock` part instead of cc1b476?

**Comment by xdustinface** [comment]
@UdjinM6 Sorry for the late reply, i was just too deep into other stuff the last week and i just didn't find time in my mind to think about this and #3978 🙈 But i agree, it makes sense to drop it 👍 Added a51875f900085e1898fcd85865f09f303c8b0770 instead of cc1b476!

**Review by UdjinM6 — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Can you explain a51875f900085e1898fcd85865f09f303c8b0770 more? why are we dropping that?

**Comment by xdustinface** [comment]
> why are we dropping that?

See https://github.com/dashpay/dash/pull/3976#issuecomment-772129953

https://github.com/dashpay/dash/blob/a51875f900085e1898fcd85865f09f303c8b0770/src/llmq/quorums_chainlocks.cpp#L634 will always trigger in this case because we already make sure before that its higher than best chainlock height https://github.com/dashpay/dash/blob/a51875f900085e1898fcd85865f09f303c8b0770/src/llmq/quorums_chainlocks.cpp#L120

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
