### PR TITLE
Update docker tags

### PR DESCRIPTION
**Pull request by strophy**
This PR updates the GitHub Action used to tag the Docker images so that build tags containing `-rc` are tagged `latest-dev` and releases are tagged `latest` on Docker Hub. You can see sample build outputs [here](https://hub.docker.com/repository/docker/strophy/dashd/tags?page=1&ordering=last_updated), input release tags were `0.16.1.1` and `0.17.0.0-rc4`.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Hmm. so `0.16.1.1` release produced 3 tags `0.16.1.1`, `0.16.1` and `0.16` instead of just one `0.16.1.1`, right? How is this going to work if we would have `0.16.1.0` release first and then `0.16.1.1` after some time? Will `0.16.1.1` overwrite `0.16` and `0.16.1` tags?

**Comment by strophy** [comment]
Yes, that description is correct. The major.minor.patch is pinned only to the degree specified by the user when they request the image, the unspecified portion should always be the highest available according to semver. This means an operator can specify version `dashpay/dashd:0.16` in their config and it will automatically update to all versions on the `0.16` series, but require manual intervention for a protocol upgrade.

**Review by UdjinM6 — APPROVED** [review]
Nice! 👍 

utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
