### PR TITLE
llmq: Use thread pool for quorum cache and data recovery threads

### PR DESCRIPTION
**Pull request by UdjinM6**
Move quorum data and cache thread handling into CQuorumManager (use thread pool instead of spawning one thread per quorum).

### CODE REVIEW

**Review by xdustinface — CHANGES_REQUESTED** [review]
Good idea 👍 See two comments, or 97dd970e788e6d462bbee378d72672abfe274b43 as alternative if you want to be explicit about all captures. Also, see 376cf14 which not a must though, add it if you like it :)

**Comment by UdjinM6** [comment]
Applied both patches. Thanks! 👍

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
