### PR TITLE
backport: Merge bitcoin#23142, (partial) bitcoin-core/gui#409, 23333, 23755, (partial) 22981

### PR DESCRIPTION
**Pull request by vijaydasmp**
backports from bitcoin

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 requesting review

**Review by UdjinM6 — CHANGES_REQUESTED** [review]

**Review by UdjinM6 — APPROVED** [review]
utACK 71689fe6dcfce9f7fe42e75767009f98fa5850e2

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta  requesting review

**Review by knst — APPROVED** [review]
utACK 71689fe6dcfce9f7fe42e75767009f98fa5850e2

**Pull request merged**
