### PR TITLE
Merge #15144: [refactor] CNode: Use C++11 default member initializers

### PR DESCRIPTION
**Pull request by vijaydasmp**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Please fix CI, and then mark PR as ready for review

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see https://github.com/UdjinM6/dash/commit/0962b86cb6e27ea60314ed900314327dcae88b14

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via squash merge

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
