### PR TITLE
Facelift of splash screens, adding "Digital Cash" tagline

### PR DESCRIPTION
**Pull request by schinzelh**
Thanks go to @raze 👍

### CODE REVIEW

**Comment by UdjinM6** [comment]
Nice :)

I have few notes/questions though:
1. `drkblue` is the theme with these arrow-ish things all the way through, see background https://github.com/dashpay/dash/blob/21f6952bb37a6435a2248a0c0982a274396ec930/src/qt/res/images/drkblue/drkblue_walletFrame_bg.png and `about` dlg https://github.com/dashpay/dash/blob/21f6952bb37a6435a2248a0c0982a274396ec930/src/qt/res/images/drkblue/about.png It also has it's own light-blue color scheme (for mainnet). IMO new splash screen style doesn't fit there and we should just keep the old one. The same is more or less true for `trad` theme too but this one has image only for `about` dlg and no background. (`trad` theme also needs some attention btw, it's a mess with transparent sync progress dlg right now @crowning-)

2. Why testnet screens are green now? We used to match splash screen main color to tray icon color, so we should either keep old color for splash screen or update icon color and make it gree too imo.

**Comment by nmarley** [comment]
Agree w/ @UdjinM6 , esp. point 2. The green on testnet looks strange, being used to orange for so long now.

**Comment by UdjinM6** [comment]
Green is probably a result of bitcoin core influence ;) It has light green btc logo for testnet and light blue for regtest. I'm fine with either color, I'm a bit concerned with color inconsistency this PR brings so far - we should either fix testnet (desktop and tray) icons too or leave the color for testnet splash screen as is it imo.

**Comment by schinzelh** [comment]
Pushed orange testnet splash screens, please review :)

**Comment by UdjinM6** [comment]
Ok, colors look better now :)
What about `drkblue` theme?

**Comment by schinzelh** [comment]
Lets leave `drkblue` theme untouched then, I'll revert it 👍

**Pull request merged**
