### PR TITLE
merge bitcoin#16244...18699: translation backports

### PR DESCRIPTION
**Pull request by kittywhiskers**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
https://github.com/dashpay/dash/pull/4753#pullrequestreview-932547843

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see https://github.com/UdjinM6/dash/commit/f0125d3c968a6ccf7add127c36f44f5bed98c14d

**Review by PastaPastaPasta — APPROVED** [review]
re-utACK

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
