### PR TITLE
qt: MasternodeList  - Introduce column enum and fix column sorting

### PR DESCRIPTION
**Pull request by xdustinface**
Items in `MasternodeList` are currently sorted by their string value (default behaviour) which leads to incorrect sorting for  numbers. This PR introduces `CMasternodeListWidgetItem` which implements a custom comparison for the numeric columns.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Nice! Let's maybe fix `Service` column too https://github.com/UdjinM6/dash/commit/69558345ac61662b154002c383704138f31c7eff while at it?

**Comment by PastaPastaPasta** [comment]
Would this have any adverse affects like slow downs?

**Comment by thephez** [comment]
:heart_eyes: This has always annoyed me (just not enough to figure out how to fix it myself :wink:).

**Comment by xdustinface** [comment]
> Would this have any adverse affects like slow downs?

Actually not, sorting strings should always be slower. But it indeed slowed things down for a weird reason which is fixed by c9f9a06.  

> Nice! Let's maybe fix `Service` column too [UdjinM6@6955834](https://github.com/UdjinM6/dash/commit/69558345ac61662b154002c383704138f31c7eff) while at it?

Make sense, added 👍 

Though i had to change it a bit to fix the slow down addressed above. I have no concrete idea why, so if someone can tell me, please do, but if i add only a single `if`/`switch` statement to `CMasternodeListWidgetItem::operator<` sorting slows down very noticeable. Which is weird because `return data(Qt::UserRole) < other.data(Qt::UserRole);` also works fast but has more than only one `if` down the road of `QVariant::operator<`. 🤔 However, `QByteArray` comparison doesn't work in this case thats why i used a template now.

**Review by UdjinM6 — APPROVED** [review]
ACK 👍

**Comment by UdjinM6** [comment]
I would assume that "non-template" versions are slower because of constant conversions from `QVariant` inside of `operator<`. There are probably also some optimizations when you have only 1 type of data which are thrown away as soon as you add another one. In the "template" version you store and use data as is for each data type and all conversions are done at the creation time only.

**Comment by xdustinface** [comment]
> I would assume that "non-template" versions are slower because of constant conversions from `QVariant` inside of `operator<`. There are probably also some optimizations when you have only 1 type of data which are thrown away as soon as you add another one. In the "template" version you store and use data as is for each data type and all conversions are done at the creation time only.

Hmm buut the thing is 

```
class CMasternodeListWidgetItem : public QTableWidgetItem
{
public:
    explicit CMasternodeListWidgetItem(const QString& text, const QVariant& data, int type = Type) : QTableWidgetItem(text, type)
    {
        setData(Qt::UserRole, data);
    }
    bool operator<(const QTableWidgetItem& other) const
    {
        return data(Qt::UserRole) < other.data(Qt::UserRole);
    }
};
```

is also no template, has the same conversions you talked about but is also as fast as the template. Thats the case i talked about in my last comment where `QByteArray` comparison doesn't work.

But if you now add an `if` in there like 

```
bool operator<(const QTableWidgetItem& other) const
{
    if (column() == MasternodeList::COLUMN_REGISTERED){
        return data(Qt::UserRole) < other.data(Qt::UserRole);
    }
    return QTableWidgetItem::operator<(other);
}
```

Its again slow.. at least here for me but i guess you can confirm this?

Thats sounds funny if you look at what happens in the deeps of [QVariant::compare](https://code.woboq.org/qt5/qtbase/src/corelib/kernel/qvariant.cpp.html#_ZNK8QVariant7compareERKS_) which gets called by the operator if `return data(Qt::UserRole) < other.data(Qt::UserRole);` is executed.

**Comment by UdjinM6** [comment]
Interesting. So the slow part here is [QTableWidgetItem::column()](https://doc.qt.io/qt-5/qtablewidgetitem.html#column) actually:
> Returns the column of the item in the table. If the item is not in a table, this function will return -1.

Each call is basically a lookup in a vector of all items (5120x12=61k+ items for mainnet): [QTableWidgetItem::column()](https://code.woboq.org/qt5/qtbase/src/widgets/itemviews/qtablewidget.h.html#391) -> [QTableWidget::column()](https://code.woboq.org/qt5/qtbase/src/widgets/itemviews/qtablewidget.cpp.html#1977) -> [QTableModel::index()](https://code.woboq.org/qt5/qtbase/src/widgets/itemviews/qtablewidget.cpp.html#351) -> `tableItems.at(id)`.

The code below works much faster than the one with `column()` for example:
```c++
class CMasternodeListWidgetItem : public QTableWidgetItem
{
private:
    int column;
public:
    explicit CMasternodeListWidgetItem(const QString& text, const QVariant& data, int _column = -1, int type = Type) : QTableWidgetItem(text, type), column(_column)
    {
        setData(Qt::UserRole, data);
    }
    bool operator<(const QTableWidgetItem& other) const
    {
        if (column == MasternodeList::COLUMN_SERVICE) {
            return data(Qt::UserRole).toByteArray() < other.data(Qt::UserRole).toByteArray();
        }
        return data(Qt::UserRole) < other.data(Qt::UserRole);
    }
};
...
void MasternodeList::updateDIP3List()
{
...
        QTableWidgetItem* addressItem = new CMasternodeListWidgetItem(QString::fromStdString(dmn->pdmnState->addr.ToString()), addr_ba, MasternodeList::COLUMN_SERVICE);
```

But c9f9a06 is a cleaner and more universal solution imo.

**Comment by xdustinface** [comment]
> Interesting. So the slow part here is [QTableWidgetItem::column()](https://doc.qt.io/qt-5/qtablewidgetitem.html#column) actually

Ahhhhh...Nice!! I didn't even thought a second about `column()` could be the bottleneck here.. it just doesn't sounds too harmless 🙈

> But [c9f9a06](https://github.com/dashpay/dash/commit/c9f9a06ef54c4fb398110e0c2bc4605a3fe2b300) is a cleaner and more universal solution imo.

Agree, but still good to see the other solution, thanks 🙂

**Comment by UdjinM6** [comment]
It's been more than a week with no change requests or any issues raised, merging.

**Review by PastaPastaPasta — COMMENTED** [review]
post-utACK

**Pull request merged**
