### PR TITLE
qt: Introduce appearance tab and setup dialog

### PR DESCRIPTION
**Pull request by xdustinface**
This PR ist part of a series of +-25 PRs related to UI redesigns. Its ancestor is #3567, its successor is  #3569. I did not screenshot every single PR and its changes, instead i made "walk through all screen" videos with the result of this PR series and also with the 0.15 UI. If there are any concrete screenshots wanted, just let me know. To build with the full set of changes you can build from the branch [xdustinface:pr-ui-redesign](https://github.com/xdustinface/dash/tree/pr-ui-redesign) which always contains all changes.

[ -> Walk through 0.15](https://youtu.be/cWQeHj5tWR0)
[ -> Walk through Redesign](https://youtu.be/0QeSyXo1aao)

I tried to give the commits enough text to make things obvious without a lot description for each PR. Also here, if you want more description for this specific PR, let me know.
### About this PR

This PR implements a new tab in OptionsDialog. Called "Appearance" which now contains the theme setting. Also you can apply some customization there related to font size, font weight or font family.

The content of this new tab is also used for an "Initial appearance setup dialog" which appears if Dash Core gets started the first time after this PR.

### CODE REVIEW

**Comment by xdustinface** [comment]
Ready for review! Like discussed in #3578 this PR also introduces a "initial appearance setup dialog" now.. basically just to let user know it's there and to give them the opportunity to set their preferred defaults. It will only pop up the first time a user runs any dash core version with this PR included. 

Dark             |  Light
:-------------------------:|:-------------------------:
 |

**Comment by UdjinM6** [comment]
Looks ok-ish but works weird with `-resetguisettings` flag - initial settings for font weights for normal text do not match the weight that is loaded on font switching: default (all sliders to the right) -> Montserrat -> default (normal to the left, bold to the right).

**Comment by xdustinface** [comment]
@UdjinM6 The latest commits should clean that up and fix it. There are still rare cases i have on my list now (i.e. if command line parameters are used on first start) where we run into inconsistencies but i assume that can be a known issue at this point? I would like to rework all that weight handling stuff a bit when i move all that code in some theme handler class. Are we good with that?

**Comment by UdjinM6** [comment]
Pls see 0e9a7500a5 and e698624d9e.

**Comment by xdustinface** [comment]
Makes both sense, picked 👍

**Pull request merged**
