### PR TITLE
backport: Merge bitcoin#20023, 21713, 20575, 21989, 20971, 20964, 20497, 20425, 19980, (partial) 20125

### PR DESCRIPTION
**Pull request by vijaydasmp**

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 , please review

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Review by knst — DISMISSED** [review]
utACK

update title "...20125" -> "...partial 20125"

**Review by UdjinM6 — DISMISSED** [review]
utACK

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta , please review

**Review by UdjinM6 — DISMISSED** [review]
re-utACK

**Review by PastaPastaPasta — APPROVED** [review]
not sure why 20125 is partial (remaining changes seem like they could be done) but otherwise;
utACK for merging via merge commit

**Comment by vijaydasmp** [comment]
> not sure why 20125 is partial (remaining changes seem like they could be done) but otherwise; utACK for merging via merge commit

src/wallet/wallet.h changes done in bitcoin#19980, (the changes are similar) for the line 
we don't have wallet_descriptor.cpp , 
removed Partial

**Comment by knst** [comment]
The changes in file `test/functional/wallet_descriptor.py` will be missing if 20125 would be marked as completely DONE.
Because when this file will appear no one will remember that should be included this check:
```
        assert_equal(wallet_info['format'], 'sqlite')
```

For case if there's refactoring where interface a changed or behaviour is changed -> these changes would be caught by compiler or unit/functional tests. But these changes will be just omitted.

Please, have "partial" marker for 20125 until wallet_descriptor is in repo.

**Review by UdjinM6 — APPROVED** [review]
re-utACK

**Review by knst — APPROVED** [review]
utACK

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta , please review

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta , please review

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta , please review

**Comment by vijaydasmp** [comment]
Are there any further comments on this PR @UdjinM6 @knst @PastaPastaPasta

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
