### PR TITLE
Trivial: fix mac compile warnings

### PR DESCRIPTION
**Pull request by mkinney**
See https://github.com/google/leveldb/pull/422/files for details.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Thanks! I would merge this only after the referenced one is merged however.

**Comment by schinzelh** [comment]
Yep, they are still discussing it in the originating PR, moved to 12.2

**Comment by SCDeveloper** [comment]
They've been discussing that for an eternity.........

**Comment by schinzelh** [comment]
They seem to prefer https://github.com/google/leveldb/pull/449 over this fix - still not merged though

**Pull request closed without merging**
