### PR TITLE
ci: Add `--enable-werror` to arm and c++17 builds (and fix all issues found via these builds)

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Is this ready?

**Comment by UdjinM6** [comment]
Rebased and fixed a couple of new issues. Will require another rebase after #4223 though.

**Comment by PastaPastaPasta** [comment]
Ready to review?

**Comment by UdjinM6** [comment]
It was looking good before recent merges to develop and I think there were no breaking changes so it _should_ be ready... but I rebased it one more time just in case, let's see :)

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
CI happy :)

**Comment by PastaPastaPasta** [comment]
merge?

**Comment by UdjinM6** [comment]
I think it conflicts with #4247 and also, it requires #4254. I'd like to rebase it once again once these two are merged to make sure everything is clean.

**Comment by PastaPastaPasta** [comment]
It'd be very nice if we had the bot that bitcoin has to identify conflicting PRs

**Comment by UdjinM6** [comment]
Ok, so #4254 is merged now. But #4247 isn't quite ready yet it seems, so I'm just going to merge this one first instead.

(I verified locally that it compiles with `--enable-werror` after rebasing it on top of `develop`).

**Pull request merged**
