### PR TITLE
Bitcoin backport #16227 refactoring CWallet

### PR DESCRIPTION
**Pull request by knst**
It is attached to pull request as separates changes for easier review and easier conflict resolving during merge.
Should be squashed to one commit when merged.

```
commit 735d6b57e795503d4ce7354225b599ce97e236b8 (HEAD)
Merge: 28d1353f4 93ce4a0b6
Author: Wladimir J. van der Laan <laanwj@gmail.com>
Date:   Thu Jul 11 22:01:12 2019 +0200

    Merge #16227: Refactor CWallet's inheritance chain
    
    93ce4a0b6fb54efb1f424a71dfc09cc33307e5b9 Move WatchOnly stuff from SigningProvider to CWallet (Andrew Chow)
    8f5b81e6edae9cb22559545de63f391d97c15701 Remove CCryptoKeyStore and move all of it's functionality into CWallet (Andrew Chow)
    37a79a4fccbf6cd65a933594e24e59d36e674653 Move various SigningProviders to signingprovider.{cpp,h} (Andrew Chow)
    16f8096e911e4d59292240a17e2d4004f0500b9e Move KeyOriginInfo to its own header file (Andrew Chow)
    d9becff4e13da8e182631baa79b9794c03d44434 scripted-diff: rename CBasicKeyStore to FillableSigningProvider (Andrew Chow)
    a913e3f2fbeb1352fc66f334d4f5f7332ea89ad7 Move HaveKey static function from keystore to rpcwallet where it is used (Andrew Chow)
    c7797ec65544bd23a2e571b2892e1bf512f2a485 Remove CKeyStore and squash into CBasicKeyStore (Andrew Chow)
    1b699a5083b435c2b79f3951f94ac9f967d24f6c Add HaveKey and HaveCScript to SigningProvider (Andrew Chow)
    
    Pull request description:
    
      This PR compresses the `CWallet` chain of inheritance from 5 classes to 3 classes. `CBasicKeyStore` is renamed to `FillableSigningProvider` and some parts of it (the watchonly parts) are moved into `CWallet`. `CKeyStore` and `CCrypoKeyStore` are completely removed. `CKeyStore`'s `Have*` functions are moved into `SigningProvider` and the `Add*` moved into `FillableSigningProvider`, thus allowing it to go away entirely. `CCryptoKeyStore`'s functionality is moved into `CWallet`. The new inheritance chain is:
    
      ```
      SigningProvider -> FillableSigningProvider -> CWallet
      ```
    
      `SigningProvider` now is the class the provides keys and scripts and indicates whether keys and scripts are present. `FillableSigningProvider` allows keys and scripts to be added to the signing provider via `Add*` functions. `CWallet` handles all of the watchonly stuff (`AddWatchOnly`, `HaveWatchOnly`, `RemoveWatchOnly` which were previously in `CKeyStore`) and key encryption (previously in `CCryptoKeyStore`).
    
      Implements the 2nd [prerequisite](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/Wallet-Class-Structure-Changes#cwallet-subclass-stack) from the wallet restructure.
    
    ACKs for top commit:
      Sjors:
        re-ACK 93ce4a0; it keeps `EncryptSecret`, `DecryptSecret` and `DecryptKey` in `wallet/crypter.cpp`, but makes them not static. It improves alphabetical includes, reorders some function definitions, fixes commit message, brings back lost code comment.
      instagibbs:
        utACK https://github.com/bitcoin/bitcoin/pull/16227/commits/93ce4a0b6fb54efb1f424a71dfc09cc33307e5b9
    
    Tree-SHA512: 393dfd0623ad2dac38395eb89b862424318d6072f0b7083c92a0d207fd032c48b284f5f2cb13bc492f34557de350c5fee925da02e47daf011c5c6930a721b6d3
```

### CODE REVIEW

**Comment by knst** [comment]
ARM build is failed: https://gitlab.com/dashpay/dash/-/jobs/2679347830
What exactly here is fatal error? I see bunch of warning.
```
A new circular dependency in the form of "hdchain -> wallet/walletdb -> script/sign -> script/signingprovider -> hdchain" appears to have been introduced.
```
This one?

**Comment by UdjinM6** [comment]
> ARM build is failed: https://gitlab.com/dashpay/dash/-/jobs/2679347830 What exactly here is fatal error? I see bunch of warning.
> 
> ```
> A new circular dependency in the form of "hdchain -> wallet/walletdb -> script/sign -> script/signingprovider -> hdchain" appears to have been introduced.
> ```
> 
> This one?

yes, you can "fix" it like that https://github.com/UdjinM6/dash/commit/327b412fd9736873ea4de99e0aefac15e88137c7

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
