### PR TITLE
refactor: begin to de-globalize masternodeSync

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented

minimizing global uses

## What was done?

Started the deglobalization, a future PR should be done to continue this deglobalization

## Breaking Changes

none

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by UdjinM6** [comment]
linter complains:
>A new circular dependency in the form of "masternode/sync -> validation -> masternode/sync" appears to have been introduced.

**Comment by PastaPastaPasta** [comment]
Yup. I see that 👍

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
https://gitlab.com/dashpay/dash/-/jobs/3541868035 👀 smth like https://github.com/UdjinM6/dash/commit/c3b585b1cca0a63fac9cb4cfee751b5cf374321c should help

**Comment by PastaPastaPasta** [comment]
applied

**Comment by UdjinM6** [comment]
pls see https://github.com/UdjinM6/dash/commits/pr5103 for more suggestions

**Comment by PastaPastaPasta** [comment]
Seems all good changes to me. Applied

**Review by UdjinM6 — COMMENTED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]

**Pull request merged**
