### PR TITLE
Backports v0.18: PR 13743: refactor: Replace boost::bind with std::bind

### PR DESCRIPTION
**Pull request by dzutte-cpp**
Fixes:  4340

### CODE REVIEW

**Comment by dzutte-cpp** [comment]
GitLab CI fails on two targets.
For **arm-linux-build**, the failure is reported before this PR with 592cd0a. 
For **linux64-test**, the failure is reported for **feature_llmq_connections.py** which is confusing because it passed alright locally:

```
...
feature_llmq_chainlocks.py            | ✓ Passed  | 42 s
feature_llmq_connections.py           | ✓ Passed  | 28 s
feature_llmq_data_recovery.py         | ✓ Passed  | 121 s
feature_llmq_dkgerrors.py             | ✓ Passed  | 38 s
feature_llmq_is_cl_conflicts.py       | ✓ Passed  | 21 s
feature_llmq_is_retroactive.py        | ✓ Passed  | 121 s
feature_llmq_signing.py               | ✓ Passed  | 53 s
feature_llmq_signing.py --spork21     | ✓ Passed  | 44 s
feature_llmq_simplepose.py            | ✓ Passed  | 143 s
....

ALL                                   | ✓ Passed  | 1937 s (accumulated) 
```

**Comment by PastaPastaPasta** [comment]
> GitLab CI fails on two targets.
> For **arm-linux-build**, the failure is reported before this PR with [592cd0a](https://github.com/dashpay/dash/commit/592cd0a939e283a9cef8d8ef6321a1aec58c0d94).
> For **linux64-test**, the failure is reported for **feature_llmq_connections.py** which is confusing because it passed alright locally:
> 
> ```
> ...
> feature_llmq_chainlocks.py            | ✓ Passed  | 42 s
> feature_llmq_connections.py           | ✓ Passed  | 28 s
> feature_llmq_data_recovery.py         | ✓ Passed  | 121 s
> feature_llmq_dkgerrors.py             | ✓ Passed  | 38 s
> feature_llmq_is_cl_conflicts.py       | ✓ Passed  | 21 s
> feature_llmq_is_retroactive.py        | ✓ Passed  | 121 s
> feature_llmq_signing.py               | ✓ Passed  | 53 s
> feature_llmq_signing.py --spork21     | ✓ Passed  | 44 s
> feature_llmq_simplepose.py            | ✓ Passed  | 143 s
> ....
> 
> ALL                                   | ✓ Passed  | 1937 s (accumulated) 
> ```

Correct, linter failure should be fixed in https://github.com/dashpay/dash/pull/4344

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge, LGTM
```
~/workspace/dash$ git grep -n "bind.hpp"
~/workspace/dash$ git grep -n "boost::bind"
```

**Review by UdjinM6 — APPROVED** [review]
👍 

utACK

**Pull request merged**
