### PR TITLE
backport: bitcoin#13424, #14092, #14380, #14879, #15693, #16185, #16489, #16556, #16806, #16866, #16873, partial #16197, fixes for #10637

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Some backports from bitcoin v19 and earlier

## What was done?
- applied some fixes for bitcoin#10637
- bitcoin#13424
- bitcoin#14092
- bitcoin#14380
- bitcoin#14879
- bitcoin#15693
- bitcoin#16185
- bitcoin#16489
- bitcoin#16556
- bitcoin#16806
- bitcoin#16197
- bitcoin#16866
- bitcoin#16873

## How Has This Been Tested?
Run functional/unit tests

Thanks @UdjinM6 for fixing `test_in_flight_max` in functional test `[p2p_tx_download.py](https://github.com/bitcoin/bitcoin/pull/16197/files#diff-d5657ef7092f5ab95d162966ae1e3e96e0f669d81fe4cde90caa523f8bdfa56c)`

## Breaking Changes
No breaking changes

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by knst** [comment]
> How Has This Been Tested?

1. Please, help me to test backport bitcoin#16477
 -  `contrib/macdeploy/macdeployqtplus`

--------
2. Seems as changes in bitcoin#16197 doesn't work as expected with dash code.
I disabled part  `test_in_flight_max` in functional test `[p2p_tx_download.py](https://github.com/bitcoin/bitcoin/pull/16197/files#diff-d5657ef7092f5ab95d162966ae1e3e96e0f669d81fe4cde90caa523f8bdfa56c)` temporary

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see below + 00b3228839f74771e50e2c08a0fe8c29bba12907 + 01f8813576

**Review by UdjinM6 — DISMISSED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Review by UdjinM6 — APPROVED** [review]
re-utACK

**Pull request merged**
