### PR TITLE
remove SDK download from gitian build script

### PR DESCRIPTION
**Pull request by charlesrocket**
better practice with xcode license. more details [here](https://github.com/bitcoin/bitcoin/pull/14539)

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Concept ACK
```People need to download the SDK from Apple and convert it to the tar.gz themselves. This is for two reasons: 1) security, not trusting some opaque blob provided by the project, and 2) we don't even have a license to distribute this file last I checked (it's full of Apple-copyrighted stuff).```
We might not be breaking any rules by downloading it, but bitcoin (probably) is by hosting it. [XCode License](https://www.apple.com/legal/sla/docs/xcode.pdf)

**Comment by charlesrocket** [comment]
@PastaPastaPasta redistribution is also against the xcode license

**Comment by UdjinM6** [comment]
This solves nothing imo because 
>2.5 Copies
> You agree to retain and reproduce in full the Apple copyright, disclaimers and other proprietary notices in all copies of the Apple Software that You are permitted to make under this Agreement. For clarity, You may copy only the entire package or piece of the Apple Software and Services in its entirety and only for use as permitted herein. You may not alter the Apple Software or Services in any way in such copy, e.g., _You are expressly prohibited from separately using the Apple SDKs or attempting to run any part of the Apple Software on non-Apple-branded hardware._ Images contained in the Documentation may not be separately copied or used outside of the Documentation.

i.e. we (and bitcoin, and all other projects using SDKs in automated builds/CI) are breaking their rules anyway, so ¯\\_(ツ)_/¯

**Comment by charlesrocket** [comment]
@UdjinM6 theres also another side - SDKs have developer account hash from xcode. doesn't look like clang is pulling it for builds outside of xcode tho - trying to get more clarification on this one

**Comment by charlesrocket** [comment]
i guess everybody's down keep violating apple sdk license so this is being closed

**Pull request closed without merging**
