### PR TITLE
Fix sync process

### PR DESCRIPTION
**Pull request by UdjinM6**
Changes:
- `CMasternodeBroadcast` hash compatibility with 70103
- ignore some requests while syncing
- fix locking/initializing in sync

EDIT:
to test this on mainnet you need to temporary disable `SPORK_10_MASTERNODE_PAY_UPDATED_NODES`
```
diff --git a/src/masternode-payments.cpp b/src/masternode-payments.cpp
index e829392..89bb7ef 100644
--- a/src/masternode-payments.cpp
+++ b/src/masternode-payments.cpp
@@ -181,9 +181,7 @@ void CMasternodePayments::FillBlockPayee(CMutableTransaction& txNew, CAmount nFe
 }
 
 int CMasternodePayments::GetMinMasternodePaymentsProto() {
-    return IsSporkActive(SPORK_10_MASTERNODE_PAY_UPDATED_NODES)
-            ? MIN_MASTERNODE_PAYMENT_PROTO_VERSION_2
-            : MIN_MASTERNODE_PAYMENT_PROTO_VERSION_1;
+    return MIN_MASTERNODE_PAYMENT_PROTO_VERSION_1;
 }
 
 void CMasternodePayments::ProcessMessage(CNode* pfrom, std::string& strCommand, CDataStream& vRecv)
```

### CODE REVIEW

**Comment by UdjinM6** [comment]
There are still issues with governance sync:
1) format changed and client is throwing exceptions
2) no nodes on mainnet to receive new messages from so sync never finishes

Regarding (1): we could either simply ignore governance messages from old nodes via `if(pfrom->nVersion < 70201) return;` or we can introduce new messages instead of reusing old ones i.e. we could define both (old) `MNBUDGET*` and (new) `MNGOVERNANCE*` but process only (new) `MNGOVERNANCE*`.

Thoughts?

**Comment by thelazier** [comment]
I would like to vote for defining both (old) and (new) , the migration would be much nicer, IMO.

**Comment by crowning-** [comment]
If you add some deprecated-attribute to the old messages (and probably log them in debug.log)  I'm also for defining both.

**Comment by UdjinM6** [comment]
Rebased, refactored, more fixes for sync, more verbosity for debug.log

**Comment by crowning-** [comment]
ACK

I wasn't able to reproduce every possible scenario, but the things I tested all worked as designed :thumbsup:

**Comment by schinzelh** [comment]
utACK

**Comment by schinzelh** [comment]
Shall we merge or wait for @evan82 feedback? He seems to be rather swamped by sentinel development nowadays :)

**Comment by UdjinM6** [comment]
@schinzelh this one interferes a bit with governance but resolving conflicts there (if any) shouldn't be that hard imo and since there is no strong NO I guess we are ok? ;)

**Comment by crowning-** [comment]
LOVE it :heart:

Much easier to read and understand now.

100% utACK

**Pull request merged**
