### PR TITLE
rpc: spend less time in cs_main lock

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Some of these changes maybe aren't the best, but I think they are

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see https://github.com/UdjinM6/dash/commit/cca12800a5770274f365b174e312dc6131e9e58a

**Review by UdjinM6 — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Ya know, it'd be super nice if our build was like rust, such that if you try to access something in a not threadsafe way, it just won't compile

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
