### PR TITLE
backport: 24306, 24312, 24371

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
A few simple backports

## How Has This Been Tested?
Built locally; see CI

## Breaking Changes
None

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by UdjinM6** [comment]
24306: pls consider 75c504362f

24498: somehow 2030c69b50277ee7d571a72d7b86b36eea0190c7 is a completely different set of changes 🤷‍♂️

**Comment by PastaPastaPasta** [comment]
Both should be resolved; somehow I ended up having the wrong commit message; weird!

**Review by UdjinM6 — APPROVED** [review]
utACK ba7e500062148455cb0157a47d4859984eba49f5

**Review by kwvg — APPROVED** [review]
utACK ba7e500062148455cb0157a47d4859984eba49f5

**Pull request merged**
