### PR TITLE
Backports 0.18 pr6

### PR DESCRIPTION
**Pull request by Munkybooty**

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Pls rebase (make sure to resolve merge conflicts for 14120 correctly, see ~https://github.com/UdjinM6/dash/commit/2619b7e80645fe6cbc8e3bdd0e25cc77f0ce6cec0~) and drop 14135 and 14129 while at it (they were backported in #4220).

**Comment by Munkybooty** [comment]
@UdjinM6 UdjinM6@2619b7e does not seem to lead anywhere.

**Comment by Munkybooty** [comment]
Disregard, now it leads somewhere. thats so strange the link one my comment works

**Comment by UdjinM6** [comment]
That's weird.. and also, my commit was broken somehow. Anyway, you should _rebase_ it and fix merge conflicts, simply _merging_ develop into this branch is not enough. I redid 14120 (after rebase, see https://github.com/UdjinM6/dash/commits/pr4227), c5269526fc0ae67deffcccee835201e4139bc499 should be the right version of it I think.

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
b03ee2a854b276ebdaa5c5910634e815221bcc1a (14120) has some unrelated changes

**Comment by UdjinM6** [comment]
Recent force-push fixed nothing (no changes in https://github.com/dashpay/dash/compare/ee60af0dc01d71430e36f9a3fb4c6b0c9948a318..38c6a595e3472a7290fb537947d94dd0ba48fb36), still have to backport 14120 properly - it should touch `doc/tor.md` only.

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
