### PR TITLE
Fix rpc-tests

### PR DESCRIPTION
**Pull request by UdjinM6**
Relies on PRs #715-#719
Requires https://github.com/dashpay/dash_hash to be installed (we need to fix gitian to do this too, not part of this PR).

### CODE REVIEW

**Comment by schinzelh** [comment]
Merged all of them, many thanks! Let's see if Travis agrees :)

**Comment by UdjinM6** [comment]
thanks! travis most likely will complain though because there is no setup step for dash_hash yet... :/

**Comment by schinzelh** [comment]
Yep, dash_hash not found :-)

**Comment by UdjinM6** [comment]
I actually have a fix for this https://github.com/UdjinM6/dash/commit/989281357999f6137d0269bb090e9944203e4b3d ;)
but now test fails on `proxy_test.py` https://travis-ci.org/UdjinM6/dash/jobs/114089206#L6234 and I have no idea why because it's identical to bitcoin's... :/
and btw `make check` also fails so there is still a lot to fix...

**Comment by schinzelh** [comment]
It fails at https://github.com/dashpay/dash/blob/v0.12.1.x/qa/rpc-tests/proxy_test.py#L59 - guessing without looking deeper: something with IPv6 is broken, as conf3 is the only one using IPv6

**Pull request closed without merging**
