### PR TITLE
added gitian builds for Raspberry Pi

### PR DESCRIPTION
**Pull request by schinzelh**

### CODE REVIEW

**Comment by elbereth** [comment]
Is the tar.gz contain https://github.com/raspberrypi/tools.git ?
If so I will be adding it to my autobuild system.

**Comment by schinzelh** [comment]
Yes, just wget the tarball of master via https://github.com/raspberrypi/tools/tarball/master
It needs a small patch though, will provide it later.

**Comment by schinzelh** [comment]
@elbereth I have put the necessary file at http://static.darkcoin.qa/dash/raspberrypi-tools.tar.gz
Have fun

**Comment by elbereth** [comment]
Oh thanks a lot!

**Pull request merged**
