### PR TITLE
Update travis.yml for disable wallet testing.

### PR DESCRIPTION
**Pull request by thelazier**

### CODE REVIEW

**Comment by UdjinM6** [comment]
I don't think this will have any effect at all, see https://github.com/dashpay/dash/blob/master/depends/README.md

>If some packages are not built, for example make NO_WALLET=1, the appropriate options will be passed to Dash Core's configure. In this case, --disable-wallet.

**Comment by thelazier** [comment]
Please check the effect from the failed travis build log

**Comment by UdjinM6** [comment]
Hmmm... Interesting... but still not convinced :) fails due to a bug I think (should be fixed by https://github.com/dashpay/dash/pull/1991)

**Comment by thelazier** [comment]
Yes, I found the bug then I guess using travis to show you the bug should be better than try fixing the bug. Then, later new pr would not miss this disable wallet failed case again. :)

**Comment by thelazier** [comment]
Anyway, agree with you that this should be fixed somewhere else so the statement in that README.md will be true. Closing this :)

**Pull request closed without merging**
