### PR TITLE
backport: Merge bitcoin#18726,(partial)18628,18544,18672, (partial) 18764

### PR DESCRIPTION
**Pull request by vijaydasmp**

### CODE REVIEW

**Comment by knst** [comment]
just a note: `bitcoin#18628` indeed fails in `p2p_invalid_tx.py`, I can't find a reason why at the moment: https://github.com/dashpay/dash/pull/5541/commits/05802174ab64493f630f74cf13ce5832868d3595#diff-df1d8c6f908e37a0ea01379f94855afcff3448005677c4795b74558c4d277fb6R206

@vijaydasmp maybe you can mark this backport "partial" and exclude `p2p_invalid_tx.py`  changes; or just skip this backport?

**Comment by vijaydasmp** [comment]
> mark this backport "partial" and exclude `p2p_invalid_tx.py`

Hello @knst,  Thanks for checking on this PR , I will mark this backport "partial" and exclude p2p_invalid_tx.py

**Comment by vijaydasmp** [comment]
Hello @knst @UdjinM6 , please review

**Comment by UdjinM6** [comment]
>Check Merge Fast-Forward Only / check_merge (pull_request) Failing after 21s

needs rebase

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
