### PR TITLE
chore: Testnet re-organization required changes

### PR DESCRIPTION
**Pull request by ogabrielides**
## Issue being fixed or feature implemented
Dropped all changes made so far to be able to sync Testnet.

## Breaking Changes
Testnet syncing obviously

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by ogabrielides** [comment]
@UdjinM6 @PastaPastaPasta @knst Marking this as draft for now.
Please review if I forgot something so far

**Review by PastaPastaPasta — DISMISSED** [review]
ACK for squash merge

Tested via checking out branch and `git grep "TODO.*testnet"`

**Review by PastaPastaPasta — APPROVED** [review]
re-ACK; did same git grep

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
