### PR TITLE
test: fixes and improvements for `feature_llmq_simplepose.py`

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
Fix some general mistakes and also `connect_nodes` related issues discovered while debugging #6276. Add some logging to make debugging a bit easier.

~NOTE: builds on top of #6278 to avoid conflicts, will rebase~ done

## What was done?
pls see individual commits

## How Has This Been Tested?
run tests

## Breaking Changes
n/a

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
6278 merged

**Comment by knst** [comment]
_just some semi-relevant feedback on PR_

CI: only one failure out of 5 (for linux64-multiprocess): https://gitlab.com/dashpay/dash/-/jobs/7917711153
```
feature_llmq_simplepose.py failed at attempt 1/3, Duration: 71 s
37/265 - feature_llmq_simplepose.py passed, Duration: 225 s
```

I run this version on my laptop in many threads and observed various different failures:

Beside 40 successful runs I noticed these failures,

 - 3 times for `check_banned`:
```
2024-09-26T07:16:25.800000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 160, in main
    self.run_test()
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 34, in run_test
    self.test_banning(self.isolate_mn, 2)
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 191, in test_banning
    assert self.check_banned(mn)
AssertionError
```
 - once `not punished no banned`:
```
2024-09-26T07:23:54.730000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 160, in main
    self.run_test()
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 31, in run_test
    self.test_no_banning()
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 98, in test_no_banning
    assert not self.check_punished(mn) and not self.check_banned(mn)
AssertionError
```

 - once `no quorum`:
```
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 48, in run_test
    self.test_banning(self.close_mn_port)
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 189, in test_banning
    self.mine_quorum_less_checks(expected_contributors - 1, mninfos_online)
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 148, in mine_quorum_less_checks
    self.wait_for_quorum_list(q, nodes)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 1779, in wait_for_quorum_list
    wait_until_helper(wait_func, timeout=timeout, sleep=sleep)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/util.py", line 262, in wait_until_helper
    raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
AssertionError: Predicate ''''
        def wait_func():
            self.log.info("quorums: " + str(self.nodes[0].quorum("list")))
            if quorum_hash in self.nodes[0].quorum("list")[llmq_type_name]:
                return True
            self.bump_mocktime(sleep, nodes=nodes)
            self.nodes[0].generate(1)
            self.sync_blocks(nodes)
            return False
''' not true after 15.0 seconds
```


 - once failed at `contribution` stage for quorum:
```
2024-09-26T07:23:49.843000Z TestFramework (INFO): Waiting for phase 2 (contribute)
2024-09-26T07:24:19.901000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''
        def check_dkg_session():
            member_count = 0
            for mn in mninfos:
                s = mn.node.quorum("dkgstatus")["session"]
                for qs in s:
                    if qs["llmqType"] != llmq_type_name:
                        continue
                    qstatus = qs["status"]
                    if qstatus["quorumHash"] != quorum_hash:
                        continue
                    if qstatus["phase"] != phase:
                        return False
                    if check_received_messages is not None:
                        if qstatus[check_received_messages] < check_received_messages_count:
                            return False
                    member_count += 1
                    break
            return member_count >= expected_member_count
'''
2024-09-26T07:24:19.902000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 160, in main
    self.run_test()
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 31, in run_test
    self.test_no_banning()
  File "/home/knst/projects/dash-reviews/test/functional/feature_llmq_simplepose.py", line 96, in test_no_banning
    self.mine_quorum(expected_connections=expected_connections)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 1839, in mine_quorum
    self.wait_for_quorum_phase(q, 2, expected_members, "receivedContributions", expected_contributions, mninfos_online, llmq_type_name=llmq_type_name)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/test_framework.py", line 1747, in wait_for_quorum_phase
    wait_until_helper(check_dkg_session, timeout=timeout, sleep=sleep)
  File "/home/knst/projects/dash-reviews/test/functional/test_framework/util.py", line 262, in wait_until_helper
    raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
```

**Review by knst — APPROVED** [review]
ACK a656d2f14f7f44609787b9ee10ae069a9b8dac97

**Review by PastaPastaPasta — APPROVED** [review]
utACK a656d2f14f7f44609787b9ee10ae069a9b8dac97

**Pull request merged**
