### PR TITLE
Backport 0.17 pr27

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Relatively small PR that enables support for setting pruning in qt. qt might need minor formatting tweaks pls @xdustinface

### CODE REVIEW

**Review by xdustinface — CHANGES_REQUESTED** [review]
@PastaPastaPasta see https://github.com/xdustinface/dash/tree/suggestions-4097

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Pls see https://github.com/UdjinM6/dash/commit/78f048f8127f4e92f57ec96fa99c115bc26dd7db

**Comment by PastaPastaPasta** [comment]
picked

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
