### PR TITLE
Net: Make tor connections off by default

### PR DESCRIPTION
**Pull request by akhavr**
Right now `dash-qt` wallet tries to connect to a tor service even if it wasn't configured to `-listen`.  I guess not many users of the QT wallet do connect through tor.
This pollutes `debug.log` file with useless messages and intervenes actual debugging.

In case one is running `dashd` with the intent of relaying on tor, he could turn it back with a CLI option `-listenonion=1`

### CODE REVIEW

**Comment by UdjinM6** [comment]
Few notes:
1. Please update PR description with the reason why you think the default behaviour should be changed
2. You have to update `doc/tor.md` to match the new default behaviour
3. It's `net`, not `wallet` :)

**Comment by akhavr** [comment]
Updated PR title and `doc/tor.md`

**Comment by UdjinM6** [comment]
>Right now dash-qt wallet tries to connect to a tor service even if it wasn't configured to -listen

Hmmm. So the _actual_ issue is qt wallet not quite respecting the behaviour described in docs atm, right?

**Comment by UdjinM6** [comment]
Pls see/test #3190

**Comment by akhavr** [comment]
I'm not sure that `dashd` should listen to tor by default, if told to `-listen`.  Are tor setups frequent in your practice?

**Comment by UdjinM6** [comment]
I have no exact data on how many people use dash+tor but I would guess you can count them on fingers, that's true. Make it even harder to run won't help to improve this situation however.

Anyway, I'm trying to reproduce the log spam issue you mentioned and I can't tbh. Do I need to tweak some some specific settings in dash.conf/Network tab in Options to reproduce it? Anything else I might need?

**Comment by akhavr** [comment]
I've not tried clean copy of full dash node.  Do you have tor service running?  I do, but I've not configured it nor I configured `dashd` to connect to tor.

My `dash.conf` is 

```
rpcuser=darkcoinrpc
rpcpassword=******
rpcallowip=127.0.0.1
#listen=1
#server=1
#daemon=1
logtimestamps=1
maxconnections=256
wallet=mn.dat
```

**Comment by UdjinM6** [comment]
Ok, so I installed 0.14.0.3 from scratch on a fresh new machine but I still can't reproduce the issue. Initially, it just does nothing unusual and there are no lines with `tor:` string in debug.log. Next, I added `ControlPort 9051` into `/usr/share/tor/tor-service-defaults-torrc` and this time there is one line at node start `tor: Authentication cookie /var/run/tor/control.authcookie could not be opened (check permissions)` which is expected. After adding `dash` user (the one  `dashd` is running under) to `debian-tor` group via `sudo usermod -a -G debian-tor dash` it just starts as it should - `tor: Got service ID mxolubx2bq7caaiq, advertising service mxolubx2bq7caaiq.onion:9999` and `AddLocal(mxolubx2bq7caaiq.onion:9999,4)`. There must be smth in some config on your side which is causing the issue I think but I'm not very familiar with tor config options to guess what it is exactly 🙈

**Comment by codablock** [comment]
@akhavr is this about the "tor: Error connecting to Tor control socket" log message regularly appearing in logs?

**Comment by codablock** [comment]
Digging more into this, I see that https://github.com/dashpay/dash/blob/e0781095f0d797c978fa25d2e0afb4b6dbffddfe/src/init.cpp#L955 should do what is described in the tor.md docs. It disables `-listenonion` when `-listen` is disabled. As far as I can see, this works as expected on my nodes.

@akhavr Can you give examples of the log pollution you've seen? This would make it easier to trace the origin of the misbehavior.

**Comment by codablock** [comment]
Any new on this? Or should we close this PR?

**Comment by UdjinM6** [comment]
Closing this until there are clear steps to reproduce the issue this PR was meant to fix.

**Pull request closed without merging**
