### PR TITLE
refactor: remove all the unneeded and unused (probably broken) travis stuff

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
We don't use travis. There's no need to continue having this in the repo.

tested via `git grep "travis"`

### CODE REVIEW

**Review by Munkybooty — COMMENTED** [review]
- `src/univalue/.travis.yml`
- `src/crc32c/.travis.yml`
- `src/leveldb/.travis.yml`
Would we not also have to remove these as well?

**Comment by PastaPastaPasta** [comment]
No, imo we probably shouldn't since they are a part of git subtrees.

**Review by UdjinM6 — APPROVED** [review]
Pretty sure there is a PR to backport for this but utACK :)

**Review by kittywhiskers — COMMENTED** [review]
Postmortem NACK.

Even if we don't use it, it is a part of the official source tree and it interferes with reconciling the differences between Dash's and Bitcoin's CI system, efforts for which were ongoing. Proposing a revert.

**Comment by Munkybooty** [comment]
post-NACK 

I will have to agree with kittywhiskers on this, after looking through Bitcoin's repo, i found the backport that Udjin was referring too, however it mostly renames and reworks travis. #16582 is the first in a long series of CI changes involving travis

**Comment by PastaPastaPasta** [comment]
Feel free to revert this as part of a future PR if you intend to actually unify our build system, but we shouldn't keep an unsupported ci system just because it exists, just as we don't have a number of rbf related files that bitcoin does, because we don't support them, and they'd probably be broken.

**Comment by kittywhiskers** [comment]
[This branch](https://github.com/kittywhiskers/dash/commits/overhaul_ci) was originally going to be part of the Docker PR but since it was too differing in scope, it was separated. This PR causes conflicts in https://github.com/dashpay/dash/pull/4336 so it'll need to be reverted, will do so in https://github.com/dashpay/dash/pull/4336.

**Pull request merged**
