### PR TITLE
fix: add missing includes and remove obsolete includes

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Some headers or modules are used objects from STL without including it directly, it cause compilation failures on some platforms for some specific compilers such as #5554

## What was done?
Added missing includes and removed obsolete includes for `optional`, `deque`, `tuple`, `unordered_set`, `unordered_map`, `set` and `atomic`.

Please, note, that this PR doesn't cover all cases, only cases when it is obviously missing or obviously obsolete.

Also most of changes belongs to to dash specific code; but for cases of original bitcoin code I keep it untouched, such as missing <map> in `src/psbt.h`

I used this script to get a list of files/headers which looks suspicious `./headers-scanner.sh std::optional optional`:
```bash
#!/bin/bash

set -e

function check_includes() {
    obj=$1
    header=$2
    file=$3

    used=0
    included=0

    grep "$obj" "$file" >/dev/null 2>/dev/null && used=1
    grep "include <$header>" $file >/dev/null 2>/dev/null && included=1
    if [ $used == 1 ] && [ $included == 0 ]
        then echo "missing <$header> in $file"
    fi
    if [ $used == 0 ] && [ $included == 1 ]
        then echo "obsolete <$header> in $file"
    fi
}
export -f check_includes

obj=$1
header=$2

find src \( -name '*.h' -or -name '*.cpp' -or -name '*.hpp' \) -exec bash -c 'check_includes "$0" "$1" "$2"'  "$obj" "$header"  {} \;
```

## How Has This Been Tested?
Built code locally

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by UdjinM6** [comment]
LGTM but let's merge conflicting backports (#5546) first

**Review by ogabrielides — APPROVED** [review]
ACK

**Comment by knst** [comment]
> LGTM but let's merge conflicting backports (https://github.com/dashpay/dash/pull/5546) first

I updated commit a bit to avoid conflict with #5546, please, check @UdjinM6 

> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/a5258b25e95b161915ff26e0ac9dfddd5ff52449..423c9222fc65c8d5475a51ac4349f31bd884c806) the fix-headers branch from[ a5258b2 ](https://github.com/dashpay/dash/commit/a5258b25e95b161915ff26e0ac9dfddd5ff52449)to 423c922

**Comment by UdjinM6** [comment]
Hmmm... but it breaks sorting for includes, I wouldn't do that. Let's ping @PastaPastaPasta and ask him to review #5546 ASAP (and then this PR after a rebase) instead and hope for the best :D

**Comment by thephez** [comment]
Just got this one when trying to build `v20.0.0-beta.1` (`bc6360f6a`)

```
In file included from ./rpc/util.h:8,
                 from test/script_tests.cpp:9:
./node/coinstats.h:39:10: error: ‘optional’ in namespace ‘std’ does not name a template type
   39 |     std::optional<CAmount> total_amount{0};
      |          ^~~~~~~~
./node/coinstats.h:13:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
   12 | #include <streams.h>
  +++ |+#include <optional>
   13 | #include <uint256.h>
```

**Comment by knst** [comment]
> Hmmm... but it breaks sorting for includes, I wouldn't do that. Let's ping @PastaPastaPasta and ask him to review https://github.com/dashpay/dash/pull/5546 ASAP (and then this PR after a rebase) instead and hope for the best :D

Pulled latest develop, reverted re-ordering headers (assumed to avoid conflict) and added to more <optional> in `src/util/overflow.h` and `src/node/coinstats.h`

**Review by thephez — APPROVED** [review]
ACK - this is builds for me

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by ogabrielides — APPROVED** [review]
ACK

**Comment by knst** [comment]
@PastaPastaPasta please review it soon, `develop` fails without this PR on my workstation:

```
  CXX      test/test_dash-streams_tests.o
In file included from ./rpc/util.h:8,
                 from test/script_tests.cpp:9:
./node/coinstats.h:39:10: error: ‘optional’ in namespace ‘std’ does not name a template type
   39 |     std::optional<CAmount> total_amount{0};
      |          ^~~~~~~~
./node/coinstats.h:13:1: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
   12 | #include <streams.h>
  +++ |+#include <optional>
   13 | #include <uint256.h>
```

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
