### PR TITLE
Collection of PRs and single commits missed in previous backports

### PR DESCRIPTION
**Pull request by codablock**
This PR contains a few full PR backports and individual commits from PRs that I decided to not backport (e.g. RBF, or SegWit related).

I'll do another PR later for more individual commits that were part of compact block related PRs.

Sources of commits in this PR:
Full PR: https://github.com/bitcoin/bitcoin/pull/9114
Part of https://github.com/bitcoin/bitcoin/pull/8309: fa9976b853dbd04334cd0b5a058b99aa0014e649
Full PR:  https://github.com/bitcoin/bitcoin/pull/9650
Parts https://github.com/bitcoin/bitcoin/pull/8456: 766e8a40b478353a89622f42809ddb11e695a0c9 and 52dde66770d833ee5e42e7c5fee610453ae3852a
Full PR: https://github.com/bitcoin/bitcoin/pull/9486
Full PR: https://github.com/bitcoin/bitcoin/pull/7166

### CODE REVIEW

**Comment by UdjinM6** [comment]
Hmm... `IsAllFromMe` doesn't seem to be used anywhere in Dash (yet?)

**Comment by codablock** [comment]
Hmm yeah, I assumed it might be useful in the future but I checked Bitcoin 0.15 now and even there it is only used for RBF. Should I remove that commit?

**Comment by UdjinM6** [comment]
SO I guess we are missing some other RBF-related changes then, right? We already have some RBF-related code in Dash, it's just disabled by default so maybe it's better to backport these missing fixes too instead?

**Comment by codablock** [comment]
The only RBF related PRs that I left out were related to RPC changes or which added new ways to enable RBF. We should be safe without these PRs.

So what about IsAllFromMe? Remove it?

**Pull request merged**
