### PR TITLE
chore: update dash_hash install and instructions

### PR DESCRIPTION
**Pull request by thephez**
## Issue being fixed or feature implemented
Install of dash_hash will change once https://github.com/dashpay/dash_hash/pull/17/ is merged

## What was done?
- Changed install instructions to match new install in dash_hash README
- Updated Dockerfile to install correctly

## How Has This Been Tested?
N/A

## Breaking Changes
None

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by knst** [comment]
Maybe better to use pushd instead cd:
`pushd dash_has && pip3 .... && popd`

**Review by knst — DISMISSED** [review]
utACK

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
`bin/sh: 1: pushd: not found`
https://gitlab.com/dashpay/dash/-/jobs/4060116494

**Comment by thephez** [comment]
Converted to draft since it can't pass tests until the dash_hash PR is merged

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
