### PR TITLE
Backport rpcauth

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
This should update rpcauth to the latest

(I'm investigating using rpcauth to restrict platform / L2 to specific commands / rate limiting, so expect that in the somewhat not near near future)

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Re 13051 looks like a good idea, so backported, currently causing tests to fail. I can't spend any more time on it for this moment, so if one of you want to look into why tests are failing that'd be cool

**Comment by xdustinface** [comment]
Which tests did you see fail? `rpc_users.py` works again standalone + still through `test_runner.py` and CI is happy! So it seems its all good?

**Comment by PastaPastaPasta** [comment]
Hmm, rpc_users.py was failing both when ran via test_runner and stand alone... Weird. Will take a look again tonight

**Comment by PastaPastaPasta** [comment]
okay, reorganized commits a bit. Ready for review

**Pull request merged**
