### PR TITLE
fix: non-aligned BLS serialization within MNLISTDIFF

### PR DESCRIPTION
**Pull request by ogabrielides**
## Issue being fixed or feature implemented

When constructing `CSimplifiedMNListDiff`, `CSimplifiedMNListDiff::nVersion` is set to 2 if the v19 fork is active.
It turns out that `CSimplifiedMNListEntry::nVersion` wasn't set to 2 as well as it was supposed.

Because we used `emplace_back` when filling the list of `CSimplifiedMNListEntry`, this actually constructed the object with the default value of 1 instead of copying it.

Surprising but I managed to see that while debugging.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Concept ACK, but I'd prefer something like below as we discussed on our call just now

```
Subject: [PATCH] fix
---
Index: src/evo/deterministicmns.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/evo/deterministicmns.cpp b/src/evo/deterministicmns.cpp
--- a/src/evo/deterministicmns.cpp	(revision a9709b61d466e42ddb70d9c00df47ea3d55e33e7)
+++ b/src/evo/deterministicmns.cpp	(date 1673375150308)
@@ -361,16 +361,15 @@
         if (fromPtr == nullptr) {
             CSimplifiedMNListEntry sme(toPtr);
             sme.nVersion = diffRet.nVersion;
-            diffRet.mnList.emplace_back(toPtr);
+            diffRet.mnList.push_back(std::move(sme));
         } else {
             CSimplifiedMNListEntry sme1(toPtr);
             CSimplifiedMNListEntry sme2(*fromPtr);
             sme1.nVersion = diffRet.nVersion;
             sme2.nVersion = diffRet.nVersion;
-            if (sme1 != sme2) {
-                diffRet.mnList.emplace_back(toPtr);
-            } else if (extended && (sme1.scriptPayout != sme2.scriptPayout || sme1.scriptOperatorPayout != sme2.scriptOperatorPayout)) {
-                diffRet.mnList.emplace_back(toPtr);
+            if ((sme1 != sme2) ||
+                    (extended && (sme1.scriptPayout != sme2.scriptPayout || sme1.scriptOperatorPayout != sme2.scriptOperatorPayout))) {
+                diffRet.mnList.push_back(toPtr);
             }
         }
     });
```

**Comment by ogabrielides** [comment]
@PastaPastaPasta Done!

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
