### PR TITLE
backport: merge bitcoin#23842, #24714, #21059, #23994, #19866, #19935, #23756, #19064, #23411, #20080 (util backports)

### PR DESCRIPTION
**Pull request by kwvg**
### Additional Information

* Dependency for #5337
* Earlier variants of backporting [bitcoin#19064](https://github.com/bitcoin/bitcoin/pull/19064) resulted in consistent `UnicodeDecodeError` terminations when running `combine_logs.py` ([GitLab build](https://gitlab.com/dashpay/dash/-/jobs/4938814052#L465), [again](https://gitlab.com/dashpay/dash/-/jobs/4938020244#L462) and [again](https://gitlab.com/dashpay/dash/-/jobs/4937781814#L463))
  * This has been resolved with squashing changes from 208abd4668ed3265f97f4844c43c36aa057773d4 into the backport (Thanks @UdjinM6!)

### CODE REVIEW

**Comment by knst** [comment]
I feel like it is not good idea for rushing with backports such as "merge [bitcoin#22976](https://github.com/bitcoin/bitcoin/pull/22976): Rename overloaded int GetArg to GetIntArg"

By rough estimation, there are more than 500 backports to do, and each of them who use old version of `GetArg` will create an extra conflict that requires a manual resolving.

Of course, each particular fix in each particular case is trivial, the compiler even will show it as a compilation error, so, it won't cause any real issue.

But disadvantage of doing #22976 at this moment is an overall slowdown of backporting process. Current backport status of full coverage (98-99%) at this point in [v21](https://docs.google.com/spreadsheets/d/1DnKxat0S0H62CJOzXpKGPXTa8hgoVOjGYZzoClmGSB8/edit?pli=1#gid=331846632):

> 	Q_Staged (merged to knstqq local repo)	ae32e5ce3d	Merge #18669: log: Use Join() helper when listing log categories		FALSE	8/21/2023	3	3	FALSE

If get list all of commit between them 22976 and 18669:

```
 git rev-list --ancestry-path ae32e5ce3d..825f4a64e612dab62cd0a73b2afe32dac5e0c69f
```

and grep  'GetArg' after that:
```
git rev-list --ancestry-path ae32e5ce3d..825f4a64e612dab62cd0a73b2afe32dac5e0c69f^ | xargs git show  | grep "\<GetArg\>"  | grep '^[+-]' -c
477
```

There's 477 particular usage of `GetArg` and even assuming that 50% of this changes are already backported, it is still huge amount.

It means that all trivial changes such as this https://github.com/bitcoin/bitcoin/pull/21056/files
```
+    const int timeout = gArgs.GetArg("-rpcwaittimeout", DEFAULT_WAIT_CLIENT_TIMEOUT);
+    const int64_t deadline = GetTime<std::chrono::seconds>().count() + timeout;
```
will require one extra manual conflict resolving/compilation fix.

@kwvg may I ask you to don't backports any big refactorings from v22 or later until the gap is so long?

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by knst — COMMENTED** [review]
These backports LGTM: bitcoin#24714, #21059, #23994, #19866, #19935, #23756, #19064, #23411, #20080 (all except 23842)

https://github.com/bitcoin/bitcoin/pull/23842/files
there's missing changes for:
> src/dummywallet.cpp
> src/qt/test/wallettests.cpp
> src/qt/test/addressbooktests.cpp

And they are missing not because they are forgotten, but because there huge refactoring that seems preemptive to for me. 

It's almost last PR from bitcoin v23 but a coverage of backports for v21, v22 and v23 are 62.33%, 39.32%, 16.74%

I don't feel like it is a time to do it :D especially because it's a scripted refactoring (rename of interfaces/variables) - no any new feature, fixes or improvements.


btw, utACK (whatever with 23842 or without, because seems as amount of possible conflicts in future is manageable few)

**Comment by kwvg** [comment]
> I don't feel like it is a time to do it :D especially because it's a scripted refactoring (rename of interfaces/variables) - no any new feature, fixes or improvements.

Wasn't a fan of it either myself (had to change my other pull requests to match this newer convention as I've rebased them on top of squashed versions of this PR) but subsequent feature backports assume this new naming convention and I have to therefore pick between changing them now or modifying the backport to use the old naming convention and since the changes were imo manageable, the latter seemed like an unattractive option.

> It's almost last PR from bitcoin v23 but a coverage of backports for v21, v22 and v23 are 62.33%, 39.32%, 16.74%

Backporting to ensure feature parity means skipping ahead at times. That is never fun from the perspective of backporting chronologically. Feature parity attempts to make up for the lag in upstream parity by selectively backporting the most impactful segments of the codebase (and is sometimes forced upon downstream projects if features are depending on projects that are deprecating components said features require)

It does help to somewhat close the gap but, is a balancing act between being as prolific as possible and making sure that chronological backports don't become painful.

**Review by knst — DISMISSED** [review]
as I mentioned before:

> btw, utACK (whatever with 23842 or without, because seems as amount of possible conflicts in future is manageable few)

**Comment by PastaPastaPasta** [comment]
> subsequent feature backports

Which feature backports require 23842?

**Comment by knst** [comment]
> Which feature backports require 23842?

Lint failure in other PR #5337 if remember correctly

**Comment by kwvg** [comment]
Rebased on top of `develop` (3507b4a721f952352b42ae55bab0c1f35b032699) to resolve conflicts

**Review by UdjinM6 — APPROVED** [review]
re-utACK

**Review by knst — APPROVED** [review]
re-utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
