### PR TITLE
[UI] Overviewpage digits and number of recent transactions changed

### PR DESCRIPTION
**Pull request by crowning-**
Reference: https://github.com/dashpay/dash/issues/816

Internally still all available digits are used for computations, see _"Selected amount"_ in the second screenshot. Default setting is (still) 2 digits.

Overview Page:
overview

Transactions:
transactions

### CODE REVIEW

**Comment by akijuh** [comment]
Excellent, you also made transactions tab to follow digits setting.

**Comment by crowning-** [comment]
Nope, the digits are chopped off.

**Comment by UdjinM6** [comment]
I like the consistency of amounts on overview screen with these changes. Not sure about transactions screen though which was meant to be detailed info for what you see on overview screen. This also brings inconsistency among displayed rows and selected amount and I don't really like that tbh. @evan82 @schinzelh ?

Also I think that it looks weird with 7 latest tx and simplified PS UI now... :-/ Maybe it's would be better to keep it 5 for now and push a code to make it PS UI option dependent a bit later (on -> 7, off -> 5). I actually already have this implemented as a proof of idea and it looks nicer when it adapts to settings imo. Can clean it up a bit and push a PR.

**Comment by schinzelh** [comment]
@UdjinM6 I did not engage in the original discussion of introducing this feature, so no vote from me here, but

- From technical point of view i don't like rounding/chop off of amounts at all - it's simply inconsistent.
- From UX point of view i can understand that the user is not comfortable with 8 decimal digits.

**Comment by akijuh** [comment]
I agree with @UdjinM6 in his last post.

**Comment by UdjinM6** [comment]
@schinzelh ok, thanks. I'm kind of ok with amounts chopping on overview screen because:
- we have settings for that, user can choose how many digits is ok for him _personally_
- it's an overview screen which should not be way too overcomplicated and cutting off lots of insignificant digits helps to achieve this imo

But transaction list tab is another story and should have precise info all the time imo.

**Comment by crowning-** [comment]
Okay, so if nobody disagrees we will:
- revert the transaction-screen back to display all available digits (I'll do that today after work)
- make the number of recent transactions dependent on the screen setting ( @UdjinM6 creates a PR for this).

**Comment by crowning-** [comment]
Transaction-screen reverted to always show all digits.

Waiting for @UdjinM6 waiting

**Comment by UdjinM6** [comment]
Revert `NUM_ITEMS` also pls and see #872 for my part :)

**Comment by crowning-** [comment]
I thought you would do it while you're at it...

Anyway, done :-)

**Comment by UdjinM6** [comment]
Nice, thanks!
ACK squash merge 1f707ab

**Pull request merged**
