### PR TITLE
backport: bitcoin#21694 (Use XLIFF file to provide more context to Transifex)

### PR DESCRIPTION
**Pull request by kittywhiskers**
## Additional Notes

* Depends on https://github.com/dashpay/dash/pull/4830

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
please mark as ready to review once 4830 is merged

**Comment by kittywhiskers** [comment]
Because the Docker container does more than CI ever since https://github.com/dashpay/dash/pull/4336 was merged. It now serves as a "base container" which can be appropriated for CI or development, I use it for the latter and to generate the contents of 26fa69bdfdf1974a1f5f1c63bee3c68ff0977967, I required to add support for it in the base container.

**Review by UdjinM6 — APPROVED** [review]
makes sense, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
