### PR TITLE
backport: merge bitcoin#22741, #22788, #23207, #23300, partial bitcoin#22550 (moving `generate*` to TestFramework)

### PR DESCRIPTION
**Pull request by kwvg**
## Additional Information

* [bitcoin#23207](https://github.com/bitcoin/bitcoin/pull/23207) has been marked partial as `test/functional/wallet_transactiontime_rescan.py` has not been backported yet.
* [bitcoin#22550](https://github.com/bitcoin/bitcoin/pull/22550) has been partially backported to track changes to `generate_to_height()` made in successive backports.
* <table>
  <tr>
  <td>

  `develop` ([`5a0479fe`](https://github.com/dashpay/dash/commit/5a0479fe53868569ceb31f988e2ad8840dfa77fc), [build](https://gitlab.com/dashpay/dash/-/jobs/7968420284#L640))

  </td>
  <td>

  `dash#6288` ([`ecb51351`](https://github.com/dashpay/dash/commit/ecb51351d1d24c747dc0bbcc87345ed588d0d517), [build](https://gitlab.com/dashpay/dash/-/jobs/7968651474#L612))

  </td>
  </tr>
  <tr>
  <td>

  ```
  Running Unit Tests for Test Framework Modules
                         
  ----------------------------------------------------------------------
  Ran 18 tests in 32.370s
  OK
  1/266 - wallet_hd.py --legacy-wallet passed, Duration: 12 s
  [...]
  feature_bind_port_discover.py                      | ○ Skipped | 1 s
  feature_bind_port_externalip.py                    | ○ Skipped | 1 s
  interface_usdt_net.py                              | ○ Skipped | 1 s
  interface_usdt_utxocache.py                        | ○ Skipped | 1 s
  interface_usdt_validation.py                       | ○ Skipped | 1 s
  rpc_bind.py --ipv6                                 | ○ Skipped | 1 s
  ALL                                                | ✓ Passed  | 6961 s (accumulated) 
  Runtime: 1779 s
  ```

  </td>
  <td>

  ```
  Running Unit Tests for Test Framework Modules
                          
  ----------------------------------------------------------------------
  Ran 18 tests in 32.318s
  OK
  1/266 - wallet_hd.py --legacy-wallet passed, Duration: 19 s
  [...]
  feature_bind_port_discover.py                      | ○ Skipped | 1 s
  feature_bind_port_externalip.py                    | ○ Skipped | 1 s
  interface_usdt_net.py                              | ○ Skipped | 1 s
  interface_usdt_utxocache.py                        | ○ Skipped | 1 s
  interface_usdt_validation.py                       | ○ Skipped | 1 s
  rpc_bind.py --ipv6                                 | ○ Skipped | 1 s
  ALL                                                | ✓ Passed  | 7048 s (accumulated) 
  Runtime: 1825 s
  ```

  </td>
  </tr>
  </table>

## Breaking Changes

None expected.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas **(note: N/A)**
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation **(note: N/A)**
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by UdjinM6 — DISMISSED** [review]
utACK ecb51351d1d24c747dc0bbcc87345ed588d0d517

**Review by UdjinM6 — APPROVED** [review]
utACK 4a4905ac32b67b085a1f94ca575b1335ced006f6

**Comment by PastaPastaPasta** [comment]
LGTM; lets mark
```
partial bitcoin#22741: Add generate* calls to test framework
partial bitcoin#23207: Delete generate* calls from TestNode
```
as fully done; the stuff they exclude will be trivially detected as soon as someone backports those scripts because they will fail :) it's just annoying to have these as "partial" for no real benefit to maintaining imo.

**Review by PastaPastaPasta — APPROVED** [review]
utACK 131d16133c656adc66717bfc819c5751d59a7f6c; no diff rebase, going to merge

**Pull request merged**
