### PR TITLE
backport: final v19.2 backports, v19.2.0 release notes and version bump

### PR DESCRIPTION
**Pull request by UdjinM6**
## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Review by PastaPastaPasta — APPROVED** [review]
ACK for merging via merge commit

**Review by PastaPastaPasta — APPROVED** [review]
trivial diff; 
ACK for merging via merge commit

**Review by thephez — COMMENTED** [review]
Post-merge utACK

**Pull request merged**
