### PR TITLE
build: downgrade to python 3.8, consistently use focal across images and documentation

### PR DESCRIPTION
**Pull request by kittywhiskers**
## Description

The codebase contains references to Ubuntu 18.04 (`bionic`), which has surpassed its EoSS* in May 2023 ([source](https://ubuntu.com//blog/18-04-end-of-standard-support)), mostly in Dash-specific CI and Gitian, which was being sunset around the time period Ubuntu 14.04 (`trusty`) was still being deployed ([source](https://github.com/bitcoin/bitcoin/commit/bb174e19bc0e91854c40269cf8214943d70049a2)). 

https://github.com/dashpay/dash/pull/4717 bumped the reported minimum Python version to 3.10, a version not available on `focal` as of this writing ([source](https://packages.ubuntu.com/focal/python3)). `focal` does optionally offer the ability to use 3.9 ([source](https://packages.ubuntu.com/focal/python3.9)) but not 3.10 ([source](https://packages.ubuntu.com/focal/python3.10), error page).

The bumping to 3.10 did not include the addition of alias detection for current releases, which would be available through rolling release distros, or itself, as `python3.10`. In light of that, it was reverted and pull requests related to Python being bumped have been backported.

Bitcoin currently asserts the minimum Python version as 3.8, which is the same version offered by default on `focal` and so this pull request doesn't assert the minimum version as 3.10. Should Dash choose to move its base distribution to Ubuntu 22.04 (`jammy`), then the minimum version can be set to 3.10.

_\* - EoSS is not EoL, `bionic`'s EoL is in 2028 as its currently within its extended support cycle_

## Additional Notes

References to Debian Stretch (which reached EoL in June 2022, [source](https://www.debian.org/releases/stretch/)) will be replaced with Buster with backports like https://github.com/bitcoin/bitcoin/pull/27029 and so have been left untouched here for now.

https://github.com/bitcoin/bitcoin/pull/18705 needed to be backported as its a) no longer support `trusty` and b) it interferes with the scripted-diff verification script (see [build](https://gitlab.com/dashpay/dash/-/jobs/4257545356))

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
I was pretty concerned about this, but actually it seems this version is supported on m1 macs now. 👍 however, tbh I'm thinking we should update everything to jammy

**Comment by kittywhiskers** [comment]
Currently the emphasis of this PR is to harmonize references to current running base image. I'm not against moving to `jammy` but `focal`'s EoSS is in April 2025 ([source](https://wiki.ubuntu.com/Releases)), which means it's still actively deployed and should be tested against.

**Comment by PastaPastaPasta** [comment]
> Currently the emphasis of this PR is to harmonize references to current running base image. I'm not against moving to `jammy` but `focal`'s EoSS is in April 2025 ([source](https://wiki.ubuntu.com/Releases)), which means it's still actively deployed and should be tested against, at least till the end of 2024.

Well, I'm not sure I agree with that fully: that we HAVE to test against focal as well. I think it would be fine if we just moved everything over to jammy. We should definitely maintain binary support for it, but we don't really need to retain development support for it.

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
