### PR TITLE
Backports 0.16 pr17

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
test failure seems unrelated, tests still fail after merging codablocks latest PR in test branch (https://travis-ci.com/github/PastaPastaPasta/dash/builds/159966024). Travis is somewhat happy with the tests though.

**Comment by UdjinM6** [comment]
f1d026e/#13652 is missing some previous pr which introduced `signrawtransactionwithwallet` rpc

**Comment by PastaPastaPasta** [comment]
@UdjinM6 That's weird... https://github.com/bitcoin/bitcoin/pull/10579 is the PR which adds `signrawtransactionwithwallet` but this PR was merged into 0.17 and as far as I can tell never backported to 0.16, whereas #13652 was merged into 0.17 but backported to 0.16 in github.com/bitcoin/bitcoin/commit/20461fc27

**Comment by PastaPastaPasta** [comment]
Ahh, I see, the backported commit, is using the old RPC. How do you think I should resolve this? should I drop #13652 and pick it up when I reach it in 0.17 backports or should I backport #10579 early/now

**Comment by PastaPastaPasta** [comment]
resolved `signrawtransactionwithwallet` problem

**Comment by PastaPastaPasta** [comment]
rebased on develop

**Comment by UdjinM6** [comment]
07f13ae/#13545 is missing changes for `lint-includes.sh` which was introduced in #11878 and changed/moved later, should be dropped probably (to make sure we won't miss these changes later). Otherwise looks good imo.

**Comment by PastaPastaPasta** [comment]
renamed https://github.com/dashpay/dash/commit/07f13aea51206ccef542a2968ddf71b3d23951d9 to be a partial merge, should grab it when I go fully through 0.17

**Comment by PastaPastaPasta** [comment]
test failure seems unrelated (pose test)

**Pull request merged**
