### PR TITLE
[0.12.1.x] update splash screen

### PR DESCRIPTION
**Pull request by schinzelh**
raze created some new splash screens for the traditional/drk theme with nicer URL font :)

### CODE REVIEW

**Comment by UdjinM6** [comment]
hmmm.. isn't that `light` theme actually?

**Comment by schinzelh** [comment]
updated to correct theme now

**Comment by UdjinM6** [comment]
Nice! What about updating `light` theme with new images you had here before?

**Comment by schinzelh** [comment]
I'll discuss updating light theme with raze at a later time, not sure what our designers are up to :)

**Pull request merged**
