### PR TITLE
Try to properly disconnect and delete nodes on shutdown

### PR DESCRIPTION
**Pull request by UdjinM6**
Should fix crashes like https://gitlab.com/dashpay/dash/-/jobs/408198109#L3474

Note: most of it is just moving some code around to reuse it, see https://github.com/dashpay/dash/commit/035a84173?w=1 for a no-whitespace-changes version

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
On travis blockchain.py failed

**Comment by codablock** [comment]
@UdjinM6 is the failure on Travis related?

**Comment by UdjinM6** [comment]
I _think_ it's not but it's hard to say for sure...

**Comment by charlesrocket** [comment]
Sounds like https://github.com/dashpay/dash/issues/3331

**Comment by PastaPastaPasta** [comment]
What's blocking this? Is there a reason to not merge?

**Pull request closed without merging**
