### PR TITLE
merge bitcoin#18820, #19764, #13686, #17538, #18405: zmq backports, boost depends split

### PR DESCRIPTION
**Pull request by kittywhiskers**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Entire CI is unhappy

**Comment by kittywhiskers** [comment]
I'll mark them as drafts

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Review by UdjinM6 — APPROVED** [review]
gitian complains `export of symbol in6addr_loopback not allowed` but this can be fixed later by backporting bitcoin#20129 so ACK

**Pull request merged**
