### PR TITLE
#include reorder and duplicate removal/byteswap update/copyright addition

### PR DESCRIPTION
**Pull request by spencerlievens**
* Removed duplicate includes
* Reordered all includes in /src/*
* Byteswap updated to allow building on OSX
* Addition of copyright to darksend-relay.cpp

### CODE REVIEW

**Comment by spencerlievens** [comment]
I haven't touched the test file #includes, but I will take a look at those next. However, they build/pass currently as they stand.

**Comment by spencerlievens** [comment]
Not sure why Travis-CI failed. Tests might just need restarting.

**Comment by schinzelh** [comment]
Actually the Windows builds are broken

https://travis-ci.org/dashpay/dash/jobs/205494589

**Comment by spencerlievens** [comment]
Yeah I got a bit carried away :P

I will actually close this, but I do want to commit some similar PR's that are much more atomic.

**Pull request closed without merging**
