### PR TITLE
update public part of windows code signing certificate

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Signed-off-by: pasta <pasta@dashboost.org>

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
utACK, matches the expected one

**Review by xdustinface — APPROVED** [review]
utACK

**Review by xdustinface — CHANGES_REQUESTED** [review]
Hmm linter complains about trailing whitespaces.. however, i couldn't find anything in that file, thoughts?

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
@PastaPastaPasta looks like you used some weird text editor for this which added line breaks in an unexpected format. Pls see 161d86cb61.

**Comment by PastaPastaPasta** [comment]
Cherry-picked. I'm not sure what happened...

**Review by UdjinM6 — APPROVED** [review]

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
