### PR TITLE
refactor: Move CCoinJoinClientOptions from coinjoin-client.*

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
We use CCoinJoinClientOptions quite a few places around the codebase where we don't use the rest of coinjoin client. This PR separates CCoinJoinClientOptions out into it's own file. Plus this will be useful to dis-entangle some circular dependencies around the coinjoin codebase and generally make it more modular later on.

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Good idea! 👍 

LGTM in general but I would probably drop some redundant forward declarations b529bb7cc0a2afe190723672e6e8c4358b674f7f

**Comment by PastaPastaPasta** [comment]
Good catch, done :+1:

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
