### PR TITLE
fix flag/ref order + cs_vNodes in ConnectNode

### PR DESCRIPTION
**Pull request by UdjinM6**
should probably fix recently observed crash

### CODE REVIEW

**Comment by tgflynn** [comment]
I doubt this will fix anything.  The node can be deleted any time after FindNode returns unless cs_vNodes is locked.

**Comment by tgflynn** [comment]
I think you'll need to fix the cs_main problem or there will be deadlocks.

It's a bit of work but what I would suggest is:

Create an overloaded version of PushVersion that takes a block height parameter.

Add block height parameter to the CNode constructors and pass to PushVersion.

Temporarily lock cs_main at the start of ConnectNode to get the block height then pass it to the CNode construcor calls.

**Comment by UdjinM6** [comment]
yep, deadlock is exactly what happened in dbbb56f https://travis-ci.org/dashpay/dash/jobs/197346945 :) , shouldn't happen after 504caf0

**Comment by tgflynn** [comment]
Oh, right you avoided a locking cs_vNodes around the constructor completely.

:+1:

**Comment by tgflynn** [comment]
You should be able to remove the locking in ThreadMnbConnections now.

**Comment by UdjinM6** [comment]
>You should be able to remove the locking in ThreadMnbConnections now.

Well, I'm not sure... I think it's a different issue https://github.com/dashpay/dash/pull/1301#issuecomment-276688300 and we should keep lock there to add another ref before node is picked by `if (pnode->fDisconnect ||` in `ThreadSocketHandler`.

**Pull request merged**
