### PR TITLE
qt: Finetune OverviewPage

### PR DESCRIPTION
**Pull request by xdustinface**
This PR brings the following changes to the `OverviewPage`:

- Make sure that the "Balances", "Recent Transactions" and "PrivateSend" frames are aligned properly around the window center it gets resized.
- Give the transaction the same coloring/highlighting like in the transaction tab
- Adjust the warning box
- Make sure PrivateSend related widgets show/hide as expected based on its settings/state
- Finetune the overall css layouts and remove obsolete entries

@UdjinM6 68b3e36 and 876fffd are inspired by 55c0f40, thanks for that 👍 let me know if you would like to see more of it in here.

Requires #3710 to make sense / look good.

### Preview

| Before | With this PR | 
| - | - | 
| Bildschirmfoto 2020-09-16 um 03 06 53 | Bildschirmfoto 2020-09-16 um 02 56 50 | 
| Bildschirmfoto 2020-09-16 um 03 06 48 | Bildschirmfoto 2020-09-16 um 02 56 54 |

### CODE REVIEW

**Comment by UdjinM6** [comment]
Pls see https://github.com/UdjinM6/dash/commits/pr3715

**Review by UdjinM6 — APPROVED** [review]
ACK

**Comment by PastaPastaPasta** [comment]
Will review after we finalize 3710

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Found an issue, pls see d4505c64cf

**Comment by xdustinface** [comment]
Thats really a huge wallet :D Thoughts/Concerns about adding 1c5427954322f5f487f66a727b5f042dbf4ad0b5 (OptionsDialog isn't used in that method but TransactionTableModel is) and d44a290 (Fail early, tiny reorder, avoid the else statement and avoid have the `setLimit` call twice) to this PR?

**Comment by UdjinM6** [comment]
d44a290 doesn't work for me, see 4ec87a62b2. Also, a tiny code style issue, see 96cb304116.

**Comment by xdustinface** [comment]
@UdjinM6 Just asking because i couldn't figure an issue here on my side, whats the issue you get without 4ec87a62b2ea590e08f383648f4267cca4fdae7f? Actually i would assume there should be no need to set the same model/modelColum again and again?

**Comment by UdjinM6** [comment]
> whats the issue you get without 4ec87a6

The number of items in tx list isn't updated when you start/stop mixing.

> here should be no need to set the same model/modelColum again and again

Well, changing the limit requires that it seems. But we can optimize this indeed, see 6593b43ae3

**Comment by xdustinface** [comment]
> see [6593b43](https://github.com/dashpay/dash/commit/6593b43ae3bb99b995d194a943741450a19caebd)

Makes sense, picked 👍 

However, there is still an issue.. but i spent way too much time on that today so i decided to go with 5acf6e861b1b9547c3ff5f4ffb3fc94fb466fc5a instead for now :D actually i would really love to get the WHY it does behave like this so if someone else has an idea, please tell me 😄 

My understanding of the issue: 

After sync and whatnot are done `filter->setLimit(nNumItems);` updates only start to work as soon as the transaction table model fires its first data/header/whatever changed signal. This may happen by multiple sources like: Just opening the OptionsDialog, without doing anything in there press OK (you can do something but its not required since the only thing which counts is that display unit signal from the optionsmodel gets fired) or also an incoming block forces a appropriate signal to fire. Now, as soon as the TTM got its first update removing/adding rows with `filter->setLimit(nNumItems);` just always works well without 5acf6e861b1b9547c3ff5f4ffb3fc94fb466fc5a... but it always, after a restart, requires one update to the TTM after the initial startup/initialization. Like i said, i have no clue right now what exactly the root cause for this is but its easy to reproduce at least so it should be no problem to figure it out with some more time... i just don't want to waste more time with something like this before the release.. so, if someone has a better one than 5acf6e861b1b9547c3ff5f4ffb3fc94fb466fc5a share it, else if there are no other issues, approve the PR! :D

**Comment by PastaPastaPasta** [comment]
I'm really not a fan of the empty space to the left of the balances. Everything else seems to be fine so far..

**Comment by PastaPastaPasta** [comment]
Also: 

All things under privatesend should be tabbed to indicate they are a part of that section

**Comment by UdjinM6** [comment]
I think I figured it out, pls see 30d17bbc54 and d1215c4f23

**Comment by xdustinface** [comment]
> I think I figured it out, pls see [30d17bb](https://github.com/dashpay/dash/commit/30d17bbc5443ee1b5e5115737829a275ace62a24) and [d1215c4](https://github.com/dashpay/dash/commit/d1215c4f2368cd4a08d37886e12f0f071b21b258)

Yes! That works, nice! 👍

**Comment by xdustinface** [comment]
> I'm really not a fan of the empty space to the left of the balances. Everything else seems to be fine so far..

It looks better if there are addresses inside instead of labels :D but i agree there is room for improvement 👍 

> Also:
> 
> All things under privatesend should be tabbed to indicate they are a part of that section

Hm IMO thats very clear visible due to the different titles on that screen. I mean, there isn't really anything else around those widgets what you could confuse with the section 🤔

**Comment by PastaPastaPasta** [comment]
> > I'm really not a fan of the empty space to the left of the balances. Everything else seems to be fine so far..
> 
> It looks better if there are addresses inside instead of labels :D but i agree there is room for improvement +1

What do you mean? I'm not talking about the recent transactions on the right, but the balances on the left. Old behavior of no added whitespace to the left of the balances is good, and should be preserved

**Comment by PastaPastaPasta** [comment]
Also, please rebase this PR on develop

**Review by PastaPastaPasta — APPROVED** [review]
ACK dependent on @iamsuba agreeing to these changes

**Comment by iamsuba** [comment]
Honestly the whole layout is not designed to be responsive. So centrally aligning them makes more sense than letting expand around the corners.

**Review by UdjinM6 — APPROVED** [review]
ACK

**Pull request merged**
