### PR TITLE
instantsend: Introduce ISDB specific CCriticalSection, avoid locking IS cs where possible

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Now, I'm not necessarily sure this is okay, but imo either this is okay, or we should say db is guarded by cs. LMK which you think it should be @UdjinM6

### CODE REVIEW

**Comment by UdjinM6** [comment]
I guess it's clear now (from functional tests failures) that isdb should be protected :) But _maybe_ you can do this internally instead (via smth like `CInstantSendDb::cs`)? 🤔

**Comment by PastaPastaPasta** [comment]
> I guess it's clear now (from functional tests failures) that isdb should be protected :) But _maybe_ you can do this internally instead (via smth like `CInstantSendDb::cs`)? thinking

Yeah, it is clear :D will investigate an internal CS for DB

**Comment by PastaPastaPasta** [comment]
Everything is happy now :)

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
