### PR TITLE
 build: bump gmp from 6.1.2 to 6.2.1 

### PR DESCRIPTION
**Pull request by kittywhiskers**

### CODE REVIEW

**Review by PastaPastaPasta — DISMISSED** [review]
ACK for squash merge

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
> GMP speeds up the library by ~ 3x

https://github.com/dashpay/bls-signatures/blob/main/README.md?plain=1#L213

GMP is detected by relic automagically/implicitly. Could make it explicit to avoid such a confusion in the future i.e. add `-DARITH=gmp` here https://github.com/dashpay/dash/blob/develop/depends/packages/bls-dash.mk#L38

NACK

**Comment by kittywhiskers** [comment]
I suspected something similar so [035f038](https://github.com/kittywhiskers/dash/commit/035f038451f7ff4db6fc8ecb161e072a3f332d2a) was always ready as a replacement

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
