### PR TITLE
[0.12.0.x] update splash image

### PR DESCRIPTION
**Pull request by schinzelh**

### CODE REVIEW

**Comment by UdjinM6** [comment]
I would rather leave splash screens in 0.12.0.x as it is, current splash screen matches current theme and new one doesn't imo.

**Comment by schinzelh** [comment]
I am still negotiating with raze re. this...

**Comment by schinzelh** [comment]
updated to correct theme now

**Comment by UdjinM6** [comment]
utACK 29806e9

**Pull request merged**
