### PR TITLE
chore(rpc): renamed from bitcoin to coins in help text

### PR DESCRIPTION
**Pull request by ogabrielides**
## What was done?
Renamed `bitcoin` to `coins` in help texts of mining RPCs.

## Breaking Changes
no

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
`Dash` is the name of the project, not units. I would suggest to use `coins` c81ab53d17

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by knst — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge; although I think I'm fine with either `Dash` or `coins`

**Pull request merged**
