### PR TITLE
backport: merge bitcoin#24252, #24301, #25808, #25873, #26557, #25465, #26952, #25898:, #30217, #24266, partial bitcoin#28622 (replace boost::filesystem with std::filesystem: part 2)

### PR DESCRIPTION
**Pull request by kwvg**
## Additional Information

* Depends on https://github.com/dashpay/dash/pull/6138

## Breaking Changes

None observed.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas **(note: N/A)**
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation **(note: N/A)**
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by UdjinM6 — DISMISSED** [review]
utACK 52891abbda7533609964f711dfcf25a4691afdf5

(compiles on macos 14.6.1, local tests are green too)

**Review by PastaPastaPasta — APPROVED** [review]
LGTM 2554aa4e63728a55e944ecd5d5cc6d95210be602; gonna rebase on develop

**Comment by PastaPastaPasta** [comment]
```
 -:  ---------- >  1:  5394d63e18 feat: improve merge-check action to leave a comment and label to PRs
 -:  ---------- >  2:  35c76705d1 feat: implement basic Github Actions based CI, which reuses underlying logic from GitLab CI
 -:  ---------- >  3:  d1addb27aa fix: change fallback download path to be an s3 link which includes a few packages
 -:  ---------- >  4:  ed8ffa7fb4 feat: have cppcheck linter respect CACHE_DIR env variable
 -:  ---------- >  5:  4dbdecdd1e refactor: rename builder-image -> build-image and builder as image name to dashcore-ci-runner
 -:  ---------- >  6:  acf1315270 Merge bitcoin/bitcoin#25091: test: Remove extended lint (cppcheck)
 -:  ---------- >  7:  2237b4266b refactor: use `=` with ENV in dockerfiles
 -:  ---------- >  8:  1b139e4837 feat: automatically run guix-build on all tags pushed
 -:  ---------- >  9:  101a31555f refactor: simplify caching setup, add a restore key to actually cache besides 1 run
 -:  ---------- > 10:  580bbe6d1c feat: improve guix building; run always, save artifacts
 -:  ---------- > 11:  770651aa15 set hosts in guix-check
 -:  ---------- > 12:  9590929900 Merge bitcoin/bitcoin#24944: rpc: add getblockfrompeer RPCTypeCheck and invalid input test coverage
 -:  ---------- > 13:  df2f533aaf Merge bitcoin/bitcoin#26759: test: Drop no longer needed `race:epoll_ctl` TSan suppression
 -:  ---------- > 14:  7f2b934089 Merge bitcoin/bitcoin#26772: contrib: fix sha256 check in install_db4.sh for FreeBSD
 -:  ---------- > 15:  092ddc3a3e Merge bitcoin/bitcoin#26603: doc: CalculateSequenceLocks: prevHeights entries are set to 0, not removed
 -:  ---------- > 16:  864d02e4a9 Merge bitcoin/bitcoin#26809: compat: use STDIN_FILENO over 0
 -:  ---------- > 17:  d1b93c78b7 Merge bitcoin/bitcoin#26818: test: Fix feature_startupnotify intermittent issue
 -:  ---------- > 18:  6fe46fc02a Merge bitcoin/bitcoin#26864: doc: net: fix link to onion address encoding scheme [ONIONADDRESS]
 -:  ---------- > 19:  07f4c39c44 Merge bitcoin/bitcoin#26730: test: add coverage for `purpose` arg in `listlabels`
 -:  ---------- > 20:  93c4652a05 Merge bitcoin/bitcoin#26821: refactor: Make `ThreadHTTP` return void
 -:  ---------- > 21:  b6bde7322c Merge bitcoin/bitcoin#26827: doc: use "std lib clock" over "C++11 clock"
 -:  ---------- > 22:  0dd997c4e5 Merge bitcoin/bitcoin#26835: contrib: add PE Canary check to security-check
 -:  ---------- > 23:  92f82f6fc6 fix: group the ENV in quotations
 -:  ---------- > 24:  aafded67d9 fix: compilation error due to rebase error between bitcoin#22937 and ipc/process
 -:  ---------- > 25:  540f6871d3 fix: lock `::cs_main` before accessing `ChainstateManager::m_best_header`
 -:  ---------- > 26:  2777d30caa fix(ci): only run some GH actions on PR approval, not on every comment
 -:  ---------- > 27:  c2bd834f3b Merge bitcoin/bitcoin#21169: fuzz: Add RPC interface fuzzing. Increase fuzzing coverage from 65% to 70%.
 -:  ---------- > 28:  4dd36f603a Merge bitcoin/bitcoin#21798: fuzz: Create a block template in tx_pool targets
 -:  ---------- > 29:  813993d44a Merge bitcoin/bitcoin#21892: fuzz: Avoid excessively large min fee rate in tx_pool
 -:  ---------- > 30:  2398283ff6 Merge bitcoin/bitcoin#21922: fuzz: Avoid timeout in EncodeBase58
 -:  ---------- > 31:  3bfefde53b Merge bitcoin/bitcoin#21931: ci: Bump cirrus fuzz CPUs to avoid timeout
 -:  ---------- > 32:  82a6aa5907 Merge bitcoin/bitcoin#21810: fuzz: Various RPC fuzzer follow-ups
 -:  ---------- > 33:  d89847f43e Merge bitcoin/bitcoin#22004: fuzz: Speed up transaction fuzz target
 -:  ---------- > 34:  06ea87040b Merge bitcoin/bitcoin#20773: refactor: split CWallet::Create
 -:  ---------- > 35:  4125485401 fix: follow-up bitcoin#20773 - for collateral lock/unlock coins
 -:  ---------- > 36:  9ad26f1664 fix: follow-up bitcoin#20773 - coinjoin loader can be nullptr too
 -:  ---------- > 37:  2f12f91d39 fix: 6205 follow-up
 -:  ---------- > 38:  52b9fcecb4 fix: can't mix `-` and `:`
 -:  ---------- > 39:  40c0e06047 fix: use coinstatsindex instead blockfilterindex in feature_prunning
 1:  97808070a4 = 40:  357d1b6792 merge bitcoin#24252: Represent paths with fs::path instead of std::string
 2:  e3719d8dd8 = 41:  aa361b2717 merge bitcoin#24301: header-only Boost
 3:  d3e061fadc = 42:  d2c968bf91 merge bitcoin#25808: work around u8path deprecated-declaration warnings with libc++
 4:  ae3c8ef4b8 = 43:  1ad64dadca merge bitcoin#25873: Boost 1.80.0
 5:  f42055c2bb = 44:  1d8b8900ef merge bitcoin#26557: Update Boost to 1.81.0 in depends
 6:  faf10978f5 = 45:  7a1f48e53c merge bitcoin#25465: remove boost library detection
 7:  af925dab22 = 46:  da5b433909 merge bitcoin#26952: Avoid `BOOST_NO_CXX98_FUNCTION_BASE` macro redefinition
 8:  df7ea23106 = 47:  05fb206f76 merge bitcoin#25898: remove WSL 1 workaround in fs
 9:  03415abb5c = 48:  9e80893a3c partial bitcoin#28622: use macOS 14 SDK (Xcode 15.0)
10:  34651f13eb = 49:  b02d5e34ff merge bitcoin#30217: Update Boost download link
11:  2554aa4e63 = 50:  f4b896ef5f merge bitcoin#24266: Avoid buggy std::filesystem:::create_directories() call
```

**Review by UdjinM6 — APPROVED** [review]
utACK f4b896ef5fe76ccb130862fbb5721560391cd500

**Review by knst — COMMENTED** [review]
post utACK f4b896ef5fe76ccb130862fbb5721560391cd500

**Pull request merged**
