### PR TITLE
Fix 'bool Relay()' CConnman argument.

### PR DESCRIPTION
**Pull request by spencerlievens**

### CODE REVIEW

**Comment by UdjinM6** [comment]
Hmmm... There are many places where it's `type &param` and many where it's `type& param` in both Dash and Bitcoin. Both forms are legit (even though it's a bit inconsistent), so why "fixing" this one? What's so special about it?

**Comment by spencerlievens** [comment]
It was simply because I was reviewing the privatesend files specifically.

**Comment by UdjinM6** [comment]
Ah, ok, so it's not an issue then. This should be a part of some global syntax refactoring if we ever start one. Closing.

**Comment by OlegGirko** [comment]
Sorry, this inconsistent syntax was introduced by me. I usually put `&` (or `*`) after space in my code, but Bitcoin and Dash uses different convention and puts it before space. I've used my own style unconsciously when eliminating use of `g_connman` global Dash-specific code and replacing it with reference to `CConnman` passed as function argument.

**Pull request closed without merging**
