### PR TITLE
Assign app name in NetworkStyle::NetworkStyle()

### PR DESCRIPTION
**Pull request by UdjinM6**
Fixes Splash Screen bug mentioned in https://github.com/dashpay/dash/pull/760#issuecomment-212278881

### CODE REVIEW

**Comment by crowning-** [comment]
POkay, let's continue here:

Copy/Paster from https://github.com/dashpay/dash/pull/760:

Where do the orange icons in my screenshot in https://github.com/dashpay/dash/pull/760 come from? They are nowhere in our repository.
I can't get them away, even a hard-coded _"QIcon icon = QIcon(":/icons/crownium/tx_input");"_ in TxViewDelegate (which should display the (existing) chrome-ish icons of that theme).

Does someone somewhere _paint_ them, no matter which *.png are choosen?

**Comment by UdjinM6** [comment]
Ahh, I see.. That's because of the platform style - https://github.com/dashpay/dash/blob/v0.12.1.x/src/qt/platformstyle.cpp#L24-L28 - it colorizes icons for some and it doesn't for otheres. I'm not sure why you are expecting crownium theme to affect your overview though because it's clearly drkblue theme there.

**Comment by crowning-** [comment]
On Ubuntu 14.04 with Unity-desktop I ALWAYS get the orange icons, no matter which theme I load.
Looks ugly...

**Comment by crowning-** [comment]
Yep, I changed https://github.com/dashpay/dash/blob/v0.12.1.x/src/qt/platformstyle.cpp#L28 to "{"other", true, false,  false}" and it worked as it should.
Shall I PR the change?

**Comment by UdjinM6** [comment]
> Shall I PR the change?

Sure, why not :)

I guess there are more issues with coloring/icons however - there are no icons in menus on mac for example so smth might look ugly on ubuntu/windows. Can you do a quick check for this also?

**Comment by crowning-** [comment]
PR is done. There are some other issues unrelated to this one, like some icons being black in the menus on Ubuntu. They are probably just missing or wrongly referenced.
I'll create another PR once I find the time to fix those.

**Comment by UdjinM6** [comment]
> They are probably just missing or wrongly referenced.

I guess that most likely it's simply misuse (in terms of Dash-styling) of `TextColorIcon()` where it should be `SingleColorIcon()` instead.

**Pull request merged**
