### PR TITLE
fix: speed up GetStateFor

### LINKED ISSUE #5090: Slow RPC calls on Core v18
### Describe the issue
There have been several reports of slow RPC responses ([Discord](https://discord.com/channels/484546513507188745/495696706638184482/1039281551608914001), [Slack](https://dashpay.slack.com/archives/G15927GP9/p1669143604293569)). I personally have seen this with the `getblockchaininfo` RPC (2-3 seconds before response). This does _not_ happen on mainnet from what I've seen or heard from others. Testnet is affected. It's unclear if devnets/regtest are affected.

#### If so, please list the steps to reproduce below:
1. Run `getblockchaininfo` against a Dash Core v18.0.2+ node (others have mentioned `getgovernanceinfo` and `getblockcount` too - I have not had issues with them).
2. Observe delayed response

### Expected behaviour
RPC response should be received without perceptible delay as it is on mainnet.

### Actual behaviour
RPC response delayed by several seconds (for me). Others have reported times >10 seconds.

### Screenshots.
N/A

### What version of Dash Core are you using?
Dash Core 18.0.2/18.1.0/18.2.0-rc1 (official binary and self-compiled)

### Machine specs:
- OS: Ubuntu 22.04
- CPU: Intel i7
- RAM: 32 GB
- Disk size: 1 TB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
Examples of time to run getblockchaininfo:

```
$ time dashcore-18.1.0/bin/dash-cli -testnet getblockchaininfo >> /dev/null

real	0m2.076s
user	0m0.000s
sys	0m0.004s
$ time dashcore-18.1.0/bin/dash-cli -testnet getblockchaininfo >> /dev/null

real	0m2.073s
user	0m0.000s
sys	0m0.004s
$ time dashcore-18.1.0/bin/dash-cli -testnet getblockchaininfo >> /dev/null

real	0m2.066s
user	0m0.002s
sys	0m0.000s
$ time dashcore-18.1.0/bin/dash-cli -testnet getblockchaininfo >> /dev/null

real	0m2.067s
user	0m0.000s
sys	0m0.004s
```

Also, this is what my CPU is doing when running the RPC (see spikes to 80+%):
image

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
should fix #5090 

## What was done?
calculate `nStartHeight` only when it's really needed and using only a subset of cache that matters for such caclulations

## How Has This Been Tested?
`time dash-cli getblockchaininfo`
before: `real	0m9.211s`
after: `real	0m0.164s`

## Breaking Changes
hopefully none

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

kudos to @nmarley for noticing the issue, @thephez for testing/confirming/documenting it and to @knst for finding the exact piece of slow code 👍

### CODE REVIEW

**Comment by MrDefacto** [comment]
Patch fixes this speed issue. tested on couple testnet instances with that issue. GJ

**Review by knst — APPROVED** [review]
Looks good for me, but may be better to move code out as a function? It will make implementation shorter and less noise inside GetStateFor() 
https://github.com/knst/dash/commit/9e203a230fe02efb2cb80a91e5e0f60a07bbf048

**Comment by PastaPastaPasta** [comment]
May be better to make it a lambda, no strong preference.

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Review by ogabrielides — APPROVED** [review]
Good job guys!
utACK

**Pull request merged**
