### PR TITLE
fix bip69 inputs sort order to match specs

### PR DESCRIPTION
**Pull request by UdjinM6**
"in reversed byte-order" part

### CODE REVIEW

**Comment by tgflynn** [comment]
Why do this ?

BIP69 appears to be just a proposal and bitcoin does not appear to have implemented it.

**Comment by UdjinM6** [comment]
Well, everything is just a proposal :)

Yes, Bitcoin _Core_ doesn't have an implementation for this bip but there are others https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki#implementations

It's especially helpful for mixing txes where user can easily verify that tx doesn't leak any information about input/output linkage. This can be done manually currently, to prevent leaks from MN and make sure it's always the case see #1510

**Comment by tgflynn** [comment]
But why change the existing convention ?  All this does is substitute one convention for another and I don't really see a strong rationale for that.

**Comment by UdjinM6** [comment]
Current implementation doesn't quite match bip69 and it is not easy to verify inputs order in block explorers etc because you need to read txids from right to left. You can check any tx with multiple inputs to make sure.

**Pull request closed without merging**
