### PR TITLE
Fixing light theme

### PR DESCRIPTION
**Pull request by UdjinM6**
Fixing light theme:
- colorized few images/icons to use “Strong blue” #1c75bc
- replaced "smile" icon with pick-axe
- fixed ds status overlap
- trying to make theme less "heavy" - fewer bold labels, lighter colors for labels
- removed unused files

old overview screen:
screen shot 2016-05-12 at 13 55 25

new one:
screen shot 2016-05-12 at 16 15 40

other screens (haven't made screenshots for current version, only have for new one, sorry)

screen shot 2016-05-12 at 17 07 40

screen shot 2016-05-12 at 17 07 50

screen shot 2016-05-12 at 17 07 59

### CODE REVIEW

**Comment by akijuh** [comment]
Hi udjin, AjM here.

Sorry to bother you, but...
- in transactions tab:  columns and titles are not in the same width.
- In Masternodes tab:  some columns titles are not wide enough, 
  and 'All masternodes' masternode first letter should be capital letter, like 'My Masternodes'

**Comment by UdjinM6** [comment]
@akijuh yes, I'm aware of these issues but the have nothing to do with light theme and this PR ;)
Let's fix them somewhere else.

**Comment by akijuh** [comment]
Yep, but you have some nice gui pics in here :)

**Comment by UdjinM6** [comment]
@akijuh 
> Yep, but you have some nice gui pics in here :)

https://github.com/dashpay/dash/blob/v0.12.1.x/CONTRIBUTING.md#pull-request-philosophy 😉

**Comment by crowning-** [comment]
I like the new icons :thumbsup:

I'm not 100% if we should really reduce to only one single blue....dash.org has 2 different blues, and if I remember correctly salmion explicitly decided to use the same 2 blues.

**Comment by UdjinM6** [comment]
@crowning- there is actually second blue - for buttons it's slightly different ;)

**Comment by salmion** [comment]
These will look a look better :)

tx_out
tx_mined
tx_mined_
tx_inout
tx_in

**Comment by UdjinM6** [comment]
Allright, more screenshots :)

Mining1
screen shot 2016-05-13 at 4 01 49
screen shot 2016-05-13 at 4 01 59

Mining2
screen shot 2016-05-13 at 4 04 43
screen shot 2016-05-13 at 4 04 52

Which one to commit? Should we submit a proposal to ask masternodes? 😄

**Comment by snogcel** [comment]
Mining1! :-)

**Comment by akijuh** [comment]
Both icon set looks good, but why they need to be so BIG in the overview tab > latest transaction list?

**Comment by crowning-** [comment]
Mining1

While I love the pickaxe/shovel combination on the overview-page the tiny version on the transaction-page looks too busy.The single pickaxe looks better there.

**Comment by UdjinM6** [comment]
Ok, thanks for voting :)
Pushed new icons (mining1)

> but why they need to be so BIG in the overview tab > latest transaction list?

It's the same size for every theme sooo... `<link to PR philosophy here>` 😄 
Maybe we'll look at that later ;)

**Comment by UdjinM6** [comment]
I think we can merge this now and merge #777 as well. Is there anything else that needs to be fixed _in this theme_?

**Comment by akijuh** [comment]
One late note...

Send tab icon arrow point UP, but in transactions icon point RIGHT.
Receive tab icon arrow point DOWN, but in transactions icon point LEFT.

Shouldnt these icons need to be equal style?

**Comment by salmion** [comment]
Well spotted. My logic on this was that incoming transaction point inward and outgoing point outward. trivial to make new ones if you all disagree.

**Comment by UdjinM6** [comment]
>Shouldnt these icons need to be equal style?
Edit: I mean, point in the same direction.

I'd like to keep it the way it is because every theme uses this logic actually and I think it would be better to change them all at once in another PR if needed.

**Comment by akijuh** [comment]
Windows 7 64bit - Dash core v0.12.1.0-43cd805

**Overview** and **Receive** tab text is truncated when selected, because text is set bold.

lightthemetabs

**Comment by schinzelh** [comment]
@akijuh good find! Applies to Win32 as well:

image

**Pull request merged**
