### PR TITLE
Adding $PATH cleaner for building in WSL

### PR DESCRIPTION
**Pull request by marknl**
As discussed in https://github.com/dashpay/dash/pull/2939

### CODE REVIEW

**Comment by UdjinM6** [comment]
Hmmm... I don't think these instructions belong to `build-cross.md` tbh, more like https://github.com/dashpay/dash/blob/master/doc/build-windows.md#compiling-with-windows-subsystem-for-linux because 1. it's wsl specific issue and 2. `PATH` should probably be fixed every time you open new shell and start building dependencies or source code.

**Comment by marknl** [comment]
aw shoot! Also fine. I was doubt where to put it. I don't know man, you put it somewhere then ;)
I just figured "People should know about this when building in WSL".

**Comment by codablock** [comment]
@marknl As I understand you, you do not plan to update this PR so that the instructions are found in `build-windows.md`?

**Comment by UdjinM6** [comment]
Superseded by https://github.com/codablock/dash/commit/08513bfffd9fb0d141c00ed492014fb99d554517 in #3111

**Pull request closed without merging**
