### PR TITLE
V0.12.0.x msghand

### PR DESCRIPTION
**Pull request by UdjinM6**
Revert some changes https://github.com/dashpay/dash/commit/40149c4e41114499c324abc313aea93a59bfa2f7#diff-9a82240fe7dfe86564178691cc57f2f1R1485 and cherry-pick 351593b9c8687b4da2e86769899b8b61ea44b630
Should help with #535

### CODE REVIEW

**Comment by UdjinM6** [comment]
before
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 89.04    0.003298           1      2476      1235 futex
  9.64    0.000357           0     45249           gettimeofday
  1.16    0.000043           0       480           sendto
  0.16    0.000006           0      1235           clock_gettime
  0.00    0.000000           0        32           write
------ ----------- ----------- --------- --------- ----------------
100.00    0.003704                 49472      1235 total
```
after
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
  0.00    0.000000           0        36           write
  0.00    0.000000           0       200           sendto
  0.00    0.000000           0      2451           gettimeofday
  0.00    0.000000           0       243         9 futex
  0.00    0.000000           0         1           restart_syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.000000                  2931         9 total
```
still smth is broken somewhere but looks much better now imo

**Comment by minersday** [comment]
Compiling and testing on one of my live masternodes..

**Comment by minersday** [comment]
OK, now it's running live, 
changed the clocksource back to tsc = default.
Everything seems to be fine currently, there are no 
futex: (Connection timed out), messages in strace as of now, there are some futex resource unavailable from time to time, and futex ..... = 0. but we will see.

looking realtime graph and
CPU usage went from ~20% to ~5%.
Still monitoring memory if it's starts to do the chainsaw or is it stable for now...
Network packets also went down from 3500 to around 2000.

**Comment by minersday** [comment]
2cpu-usage
2memory-usage
2network-usage

**Comment by minersday** [comment]
Current graphs, we will see in day or two what happens..

3cpu-usage
3memory-usage
3network-usage

**Comment by minersday** [comment]
Here's a week graph, you can see the CPU usage is good, even it's sawing a little, memory is all over the place, same as disk usage is increasing and is sawing These has to do something with the masternode count?
going to compile the latest release and try that.

4cpu-usage
4disk-usage
4memory-usage
memory-usage

**Comment by minersday** [comment]
Newest 0.46 release, looking very good. Memory usage back down to normal no sawing and cpu-usage too, going to update the rest of the masternodes.
5cpu-usage
5memory-usage

**Comment by UdjinM6** [comment]
@minersday thank you for extended testing and report! :+1:

**Comment by schinzelh** [comment]
@minersday many thanks for your testing from me, too!

**Comment by minersday** [comment]
NP =)

**Comment by minersday** [comment]
Here's latest graphs for you please (daily range), you can clearly see at the end when updated to .46.
6cpu-usage
6disk-usage
6memory-usage

**Comment by schinzelh** [comment]
I can confirm this, i have updated some nodes and the load reduces significantly (at least after startup)

**Pull request merged**
