### PR TITLE
Backport 11651

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Contains #10286, which will be dropped once PR9 is merged

### CODE REVIEW

**Comment by UdjinM6** [comment]
`scripted-diff: Replace #include "" with #include <> (ryanofsky)` 64a79b0 is broken - should remove leading whitespaces in the title. Also missing 37580b0 and 1c0acbe from #3353 (which should be dropped on rebase later) to fix the included 10286.

**Comment by UdjinM6** [comment]
Needs rebase

**Comment by PastaPastaPasta** [comment]
force pushed, I think I fixed the problem with the scripted diff

**Comment by UdjinM6** [comment]
Looks like 8d15df8 is incomplete, changes in quite a few files are missing a83e72a (which is why scripted-diff fails).

**Comment by PastaPastaPasta** [comment]
fixed https://github.com/dashpay/dash/commit/8d15df8ef3ac85982a781ec7ae9f2b5abf742d5e and forcepushed

**Comment by PastaPastaPasta** [comment]
Alrighty... Building + tests passing locally, plus scripted diffs verify locally

For some reason, I wasn't able to figure it out, the changes done in https://github.com/bitcoin/bitcoin/pull/11651/commits/138016bf9275692995d37f707e5b83e0d7fed1a9 resulted in an empty commit, so that commit has been dropped

**Comment by PastaPastaPasta** [comment]
Gitlab is failing, however, it shouldn't be. See travis here https://github.com/PastaPastaPasta/dash/runs/508439966

**Comment by UdjinM6** [comment]
Changes from the commit you dropped as well as changes to `.moc` files and other generated-on-compile files should NOT go into scripted-diff and should be applied in a separate commit.

**Comment by PastaPastaPasta** [comment]
I don't see any `.moc` files being changed in either of the scripted diffs. The scripted diff commit was created by running the script, followed by `git add *.h` `git add *.cpp`

**Comment by UdjinM6** [comment]
Oh, sorry, I mean changes _mentioning_ those files, not changes _to_ them

**Comment by PastaPastaPasta** [comment]
So... Why did those changes occur when executing the script??

**Comment by UdjinM6** [comment]
Because you are running the script in a non-clean folder? Do `make clean` before running the script and it should give you the right set of changes.

**Comment by PastaPastaPasta** [comment]
Alrighty. Created a new branch `backport-11651-t` which started out as develop, I ran `make clean` then executed the upstream script and created the scripted diff commit, then did the same for the dash scripted diff. Then I cherry-picked all of the other commits from `backport-11651` then I cherrypicked `test: refactor: Use absolute include paths for test data files` which was dropped from `backport-11651` and resolved conflicts. Then I cherry-picked the remaining commits from `backport-11651`. Then I checked-out `backport-11651` then `git reset --hard backport-11651-t`. Scripted diffs pass locally

I haven't build it locally yet (depends is messed up so I'm building that rn) but I have no reason to believe it wont build

**Comment by UdjinM6** [comment]
Nice, both scripted diffs have "ok" status on gitlab too 👍 Need (at least) a couple more fixes now it seems, pls see bbe6779a11e61ef8c545f4a8a7cc79a4032de6d0, 9ff4164281f3af3f9410168f130cd335135b0983, 65cc460e65f9450d1f826c03c1e70ba59f7d9055

**Comment by PastaPastaPasta** [comment]
cherry-picked

**Comment by PastaPastaPasta** [comment]
Gitlab passing

**Comment by PastaPastaPasta** [comment]
Merge?

**Pull request merged**
