### PR TITLE
Fix alerts

### PR DESCRIPTION
**Pull request by UdjinM6**
Some parts of alert code are completely missing in bitcoin for whatever reason, so please use this with caution :)

Note: test generation works and passes with some random pair of priv/pub keys, network broadcast should be tested by _whoever_is_holding_the_testnet_alert_key_ ;) preferably, in `-printalert` mode first.

### CODE REVIEW

**Comment by akijuh** [comment]
Is the protocol version right?
Just checking...

src/sendalert.cpp :

// These versions are protocol versions
+    alert.nMinVer       = 70000;
+    alert.nMaxVer       = 70103;

**Comment by UdjinM6** [comment]
`nMinVer` and `nMaxVer` are defining the range of versions which alert should be applied to and 70000-70103 range should be ok if we would want to send it to 12.0 nodes and not to 12.1.

Note: the alert in this function is just an example and code should be adjusted/verified/recompiled _each time_ one needs to send new alert.

**Comment by akijuh** [comment]
Aha, ok, thanks!

**Comment by UdjinM6** [comment]
Can't get this to actually broadcast msg on testnet for some reason... :/ I'm probably missing smth... will do more testing..

**Comment by UdjinM6** [comment]
I guess msg failed to be broadcasted on testnet because my 0.12.0.60 node was surrounded by 0.12.1.0 nodes and, surprisingly enough, `DEFAULT_ALERTS` is now set to `false` meaning that 12.1 nodes won't process/relay p2p alerts by default. Connecting to that node directly did the trick.

Re-enabling p2p alerts by default (for future upgrades).

**Pull request merged**
