### PR TITLE
Update activemn if protx info changed

### PR DESCRIPTION
**Pull request by nmarley**
Currently there is a bug in `masternode status` where the info (e.g. payout addr, vote addr) is not being updated when a `ProUpRegTx` is mined. This is currently only updated when the MN status is not "ready", if the MN is not in the valid list or if the operator key is changed.

This is an attempt to solve this by calling `Init()` in activemasternode if any of the MN's several fields are changed.

Another alternative would be to just call `Init()` regardless every block.

### CODE REVIEW

**Comment by nmarley** [comment]
👍 I like this better, originally tried doing something similar adding a comparison method to `CDeterministicMNState` but had compile issues so I abandoned it.

I have reset HEAD of this branch to your latest commit & force pushed.

**Comment by codablock** [comment]
IMHO the correct solution would be to remove `mnListEntry` completely and instead get the correct and up-to-date entry from the MN manager each time it's needed.

**Comment by codablock** [comment]
Here is an alternative implementation that removes the need to keep track of `mnListEntry`: 3e0ff6e35d19eff84a1e02c6a89b1f4dc7e6be8c
If you take it, I would also suggest to remove fba468758113084785c0bc0fffd6d704911be8a3 again.

**Comment by UdjinM6** [comment]
Agree, 3e0ff6e looks even better 👍

**Comment by nmarley** [comment]
Thanks, I agree this is better, ff'd https://github.com/dashpay/dash/commit/3e0ff6e35d19eff84a1e02c6a89b1f4dc7e6be8c and reverted https://github.com/dashpay/dash/commit/fba468758113084785c0bc0fffd6d704911be8a3.

**Pull request merged**
