### PR TITLE
backport bitcoin#16509 and add devnet test

### PR DESCRIPTION
**Pull request by KolbyML**
Backport of bitcoin/bitcoin#16509

Allows tests to use networks other then regtest so we can add tests for devnet and solve issue #3550 Which I will probably make a PR for later today

This PR also adds a test to solve #3550

### CODE REVIEW

**Comment by KolbyML** [comment]
I am gonna close the PR as I wanna change the code to work with devnets

**Comment by UdjinM6** [comment]
If you are going to submit another one, pls add Dash specific code as a separate commit on top of the backport to make it easier to review (reopening this PR with a changed title and marking it as "draft' for now would be ok too btw).

**Comment by PastaPastaPasta** [comment]
Agree with Udjin, would be good to mark this as a draft if you want to do the devnet stuff before we review, then add that as a separate commit

**Comment by KolbyML** [comment]
Ok I will reopen it and add draft to the title, I will probably work on it for a few days then do like dash fixup and will rename the "Dash specific code" commit

**Review by PastaPastaPasta — COMMENTED** [review]
Tested, seems to work. See comments

**Comment by KolbyML** [comment]
So you wanted me to add that? I did see that PR and did see it would make the original backport I wanted more complete but did add it because I didn't need it for what I wanted to do.

I will keep that in mind for the future, as I guess that PR does make the one I was backporting more whole, thanks for the insight.

**Comment by UdjinM6** [comment]
>because I didn't need it for what I wanted to do.

Ah, I see. It makes sense I guess for some complicated set of backports with lots of things toughed at once but this one is relatively straightforward imo and we shouldn't leave tests in some inconsistent state in general.

**Review by UdjinM6 — DISMISSED** [review]
utACK

**Comment by KolbyML** [comment]
> > because I didn't need it for what I wanted to do.
> 
> Ah, I see. It makes sense I guess for some complicated set of backports with lots of things toughed at once but this one is relatively straightforward imo and we shouldn't leave tests in some inconsistent state in general.

Oh ok. I will keep that in mind.

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
Actually, please squash 0f6f62e57cb14bbf7e1ffdfb0f1b8975ac6159a7 into 84b4721f9ad92db786cbd1f59aece0623c0a8dfc

**Comment by KolbyML** [comment]
> Actually, please squash [0f6f62e](https://github.com/dashpay/dash/commit/0f6f62e57cb14bbf7e1ffdfb0f1b8975ac6159a7) into [84b4721](https://github.com/dashpay/dash/commit/84b4721f9ad92db786cbd1f59aece0623c0a8dfc)

Ok I squashed the commits, I wanted to actually do that so awesome.

**Review by PastaPastaPasta — APPROVED** [review]
utACK, force-push clean

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
