### PR TITLE
Fix a couple of issues with PS fee calculations

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
can you provide some examples of when these fee issues would occur and don't now?

**Comment by UdjinM6** [comment]
Sure.

1. Basically, what b8b9563's description says - try selecting PS inputs in Coin Control and spending them with "subtract fee" checkbox enabled and you should notice that the fee is way too high.

2. The issue with e70413d is that we don't fully follow the logic for setting the change position in other places which can potentially cause issues for some external scripts which create PS txes via `raw` rpcs.

**Comment by PastaPastaPasta** [comment]
hmm, I'm not able to reproduce that regarding https://github.com/dashpay/dash/commit/b8b956313a55b7be88321ed892f973292e5969d6

**Comment by UdjinM6** [comment]
Re b8b9563:

Before:

Screenshot 2019-09-17 at 01 27 58

After:

Screenshot 2019-09-17 at 01 29 25

**Comment by PastaPastaPasta** [comment]
able to reproduce, thanks, will test.

**Pull request merged**
