### PR TITLE
Merge #11117: Prepare for non-Base58 addresses

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Lots of conflicts on this one, so likely so problems. I am also expecting tests to fail

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Okay, I've resolved all of the errors I've been able to, I'm not sure what to do about `address.IsScript()`

**Comment by UdjinM6** [comment]
Pls see 80507fc3f7684726bdc357dd96f59b631e43fb6e

**Comment by PastaPastaPasta** [comment]
cherry-picked

**Comment by UdjinM6** [comment]
>cherry-picked

Might need to push it again, looks like your previous attempt failed or smth - I don't see 80507fc in your branch.

**Comment by PastaPastaPasta** [comment]
I only said cherry-picked, I never said I pushed it :joy:

**Comment by UdjinM6** [comment]
FYI: test failure on Gitlab is unrelated and should be fixed by #3296

**Comment by PastaPastaPasta** [comment]
On travis blockchain.py failed

**Comment by PastaPastaPasta** [comment]
cherry-picked and pushed this time

**Pull request merged**
