### PR TITLE
backport: merge bitcoin#22817, #23042, #22777, #23774, #25443, #26138, #26854, #27128, #27761, #27863, #28287, #30118, partial bitcoin#22778 (auxiliary backports: part 16)

### PR DESCRIPTION
**Pull request by kwvg**
## Additional Information

* Depends on https://github.com/dashpay/dash/pull/6286

* Depends on https://github.com/dashpay/dash/pull/6287

* Depends on https://github.com/dashpay/dash/pull/6289

* When backporting [bitcoin#28287](https://github.com/bitcoin/bitcoin/pull/28287), `p2p_net_deadlock.py` relies on the function, `random_bytes()`, that is introduced in [bitcoin#25625](https://github.com/bitcoin/bitcoin/pull/25625). Backporting [bitcoin#25625](https://github.com/bitcoin/bitcoin/pull/25625) would attract changes outside the scope of this PR.

  In the interest of brevity, the changes that introduce `random_bytes()` have been included in [bitcoin#28287](https://github.com/bitcoin/bitcoin/pull/28287) instead.

## Breaking Changes

None expected.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas **(note: N/A)**
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation **(note: N/A)**
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by knst — COMMENTED** [review]
should you just skip 25443 because

```
test: soften connect_nodes assertions
....
Effectively reverts https://github.com/bitcoin/bitcoin/pull/25443
```
?

**Comment by kwvg** [comment]
There are changes introduced to `connect_nodes()` after bitcoin#25443 and for ease of review, bitcoin#25443 was retained to keep the diffs intact.

Making a separate "effective revert" commit _after_ `connect_nodes()` changes have been made, allows for one commit to be reverted when a potential future PR resolves the underlying cause instead of modifying every commit that changes `connect_nodes()` to account for the absence of bitcoin#25443.

**Comment by knst** [comment]
we don't have signet as well:
```
# Setup the three signets, which are incompatible with each other
```

> allows for one commit to be reverted when a potential future PR
Do 20445 "partial" at least... No one going to remember, that we need to revert here something, add TODO maybe?

**Comment by UdjinM6** [comment]
let's extract https://github.com/dashpay/dash/pull/6276/commits/fd82bdc09eea333465c495320927e0e963e0bddf and https://github.com/dashpay/dash/pull/6276/commits/927dd6f92e0a2cca56544f5f9bbd64a3244010b1 into their own PR maybe?

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
`p2p_node_network_limited.py` fails. Backporting 30118 (2c825b4b4a) should help.

**Review by UdjinM6 — APPROVED** [review]
utACK e458adb61ce4ca557f45bc5b713f976676ee4f78

**Review by PastaPastaPasta — APPROVED** [review]
utACK e458adb61ce4ca557f45bc5b713f976676ee4f78

**Pull request merged**
