### PR TITLE
backport: bitcoin#18038, #14193, #17564, #17999, #18740, #19096, #16426, #17737, #18698: deglobalization backports (part 2)

### PR DESCRIPTION
**Pull request by kittywhiskers**
Made possible with significant contributions by @UdjinM6

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see below + https://github.com/UdjinM6/dash/commits/pr4801 + rebasing after https://github.com/dashpay/dash/pull/4826 should help a bit

**Comment by UdjinM6** [comment]
pls see https://github.com/UdjinM6/dash/commits/pr4801

**Review by PastaPastaPasta — DISMISSED** [review]
utACK for merging via merge commit

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
It looks like I messed up in 784ba27a2e9da233f9dc32a1984bdd718d28875b - it's incomplete (wallet crashes on testnet due to potential deadlocks) and fixing it makes things looks ugly and fragile...  Sorry! 🙈 let's revert changes added via 784ba27a2e9da233f9dc32a1984bdd718d28875b (880320fc6e83d3923d9fbab0d546a2d625857caa) and apply 8e5c343ae134741c9bf23f1fa79de768e04589d4 and 2f5339d5b822a48e7841c4bc5f2dc1cb3597115b instead. I _think_ it should work but pls test it too!

**Review by UdjinM6 — DISMISSED** [review]
ok, it looks stable now :)

ACK

**Review by UdjinM6 — APPROVED** [review]
LGTM, ACK

**Review by PastaPastaPasta — DISMISSED** [review]
utACK for merging via merge commit

**Comment by UdjinM6** [comment]
LGTM but 16426 was built on top of 16034 originally and we backport 16034 in #4679 which should be merged first imo. This PR should be rebased after that.

**Review by UdjinM6 — APPROVED** [review]
LGTM, re-ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
