### PR TITLE
bitcoin#8365: Treat high-sigop transactions as larger rather than rejecting them

### PR DESCRIPTION
**Pull request by kittywhiskers**
Split as https://github.com/dashpay/dash/pull/4562 (this PR) and https://github.com/dashpay/dash/pull/4560 for ease of review

### CODE REVIEW

**Review by PastaPastaPasta — DISMISSED** [review]
LGTM, but I'm not positive that this is correct / ideal. Waiting for Udjin
utACK for squash merge

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
I don't think we can just drop `nSigOps > nSize / nBytesPerSigOp` and tweak help text without implementing actual changes it describes, that feels wrong. Moreover, going through 8365 discussion it looks like it's a bugfix and it makes sense to backport it imo. I guess we missed it due to a very segwit-only looking code but it's not segwit-only actually. Also, I found a couple of related bugs (in test and bench) while trying to make it work. Anyway, pls see https://github.com/UdjinM6/dash/commits/pr4562

**Review by PastaPastaPasta — APPROVED** [review]
UtACK for squash merge

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
