### PR TITLE
test: multiple linter warnings to suppress or fix

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
On my local kubuntu linters have way too much spam

## What was done?
See each commit

## How Has This Been Tested?
Run locally. Amount of warnings decreased from thousands to fewer amount. Excluding typos, they are:
```
src/coinjoin/client.cpp:1420:5: warning: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
src/coinjoin/client.cpp:1426:5: warning: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
src/coinjoin/client.cpp:655:26: warning: Consider using std::copy_if algorithm instead of a raw loop. [useStlAlgorithm]
src/coinjoin/server.cpp:593:33: warning: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
src/coinjoin/server.cpp:630:106: warning: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
src/governance/governance.cpp:1057:9: warning: C-style pointer casting [cstyleCast]
src/governance/governance.cpp:1068:9: warning: C-style pointer casting [cstyleCast]
src/governance/governance.cpp:1079:13: warning: C-style pointer casting [cstyleCast]
src/governance/governance.cpp:1086:9: warning: C-style pointer casting [cstyleCast]
src/governance/governance.cpp:1094:9: warning: C-style pointer casting [cstyleCast]
src/governance/governance.cpp:1099:5: warning: C-style pointer casting [cstyleCast]
src/governance/governance.cpp:1486:34: warning: Consider using std::copy_if algorithm instead of a raw loop. [useStlAlgorithm]
src/llmq/commitment.cpp:102:5: warning: Consider using std::all_of or std::none_of algorithm instead of a raw loop. [useStlAlgorithm]
src/llmq/instantsend.cpp:820:38: warning: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
src/llmq/quorums.cpp:831:102: warning: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
src/llmq/quorums.h:300:17: warning: C-style pointer casting [cstyleCast]
src/llmq/quorums.h:301:17: warning: C-style pointer casting [cstyleCast]
src/llmq/quorums.h:302:17: warning: C-style pointer casting [cstyleCast]
src/llmq/quorums.h:303:17: warning: C-style pointer casting [cstyleCast]
src/spork.cpp:119:58: warning: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
src/statsd_client.cpp:234:63: warning: C-style pointer casting [cstyleCast]

Advice not applicable in this specific case? Add an exception by updating
IGNORED_WARNINGS in test/lint/lint-cppcheck-dash.sh
^---- failure generated from test/lint/lint-cppcheck-dash.sh
Consider install flake8-cached for cached flake8 results.
test/functional/data/invalid_txs.py: error: Source file found twice under different module names: "invalid_txs" and "data.invalid_txs"
test/functional/data/invalid_txs.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
test/functional/data/invalid_txs.py: note: Common resolutions include: a) adding `__init__.py` somewhere, b) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
^---- failure generated from test/lint/lint-python.s
```
 

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
I think NACK on cppcheck changes here (https://github.com/dashpay/dash/pull/5880/commits/ed6f3df5ff8df380b016f857053214e05b53b65e) in current state. Can you look at your version of cppcheck? 

We currently use `ARG CPPCHECK_VERSION=2.10` in docker and everything is happy there.

I've found that different minor versions of cppcheck have significant regressions that cause these kind of issues. I think your other changes are good

**Review by UdjinM6 — APPROVED** [review]
light ACK (compiles and tests are ok, less linter complaints on mac too)

**Comment by knst** [comment]
> We currently use ARG CPPCHECK_VERSION=2.10 in docker and everything is happy there.

`cppcheck 2.11` is running by me.

**Comment by PastaPastaPasta** [comment]
> > We currently use ARG CPPCHECK_VERSION=2.10 in docker and everything is happy there.
> 
> `cppcheck 2.11` is running by me.

Yeah; I feel like that is the "issue" here. It may make sense to include these suppressions, but only if we bump to cppcheck 2.11 (but I'd also want us to see if these suppressions are needed with 2.12 or 2.13)

**Comment by knst** [comment]
> (but I'd also want us to see if these suppressions are needed with 2.12 or 2.13)

see https://github.com/dashpay/dash/pull/5880#pullrequestreview-1888670859
> EDIT: I use cppcheck 2.13.0 installed via brew

**Comment by UdjinM6** [comment]
> > > We currently use ARG CPPCHECK_VERSION=2.10 in docker and everything is happy there.
> > 
> > 
> > `cppcheck 2.11` is running by me.
> 
> Yeah; I feel like that is the "issue" here. It may make sense to include these suppressions, but only if we bump to cppcheck 2.11 (but I'd also want us to see if these suppressions are needed with 2.12 or 2.13)

I can confirm that 2.13.0 (current stable release) still needs them

**Comment by PastaPastaPasta** [comment]
> > (but I'd also want us to see if these suppressions are needed with 2.12 or 2.13)
> 
> see [#5880 (review)](https://github.com/dashpay/dash/pull/5880#pullrequestreview-1888670859)
> 
> > EDIT: I use cppcheck 2.13.0 installed via brew

Well; yeah, Udjin is saying it's happy with 2.13; but are the suppressions needed?

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Comment by UdjinM6** [comment]
@knst hmm.. so you decided to drop a9add44. why?

**Comment by knst** [comment]
> hmm.. so you decided to drop [a9add44](https://github.com/dashpay/dash/commit/a9add44e1bed7f959d8c014fed2a4cb0dd8bb358). why?

@UdjinM6 
By pasta's request, I will prepare new PR later:
https://github.com/dashpay/dash-issues/issues/67

**Review by UdjinM6 — APPROVED** [review]
sad :(

Anyway, utACK

**Pull request merged**
