### PR TITLE
 Merge #14023: Remove accounts rpcs

### PR DESCRIPTION
**Pull request by pravblockc**
bb08423d5ca866d4a139a3b57ff110d818d08b32 [doc] Add release notes for 'account' API removal (John Newbery)
1f4b865e57b4567270b1586bb1f348ab9106485d [wallet] Re-sort wallet RPC commands (John Newbery)
f0dc850bf698f7377797d7d68365d4fc79b0221c [wallet] Remove wallet account RPCs (John Newbery)
c410f415758913c933ad6c71cf50227cc85aa385 [tests] Remove wallet accounts test (John Newbery)

Pull request description:

  This is the first part of #13825. It simply removes the RPC methods and tests.

  #13825 touches lots of files and will require frequent rebasing.

  Breaking it down for easier reviewing and fewer rebases.

Tree-SHA512: d29af8e7a035e4484e6b9bb56cb86592be0ec112d8ba4ce19c15d15366ff3086e89e99fca26b90c9d66f6d3e06894486d0f29948df0bb7dcb1e2c49c6887a85a

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Linter and tests currently failing. Please take another look at this, and let me / Udjin know if you end up needing some help. Marking as draft right now. Please mark as ready for review once you fix those issues.

**Comment by pravblockc** [comment]
@PastaPastaPasta  We have already discussed about this issue(failing wallet_listtransactions.py test- listtransactions returning 0)
I have requested @UdjinM6 help through slack

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Ok, so this is a tricky one. The problem is that we already backported 14441 which backported 14411 (to 0.17 btc branch) which in its turn reverted some of the changes made in 14023. So the easiest way to backport 14023 now is to revert 14441, apply 14023 (correctly), and then backport 14411. This should get us back on track with btc master backports. But 14411 requires at least https://github.com/bitcoin/bitcoin/commit/c9c32e6b844fc79467b7e24c6c916142a0d08484 (I can't find the PR it was merged with though 👀 @PastaPastaPasta ). I created a branch here with all the fixes and it _seems_ to be working https://gitlab.com/UdjinM6/dash/-/pipelines/349680102.

**Comment by UdjinM6** [comment]
No updates for 1+ month. Closing this one and continuing in #4442.

**Pull request closed without merging**
