### PR TITLE
Refactor PrivateSend

### PR DESCRIPTION
**Pull request by UdjinM6**
This only moves things around and drops deprecated stuff, should be no protocol level or functional changes.

### CODE REVIEW

**Comment by gladcow** [comment]
ACK, tested client PS functionality

**Comment by UdjinM6** [comment]
rebased to solve merge conflicts

**Comment by UdjinM6** [comment]
Dropped `GetMasternodeByRank` (it's not used anymore after `darksend-relay.*` removal)

**Comment by gladcow** [comment]
utACK

**Pull request merged**
