### PR TITLE
build: add libgmp detection, make immer a package

### PR DESCRIPTION
**Pull request by kittywhiskers**

### CODE REVIEW

**Comment by kittywhiskers** [comment]
Dropping `bls-dash` detection for now, error cannot be reproduced locally

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Looks good but needs a bit of cleanup in tools https://github.com/UdjinM6/dash/commit/08218edfb7093824fceeac47732bca9cfec39b49

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
