### PR TITLE
[0.13.0.x] Translations201901

### PR DESCRIPTION
**Pull request by UdjinM6**
80%+ completion languages ([X] means 100% and added to this PR):
- [x] ar
- [X] bg
- [X] de
- [X] es
- [X] fi
- [x] fr
- [X] it
- [x] ja
- [X] ko
- [X] nl
- [X] pl
- [x] pt
- [X] ru
- [X] sk
- [X] th
- [X] tr
- [X] vi
- [X] zh_CN
- [x] zh_TW

### CODE REVIEW

**Comment by akijuh** [comment]
@udjinM6 

Fi done.
Can you tell me where is word popup used, ie related to popup window or something else, i'm not sure.

**Comment by UdjinM6** [comment]
@akijuh if it's the one about PrivateSend, then yes, it's a notification/popup/window - that thing which is shown when new tx is received.

**Comment by akijuh** [comment]
@UdjinM6
Yes, there is 2 of them, and both are related to PS.
Thanks, all good.

**Comment by UdjinM6** [comment]
Yep, it's the checkbox in settings (Preferences -> Wallet -> Expert) and its tooltip.

**Comment by UdjinM6** [comment]
Updated PR description to give a better sense of the progress.

**Comment by UdjinM6** [comment]
No longer WIP, should be ready for reviews.

**Pull request merged**
