### PR TITLE
Merge master 0.16.0.1 back into develop

### PR DESCRIPTION
**Pull request by UdjinM6**
~EDIT: it looks like Gitlab CI fails on `test/lint/commit-script-check.sh` with some weird error and I can't figure out why (and there are no scripted-diff commits here).~ Have to bump `GIT_DEPTH` to 150 to temporary fix it. Travis is green https://travis-ci.com/github/UdjinM6/dash/builds/189855974 (but `test/lint/commit-script-check.sh` is skipped there because it's just another branch, not a PR).

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Build fails

**Comment by UdjinM6** [comment]
Added e537c3c which should fix the build. It's a temporary fix for a huge commit list. Not sure if it's ok to keep it this way, Gitlab suggests using lower values (e.g. 10, default is 50) to speed things up https://docs.gitlab.com/ee/ci/large_repositories/#shallow-cloning. We do not have huge files though, so maybe 150 is ok-ish to keep. If you think it's not, pls ACK eeadfe4 instead and I'll drop e537c3c.

**Comment by xdustinface** [comment]
@UdjinM6 want to make a `Merge master 0.16.1.1 back into develop` here or should this be seperated? 

Btw, im good with trying e537c3c and see if it causes any problems/slowdowns... We will anyway run into the same again if we don't add it? But me feeling says it should be fine.. 3x default doesn't sound that bad also with a max of 20x default haha.. 

Nit: Maybe remove the `# temporary fix` then if we go with it?

**Comment by UdjinM6** [comment]
>want to make a Merge master 0.16.1.1 back into develop here or should this be separated?

This set contains quite a few changes to images and it's a pita to resolve merge conflicts for binary files, so I would _really_ like to avoid doing that again :)

> We will anyway run into the same again if we don't add it? 

My understanding is that this will only happen for PRs with 50+ commits which we should avoid. If we all agree that a patch like e537c3c is still a nice/useful/harmless thing to have I would suggest to drop it here anyway and submit it as a separate PR to avoid bringing this change in a "merge back" pack.

**Comment by xdustinface** [comment]
> My understanding is that this will only happen for PRs with 50+ commits (and we should avoid producing such monsters normally). 

Yeah i meant, after the next big release if we again end up with the a merge master back PR

> If we all agree that a patch like [e537c3c](https://github.com/dashpay/dash/commit/e537c3c1fb474586bb567ef9714614a869562348) is still a nice/useful/harmless thing to have I would suggest to drop it here anyway and submit it as a separate PR to avoid bringing this change in a "merge back" pack.

Alright, im in, lets see what @PastaPastaPasta has to say

**Review by PastaPastaPasta — APPROVED** [review]
utACK eeadfe4d0b69eef7d62a753169c4240d11b5bbf8

I lean towards not bumping GIT_DEPTH. We should hardly ever produce PRs this large, even after releases, this is out of the usual due to the fact we were developing v0.17 for a while before releasing 0.16

**Comment by UdjinM6** [comment]
Dropped e537c3c

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
