### PR TITLE
qt: Finetune CoinControlDialog + bitcoin#14828

### PR DESCRIPTION
**Pull request by xdustinface**
The rows resize without it if they get locked and the lock icon appears besides the checkbox. Looks weird.. and especially if you press the lock all button its just not nice.

#### Update
The scope has been expanded during review, see https://github.com/dashpay/dash/pull/3701#issuecomment-693697063 for the final result.

### CODE REVIEW

**Comment by UdjinM6** [comment]
I can't reproduce the issue...

**Comment by xdustinface** [comment]
Hmm can you send screens? Does it make anything look worse over there? 

Here is how it looks on my mac

Unlocked          |  Locked
:-------------------------:|:-------------------------:
 |  

And here besides the "lock resizes the items" thing linux needs min-height anyway otherwise it looks squished imo.
Linux without min-height  |  Linux with min-height
:-------------------------:|:-------------------------:
 |  

Also on windows it doesn't hurt..

Windows without min-height  |  Windows with min-height and hover transparency
:-------------------------:|:-------------------------:
 |  

Not sure how this stuff looks on other resolutions but here in my VMs it this improves it

**Comment by UdjinM6** [comment]
I don't know, for me it just works, nothing jumps or shifts anywhere. With this patch it looks ok-ish but there is too much space between rows now imo. Lets maybe add some lines there e.g. aa48d26dda (this also unifies the look with other tables as a side effect :) )?

**Comment by UdjinM6** [comment]
Also, how about applying 9f02792ee5 while at it? This one is from btc 0.18 and had a couple of (trivial-ish) merge conflicts, so (if @PastaPastaPasta would complain :P) we could simply reduce this https://github.com/dashpay/dash/blob/develop/src/qt/forms/coincontroldialog.ui#L379 by 2 instead for now. And then apply smth like 8cf9965c95 maybe.

| Mode | This PR currently | With 3 more patches on top |
|-|-|-|
| List | Screenshot 2020-09-13 at 13 52 20 | Screenshot 2020-09-13 at 13 53 29 |
| Tree | Screenshot 2020-09-13 at 13 52 32 | Screenshot 2020-09-13 at 13 53 43 |

**Comment by xdustinface** [comment]
@UdjinM6 I won't be able to test it until late evening here my time, but in the meantime, from looking at the screenshots i see some things we should probably still tweak

- The lines are not fully drawn over the full width.. looks a bit strange to me right now but im also not sure how good it will look like in the tree mode with fully drawn lines. I think that was even one reason why i initially removed the lines in the CoinControl :D In case you want to try it i think you can extend them with `::branch`.
- The last column in your patched screenshots are not stretched so there is a gap between the column end and the border of the widget. I think it should still be possible to stretch them over the full width without getting a horizontal scroll, no? 

I would be fine with adding the bitcoin backport here btw 👍 lets see what pasta has to say.

**Comment by xdustinface** [comment]
@UdjinM6 i added some more commits with the following impacts: 

- 69bed8d adds the border like you proposed.. didn't add the branch borders i talked about, even though it somehow looks "unfinal" without them it still looks better compared to when the lines are over the full width :D 
- 55d6d64 streches the address column to have the tree stretched over the full width, solves the issue with the last column i pointed out in your last suggestions 
- 7327ed1
    - Hides Denominated/Collateral utxos for normal Send tab's CoinControl by default (Still possible to show them with a new button)
    - Hides not fully mixed utxos in PrivateSend tabs's CoinControl by default (Still possible to show them with a new button, helps to see whats going on with the mixing process)
- f0fb60f Removes the mixing rounds from the normal Send tab's CoinControl as it doesn't make a lot sense there imo
- fcdf46b Removes the selection between list/tree mode for PrivateSend CoinControl as we anyway will always have only 1 utxo per address it makes no sense to offer tree view, right? Correct me if there are cases where it would make sense to have a tree view! 
-  9272da7 Hides the label column in the PrivateSend CoinControl, didn't see the point in leaving it there, complain if there are reasons.. 
- 631d08b I guess it makes sense now to rename it as we won some space and we can have a longer string for it. 
- f2e2d70 looks like something the guys from the bitcoin PR missed?

### Preview 

| Mode |Before| With this PR|
|-|-|-|
| Send Tree | Bildschirmfoto 2020-09-16 um 22 52 40 | Bildschirmfoto 2020-09-16 um 22 47 07 |
| Send List | Bildschirmfoto 2020-09-16 um 22 52 32 | Bildschirmfoto 2020-09-16 um 22 47 03 | 
| PrivateSend |  Bildschirmfoto 2020-09-16 um 22 53 04 | Bildschirmfoto 2020-09-16 um 23 29 36

**Comment by UdjinM6** [comment]
That's an interesting idea 👍 How about 2bf641fb47 on top of it?

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by UdjinM6 — APPROVED** [review]
re-ACK

**Comment by PastaPastaPasta** [comment]
Initial thoughts (might get edited as I find more stuff I don't like :D ) :
PrivateSend tab inputs should default to show all privatesend coins, not default to only fully mixed coins

**Comment by xdustinface** [comment]
> PrivateSend tab inputs should default to show all privatesend coins, not default to only fully mixed coins

To be honest, i don't think that this makes a lot sense. Why do you think that? The purpose of this dialog is to pick coins for sending, means there is actually no need to show unrelated (non-spendable) entries by default it's just a nice to have IMO.

> Also, please edit the initial post that gives the high level of all the changes this PR includes

Oh will do 👍 didn't realize that the scope of this PR has become that big compared to what the initial post says 😄

**Comment by PastaPastaPasta** [comment]
> > PrivateSend tab inputs should default to show all privatesend coins, not default to only fully mixed coins
> 
> To be honest, i don't think that this makes a lot sense. Why do you think that? The purpose of this dialog is to pick coins for sending, means there is actually no need to show unrelated (non-spendable) entries by default it's just a nice to have IMO.

If we don't do that, I think people are going to "lose" coins after they get denominated but not fully mixed, since they won't be able to see those coins in either the Send tab or PrivateSend tab

**Comment by xdustinface** [comment]
> > > PrivateSend tab inputs should default to show all privatesend coins, not default to only fully mixed coins
> > 
> > 
> > To be honest, i don't think that this makes a lot sense. Why do you think that? The purpose of this dialog is to pick coins for sending, means there is actually no need to show unrelated (non-spendable) entries by default it's just a nice to have IMO.
> 
> If we don't do that, I think people are going to "lose" coins after they get denominated but not fully mixed, since they won't be able to see those coins in either the Send tab or PrivateSend tab

Well.. the button says `Show all PrivateSend coins` so i guess the moment of "lose" coins will be very short, no? :D

**Comment by PastaPastaPasta** [comment]
> > > > PrivateSend tab inputs should default to show all privatesend coins, not default to only fully mixed coins
> > > 
> > > 
> > > To be honest, i don't think that this makes a lot sense. Why do you think that? The purpose of this dialog is to pick coins for sending, means there is actually no need to show unrelated (non-spendable) entries by default it's just a nice to have IMO.
> > 
> > 
> > If we don't do that, I think people are going to "lose" coins after they get denominated but not fully mixed, since they won't be able to see those coins in either the Send tab or PrivateSend tab
> 
> Well.. the button says `Show all PrivateSend coins` so i guess the moment of "lose" coins will be very short, no? :D

IMO, the default between the two tabs, needs to show all coins. If we want the "Send" tab to show all coins that are not fully mixed, then that's fine, but I'd prefer just changing the default on privatesend tab to be showing all, if someone wants to see just mixed coins, it's just a click away

**Comment by xdustinface** [comment]
> if someone wants to see just mixed coins, it's just a click away

Same applies vice versa, not? 

And still, the main purpose of the tab is "Pick coins to Send" not "Look what your coins are doing" so i guess it will happen more often that you need to do that one click if they are shown by default because the not fully mixed just distract when choosing coins.

**Comment by PastaPastaPasta** [comment]
> > if someone wants to see just mixed coins, it's just a click away
> 
> Same applies vice versa, not?
> 
> And still, the main purpose of the dialog is "Pick coins to Send" not "Look what your coins are doing" so i guess it will happen more often that you need to do that one click if they are shown by default because the not fully mixed just distract when choosing coins.

Maybe it's just my usage, but I probably use it more often as a way to see the status of my outputs then choosing the outputs to spend

**Comment by UdjinM6** [comment]
Agree with @xdustinface on this, the purpose of this dialog is to list coins that are safe to spend and not coins that are (potentially) yours. When IS is disabled you won't see 0-conf coins received from someone else for example (same as in btc). With this in mind it makes perfect sense imo to make it harder for advanced users to mess things up (spending "fully mixed" coins in non-PS tx creates new change output which will become a link between this tx and some another tx spending it) and makes it easier to pick coins that are actually ready to spend (by hiding/disabling coins that are PS elated but aren't spendable via PS yet/at all).

**Comment by PastaPastaPasta** [comment]
> Agree with @xdustinface on this, the purpose of this dialog is to list coins that are safe to spend and not coins that are (potentially) yours. When IS is disabled you won't see 0-conf coins received from someone else for example (same as in btc). With this in mind it makes perfect sense imo to make it harder for advanced users to mess things up (spending "fully mixed" coins in non-PS tx creates new change output which will become a link between this tx and some another tx spending it) and makes it easier to pick coins that are actually ready to spend (by hiding/disabling coins that are PS elated but aren't spendable via PS yet/at all).

Okay, I'd prefer at least in the long term to make it even harder spending mixed funds in a not PrivateSend tx.

@xdustinface please update pr description and I'll try to give it a full review tomorrow

**Comment by xdustinface** [comment]
> @xdustinface please update pr description 

Done

**Review by PastaPastaPasta — APPROVED** [review]
ACK, all working as expected. mild code review

**Pull request merged**
