### PR TITLE
Use LogPrintf instead of LogPrint

### PR DESCRIPTION
**Pull request by CryptoDJ**

### CODE REVIEW

**Comment by UdjinM6** [comment]
Why?

PS. same question applies to #663

**Comment by CryptoDJ** [comment]
For consistency since LogPrintf is used elsewhere in this method.   When reading the code, I thought it was doing something different but when I looked at the definition, they are the same. 

different issue:  why is #define used instead of static const in masternode-budget.h and other places.
#define VOTE_ABSTAIN  0  
should be changed to
static const uint32_t VOTE_ABSTAIN = 0;  
Many recommend against using the preprocessor for constants (see Scott Meyers).  If you agree they all should be changed to const, I will submit a pull.

**Comment by UdjinM6** [comment]
Ah, I see. But no, they are different. Note that `LogPrint` here uses debug category `mnbudget` to suppress log output and prevent unwanted log spam unless you really want to see it (i.e. you are debugging budget messages with `-debug=mnbudget` cmd-line switch). `LogPrintf` however ignores categories so it will always write to `debug.log` which is no good in this particular case.

RE define->static: this part is off topic here but I agree we should name/use things in a more consistent way...  blame @evan82 for this :stuck_out_tongue_winking_eye: Not sure if it's critical though... I guess you can make a PR and we'll move this part of discussion there (let's see what others think about it).

**Comment by CryptoDJ** [comment]
Okay, thank you and I will submit a separate pull request for the #define proposal.  This masternode budget code is really impressive.   @evan82, you and the rest of the Dash development team should get more recognition for this innovative technology.

**Pull request closed without merging**
