### PR TITLE
Fix crash in UpdatePreferredDownload

### PR DESCRIPTION
**Pull request by spencerlievens**

### CODE REVIEW

**Comment by tgflynn** [comment]
The locking problem that causes this crash should have been fixed here:

https://github.com/dashpay/dash/pull/1389

It shouldn't be possible for UpdatePreferredDownload to be called with a NULL state argument.

**Comment by UdjinM6** [comment]
Agree with @tgflynn 
Also in general it's not a good idea to fail silently imo.

**Comment by spencerlievens** [comment]
I actually also implemented #1389 as well as this.

**Comment by UdjinM6** [comment]
This was fixed by backporting

**Pull request closed without merging**
