### PR TITLE
[WIP] Tweak UI design (overview screen, bg and toolbar)

### PR DESCRIPTION
**Pull request by UdjinM6**
Just experimenting and trying to make UI a bit cleaner and closer to our new style guide...

Current:
screen shot 2018-08-05 at 23 14 55

This PR:
screen shot 2018-08-05 at 23 06 21

Note: Current implementation overrides `light` theme and does _not_ preserve the "old layout/new logo" theme. It also removes annoying red out-of-sync labels from `light` theme.

### CODE REVIEW

**Comment by thephez** [comment]
Looks like it is a little difficult to tell which item (Overview/Send/Receive/etc.) is selected in the new screenshot since the selected item is not a different colour. :thinking:

**Comment by akijuh** [comment]
Agree, selected TAB should be different color.

**Comment by nmarley** [comment]
I like the progress so far. Would be great to remove the red lines and new icons in the tabs as well which align w/new guidelines for style and colors.

**Comment by PaulieD** [comment]
JeffH complained to me not too long ago, that at weird proportions, the background / logo was stretched and augmented, which is against the style guide.

**Comment by UdjinM6** [comment]
Closing in fav of #3000

**Pull request closed without merging**
