### PR TITLE
qt: Improved status bar

### PR DESCRIPTION
**Pull request by xdustinface**
Based on #3574  

## General 
The colors red, orange and green are used to signal different states of the icon's underlying functionalities. Like, green means just all good, orange is like a warning/kind of good/busy and red is danger/bad/disabled. I personally think that makes the status bar much more meaningful and it should be clear by intuition quickly what the stuff means when it's used. However, if you feel there is room for improvement let me know. 

## HD icon
- Always enabled (was disable before if it was no HD wallet which reduced its opacity slightly)
- The crossed HD icon `hd_disabled.png` is not longer used (i have asset cleanup PR coming later so the icons stays in here with this PR). Instead the following rule applies:
    - HD wallet -> Green HD icon
    - non HD wallet -> Grey HD icon

The grey disabled version was discussion in slack. But honestly i guess we should think one more time about this and either just hide the HD icon by default if no HD is enabled or give it a red HD icon if its not enabled just to follow the same line like with the other icons aka red == disabled and not mix the disabled state with red/grey. @UdjinM6 specifically pinging you at this point, i think you suggested the grey. Thoughts? 

HD disabled before            |  HD disabled now
:-------------------------:|:-------------------------:
 |  

HD enabled before            |  HD enabled now
:-------------------------:|:-------------------------:
 | 

## Sync icon
- Sync spinner icon color from blue to orange 
- Synced checkmark icon from blue to green

Syncing icon before            |  Syncing icon now
:-------------------------:|:-------------------------:
 | 

Synced icon before            |  Synced icon now
:-------------------------:|:-------------------------:
 | 

## Encryption icon
- The opened lock is always visible, even if the wallet is not encrypted. This was not the case before. Reason i did this change is to signal the user directly that they use an unencrypted wallet which is bad thing to do imo. 
- Besides this the following rules apply for this icon: 
    - Red - Opened lock, Unencrypted / Unlocked
    - Orange - Opened lock, Unlocked for mixing only
    - Green Closed lock, Encrypted + Locked

Unencrypted before            |  Unencrypted now
:-------------------------:|:-------------------------:
**Icon was just hidden** | 

Unlocked before            |  Unlocked now
:-------------------------:|:-------------------------:
 | 

Unlocked for mixing only before            |  Unlocked for mixing only now
:-------------------------:|:-------------------------:
 | 

Locked before            |  Locked now
:-------------------------:|:-------------------------:
 | 

## Network icon
- The 100% filled network icon gets the color green. The partially filled variations are getting the color orange. If there is no connection it stays grey. 
- The allocation "connections <-> segments in the icon" gets a small reallocation. 
    - 0 connections -> fully grey (like before)
    - 1-2 connections -> only the orange dot at the bottom (was 1-3 before)
    - 3-5 connections -> orange dot + 1 orange segment (was 4-6 before)
    - 6-7 connections -> orange dot + 2 orange segments (was 7-9 before)
    - 8 or more -> fully green (10 or more before)  

Network disabled before            |  Network disabled now
:-------------------------:|:-------------------------:
 | 

Network 0 connections before            |  Network 0 connections now
:-------------------------:|:-------------------------:
 | 

Network 3 connections before            |  Network 3 connections now
:-------------------------:|:-------------------------:
 | 

Network >=8 connections before            |  Network >=8 connections now
:-------------------------:|:-------------------------:
 | 

# Best case

This is an example how a fully synced and encrypted HD wallet looks like before and now

Before            |  Now
:-------------------------:|:-------------------------:
 |

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Greyed out HD doesn't seem super intuitive to me

Otherwise, general concept ACK

**Comment by UdjinM6** [comment]
Yeah, the HD icon is kind of a pointless one for most users cause HD mode is disabled by default. Might be a good idea to just hide it if current wallet is a non-HD one.

**Comment by xdustinface** [comment]
Done, im glad you felt the same :D

**Comment by xdustinface** [comment]
Rebased on develop

**Comment by UdjinM6** [comment]
I think you need to update HD icon here since this change was reverted in #3574

**Comment by xdustinface** [comment]
good point haha

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
