### PR TITLE
refactor: move some protocol constants

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by UdjinM6** [comment]
1. Good catch re removal of `GOVERNANCE_FILTER_PROTO_VERSION` 👍  but I don't see a reason to move the rest into `version.h`:
   - `GOVERNANCE_POSE_BANNED_VOTES_VERSION` is only used in `governance-vote.cpp` (and only once)
   - `MIN_GOVERNANCE_PEER_PROTO_VERSION` is used mostly in `governance.cpp`. But it's not really doing anything meaningful atm cause such peers won't pass (an earlier) `MIN_PEER_PROTO_VERSION` check anyway. Moving it to `version.h` brings 0 value imo.

   I would rather move `GOVERNANCE_POSE_BANNED_VOTES_VERSION` into `governance-vote.h` and `MIN_GOVERNANCE_PEER_PROTO_VERSION` into `governance.h` if you want some cleanup anyway. And btw, build fails due to some missed includes in 5aeff49 it seems.

2. Should backport https://github.com/bitcoin/bitcoin/pull/14033 and https://github.com/bitcoin/bitcoin/pull/19486 instead of 86faf7f but I would suggest to simply ignore `CADDR_TIME_VERSION` for now to avoid potential merge conflicts in the future.

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
see above

**Comment by PastaPastaPasta** [comment]
The value of moving the network constants is having all the network constants in one place, and b/c of that easily seeing what constants are out of date

**Comment by PastaPastaPasta** [comment]
dropped CADDR commit

**Comment by UdjinM6** [comment]
>The value of moving the network constants is having all the network constants in one place, and b/c of that easily seeing what constants are out of date

Hmm.. ok. Let's maybe also move `MIN_PRIVATESEND_PEER_PROTO_VERSION` then?

**Comment by PastaPastaPasta** [comment]
added coinjoin proto moving, as well as a rebase

**Review by UdjinM6 — APPROVED** [review]
👍 

utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
