### PR TITLE
Update .clang-format to more accurately show the actual style

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
There hasn't been enough drama lately, and we all know the quickest way to create dev drama is to talk about style ;)

### Changes explained:

`BinPackArguments: true` allows multiple arguments to be on the same line if needed.
false requires each param to be on a new line if the line needs to be split.
ex:
```
void f() {
  f(aaaaaaaaaaaaaaaaaaaa, aaaaaaaaaaaaaaaaaaaa,
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa);
}
```

`BreakBeforeTernaryOperators: true` was prior false. true reads easier imo and is clearer

ex:
true
```
veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongDescription
    ? firstValue
    : SecondValueVeryVeryVeryVeryLong;
```
false
```
veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongDescription ?
    firstValue :
    SecondValueVeryVeryVeryVeryLong;
```

`ColumnLimit:     128`
This means that once a line gets over 128 columns long, it will be likely to be broken in the next couple of chars depending on the situation(will sometimes be a little longer to keep a string together etc based on the penalties below). Based on the current clang file it basically means that single expressions should NEVER get split, which is definitely not the style we actually follow.

**Penalties**
For each column above 128 there is a penalty of 5. That means that single strings and other situations where you don't want a break can be normally held together longer even if it is strictly over the column limit.

### CODE REVIEW

**Comment by UdjinM6** [comment]
>Based on the current clang file it basically means that single expressions should NEVER get split, which is definitely not the style we actually follow.

This is not accurate imo, see https://clang.llvm.org/docs/ClangFormatStyleOptions.html:
>A column limit of 0 means that there is no column limit. In this case, clang-format will respect the input’s line breaking decisions within statements unless they contradict other rules.

I'd keep `ColumnLimit` as is.

**Comment by UdjinM6** [comment]
Interesting... It looks like it only squashed lines for https://github.com/PastaPastaPasta/dash/commit/1dca0c6bd4bb626033e020d253d81131d43464dd#diff-6e1f8089e8fd6f74c2080971eb37f792R139 but not https://github.com/PastaPastaPasta/dash/commit/1dca0c6bd4bb626033e020d253d81131d43464dd#diff-6e1f8089e8fd6f74c2080971eb37f792R659. The former should really be split into smth like
```
std::string strMessage = strprintf("Version must be %d or greater", MIN_GOVERNANCE_PEER_PROTO_VERSION);
connman.PushMessage(pfrom, CNetMsgMaker(pfrom->GetSendVersion()).Make(NetMsgType::REJECT, strCommand, REJECT_OBSOLETE, strMessage));
```
for better readability anyway. Btw, I would also personally prefer to keep an indentation for the later (`LogPrintf`) and alike as is i.e. set `ContinuationIndentWidth: 8`. And while we are at it, I also like `BreakConstructorInitializers: AfterColon` option :)

Another interesting thing I noticed is https://github.com/PastaPastaPasta/dash/commit/1dca0c6bd4bb626033e020d253d81131d43464dd#diff-6e1f8089e8fd6f74c2080971eb37f792R598 which looks weird but that's probably because we should have `break;` _inside_ of the curly braces in the first place... 🙈

**Comment by PastaPastaPasta** [comment]
Okay, integrated those changes. Still not sure bout column limit ¯\\_(ツ)_/¯

Reformatted governance.cpp is below, that branch has been rebased on top of this updated clang.
https://github.com/PastaPastaPasta/dash/commit/8326b4c6fc095c3a4111ff74af00c9b1cb246a7f

**Comment by PastaPastaPasta** [comment]
Just added `AlignConsecutiveAssignments: true` which means the following will be the standard:

```
int aaaa = 12;
int b    = 23;
int ccc  = 23;
```
Based on a lot of code, that is a normal standard we have been doing

**Comment by PastaPastaPasta** [comment]
Re governance.cpp example file, reverted the two prior formatting changes, and formatted with the .clang in https://github.com/dashpay/dash/pull/2299/commits/9bd9a2a28d5ec705db1619ba600f8afb7747721e that commit can be found here https://github.com/PastaPastaPasta/dash/commit/d594496276f26e3b9763f4cdca40566db4149b0b

**Comment by PastaPastaPasta** [comment]
Also reverted https://github.com/dashpay/dash/pull/2299/commits/fc4a4a54f7b0d9e725179a3ee1bf0808c08b0da6, although I think it is a good standard for a lot of code, it does seem too aggressive in .clang-format

**Comment by PastaPastaPasta** [comment]
@nmarley you seem to care about this, thoughts?

**Pull request merged**
