### PR TITLE
build(guix): add debug symbols for osx

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
Add debug symbols for Darwin

## What was done?
Added Darwin debug symbols and combine them as output

## How Has This Been Tested?
guix build

## Breaking Changes
  _Please describe any breaking changes your code introduces_

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by UdjinM6** [comment]
pls check https://github.com/UdjinM6/dash/commits/pr5708 + you need to rebase this

**Comment by UdjinM6** [comment]
>Unknown scope "guix" found in pull request title

**Comment by PastaPastaPasta** [comment]
> Unknown scope "guix" found in pull request title

Not important imo; it probably should be a scope

**Review by UdjinM6 — APPROVED** [review]
utACK

**Comment by knst** [comment]
Guix builds of debug for osx are always non-deterministic.

Do we need them? maybe to-revert it? due to that non-determinism the file with hashes of artefact differs for different builders and impossible to make a combined gpg signature.

@UdjinM6 @PastaPastaPasta 

p.s. bitcoin does never provide debug symbols for osx, I guess due to non-determinism, but I haven't found any reasoning.
see bitcoin#17920

**Comment by PastaPastaPasta** [comment]
Yes; guix osx debug builds are non-deterministic. However, IMO it is valuable to have and archive these debug symbols so that we can take stack traces from versions and decode them; which are able to be used successfully; but taking the macOS .tar.gz and the debug tar.gz; combining them; and then running the binary. If it crashes; it'll print stack traces :)

The non-determinism is annoying; but it's valuable to keep them around so that we have these symbols. We should instead adjust the script for guis-attest to exclude artifacts which include both osx and debug; this way we have the best of both; able to combine detached sigs for release; but also have the Darwin debug symbols when needed

**Pull request merged**
