### PR TITLE
Whitelist nodes in llmq_dkgerrors.py

### PR DESCRIPTION
**Pull request by codablock**
This fixes a few rare test failures

### CODE REVIEW

**Comment by UdjinM6** [comment]
Can't we just add `-whitelist=127.0.0.1` in `llmq-dkgerrors.py` instead?

**Comment by codablock** [comment]
Hmm yeah, that's also an option and ensures that we also test invalid sigs here. I'll change this PR later

**Comment by codablock** [comment]
Updated PR to simply whitelist nodes

**Comment by codablock** [comment]
Current test failure is unrelated to this PR

**Comment by codablock** [comment]
@PastaPastaPasta llmq_dkgerrors.py is not supposed to test p2p banning, but the DKG's behavior on wrong behavior (which is not skipped by whitelisting).

**Comment by PastaPastaPasta** [comment]
needs rebase

**Comment by codablock** [comment]
Rebased on develop

**Pull request merged**
