### PR TITLE
Allow fees higher than smallest denom for PrivateSend tx

### PR DESCRIPTION
**Pull request by UdjinM6**
This fixes issues with sending mixed coins when no smallest denoms have enough rounds (still trying to fit it in the smallest denom first). Fees are going to be quite high of course (but no higher than a standard/user-defined one) but at least it will be up to user to make the choice either to send it or not. Imo, it's much better than current confusing "not enough funds" warning in such cases.

### CODE REVIEW

**Comment by SCDeveloper** [comment]
If people want to mix funds, they will pay. This is much better than having "not enough funds" warnings. utACK.

**Comment by tgflynn** [comment]
maxTxFee appears to be a parameter that can only be set at startup.  Shouldn't this use the max fee specified by the user for the particular transaction ?

**Comment by UdjinM6** [comment]
There is no way to set max fee via rpc and in GUI user should get a dialog asking him to review his tx before submitting (including fee), so I guess this should be enough.

**Comment by tgflynn** [comment]
As a user I think I would expect the fee I entered when requesting the transaction in the GUI to be used rather than the max fee.

**Comment by UdjinM6** [comment]
I might be missing smth but user does not enter max fee directly. "Choose..." sub-dialog has an option of paying "only required fee" (which is hardcoded) but even this doesn't really apply to PS because of the rounding (and user is informed about this fact in tx confirmation dialog).

**Comment by tgflynn** [comment]
If you click the Choose button on the Send page you can enter an exact fee or select one using a slider.

I always use this with bitcoin (because the default fee is too low) and if selected this way I wouldn't be expecting the confirmation window to show a higher fee.

**Comment by UdjinM6** [comment]
Fees in "Choose..." are either rates actually i.e. not exact fees OR "at least" i.e. min, not max. Actual fees are calculated later and shown in tx confirmation dialog.

**Comment by tgflynn** [comment]
The implementation looks fine but I'm not going to ack this because I'm not convinced silently allowing the max fee when the user may have requested other settings is a good idea.

Would be good to get other peoples input on this - @schinzelh ...

**Comment by UdjinM6** [comment]
Ok, after thinking about it more and considering current price levels (which would mean ~$8-$9 fee) with this change, I'm postponing this till 12.2 and until we lower denoms again. We probably need to address the issue in some better way.

**Comment by UdjinM6** [comment]
closing in fav of #2361

**Pull request closed without merging**
