### PR TITLE
[v0.16.x] Backport pending PRs

### PR DESCRIPTION
**Pull request by codablock**

### CODE REVIEW

**Comment by codablock** [comment]
I'd like to also include https://github.com/dashpay/dash/pull/3541, https://github.com/dashpay/dash/pull/3535 and https://github.com/dashpay/dash/pull/3534

**Comment by codablock** [comment]
Added #3535, #3546 and #3549

**Comment by UdjinM6** [comment]
utACK 0b70380, #3547 is missing

**Comment by codablock** [comment]
Add missing #3547

**Comment by codablock** [comment]
Added #3548. All backports should be done now, ready for merge and probably ready for release of rc2

**Comment by codablock** [comment]
FYI, removed all related backport-candidate-v16 labels.

**Pull request merged**
