### PR TITLE
qt: Update assets and colorize them theme related

### PR DESCRIPTION
**Pull request by xdustinface**
This PR ist part of a series of +-25 PRs related to UI redesigns. Its ancestor is #3573, its successor is  #3575. I did not screenshot every single PR and its changes, instead i made "walk through all screen" videos with the result of this PR series and also with the 0.15 UI. If there are any concrete screenshots wanted, just let me know. To build with the full set of changes you can build from the branch [xdustinface:pr-ui-redesign](https://github.com/xdustinface/dash/tree/pr-ui-redesign) which always contains all changes.

[ -> Walk through 0.15](https://youtu.be/cWQeHj5tWR0)
[ -> Walk through Redesign](https://youtu.be/0QeSyXo1aao)

I tried to give the commits enough text to make things obvious without a lot description for each PR. Also here, if you want more description for this specific PR, let me know.
### About this PR

- Replaces all checkbox and radiobutton assets with new ones aligned with the css style changes
- Brings some changes to the usage of the arrows. 
- Updates all icons (at least all that will be still used after my next few PRs) 
- Updates the spinner
- Makes sure icons are updated to the correct theme color if the theme gets changed
- Adds `GUIUtil::getIcon` and `GUIUtil::setIcon` methods. They allow to colorize two colored icons.. Ideally those colors should be just black `0x000000` or white `0xFFFFFF`. But the methods fill everything below `0x7F7F7F` with the first color provided and the other part with the alternative color provided. So you can either get themed colored icons or directly set one for `QAbtractButton` derivations.

### Preview 

Send Dark: develop             |  Send Dark: After
:-------------------------:|:-------------------------:
 | 

Console Dark: develop             |  Console Dark: After
:-------------------------:|:-------------------------:
 | 

Send Light: develop             |  Send Light: After
:-------------------------:|:-------------------------:
 | 

Console Light: develop             |  Console Light: After
:-------------------------:|:-------------------------:
 |

### CODE REVIEW

**Comment by xdustinface** [comment]
Ready for review! I updated the initial post with some description and screenshots.

**Comment by PastaPastaPasta** [comment]
I'm not a fan of the new "send/receive/send to self" icons.

I also don't like the HD logo

Otherwise looks good

**Comment by xdustinface** [comment]
> I'm not a fan of the new "send/receive/send to self" icons.

Me neither, at least for the transaction screen. But they will be removed from there anyway in a follow up PR. I just did them this way for the debug console, there were the same ones used. But overall i think i will also drop them from there because i didn't find a way yet to align them properly with the increasing/decreasing text... So you may not longer need to look at them soon anyway :D 

> I also don't like the HD logo

I also partially share that with you, but only for `hd_disabled`.. and to be honest, i didn't put a lot love into this because i want to remove it anyway with #3688.. just created it for this PR to have it similar to the new `hd_enabled`.

**Comment by UdjinM6** [comment]
Agree with @PastaPastaPasta re some new icons (hd/sent/received/to_self), would rather keep the old ones for now.

**Comment by xdustinface** [comment]
Okay i reverted the arrows. But regarding the HD icon i don't get it :D Look at the following.. does it really make sense to move it out of this PR now? IMO the old one doesn't fit any better in there.. rather worse since its smaller. Still want to revert it, let me know

 HD enabled before            |  HD enabled now
:-------------------------:|:-------------------------:
 |  

HD disabled before            |  HD disabled now
:-------------------------:|:-------------------------:
 |

**Comment by UdjinM6** [comment]
Well, it's actually easier to say if it's a HD wallet or not looking at the smaller one imo.

**Comment by xdustinface** [comment]
Soo there we go, i still don't like its since its kind of pointless after the statusbar PR and i actually wanted to update all icons in one PR but what should i say if you both feel different 😄

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK, tested an earlier version.

**Pull request merged**
