### PR TITLE
Allow overwrite of npowtargetspacing in regtest

### PR DESCRIPTION
**Pull request by ogabrielides**
Requested by Platform

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
This doesn't really make sense to me, on regtest you can generate blocks whenever you want, npowtargetspacing isn't a thing

**Comment by shumkov** [comment]
Then you need to deal with mocktime to have correct quorum forming behavior. Isn't it?

**Comment by PastaPastaPasta** [comment]
You should probably just use a devnet then. If you don't want blocks on demand, then what's the point of using regtest?

**Comment by shumkov** [comment]
I want them on demand but i don't want to deal with mocktime after the network setup.

With devnet network type, we won't be able to setup network so quick as regtest (like you do in functional tests).

**Comment by PastaPastaPasta** [comment]
I don't understand, it's just as easy to start a local devnet as it is regtest

**Comment by UdjinM6** [comment]
> With devnet network type, we won't be able to setup network so quick as regtest (like you do in functional tests).

if you need to mine `<n>` blocks quickly:
```
"-minimumdifficultyblocks=<n>", "The number of blocks that can be mined with the minimum difficulty at the start of a chain (default: 0, devnet-only)"
```

**Comment by shumkov** [comment]
@UdjinM6 Thank you. For regtest there is no difficulty at all or should we use `-minimumdifficultyblocks` too?

**Comment by PastaPastaPasta** [comment]
Regtest has no difficulty. Closing for now.

**Pull request closed without merging**
