### PR TITLE
Link to the Developer-Notes.md file in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by nmarley** [comment]
This is already linked a few lines above -- search "The project coding conventions in the developer notes must be adhered to.".

Do we need to add the link twice? Or re-organize for clarity?

Seems like it might be a bit redundant (e.g. contributors should probably be expected to read this document in full anyway -- it's not really _that_ long.)

**Comment by thephez** [comment]
IMO it is helpful to have the link at hand and not have to scroll back. The easier documentation is to use, the more likely it will be used. Just my 2 cents...

**Comment by nmarley** [comment]
I'm all for making it easier, but prefer not to have the redundancy. E.g. what if the location of the referenced doc changes? Then we'd have 2 places to update, instead of one.

We could re-word or re-organize the doc a bit though. I also would prefer not to make changes due to impatience, e.g. for those devs who are too impatient to look thru the docs or only do a quick search and can't find what they need. I think there's a balance between usability and just catering to impatience. E.g. we just maintain a single link, but can change the text to something like "The project code style conventions in the developer notes must be adhered to.".

If necessary we could also add a bullet here which references the above without adding a redundant link. But that seems to be catering to those just quick skimming w/o actually reading thru the doc.

**Comment by nmarley** [comment]
¯\_(ツ)_/¯ 🙉 😄

**Comment by PastaPastaPasta** [comment]
Oh no! You lost an arm! Here ya go: `\`

**Pull request merged**
