### PR TITLE
Master

### PR DESCRIPTION
**Pull request by salmion**
Added light theme

### CODE REVIEW

**Comment by schinzelh** [comment]
whats the purpose of this pull request?

**Comment by thelazier** [comment]
I guess @salmion would like to request pull into branch v0.12.1.x not master like this..

**Comment by salmion** [comment]
apologies yes should be v0.12.1.x

**Comment by crowning-** [comment]
If there's no quick fix for this I can integrate @salmion 's changes into my local 12.1.x branch and create a PR, because I'm quite familiar with his changes.

Only problem could be that his name as originator gets lost during that process and everyone will blame me :-)

**Comment by schinzelh** [comment]
I think i can rebase it to 12.1.x :-)

**Comment by crowning-** [comment]
@evan82 : obviously you merged this to dashpay:master, however I can't find it. Where is it?

**Comment by schinzelh** [comment]
@crowning- @evan82 accidentically merged it to master and had to revert it as it contained all untested v12.1 commits. We still need to rebase it to v12.1

**Comment by crowning-** [comment]
@flare , do you rebase it? If not I'd merge it to my local v12.1.x repository (I don't know how to rebase stuff) and re-submit it.

**Comment by schinzelh** [comment]
Please merge and resubmit, this patch is conflicting on the locale files, and i'd rather not mess around with them :)

**Pull request merged**
