### PR TITLE
backport: Merge bitcoin#22579, 23964

### PR DESCRIPTION
**Pull request by vijaydasmp**
bitcoin backport

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6, requesting review

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
22579: missing changes in VerifyChecksum

**Comment by vijaydasmp** [comment]
Hello @knst @PastaPastaPasta , please review

**Review by PastaPastaPasta — APPROVED** [review]
utACK 387f8b1105cc300310c1629e03d376fe942df475

**Pull request merged**
