### PR TITLE
Masternodes should have no wallet enabled

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by nmarley** [comment]
What is the rationale as to why they should not have a wallet enabled? Is this us trying to prevent people from shooting themselves in the foot? (Kinda being a nanny IMO if that's the only reason.)

**Comment by PastaPastaPasta** [comment]
In a way it's a forced optimization, none of the mn setup guides I've seen have suggested disabling the wallet however doing so speeds up startup and likely frees resources. Plus there are defenite security problems with running a wallet on an mn. This makes it clear that using a wallet on an mn is not supported behavior. If someone really wants to use a wallet on MNs then they can compile the code with this patch removed.

**Comment by nmarley** [comment]
> Plus there are defenite security problems with running a wallet on an mn

This does make sense... just thinking thru it a bit. Now that we have split out voting from operator I guess there would be no reason for an MN to have funds ... other than debug / testing, but I guess that can be done via custom builds as you suggested.

concept ACK

**Comment by qwizzie** [comment]
What about those masternode owners that still get their masternode rewards 
on the same pub address as where their collateral is located and need the software wallet 
with coin control to get those mn payments out ? (i''m not sure every masternode owner has fully switched to hardware wallets). 

Am i correct in assuming they need to put masternode=0 after this pull request, in order to enable their wallet and get those mn payments out?

**Comment by thephez** [comment]
@qwizzie I don't think it's been possible to set up a MN where the collateral was stored locally since 12.2 (https://github.com/dashpay/dash/pull/1706) - even before that it was highly discouraged. This change doesn't require having the collateral on a HW wallet. It just means if the collateral is stored in Dash Core, it must be on a separate machine than the one providing the MN services.

Technically playing around with the `masternode` parameter might be a workaround (is that correct @PastaPastaPasta)?

**Comment by PastaPastaPasta** [comment]
If a user for whatever reason did have a wallet on a masternode they would be able to launch dashd with masternode=0, then move funds, then relaunch their MN

**Comment by qwizzie** [comment]
> If a user for whatever reason did have a wallet on a masternode they would be able to launch dashd with masternode=0, then move funds, then relaunch their MN

My mistake, i orginally thought this was about wallets 

> @qwizzie I don't think it's been possible to set up a MN where the collateral was stored locally since 12.2 (#1706) - even before that it was highly discouraged. This change doesn't require having the collateral on a HW wallet. It just means if the collateral is stored in Dash Core, it must be on a separate machine than the one providing the MN services.
> 
> Technically playing around with the `masternode` parameter might be a workaround (is that correct @PastaPastaPasta)?

My mistake, i overlooked that we are talking about the (normally empty) server wallets here (i initially thought this was about cold storage masternode wallets and was wondering about the impact on the software wallet if that got disabled). Thats why i deleted my comment, i finally realised we are talking about server wallets (hot wallets). Sorry for the confusion.

**Pull request merged**
