### PR TITLE
merge bitcoin#15931, #16839, #17192, #17407, #18037, #17997, partial #15639, #17989: deglobalisation and mining rpc backports

### PR DESCRIPTION
**Pull request by kittywhiskers**
For more information, see #4357

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Comment by PastaPastaPasta** [comment]
IMO this should be merged after rotation (#4752)

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
