### PR TITLE
Backports 0.20 pr7

### PR DESCRIPTION
**Pull request by Munkybooty**
## Issue being fixed or feature implemented

Bitcoin Backports

## What was done?

Misc v20 Backports, check commit log to see changes.

## How Has This Been Tested?

Compilation and tested unit tests locally

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see below + 0fb17a2e74 + 54af125516

**Comment by UdjinM6** [comment]
Looks good. Pls squash fixes into corresponding "Merge ..." commits.

**Comment by PastaPastaPasta** [comment]
@Munkybooty see above

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
@Munkybooty see above

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Comment by thephez** [comment]
@Munkybooty Can you update the PR title to include the conventional commit `backport: ` prefix?

**Pull request merged**
