### PR TITLE
ci: adds flag -Werror=reorder for arm target

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
The order of members in a class/struct definition and the order of their initialization should match. This ensures that the code is more error-proof in cases where the order of member initializations is important, as they may depend on each other.

Instead manual checking of member initialization better let CI handle it.
Last PR where it's noticed: https://github.com/dashpay/dash/pull/5531#discussion_r1299404387

## What was done?
New flag "-Werror=reorder" for `configure.ac` and fixes existing code.

## How Has This Been Tested?
Build code with `--enable-werror`

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by kwvg — COMMENTED** [review]
Concept ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Review by ogabrielides — APPROVED** [review]
LGTM

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
