### PR TITLE
fix BIP34 starting blocks for mainnet/testnet

### PR DESCRIPTION
**Pull request by UdjinM6**
Dashify BIP34 constants (BIP34 was active in Dash since the beginning).

### CODE REVIEW

**Comment by schinzelh** [comment]
Makes sense, utACK

**Comment by tgflynn** [comment]
Could you explain the rationale for this change (ie. why is 227031 the correct block height for this) ?

**Comment by tgflynn** [comment]
Description could use a bit of explanation.

**Comment by UdjinM6** [comment]
@tgflynn good point, fixed

**Comment by tgflynn** [comment]
utACK

**Pull request merged**
