### PR TITLE
fix lock order in ThreadMnbRequestConnections

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by codablock** [comment]
@UdjinM6 do you remember why you had to add cs_main locking here? This place is responsible for some of the UI lockups as it holds the cs_main lock for quite some time in case it tries to connect to a MN that is down.

**Comment by UdjinM6** [comment]
@codablock iirc `cs_main` is needed because of `InitializeNode`

**Comment by codablock** [comment]
You mean a consumer of InitializeNode or the call to the signal itself? The strange thing is that cs_main is never locked in any other place ConnectNode or OpenNetworkConnection is called. Maybe this was different before the network refactoring?

**Comment by UdjinM6** [comment]
https://github.com/dashpay/dash/blob/3e0a78353d4584ccaa9635951246ee6877d7b9cb/src/net.cpp#L2498
https://github.com/dashpay/dash/blob/3e0a78353d4584ccaa9635951246ee6877d7b9cb/src/main.cpp#L327
Yes, it's not needed in bitcoin original code but in our code lock order is often (cs_main, cs_smthelse) to avoid dead locks. Maybe it's no longer needed here after network refactoring or can be refactored a bit further to revert this, I haven't checked since then. You can give revert it and see for yourself ;)

**Comment by UdjinM6** [comment]
@codablock I guess you were probably right and we can fix this now. At least I found no places where this kind of lock would still be needed. Pls review https://github.com/dashpay/dash/pull/1658

**Pull request merged**
