### PR TITLE
instantsend: Mark blocks as conflicting when there is a CL vs IS conflict

### PR DESCRIPTION
**Pull request by UdjinM6**
A followup for https://github.com/dashpay/dash/pull/3924

Extracted from #3970

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Can you talk about the reasoning a bit? Why is Conflicting better than Invalid?

**Comment by UdjinM6** [comment]
@PastaPastaPasta see #3924 and #3926

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
