### PR TITLE
fix: multiple trivial improvements

### PR DESCRIPTION
**Pull request by knst**
## What was done?
Fixed formatting in several files to make backporting changes from bitcoin easier.
Fixed a lint message that pollutes output due to misusage assert in governance rpc code.

## How Has This Been Tested?
Run unit/functional test

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK 567d629e42fbe1398c38ce318c9ad40eb1e787c6

**Comment by PastaPastaPasta** [comment]
please pull in: https://github.com/dashpay/dash/commit/653a35b81d9d0222498d985f0bb4088ad7edc999

**Review by UdjinM6 — APPROVED** [review]
utACK 859b9ad28fdd306cf383893179407cf2949967e2

**Review by PastaPastaPasta — APPROVED** [review]
utACK 859b9ad28fdd306cf383893179407cf2949967e2 it's really only whitespace. I'll merge (and build locally / run linter first), but not wait for CI

**Pull request merged**
