### PR TITLE
fix: use blocks-only instead of address-only for inventory

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Mobile client (without full blockchain) can't receive transactions before they are mined in the block.

## What was done?
Fixed a condition "is an addr relay" to "not a block relay".
It's an alternate solution for https://github.com/dashpay/dash/pull/6162

## How Has This Been Tested?
Tested with hashengineering - it works!

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by kwvg — APPROVED** [review]
utACK 72000226fea10bcd6cc81d133a285f8a239afc15

**Review by PastaPastaPasta — APPROVED** [review]
utACK 72000226fea10bcd6cc81d133a285f8a239afc15; do want @UdjinM6's input

**Review by UdjinM6 — APPROVED** [review]
👍 

ACK 72000226fea10bcd6cc81d133a285f8a239afc15

**Comment by knst** [comment]
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/72000226fea10bcd6cc81d133a285f8a239afc15..3468ab34d1f15bc90eca3d258493bd48a6a0952e) the v21-fix-mobile-connection-v2 branch from[ 7200022 ](https://github.com/dashpay/dash/commit/72000226fea10bcd6cc81d133a285f8a239afc15)to 3468ab3

signed commit

**Review by PastaPastaPasta — APPROVED** [review]
utACK [3468ab3](https://github.com/dashpay/dash/pull/6163/commits/3468ab34d1f15bc90eca3d258493bd48a6a0952e); no diff

**Review by kwvg — APPROVED** [review]
utACK 3468ab34d1f15bc90eca3d258493bd48a6a0952e

**Pull request merged**
