### PR TITLE
revert: 5636, introduce `-llmqtestinstantsend` and `-llmqtestinstantsenddip0024`

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
This reverts #5636 and introduces 2 similar cmd-line/config params which are made specifically for regtest. Turned out Platform guys actually still need smth like that for local testing #5259.

## What was done?
pls see individual commits

## How Has This Been Tested?
run tests but we don't really have(/need?) tests for this.

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

cc @shumkov

### CODE REVIEW

**Review by ogabrielides — APPROVED** [review]
utACK

**Comment by QuantumExplorer** [comment]
utACK

**Review by knst — APPROVED** [review]
LGTM

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
