### PR TITLE
[UI] In-wallet PrivateSend help

### PR DESCRIPTION
**Pull request by crowning-**
Reference: https://www.dash.org/forum/threads/q3-core-team-report-call.11085/#post-106703 and https://www.dash.org/forum/threads/in-wallet-privatesend-help.11324/

Final text by ddlink7 (thanks a lot :+1: ).

Advanced PrivateSend interface with complete help text:
advanced_ps

Simple PrivateSend interface:
simple_ps

The link at the end is clickable and goes to our Wiki.

### CODE REVIEW

**Comment by crowning-** [comment]
@schinzelh , can you have a look at the Travis build?
The reason it failed has nothing to do with my PR, and you're the only one who can add packages to this whitelist anyway :-)

**Comment by schinzelh** [comment]
WTF - whitelisted packages... this is new...

I'll consider migrating from Docker based Travis to native one..

**Comment by schinzelh** [comment]
Btw: They broke Ethereum builds as well

https://github.com/travis-ci/travis-ci/issues/6822#issuecomment-258384822

**Comment by UdjinM6** [comment]
From the description it sounds like mixing session is using 1 input from each participant and uses 1 address only which can mislead people thinking that "oh, well I have addresses for 1000 sessions, I shouldn't really care". In reality it can use up to 9 inputs per person in one mixing session iirc + it uses addresses for collaterals + sometimes mixing fails at later stage if smth goes wrong with creation of final tx (someone might be misbehaving or disconnected for some reason e.g. closed his wallet) i.e. user would see no "Denominate" tx but some of his addresses were already consumed. I think it worth fixing it at least by changing "one of your addresses" to "few of your addresses" and mentioning that such keypool size should be enough for ~100 mixing events.

**Comment by crowning-** [comment]
"Up to 9 inputs", together with "about 100 mixing events"  sounds good to me. 

I'll change it later today.

**Comment by crowning-** [comment]
New help text:
helptext2

**Pull request merged**
