### PR TITLE
V0.12.0.x additional debug categories

### PR DESCRIPTION
**Pull request by UdjinM6**
I'd like to make debug output more granular so I started with the most obvious for me :)
- add darksend debug category

@evan82 @schinzelh @crowning- Any idea what/how many additional categories we might need? I guess there is no reason to make it _too_ granular maybe but smth like _masternode_ for general mn networking stuff and _budget_ for new budget stuff maybe? 

PS. @evan82 I was thinking of combining as much categories as possible in this branch/PR so please do not merge it yet.

### CODE REVIEW

**Comment by evan82** [comment]
Ah nice! How about: 
- darksend - All messages
- masternode - Broadcast/Ping messages
- instantx - All IX messages
- masternode-winner - Consensus messages for picking the winner
- coinbase-payee - for the new consensus payee module

anything else?

**Comment by crowning-** [comment]
A category for everything related to startup and shutdown would be nice.

**Comment by UdjinM6** [comment]
- rebased to latest v12
- masternode, mnpayments, mnbudget and keepass categories
- remove c_str in logprint(f)

@crowning- there is nothing that is way too verbose on start/stop that can be moved from general log output to a specific category imo. Or at least I wasn't able to identify it and I need :eyeglasses: :smile:

**Comment by UdjinM6** [comment]
@evan82 @crowning- If you guys are happy with what/how was done - it should be ready to merge now :wink:

**Comment by crowning-** [comment]
I'm fine with that. When I'm bored I'll replace the strings with constants one day :-)
(it's much more convenient to let the compiler find the typos)

**Comment by evan82** [comment]
looks good, thanks!

**Pull request merged**
