### PR TITLE
qt: Finetune TransactionsView

### PR DESCRIPTION
**Pull request by xdustinface**
This PR brings the following changes to TransactionView

- Give the confirmation status icons different colors (they were mostly blue before)

- Removes left/right/left+right arrows as transaction type indication. Instead colorize the amount with the following rules

 Tx Type | Before          |  Now
:-------------------------|:-------------------------|:-------------------------
   Incoming TX | Left arrow / Amount color grey | Amount color green
   Internal TX |  Left+Right arrow / Amount color red  | Amount color orange
   Outgoing TX  |  Right arrow / Amount color red | Amount color red
   Mined TX | Mining icon / Amount color grey  | Amount color orange 
   Mixing TX | Left+Right arrow / Amount color grey  | Amount orange

- Removes the second column "InstantSend" from the transaction table. I feel like this isn't really needed since IS locks are only a temporarily thing and this column doesn't have any sense if the locks are gone. Instead an IS locked transaction gets a (updated) bolt icon besides the address/label, where the tx indication icon was prior to this PR. 

- Do not longer colorize the whole row with blue/red font for IS locked/abandoned transactions.

- Extends the tooltip texts for transaction hovering. It didn't indicate that the transaction was verified/locked by InstantSend/ChainLocks before.

- Adjust IS/CL indication strings ec53e705b1e389097a13f6527b504b33f961bf58 + 804dcc9

### Preview

 Before          |  Now
:-------------------------:|:-------------------------:
 |  
 | 
 | 
 | 
 |

### CODE REVIEW

**Comment by UdjinM6** [comment]
Pls see https://github.com/UdjinM6/dash/commits/pr3710. Also, not sure if "finetune overview page" PR is coming next but imo it should, cause tx list there uses wrong colors now and huge lightning bolt icon is just weird. Smth like 55c0f40336 maybe which looks like that:
| Before 55c0f40336 | After 55c0f40336 |
|-|-|
| Screenshot 2020-09-16 at 00 43 01 | Screenshot 2020-09-16 at 00 38 53 |

**Comment by xdustinface** [comment]
Yeah "Finetune Overviewpage" is next :D Thats how it look like currently. Didn't add the IS icons there yet like you but i think i like it :) .. anyway, we can talk about that in the other PR. Will open in the next hours! 

image

**Comment by xdustinface** [comment]
@UdjinM6 good points, i first had doubts about 6785214 thats why it took longer for it to appear here haha. Especially about removing the depth check for IS because of the situation when there are no CL..but.. no point to hide then that its a IS lock, so should be all fine 😄

**Review by UdjinM6 — DISMISSED** [review]
ACK

**Comment by PastaPastaPasta** [comment]
Two things:

1. please update description to include all changes
2. I don't like mined coins being blue, green is probably fine

**Comment by UdjinM6** [comment]
>I don't like mined coins being blue, green is probably fine

I don't have a strong opinion about it, but I have a concern :) On one hand, green is fine because "Mined" in "Type" column does the job of distinguishing them from non-coinbase txes already. On the other, with no type icons on overview screen there will be no way of easily identifying them there but I'm not sure if that's an issue or not.

**Comment by xdustinface** [comment]
> 1. please update description to include all changes

Done 👍  

> 2\. I don't like mined coins being blue, green is probably fine

I vote to keep the blue for the reason @UdjinM6 pointed out + It doesn't hurt to have it blue (maybe your eyes a bit, idk, but i guess you can get used to it :P). It just makes it even easier to see what are mined txes and what not. Sure the "Mined" works there but a different color stands more out than a different text.

**Comment by UdjinM6** [comment]
Thinking more about it... it's not like a lot of users will ever see mined txes at all and those who will (miners+MNOs, if any of them use Core GUI for the wallet that receives block rewards) won't see them that often. So maybe it's not an issue at all and green (like for every other "receive" category) is fine? 🤔

**Comment by PastaPastaPasta** [comment]
I don't love blue since that has the connotation of IS locks, which doesn't really make sense for coinbase txes. Sure i'd get used to it, but I think grey or green make probably more sense, since mining is basically receiving from a "user" perspective, just instead of receiving from another person, you're receiving from the blockchain itself

**Comment by xdustinface** [comment]
@PastaPastaPasta The idea i have in mind about the blue is simple.. People associate - DASH <> blue - sience our logo and overall color usage in apps and whatnot is blue. At least i have that strong association, so i guess there are others too.. it actually just makes sense, not? 😂 And because of that association i feel like blue would work very well for mined DASH + at the end mining coins is something special.. thats why i still think we should not use green because its not just a normal receive transaction.

About the IS lock thing you mentioned.. this only applies to users who are already used to the old transaction highlighting. They will realize the new way of coloring very fast and easy imo. New user won't care at all.

**Comment by PastaPastaPasta** [comment]
> And because of that association i feel like blue would work very well for mined DASH + at the end mining coins is something special.. thats why i still think we should not use green because its not just a normal receive transaction.

Except it's not the case that this is just for mined coins (even though that's what it says), but it's also for MN payouts and treasury payouts. In this case, it's not something super special, but is much more like generally receiving coins, just from the network directly.

I'm not a fan of blue, just doesn't look good, and having it be green makes sense. I'm also okay with it basically not being colored.

**Comment by xdustinface** [comment]
Mined, MN, Superblock... whatever. Receiving newly created DASH with no history is totally a special case compared to receiving coins with a history from someone else 🤷‍♂️ Or why did it get a special icon before?

Not colored would conflict with PrivateSend btw.

**Comment by PastaPastaPasta** [comment]
Well, I actually have a problem with that as well tbh... Using colors is fine imo, using colors and removing icons is also fine, but using colors as a replacement for icons doesn't make sense, in that case, you should just use icons as they are more descriptive and intuitive. I'd propose the following


 Tx Type | Before          |  Now
:-------------------------|:-------------------------|:-------------------------
   Incoming TX | Left arrow / Amount color grey (dark theme) | Amount color green
   Internal TX |  Left+Right arrow / Amount color red  | Amount color orange
   Outgoing TX  |  Right arrow / Amount color red | Amount color red
   Mined TX | Mining icon / Amount color grey (dark theme)  | Amount color green 
   PrivateSend TX | Right arrow / Amount color red  | Amount color red

In this case the colors simply indicate whether the tx (substantially, ie ignoring fees) added funds, removed funds, or did neither

**Comment by xdustinface** [comment]
I don't like it because we by purpose undermine something which we could easily highlight in a special way and those highlighting would have not any bad impact nor do they look bad (for the most people i guess). They just allow show a clear distinction between more different transaction types.

And since normal users wouldn't even be effected by this i even tend more to keep this colorings as they are.. special case for special users with a special highlighting. To be honest, im no miner and unfortunately i also have no MN.. but i think i would be happy to have such transactions stand out in my tx history 😄   

Anyway, @PastaPastaPasta it looks like you and me won't come to an end.. we should probably stop with the reasoning now there are enough points already 😅 @UdjinM6 it seems like you should take a position for either of both sides now so that we can get this PR done!

**Comment by PastaPastaPasta** [comment]
> I don't like it because we by purpose undermine something which we could easily highlight in a special way and those highlighting would have not any bad impact nor do they look bad (for the most people i guess). They just allow show a clear distinction between more different transaction types.
> 
> And since normal users wouldn't even be effected by this i even tend more to keep this colorings as they are.. special case for special users with a special highlighting. To be honest, im no miner and unfortunately i also have no MN.. but i think i would be happy to have such transactions stand out in my tx history smile
> 
> Anyway, @PastaPastaPasta it looks like you and me won't come to an end.. we should probably stop with the reasoning now there are enough points already sweat_smile @UdjinM6 it seems like you should take a position for either of both sides now so that we can get this PR done!

I do agree on wanting @UdjinM6's opinion, however, what I'm saying isn't limited to just miners / MNOs. But includes anyone using PrivateSend. 

We shouldn't use color highlighting in order to "show a clear distinction between more different transaction types" if the meaning isn't intuitive. Seeing a blue highlighting doesn't intuitively say "Mining", a icon including a pickaxe does.

**Comment by xdustinface** [comment]
Yeah i like the blue even more than the pickaxe as the latter is an icon for mining and like you said above thats different than MN/Treasury but you still got the pickaxe for those before 😆 Might not be 100% intuitive but the association `Blue <> DASH` is totally given and that makes it easy to understand it imo. About PrivateSend..I don't have a strong opinion on that one.. i think i slightly tend to give it the color.. but im good with both there, red or grey/default color..

**Comment by UdjinM6** [comment]
Few notes:

1. PR description is incorrect:

PrivateSend TX | Right arrow / Amount color red | Amount color grey
-- | -- | --

should really be


Mixing TX | Left+Right arrow / Amount color grey | Amount color grey
-- | -- | --

Spending funds via PrivateSend uses the same decoration/coloring as in Outgoing TX (just like before).

2. The Really Big Issue

How about
```diff
diff --git a/src/qt/transactiontablemodel.cpp b/src/qt/transactiontablemodel.cpp
index a970717c75..780b0bb956 100644
--- a/src/qt/transactiontablemodel.cpp
+++ b/src/qt/transactiontablemodel.cpp
@@ -506,7 +506,9 @@ QVariant TransactionTableModel::amountColor(const TransactionRecord *rec) const
 {
     switch (rec->type) {
     case TransactionRecord::Generated:
-        return GUIUtil::getThemedQColor(GUIUtil::ThemedColor::BLUE);
+        return rec->status.status == TransactionStatus::Immature ?
+            GUIUtil::getThemedQColor(GUIUtil::ThemedColor::BLUE) :
+            GUIUtil::getThemedQColor(GUIUtil::ThemedColor::GREEN);
     case TransactionRecord::RecvWithPrivateSend:
     case TransactionRecord::RecvWithAddress:
     case TransactionRecord::RecvFromOther:
```

i.e. blue while it's immature (not yet spendable) and green when it's spendable like regular coins

**Comment by xdustinface** [comment]
> Few notes:
> 
> 1. PR description is incorrect:
> 
> PrivateSend TX	Right arrow / Amount color red	Amount color grey
> should really be
> 
> Mixing TX	Left+Right arrow / Amount color grey	Amount color grey
> Spending funds via PrivateSend uses the same decoration/coloring as in Outgoing TX (just like before).

Oh right the color is wrong there! But your proposed "Left+Right arrow" is not correct unless there is something else happening in this case but if you look here: https://github.com/dashpay/dash/blob/develop/src/qt/transactiontablemodel.cpp#L435-L438 thats the right arrow. 

Why do want to call it "Mixing TX" ? Wouldn't "Mixing TX" rather fit here if we would talk about `PrivateSendDenominate` tx records? For `PrivateSend` it sounds more reasonable to me to use "PrivateSend TX", not?

> i.e. blue while it's immature (not yet spendable) and green when it's spendable like regular coins

Hmm im honestly not really a fan of that either. I mean, the idea itself sounds like a nice compromise between both and even though im totally for taking compromises in such cases in general it feels wrong to give a tx type even two colors now just to make everyone at least a bit happy 😄 What about sharing this PR with suba and let him decide instead?

**Comment by UdjinM6** [comment]
>but if you look here: https://github.com/dashpay/dash/blob/develop/src/qt/transactiontablemodel.cpp#L435-L438 thats the right arrow.

Yes, like I said
> Spending funds via PrivateSend uses the same decoration/coloring as in Outgoing TX (just like before).

Mixing aka `PrivateSend Denominate` is the `default` case here https://github.com/dashpay/dash/blob/develop/src/qt/transactiontablemodel.cpp#L439-L440

**Comment by xdustinface** [comment]
> > but if you look here: https://github.com/dashpay/dash/blob/develop/src/qt/transactiontablemodel.cpp#L435-L438 thats the right arrow.
> 
> Yes, like I said
> 
> > Spending funds via PrivateSend uses the same decoration/coloring as in Outgoing TX (just like before).
> 
> Mixing aka `PrivateSend Denominate` is the `default` case here https://github.com/dashpay/dash/blob/develop/src/qt/transactiontablemodel.cpp#L439-L440

Ahh got it! My bad.. i somehow had in mind that your changes in e08b70e11d789095720c3bf9ed0d44de467f99c4 gave the `PrivateSend` case a grey color thats what i was referring to in my last few comments 😆

**Comment by UdjinM6** [comment]
Another idea: add an option `Highlight coinbase transactions` in Options dialog (on: blue, off: green) :)

**Comment by xdustinface** [comment]
That would also introduce two possible colors for one tx type at the end (and i see the next topic: what would be the default value? 😅). I don't know.. actually i would really prefer to have a static solution in this case and not give one tx txpe two possible colors. I would say we wait for subas feedback. I sent him the PR already and asked him to read the conversation + give his feedback and whatever he decides makes most sense is just what we go with?

**Comment by iamsuba** [comment]
@UdjinM6  @xdustinface  @PastaPastaPasta 

Ideally we should limit the number of colors to only two. 

All Credit Transactions: Green (In mobile we use Dash Blue)
All Debit Transactions: Red (In mobile we use Black/White depending on the dark/light mode)
For Internal Transactions (Pay to Self or Private Send Denom): Where can use Orange.

**Comment by xdustinface** [comment]
There we go! Thanks for helping with the decision @iamsuba 😄

**Comment by UdjinM6** [comment]
How about 85452d8ed3 also?

**Review by UdjinM6 — APPROVED** [review]
ACK

(but you need to update PR description one more time :D )

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Comment by UdjinM6** [comment]
@xdustinface post-merge PR description nit: Mining TX should say `Amount color green` (not `Amount color orange`) and Mixing TX should say `Amount color orange` (not `Amount orange`)

**Pull request merged**
