### PR TITLE
Sync Blockchain first and then ProcessTick()

### PR DESCRIPTION
**Pull request by SCDeveloper**

### CODE REVIEW

**Comment by UdjinM6** [comment]
Why? You can start asking peers for sporks right away and it already won't move beyond sporks until blockchain is synced.

**Comment by SCDeveloper** [comment]
Seemed to fail anyway on Travis. But, it is simply to organise startup a bit better. Syncs chain, then requests SPORKs etc.

**Comment by UdjinM6** [comment]
I see. IMO it's better to know about activated sporks ASAP though.

**Comment by SCDeveloper** [comment]
With this change, it makes reading debug.log a lot easier.

**Comment by UdjinM6** [comment]
Doesn't sound like a good reason for me tbh

**Pull request closed without merging**
