### PR TITLE
instantsend: add bumped `nInstantSendKeepLockNew`

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Dependent on reallocation PR

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Ready for review, based on the reallocation PR

**Comment by xdustinface** [comment]
Code-wise it looks good, i just wonder.. do we really need this change since the locks are anyway handled by chainlocks? https://github.com/dashpay/dash/blob/develop/src/llmq/quorums_instantsend.cpp#L1158-#L1161

**Comment by PastaPastaPasta** [comment]
@xdustinface the thought is that even if CLs are down for an extended period of time, that IS locks would persist until they have 100 on chain confirmations. This would just make it even harder to do a 51% attack that double spent IS locked txes.

**Review by xdustinface — APPROVED** [review]
Hm ok sounds good 👍 However, if CLs are just "down" the IS locks are still kept until the next chainlock happens. This will only have an impact if we need to disable spork 19.. i honestly have no idea at right now if that happened before nor can i say if thats something which will eventually happen so i guess i just give it an utACK

**Comment by PastaPastaPasta** [comment]
Oh... Maybe this isn't really needed then... thoughts @UdjinM6 ?

**Comment by UdjinM6** [comment]
Good point @xdustinface 👍  This code won't be reachable unless spork19 is disabled. It probably would be better to use this activation bit to switch to some static number like 100 and then drop `nInstantSendKeepLock` completely later (after bit5 activation) to clean consensus params up a bit. Or we could just ignore it for now and drop `nInstantSendKeepLock` and the logic behind it after removing spork19 sometimes later.

**Comment by PastaPastaPasta** [comment]
I think it makes sense to close at this point, since ISLocks aren't removed so long as Spork19 is active

**Pull request closed without merging**
