### PR TITLE
remove spork 12

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Spork 12 was never used and really wasn't all that useful. With the soon to be added chain locks it is completely irrelevant.

### CODE REVIEW

**Comment by UdjinM6** [comment]
`ReprocessBlocks` and `DisconnectBlocks` can be dropped too now.

**Comment by nmarley** [comment]
@UdjinM6 with those gone, we can remove `mapRejectedBlocks` too now, right?

**Comment by UdjinM6** [comment]
@nmarley yes, good point! 👍

**Comment by PastaPastaPasta** [comment]
`mapRejectedBlocks` removed, squashed branch

**Comment by UdjinM6** [comment]
After some discussion in Slack it's not clear anymore if we can drop it already. Going to put this on hold for now, should probably wait at least till next release/chainlocks deployment first.

**Pull request merged**
