### PR TITLE
Backports 0.17 pr24

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Pls see https://github.com/UdjinM6/dash/commits/pr3877

**Comment by PastaPastaPasta** [comment]
Makes sense, cherry-picked all

**Review by xdustinface — APPROVED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
