### PR TITLE
Backports 0.15 pr2

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Will be rebased immediately after pr1 is merged

### CODE REVIEW

**Comment by UdjinM6** [comment]
Looks good 👍

**Comment by PastaPastaPasta** [comment]
Rebased

**Comment by UdjinM6** [comment]
FYI: the "merge" commit above is me trying Github GUI conflict resolution tool.

**Comment by UdjinM6** [comment]
I'm squash&merging this, so history won't be funny in main (`develop`) branch :)

**Comment by codablock** [comment]
Hmm...Preserving history (non-squashed merges) when doing backports is of high value IMHO as it allows fine grained blaming/annotating to figure which change was introduced by which PR and especially why it was introduced.

**Comment by UdjinM6** [comment]
Yep, it makes sense for huge non-trivial backports (like you made last time :P) but the last two by Pasta were rather small and/or trivial imo.

**Comment by UdjinM6** [comment]
I mean, changes in some critical parts like networking (e.g. compact blocks) or chain verification should probably be merged with no squashing, changes in comments, cmd-line params etc are fine to be merged as one singe commit IMO.

**Pull request merged**
