### PR TITLE
rpc: Show devnet name in getblockchaininfo

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
ACK

**Comment by PastaPastaPasta** [comment]
Can you write a test for this? :D

**Comment by UdjinM6** [comment]
It's probably a good idea to introduce some tests for devnets but this is out of the scope for this PR imo (and test framework isn't quite ready for this yet, simply specifying `-devnet` won't work).

**Review by PastaPastaPasta — APPROVED** [review]
understandable, utACK

**Pull request merged**
