### PR TITLE
trivial: adding favicon image

### PR DESCRIPTION
**Pull request by taw00**
noticed that someone already contributed all my pixmaps I have been using for
my builds (thank you, whoever you were). The favicon was left out. Adding
that as well. It is useful from a completist perspective and gives users a
resource they can just use if they have need of a favicon for their project.

### CODE REVIEW

**Comment by nmarley** [comment]
Thanks for the PR! Is this for the Debian packaging or something? I guess I don't understand what the reason for these pixmaps is.

If this is just a generic image for websites, would it be better if it were transparent? Also wonder if it would be better on the website graphics page or here in the repo (since it isn't used in the code). Just thinking out loud, will let other devs chime in.

**Comment by taw00** [comment]
It's from a completion perspective. Traditionally, favicons are not transparent, though browsers do support that. If someone wants to utilize a transparent icon, they can just use the dash32.png file.

I just added in a separate PR all of my high contrast icons (see https://github.com/dashpay/dash/pull/3209) it has an explanation for how these icons should be used by the linux desktop. I build for RPM based (Fedora and RHEL/CentOS) but it works the same for all distros.

Side note: To make the desktop configuration complete, there really needs to be a `dash-qt.appdata.xml` file appropriately deployed as well. I would add that, but I would have to alter mine a bit but if you want to read more there are some links in this file: <https://github.com/taw00/dashcore-rpm/blob/master/SOURCES/dashcore-0.14-contrib/linux/desktop/dash-qt.appdata.xml> I just didn't know where it should land in the dashpay/dash repo tree.

**Comment by taw00** [comment]
Also note, I will have no heartache if you ditch this addition. It's the most trivial of trivialities. ;) The other PR is more impactful. I would love to remove the need to ship those myself.

**Comment by taw00** [comment]
Killing this myself. It's redundant and not useful to the application.

**Pull request closed without merging**
