### PR TITLE
Remove p2p alert system

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
backports 3 PRs, see commits

### CODE REVIEW

**Comment by codablock** [comment]
bitcoin#8275 was already backported in aa32f1dc979a56dd71602eeb9d9204bb5c05db17. I'd suggest to change the title of your commit to indicate that it only removes stale code

**Comment by PastaPastaPasta** [comment]
resolved comments

**Comment by UdjinM6** [comment]
needs rebase

**Comment by PastaPastaPasta** [comment]
rebased

**Pull request merged**
