### PR TITLE
rpc: remove duplicated type field from gobject list-prepared

### PR DESCRIPTION
**Pull request by thephez**
The `type` is already included in the `data` object so it shouldn't be necessary here.

Without this change:
``` json
[
  {
    "objectHash": "307cde2e485968548cd1a19473bf48f788c16178d82f63cbe849c33988d9592b",
    "parentHash": "0000000000000000000000000000000000000000000000000000000000000000",
    "collateralHash": "987570add8979576cb8a4ee510df448fd2ae7097628b7980559489ecb116b0fa",
    "createdAt": 1608143561,
    "revision": 1,
    "type": 1,
    "data": {
      "end_epoch": 1608151237,
      "name": "test",
      "payment_address": "yd5KMREs3GLMe6mTJYr3YrH1juwNwrFCfB",
      "payment_amount": 5,
      "start_epoch": 1608147672,
      "type": 1,
      "url": "https://www.dash.org",
      "hex": "7b22656e645f65706f6368223a313630383135313233372c226e616d65223a2274657374222c227061796d656e745f61646472657373223a227964354b4d52457333474c4d65366d544a597233597248316a75774e777246436642222c227061796d656e745f616d6f756e74223a352c2273746172745f65706f6368223a313630383134373637322c2274797065223a312c2275726c223a2268747470733a2f2f7777772e646173682e6f7267227d"
    }
  }
]
```

With it:
``` json
[
  {
    "objectHash": "307cde2e485968548cd1a19473bf48f788c16178d82f63cbe849c33988d9592b",
    "parentHash": "0000000000000000000000000000000000000000000000000000000000000000",
    "collateralHash": "987570add8979576cb8a4ee510df448fd2ae7097628b7980559489ecb116b0fa",
    "createdAt": 1608143561,
    "revision": 1,
    "data": {
      "end_epoch": 1608151237,
      "name": "test",
      "payment_address": "yd5KMREs3GLMe6mTJYr3YrH1juwNwrFCfB",
      "payment_amount": 5,
      "start_epoch": 1608147672,
      "type": 1,
      "url": "https://www.dash.org",
      "hex": "7b22656e645f65706f6368223a313630383135313233372c226e616d65223a2274657374222c227061796d656e745f61646472657373223a227964354b4d52457333474c4d65366d544a597233597248316a75774e777246436642222c227061796d656e745f616d6f756e74223a352c2273746172745f65706f6368223a313630383134373637322c2274797065223a312c2275726c223a2268747470733a2f2f7777772e646173682e6f7267227d"
    }
  }
]
```

### CODE REVIEW

**Comment by xdustinface** [comment]
Looks good :) But you can also drop this line then https://github.com/dashpay/dash/blob/ab53cac29aa98dce20f62adc920ee13bf136c34e/test/functional/feature_governance_objects.py#L45

**Review by xdustinface — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Why is it more correct to remove from "header" instead of removing from "data"?

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
NACK

These are 2 different `type`s: one is `nObjectType` and the other one is decoded from `vchData`.

**Comment by xdustinface** [comment]
> NACK
> 
> These are 2 different `type`s: one is `nObjectType` and the other one is decoded from `vchData`.

Sure but the `nObjectType` is coming from the parsed `vchData` so it's still redundant, no?

**Comment by thephez** [comment]
> Why is it more correct to remove from "header" instead of removing from "data"?

FWIW, It was more about "easier" than "more correct". Didn't really think about if it made more sense one way vs another. :slightly_smiling_face:

**Comment by UdjinM6** [comment]
> > NACK
> > These are 2 different `type`s: one is `nObjectType` and the other one is decoded from `vchData`.
> 
> Sure but the `nObjectType` is coming from the parsed `vchData` so it's still redundant, no?

👀 
This is actually a really weird part https://github.com/dashpay/dash/blob/master/src/governance/governance-object.cpp#L373, I have no idea why we do this because `nObjectType` is (de)serialized here https://github.com/dashpay/dash/blob/master/src/governance/governance-object.h#L321. Could be a bug actually 🤔

**Comment by xdustinface** [comment]
> > > NACK
> > > These are 2 different `type`s: one is `nObjectType` and the other one is decoded from `vchData`.
> > 
> > 
> > Sure but the `nObjectType` is coming from the parsed `vchData` so it's still redundant, no?
> 
> 👀
> This is actually a really weird part https://github.com/dashpay/dash/blob/master/src/governance/governance-object.cpp#L373, I have no idea why we do this because `nObjectType` is (de)serialized here https://github.com/dashpay/dash/blob/master/src/governance/governance-object.h#L321. Could be a bug actually 🤔

Hmm i thiiiink its kind of fine, `LoadData()` is only called if the object gets created by constructor not by serialization so in this case `nObjectType` gets assigned by parsing `vchData`. I guess instead of including `nObjectType` to the serialization we could just leave it out there and call `LoadData()` in case of deserialization.

**Comment by xdustinface** [comment]
> > This is actually a really weird part https://github.com/dashpay/dash/blob/master/src/governance/governance-object.cpp#L373, I have no idea why we do this because `nObjectType` is (de)serialized here https://github.com/dashpay/dash/blob/master/src/governance/governance-object.h#L321. Could be a bug actually 🤔
> 
> Hmm i thiiiink its kind of fine, `LoadData()` is only called if the object gets created by constructor not by serialization so in this case `nObjectType` gets assigned by parsing `vchData`. I guess instead of including `nObjectType` to the serialization we could just leave it out there and call `LoadData()` in case of deserialization.

**Comment by UdjinM6** [comment]
Ok, I think I see what's going on here:
1. this [ctor](https://github.com/dashpay/dash/blob/master/src/governance/governance-object.cpp#L44-L45) does nothing and this is the one we use for deserialization.
2. this [ctor](https://github.com/dashpay/dash/blob/master/src/governance/governance-object.cpp#L72) is used by RPC [here](https://github.com/dashpay/dash/blob/master/src/rpc/governance.cpp#L102) and [here](https://github.com/dashpay/dash/blob/master/src/rpc/governance.cpp#L168) and we never use `type` from `vchData` anywhere else
3. technically, nothing is stopping someone from sending a gobject with an invalid `type` in `vchData` in which case two `type`s won't match but since we don't use the one from `vchData` it shouldn't really break anything it seems, sentinel will probably just ignore such gobjects too. It would however make a difference for rpc output, so still NACK at least until there is a consistency check.

**Review by xdustinface — DISMISSED** [review]
Okay jup that all sounds reasonable :)  Besides checking consistency in `ToJson` feels not like the way to go.. there should be consistency forced on protocol level IMO. So either one of the both (`nObjectType` in serialization or `type`in `vchData`) should be dropped or the latter should be validated against `nObjectType`.  

Wouldn't it make sense and be just fine to use the top level `type` only, drop the one in object data (`data`/`vchData`), change this [constructor](https://github.com/dashpay/dash/blob/master/src/governance/governance-object.cpp#L48) to also accept `int nObjectType` and drop `LoadData()` + just verify its valid JSON in `IsValidLocally` instead of checking `fUnparsable`. Seems like sentinel (maybe others too?) also uses [type](https://github.com/dashpay/sentinel/blob/master/lib/models.py#L131) in `vchData` so that would require a simple change but besides that i think it should be even fully backwards compatible in core because it's never used besides having an impact on the hash (what should also not matter). Its late.. i might miss something. If so, let me know 🙈

**Comment by UdjinM6** [comment]
Pls see https://github.com/dashpay/dash/pull/3883

**Comment by thephez** [comment]
@UdjinM6 So does the validation in #3883 mean that both "types" will now always be equal therefore remove the need for both in the RPC response?

**Review by UdjinM6 — APPROVED** [review]
Yes, I think it should be safe now.

utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
