### PR TITLE
Speed up IX tests and fix test failures

### PR DESCRIPTION
**Pull request by codablock**
1. Remove periodic sync when activating autoix/DIP3
2. Don't perform masternode payment voting when enforcement is disabled

### CODE REVIEW

**Comment by UdjinM6** [comment]
needs rebase

**Comment by codablock** [comment]
rebased (also removed https://github.com/dashpay/dash/pull/2389 commits)

**Comment by UdjinM6** [comment]
Tests on `develop` pass for me locally but fail on this branch.

**Comment by gladcow** [comment]
AutoIX tests work for me both on `develop` and this PR. @UdjinM6 , can you point exact place where test is failing in your case, please?

**Comment by gladcow** [comment]
If @UdjinM6 has sync_block timeout like in Travis case, may be we can add `block_timeout` argument to `BitcoinTestFramework.sync_all` and increase default value for this timeout in `sync_all()` call inside `activate_autoix_bip9` method (smth like https://github.com/gladcow/dash/commit/70f01c56a87a145df61d9ba1217c1c6ab62071f2)?

**Comment by codablock** [comment]
Looked into the logs and it looks like regtest is overloaded with masternode vote messages due to the fast block generation. I added a commit that skips voting when enforcement is disabled

**Comment by UdjinM6** [comment]
Yep, it seems that nodes are flooded with messages and just can't keep up. But I don't think that ab0803a is a good idea thb - even when (local node thinks that) enf is off voting helps to see the state of the network. I'd rather not merge this PR at all and keep tests a bit slower but working.

**Comment by codablock** [comment]
Tests are failing on develop (not always) as well for the same reason. See https://travis-ci.org/dashpay/dash/jobs/448242606 for example.

When the local node thinks that enforcement is off, it will still receive votes from other nodes if they have a different view on the spork. If a masternode is out-of-sync in regard to sporks, it should probably not vote at all ;)

Had to add another 2 commits which fix dip3 tests. They failed now because they expected votes to come in before enforcement was enabled.

Also rebased on develop to include latest unit test fixes...let's hope Travis is green after this :)

**Comment by UdjinM6** [comment]
Not sure if I explained it clearly enough, so again, disabling votes when spork8 is OFF makes it harder to see if it's safe to turn it back ON or not because you'll have no info from MN network which in its turn could lead to a split if there is in fact a disagreement between large enough groups of MNs. So no, nACK for 0c4fe39.

**Comment by UdjinM6** [comment]
Is there really a big win (in testing time) if we don't sync periodically in just a couple of tests? This thing (`mnw`) will go away soon anyway, so maybe we shouldn't even bother if we can make tests pass by giving them some extra time to run.

**Comment by codablock** [comment]
Didn't consider the fact that `mnw` is going to vanish and thus this PR is not worth the risk :hear_no_evil: Closing.

**Pull request closed without merging**
