### PR TITLE
feat: one more queue for "external" requests from 3rd parties

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
To avoid struggling to response to critical rpc requests, and split them from 3rd parties who uses a node as an external service, there are introduced one more queue of requests that will be served without throttling for instance consensus important rpcs

## What was done?
new command line arguments:
 - `rpcexternaluser` - List of comma-separated usernames for JSON-RPC external connections. If not specified, there's no special queue is created, all requests in one queue
 - `rpcexternalworkqueue=<n>` - Set the depth of the work queue to service external RPC calls

## How Has This Been Tested?
Functional test `rpc_platform_filter.py` is updated to test new functionality

## Breaking Changes
NA

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has began to build this PR tagged as v21.0.0-devpr6045.984c7b35. A new comment will be made when the image is pushed.

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v21.0.0-devpr6045.984c7b35. The image should be on dockerhub soon.

**Comment by thephez** [comment]
Is this a chore? It kinda seems like a feature.

**Comment by knst** [comment]
as noticed by shumkov@, need to have rpc's access to wallet, this approach won't work. 

<re-implementing...>

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has began to build this PR tagged as v21.0.0-devpr6045.c575a580. A new comment will be made when the image is pushed.

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Looks good, one small issue

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has began to build this PR tagged as v21.0.0-devpr6045.68def970. A new comment will be made when the image is pushed.

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v21.0.0-devpr6045.68def970. The image should be on dockerhub soon.

**Review by UdjinM6 — APPROVED** [review]
utACK 241f0739329b78c384b0f3016753112c5a577858

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has began to build this PR tagged as v21.0.0-devpr6045.241f0739. A new comment will be made when the image is pushed.

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v21.0.0-devpr6045.241f0739. The image should be on dockerhub soon.

**Review by PastaPastaPasta — APPROVED** [review]
utACK https://github.com/dashpay/dash/commit/241f0739329b78c384b0f3016753112c5a577858

**Pull request merged**
