### PR TITLE
governance: Make sure proposals and triggers have valid types

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by xdustinface** [comment]
That makes things definitely better 👍 But still, do you have any thoughts to share about

> Wouldn't it make sense and be just fine to use the top level `type` only, drop the one in object data (`data`/`vchData`), change this [constructor](https://github.com/dashpay/dash/blob/master/src/governance/governance-object.cpp#L48) to also accept `int nObjectType` and drop `LoadData()` + just verify its valid JSON in `IsValidLocally` instead of checking `fUnparsable`

I mean, if you don't see anything concerning / this doesn't break anything it might be the better solution for two reasons: 

1.  Don't send/include redundant data (not that we talk about huge data :D but redundant is redundant haha) 
2. Also makes sure there can't be inconsistency in `type` for trigger objects (should still be possible with this PR i think?).

**Comment by UdjinM6** [comment]
I would avoid touching `vchData`/`data` structure unless there is an actual need for this tbh because this is what we get from 3rd-party software via rpc (and an overhead is tiny imo). Good point re `type` for triggers, added 27487b0.

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
