### PR TITLE
V0.12.0.x hide "out of sync" warning on blockchain sync

### PR DESCRIPTION
**Pull request by UdjinM6**
Well, I have to agree with AjM https://dashtalk.org/threads/v12-testing-thread.5484/page-145#post-63046 This warning looks confusing now :disappointed: 
Still think progress bar is kind of ok though. Or should we revert the whole thing and reimplement it in some other way? Thoughts?

### CODE REVIEW

**Comment by evan82** [comment]
I really like the progress bar. I don't think it should be "counted" as part of the blockchain sync though, it's an extra layer on top of Bitcoin.

**Comment by UdjinM6** [comment]
Yeah, I agree on progress bar part with you @evan82 
And what about "out of sync" warning? This PR is actually about hiding it because `IsSynced` doesn't really apply to balances/transactions/DS state, it's more `IsBlockchainSynced` job.

**Comment by crowning-** [comment]
From my point of view the "out of sync" warning should at least disappear above the "Available:" and "Recent transactions" columns because they are wrong there once the blockchain is fully synced.

To label "Darksend" out of sync until Masternodes are synced makes sense, but it gives the impression that Darksend is not yet possible...I'd say display "Out of sync" there until 100 Masternodes are found.

100 should be sufficient to do start mixing...

**Comment by evan82** [comment]
Ok, I'll merge this and we can work something out for 12.1

**Pull request merged**
