### PR TITLE
Merge #18533: scripted-diff: Replace strCommand with msg_type

### PR DESCRIPTION
**Pull request by vijaydasmp**
scripted-diff: Merge #18533 Replace strCommand with msg_type

-BEGIN VERIFY SCRIPT-
sed -i 's/\<strCommand\>/msg_type/g' src/coinjoin/client.cpp 
sed -i 's/\<strCommand\>/msg_type/g' src/coinjoin/client.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/coinjoin/server.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/coinjoin/server.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/evo/mnauth.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/evo/mnauth.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/governance/governance.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/governance/governance.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/blockprocessor.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/blockprocessor.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/chainlocks.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/chainlocks.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/dkgsessionhandler.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/dkgsessionhandler.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/dkgsessionmgr.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/dkgsessionmgr.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/instantsend.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/instantsend.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/quorums.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/quorums.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/signing.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/signing.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/signing_shares.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/llmq/signing_shares.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/masternode/sync.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/masternode/sync.h 
sed -i 's/\<strCommand\>/msg_type/g'  src/net_processing.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/spork.cpp 
sed -i 's/\<strCommand\>/msg_type/g'  src/spork.h
-END VERIFY SCRIPT-

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
commit should begin with scripted-diff: smth like

`scripted-diff: Merge #18533 Replace strCommand with msg_type`

**Comment by vijaydasmp** [comment]
Updated commit message and the body of the scripted diff

**Comment by UdjinM6** [comment]
Should add an empty line between a commit title ("scripted-diff:...") and a commit description ("-BEGIN VERIFY...") to make it work (see https://github.com/dashpay/dash/commit/0bfc69274cf88d5b0fa0436cfca68d2f8c6f2e5f.patch vs https://gitlab.com/UdjinM6/dash/-/commit/736cfaa1f4feaa40cef7b073fb3d200a46b4491f.patch)

**Comment by vijaydasmp** [comment]
> 

got it, Thanks @UdjinM6

**Comment by PastaPastaPasta** [comment]
DNM until after https://github.com/dashpay/dash/pull/4752 is merged

**Comment by UdjinM6** [comment]
```diff
diff --git a/src/net_processing.cpp b/src/net_processing.cpp
index ef093c4..6f22fff 100644
--- a/src/net_processing.cpp
+++ b/src/net_processing.cpp
@@ -3937,7 +3937,7 @@ bool static ProcessMessage(CNode* pfrom, const std::string& msg_type, CDataStrea
         return true;
     }
 
-    if (strCommand == NetMsgType::GETQUORUMROTATIONINFO) {
+    if (msg_type == NetMsgType::GETQUORUMROTATIONINFO) {
         llmq::CGetQuorumRotationInfo cmd;
         vRecv >> cmd;
 
@@ -3954,7 +3954,7 @@ bool static ProcessMessage(CNode* pfrom, const std::string& msg_type, CDataStrea
         return true;
     }
 
-    if (strCommand == NetMsgType::QUORUMROTATIONINFO) {
+    if (msg_type == NetMsgType::QUORUMROTATIONINFO) {
         // we have never requested this
         LOCK(cs_main);
         Misbehaving(pfrom->GetId(), 100, strprintf("received not-requested quorumrotationinfo. peer=%d", pfrom->GetId()));
```

**Comment by vijaydasmp** [comment]
Thanks @UdjinM6 just fixed it

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

Note: I put this on v19 milestone, and as a v18 backport @UdjinM6 please change if you disagree with those

**Pull request merged**
