### PR TITLE
perf: reduced delays and syncs in functional tests to run faster

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Functional tests take too long time to run.

(PR is recreated from https://github.com/dashpay/dash/pull/6268 because CI is broken)

## What was done?
 - increased robustness `feature_llmq_simplepose.py` by adding missing bump for mocktime during block generations
 - removed sleep(1) from each stage of mine_quorum
 - removed sleep(6) from final stage of mine_cycled_quorum
 - size of batch for block generation in `feature_asset_locks.py` and in `activate_fork_by_name()` increased from 10 blocks to 50 blocks
 - moved governance's functional tests to "60 seconds+" category because they always the last one to wait if running more than 10 jobs at once
Plus extra refactoring which removes dead and commented code from test_framework.py

## How Has This Been Tested?
Locally, the functional tests speed up with these fixes for 15% for overall time and 20% for accumulated time
`test/functional/test_runner.py -j20`

Before:
```
ALL                                                | ✓ Passed  | 7860 s (accumulated)  
Runtime: 481 s
```  

After:
```
ALL                                                | ✓ Passed | 6237 s (accumulated) 
Runtime: 416 s
```

---
CI tsan job speeds up for 5 minutes in absolute time (~5%) and 1000 seconds in accumulated time.
```
ALL                                                | ✓ Passed  | 23854 s (accumulated) 
Runtime: 6249 s
```
↑ [old version](https://gitlab.com/dashpay/dash/-/jobs/7822664869) vs [new version](https://gitlab.com/dashpay/dash/-/jobs/7825461091) ↓
```
ALL                                                | ✓ Passed  | 22901 s (accumulated) 
Runtime: 5962 s
```

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
ACK b9961c4cc3b092bcae2ae3fd6b7c85c8d5287aec

**Comment by knst** [comment]
@PastaPastaPasta see my comment here:

https://github.com/dashpay/dash/pull/6268#issuecomment-2358998909

Re-create PR due to CI stuck on previous PR and unavailable "re-open" button

**Comment by PastaPastaPasta** [comment]
Soooo do I no longer need to test / compare multiple commits here?

**Comment by knst** [comment]
> Soooo do I no longer need to test / compare multiple commits here?

If you can test, may you, at least b9961c4cc3b092bcae2ae3fd6b7c85c8d5287aec (with udjin's patch)?

**Comment by knst** [comment]
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/b9961c4cc3b092bcae2ae3fd6b7c85c8d5287aec..874ef8cda231eebde408263874a28e465de50bb6) the functional-tests-delays-p2 branch from[ b9961c4 ](https://github.com/dashpay/dash/commit/b9961c4cc3b092bcae2ae3fd6b7c85c8d5287aec)to 874ef8c


rebased due to conflict with #6261

**Review by UdjinM6 — APPROVED** [review]
utACK 874ef8cda231eebde408263874a28e465de50bb6

**Review by PastaPastaPasta — APPROVED** [review]
utACK 874ef8cda231eebde408263874a28e465de50bb6

**Pull request merged**
