### PR TITLE
Make CDeterministicMN::internalId private to make sure it's set/accessed properly

### PR DESCRIPTION
**Pull request by UdjinM6**
~Based on #3504 atm to avoid merge conflicts.~
Rebased

### CODE REVIEW

**Comment by xdustinface** [comment]
Makes overall sense 👍 What about even getting rid of the setter and make it only accessible by constructor and serializations like in here 653cb219918b528e8e74617ff795d0837078b010?

**Comment by UdjinM6** [comment]
@xdustinface added your patch, thanks! 👍 I tweaked ctors a bit to ensure we never create DMNs with the initial internalId value/no id specified. There is one exception where "no id" is a desired (intermediate) outcome - the upgrade logic for `CDeterministicMNListDiff_OldFormat`. Have to use a workaround for this specific case which IMO is ok-ish because they are just temporary data structures, see `NOTE` in code.

**Comment by xdustinface** [comment]
utACK! Agree with the workaround and the tweaks are looking good 👍

**Comment by UdjinM6** [comment]
Rebased, should be clean and ready to merge now.

**Pull request merged**
