### PR TITLE
backport: v21.0.x rc.2

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
Backports a set of 6 PRs needed in rc.2

## What was done?
Backported PRs with labels

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by knst — APPROVED** [review]
LGTM db828177bf315cad8efb0f8f65d31b81b190617d

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has began to build this PR tagged as v21.0.0-devpr6115.db828177. A new comment will be made when the image is pushed.

**Review by kwvg — APPROVED** [review]
LGTM, utACK db828177bf315cad8efb0f8f65d31b81b190617d

**Review by UdjinM6 — APPROVED** [review]
utACK db828177bf315cad8efb0f8f65d31b81b190617d

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v21.0.0-devpr6115.db828177. The image should be on dockerhub soon.

**Pull request merged**
