### PR TITLE
build/depends: commit dashpay/bls-signatures@66ee820f to source tree as vendored

### PR DESCRIPTION
**Pull request by kittywhiskers**
## Issue being fixed or feature implemented

Commit dashpay/bls-signatures@66ee820f to source tree as vendored. Resolves https://github.com/dashpay/dash/issues/5025.

## What was done?

See above. Implement build system changes needed to supported subtree vendored copy. Remove build-generated file from tracking. 

## How Has This Been Tested?

Running `make check`

## Breaking Changes

Will force a depends rebuild. Will need to add back removed build-generated file before updating subtree.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~ N/A
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] ~~I have made corresponding changes to the documentation~~ N/A

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Starting Gitian-Build  
```
% python3 dash/contrib/gitian-build.py -b -o mwl -j 8 -m 14000 -D -n -c pasta d431b52dd44ed4576c63169f1608713f08e05702
```

**Review by PastaPastaPasta — APPROVED** [review]
ACK for squash merge

I have done local builds and gitian-builds

**Review by ogabrielides — APPROVED** [review]
LGTM ACK

**Review by UdjinM6 — APPROVED** [review]
I'm a little bit concerned about https://github.com/dashpay/bls-signatures/issues/54 (but can't reproduce it locally) and this PR LGTM otherwise so ACK.

**Comment by UdjinM6** [comment]
This broke develop unfortunately...

testnet:
```
2022-12-05T22:43:59Z UpdateTip: new best=0000000616102ada34749f82a3f076b80f2bb6055964c648214bfa303eec1d46 height=53172 version=0x20000000 log2_work=53.930421 tx=243370 date='2019-03-02T00:10:47Z' progress=0.042112 cache=49.0MiB(365273txo) evodb_cache=6.1MiB
2022-12-05T22:43:59Z ERROR: ConnectBlock(DASH): ProcessSpecialTxsInBlock for block 00000014036d75d8a2d29626479498799adf0528ba66ba2ae18f3f69792c1274 failed with bad-protx-payload (code 16)
2022-12-05T22:43:59Z InvalidChainFound: invalid block=00000014036d75d8a2d29626479498799adf0528ba66ba2ae18f3f69792c1274  height=53173  log2_work=53.93042058  date=2019-03-02T00:12:32Z
2022-12-05T22:43:59Z InvalidChainFound:  current best=0000000616102ada34749f82a3f076b80f2bb6055964c648214bfa303eec1d46  height=53172  log2_work=53.93042057  date=2019-03-02T00:10:47Z
2022-12-05T22:43:59Z ERROR: ConnectTip: ConnectBlock 00000014036d75d8a2d29626479498799adf0528ba66ba2ae18f3f69792c1274 failed, bad-protx-payload (code 16)
```
Reverting these changes ([6a9bf06](https://github.com/UdjinM6/dash/commit/6a9bf06b7be8e7d17054e445176f52fa1dd1fc07)) fixes the issue.

**Pull request merged**
