### PR TITLE
Backports 0.17 pr7

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
rebased on develop, builds locally, running tests locally right now, looks good so far.

**Comment by UdjinM6** [comment]
Build failed with
```
Missing shebang "#!/usr/bin/env python3" in contrib/auto_gdb/common_helpers.py (do not use python or python2)
 Missing shebang "#!/usr/bin/env python3" in contrib/auto_gdb/log_size.py (do not use python or python2)
 Missing shebang "#!/usr/bin/env python3" in contrib/auto_gdb/simple_class_obj.py (do not use python or python2)
 Missing shebang "#!/usr/bin/env python3" in contrib/auto_gdb/stl_containers.py (do not use python or python2)
 Missing shebang "#!/usr/bin/env python3" in contrib/auto_gdb/used_size.py (do not use python or python2)
 ^---- failure generated from contrib/devtools/lint-python-shebang.sh
```
https://gitlab.com/dashpay/dash/-/jobs/614222960#L64

**Comment by PastaPastaPasta** [comment]
I had fixed this... Just forgot to push :see_no_evil:

**Comment by PastaPastaPasta** [comment]
builds and passes tests. let me know if you want me to squash anything

**Pull request merged**
