### PR TITLE
Net: Limit masternode amount based on spork

### PR DESCRIPTION
**Pull request by polispay**
I think is a first good approach.
We are working on a secure and spork based way to limit the number of masternodes that can be created on the network.
The idea is to create a limit and a lock when a new user is trying to create a new masternode based on the spork value (That can be changed with the Spork Masterkey). 
We hope the Dash developers team like the idea. We are currently testing and we are looking to make it in a more secure way.

### CODE REVIEW

**Comment by UdjinM6** [comment]
What is the benefit of having an explicit limit in place? Why would you want to do this via spork instead of relying on market forces? Just set collateral requirement higher or shrink reward % if you want to lower the number of masternodes (on your network).

**Comment by codablock** [comment]
NACK for multiple reasons. Its does not compile. It does not introduce the limitation on consensus level but just in CMasternodeBroadcast::Create. No one stops anyone from simply removing this line and running his modified node. And if you would implement this on consensus level and enforce it in some way, you'll get into horrible trouble because you'd realize that the masternode list is not always consistent across nodes (happy forking all the time). Then...who is going to run these 2000 MNs if there is demand for 3000 (we have >4000 atm)? The lucky guys who came first and never let go their MNs? ;)

If you want to limit the amount of MNs in Dash, I'd suggest to first discuss this in the community and with existing MNs. I doubt many would support this idea, because I never heard of anyone wanting to limit the amount...it's actually the other way around, people demand more MNs in the form of lowering the collateral requirement (this is whole different topic with many arguments against doing this).

**Comment by polispay** [comment]
Thanks for reply. I know is a hard concept to understand. This have been discussed on Polis Core development team.
I fixed some dep issue that was bugging compilation. I know is a unsecure approach, we are working a way to do it trough consensus.
The main idea on limit the amount of MN is to create a stable community, I see that some people don't even vote, on proposals, that means they are only attracted on a masternode for money making purposes. This idea makes the MN most interesting and with a little more exclusiveness for masternode holders. 
Is just an idea, If you don't like it don't worry, just close the pull request. I just wanted to share the idea with you guys.

**Comment by UdjinM6** [comment]
>I see that some people don't even vote, on proposals, that means they are only attracted on a masternode for money making purposes.

This was discussed multiple times on dash forum and it's simply not true - many people do not vote because they are happy with the way the rest of MNOs voted already, so they just don't bother to cast their own votes. People like that mostly vote when some proposals have an opposite outcome, not the one they expected.

Of course there is still a large portion of MNOs who never vote because all they want is to run a masternode and receive rewards. But there is nothing wrong with getting some returns for your investment as long as you provide expected services - voting is a right, not an obligation and there is nothing to fix here imo.

Anyway, thanks for sharing the idea and good luck with your experiment.

**Pull request closed without merging**
