### PR TITLE
backport: 0.19 pr12

### PR DESCRIPTION
**Pull request by Munkybooty**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Doesn't build

**Comment by Munkybooty** [comment]
I know this looks ugly, but don't worry, it'll all be squashed when it works lol

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see below + https://github.com/UdjinM6/dash/commits/pr4679

**Comment by UdjinM6** [comment]
pls see a7eafbef8b53bc808255af4e705aee7ecfa5d32e and 936f35221b61986f68582c1c39407ebfbf9a16af

**Comment by UdjinM6** [comment]
LGTM. time to squash fixes maybe?

**Review by UdjinM6 — APPROVED** [review]
LGTM, ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
