### PR TITLE
merge bitcoin 15746, 16240, 17192, 17318, 17809, 18098, 18444, 18607, 19100, 19386: rpc backports

### PR DESCRIPTION
**Pull request by kittywhiskers**

### CODE REVIEW

**Review by PastaPastaPasta — DISMISSED** [review]
utACK for merging via merge commit

**Comment by PastaPastaPasta** [comment]
uhh lol, that's a lot bigger of a PR now 😂

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Comment by UdjinM6** [comment]
Is there a reason why 16240 and 19386 (should be marked partial btw) are incomplete?

**Comment by kittywhiskers** [comment]
16240 was marked as partial as b6fb617aaaad5f9cdd7f2ad2825b253ca792055d was excluded as this PR favours logical backports as it is a dependency for two other PRs and a complete backport would invite a lot of potential merge conflicts (19250 needed me to resolve conflicts multiple times, for instance)

The same applies for 19386's fa7592bfa8691eb0289b21da3571709a18391b0f.

**Review by UdjinM6 — APPROVED** [review]
utACK with https://github.com/dashpay/dash-issues/issues/45#issuecomment-1067731401

**Pull request merged**
