### PR TITLE
tests: Add more unit tests for bls/bls.cpp

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
bls.cpp is now 100% covered by testing if you include unit and functional tests. If you just look at unit tests, then we still need tests for `CBLSSecretKey::SecretKeyShare`, `CBLSPublicKey::PublicKeyShare` and `CBLSSignature::Recover`

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see https://github.com/UdjinM6/dash/commits/pr4118

**Comment by PastaPastaPasta** [comment]
Looks good :+1: Picked all

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
