### PR TITLE
backport: Merge bitcoin#18664,18917,18901,18939,18875,19452,19548,19595,20300,20375 

### PR DESCRIPTION
**Pull request by vijaydasmp**

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 , requesting review

**Review by UdjinM6 — APPROVED** [review]
utACK

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta ,please review

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
