### PR TITLE
chore/feat: few tweaks for "Check Potential Conflicts" action

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
small cleanups and improvements

## What was done?
pls see individual commits

## How Has This Been Tested?
see https://github.com/dashpay/dash/actions/runs/4715728701/jobs/8362893373?pr=5330

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by UdjinM6** [comment]
dummy comment

**Review by UdjinM6 — COMMENTED** [review]
dummy review comment

**Review by PastaPastaPasta — COMMENTED** [review]
dummy review :P

**Review by UdjinM6 — COMMENTED** [review]
yet another dummy review

**Review by UdjinM6 — COMMENTED** [review]
🤷‍♂️

**Review by PastaPastaPasta — COMMENTED** [review]
lftm

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
