### PR TITLE
refactoring: governance tidying and include refactoring

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Misc refactorings and clang tidying. See individual commits

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Let's reorder includes we touch while at it 07fdbd3a82

**Comment by UdjinM6** [comment]
Needs rebase

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
