### PR TITLE
backport: bitcoin#24603, #26694, #24669, #22546, #22199, #25817 (mac build)

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
```
pasta@pastas-MacBook-Pro /tmp/2/distsrc-20.0.0-arm64-apple-darwin                                                                     [11:17:11]
> $ lldb "./Dash-Qt.app/Contents/MacOS/Dash-Qt"                                                                                                 
(lldb) target create "./Dash-Qt.app/Contents/MacOS/Dash-Qt"
Current executable set to '/tmp/2/distsrc-20.0.0-arm64-apple-darwin/Dash-Qt.app/Contents/MacOS/Dash-Qt' (arm64).
(lldb) run
error: process exited with status -1 (no such process.)
```
Os X doesn't let to run guix's binaries on arm64 because these binaries are not signed.

## What was done?
Backported bitcoin/bitcoin#22546 and couple extra relevant backports or backports just better to be here to avoid conflicts now and in future

- bitcoin/bitcoin#24603
- bitcoin/bitcoin#26694
- bitcoin/bitcoin#24669
- bitcoin/bitcoin#22546
- bitcoin/bitcoin#22199
- bitcoin/bitcoin#25817

## How Has This Been Tested?
Run unit/functional tests.

@PastaPastaPasta , please, confirm that you can run guix's binaries with these changes on Mac.

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
LGTM; running Guix-build now

**Comment by PastaPastaPasta** [comment]
```
pasta@pasta1:/mnt/volume_tor1_01/guix/dash$ sha256sum guix-build-44e9cc9162b8/output/*/*
35360c9c0cfb6af055b1ecf6ec8904642c306545ffd977cd1bef3376e4b06783  guix-build-44e9cc9162b8/output/aarch64-linux-gnu/SHA256SUMS.part
81b5eecf03017e0fb3c03486aab76d12bcfd04075536ae209f9a35ee99b487b0  guix-build-44e9cc9162b8/output/aarch64-linux-gnu/dashcore-44e9cc9162b8-aarch64-linux-gnu-debug.tar.gz
56eeeb92f21d72c757fa51268e909f33086cacede9578c935c11bde398ad5f75  guix-build-44e9cc9162b8/output/aarch64-linux-gnu/dashcore-44e9cc9162b8-aarch64-linux-gnu.tar.gz
966457461faedf740ab38b7cf671486ac19b9745ee708c70807a899a47ee3738  guix-build-44e9cc9162b8/output/arm-linux-gnueabihf/SHA256SUMS.part
92c078a818e190fde5186d3d62ced5b2940fe56c5e2e86d10f7eccd829b45093  guix-build-44e9cc9162b8/output/arm-linux-gnueabihf/dashcore-44e9cc9162b8-arm-linux-gnueabihf-debug.tar.gz
0f20374fe92902440a8521d172795ffa89121c3760f8fa9342c7266f842f9f29  guix-build-44e9cc9162b8/output/arm-linux-gnueabihf/dashcore-44e9cc9162b8-arm-linux-gnueabihf.tar.gz
5fdfe04a2e2ba3689506beebf0e83d6370ebcde6313319b6992b9ade9562c0c8  guix-build-44e9cc9162b8/output/arm64-apple-darwin/SHA256SUMS.part
1eaa98146188c947c60bf80460ece73508a30811a3222619ca4261f872502780  guix-build-44e9cc9162b8/output/arm64-apple-darwin/dashcore-44e9cc9162b8-arm64-apple-darwin-debug.tar.gz
52aa281f6bc1f0c034cc8a987fa448990732b79d6fe97f7f3c5e84494cb418c9  guix-build-44e9cc9162b8/output/arm64-apple-darwin/dashcore-44e9cc9162b8-arm64-apple-darwin-unsigned.dmg
36ef1c692cd756f6540b51e5e8027a6c174c3dac1839b84d0516cfff209ac1c5  guix-build-44e9cc9162b8/output/arm64-apple-darwin/dashcore-44e9cc9162b8-arm64-apple-darwin-unsigned.tar.gz
356a4eb9b3efe2b8ca38127dc17e90a3c5eef7d7c5d817eaa700665171c188c1  guix-build-44e9cc9162b8/output/arm64-apple-darwin/dashcore-44e9cc9162b8-arm64-apple-darwin.tar.gz
792ef785bed18aa4011e368f3157fc6f3fd782a0a0f4fd9cdb0fe2317fe3dd37  guix-build-44e9cc9162b8/output/dist-archive/dashcore-44e9cc9162b8.tar.gz
4c0a44d8f1ceebd1bdd60e251075bb9bab7679e1b086a6b22c906fe4d20eebe3  guix-build-44e9cc9162b8/output/riscv64-linux-gnu/SHA256SUMS.part
da2605634a2956e75383b45e641f4c6586b40e463af8ecfb47afaf338fec0fa2  guix-build-44e9cc9162b8/output/riscv64-linux-gnu/dashcore-44e9cc9162b8-riscv64-linux-gnu-debug.tar.gz
3751e2fdc1657f8ef3e682655e53e2a623a52009a6a47188e9be5cf300aaf0b7  guix-build-44e9cc9162b8/output/riscv64-linux-gnu/dashcore-44e9cc9162b8-riscv64-linux-gnu.tar.gz
7f4859976cb6cd6e0e6002d41ff5c4181379a9bca5424feaac1ee1190e600c91  guix-build-44e9cc9162b8/output/x86_64-apple-darwin/SHA256SUMS.part
9f69c4302942470d93ec1a9f6070f25eca7b229065a399aef96549e08333e775  guix-build-44e9cc9162b8/output/x86_64-apple-darwin/dashcore-44e9cc9162b8-x86_64-apple-darwin-debug.tar.gz
a5b9119efebc7334c121cbda53d0fbdd3b943322ff81d90f3584375b82aa9ef9  guix-build-44e9cc9162b8/output/x86_64-apple-darwin/dashcore-44e9cc9162b8-x86_64-apple-darwin-unsigned.dmg
da51d6c3b27289a9c22118ecdd71f4204b2ed9cd19eada7d39cff9c39f800117  guix-build-44e9cc9162b8/output/x86_64-apple-darwin/dashcore-44e9cc9162b8-x86_64-apple-darwin-unsigned.tar.gz
889cb5e721354c488b037daf4c008ebf906f86c33a8044dced19faa77f3cf059  guix-build-44e9cc9162b8/output/x86_64-apple-darwin/dashcore-44e9cc9162b8-x86_64-apple-darwin.tar.gz
4ef4ec4b88c0859782a0dab2ed8f19fa22703723e94dbeb1164ab587acff1cef  guix-build-44e9cc9162b8/output/x86_64-linux-gnu/SHA256SUMS.part
e46c1be4c01d5befba543f3b3157e82b9e8878606ece080d2457cc14bd75954c  guix-build-44e9cc9162b8/output/x86_64-linux-gnu/dashcore-44e9cc9162b8-x86_64-linux-gnu-debug.tar.gz
8fba2bd2a6f4e260d1b513986e1bffd82b1fde5e9445006f7e683097bada81d1  guix-build-44e9cc9162b8/output/x86_64-linux-gnu/dashcore-44e9cc9162b8-x86_64-linux-gnu.tar.gz
6a2018866d89b6484de42f6eb5d65971faa376090f2da67e8a9e8c8f288bc875  guix-build-44e9cc9162b8/output/x86_64-w64-mingw32/SHA256SUMS.part
3f3b168cbd9d101279c76de273073ff104c505d32291833a1c0b840ba126592d  guix-build-44e9cc9162b8/output/x86_64-w64-mingw32/dashcore-44e9cc9162b8-win64-debug.zip
2055716e3cf34bdab979cd9de346506503b4bb56db65ed84624ce21b38a36483  guix-build-44e9cc9162b8/output/x86_64-w64-mingw32/dashcore-44e9cc9162b8-win64-setup-unsigned.exe
291daae578bed7045a5045e467989cd82d0fa3afbb5b6f425f6960d5780ca613  guix-build-44e9cc9162b8/output/x86_64-w64-mingw32/dashcore-44e9cc9162b8-win64-unsigned.tar.gz
bb9318f7cb4757d9c63df881f3bcac99cb61c2696013d1b7a6d5e696e42e0b84  guix-build-44e9cc9162b8/output/x86_64-w64-mingw32/dashcore-44e9cc9162b8-win64.zip
```

**Comment by UdjinM6** [comment]
Canceled "Guix Build" action, waiting for infra team to figure out what's wrong with runners.

**Comment by UdjinM6** [comment]
same hashes (except for `*-apple-darwin-debug.tar.gz`, as expected)

**Comment by UdjinM6** [comment]
Guix CI failure is unrelated, should be fixed by https://github.com/dashpay/dash/pull/5727

**Comment by knst** [comment]
> pasta@pasta1:/mnt/volume_tor1_01/guix/dash$ sha256sum guix-build-44e9cc9162b8/output/*/*

hashes matched with mine (except `debug` for mac):
```
81b5eecf03017e0fb3c03486aab76d12bcfd04075536ae209f9a35ee99b487b0  aarch64-linux-gnu/dashcore-44e9cc9162b8-aarch64-linux-gnu-debug.tar.gz
56eeeb92f21d72c757fa51268e909f33086cacede9578c935c11bde398ad5f75  aarch64-linux-gnu/dashcore-44e9cc9162b8-aarch64-linux-gnu.tar.gz
a67ee5ff35c7e47a1cef1fba84180d17161bff0959a9c58a130acb9a830dbafd  arm64-apple-darwin/dashcore-44e9cc9162b8-arm64-apple-darwin-debug.tar.gz
356a4eb9b3efe2b8ca38127dc17e90a3c5eef7d7c5d817eaa700665171c188c1  arm64-apple-darwin/dashcore-44e9cc9162b8-arm64-apple-darwin.tar.gz
52aa281f6bc1f0c034cc8a987fa448990732b79d6fe97f7f3c5e84494cb418c9  arm64-apple-darwin/dashcore-44e9cc9162b8-arm64-apple-darwin-unsigned.dmg 
36ef1c692cd756f6540b51e5e8027a6c174c3dac1839b84d0516cfff209ac1c5  arm64-apple-darwin/dashcore-44e9cc9162b8-arm64-apple-darwin-unsigned.tar.gz
92c078a818e190fde5186d3d62ced5b2940fe56c5e2e86d10f7eccd829b45093  arm-linux-gnueabihf/dashcore-44e9cc9162b8-arm-linux-gnueabihf-debug.tar.gz
0f20374fe92902440a8521d172795ffa89121c3760f8fa9342c7266f842f9f29  arm-linux-gnueabihf/dashcore-44e9cc9162b8-arm-linux-gnueabihf.tar.gz
792ef785bed18aa4011e368f3157fc6f3fd782a0a0f4fd9cdb0fe2317fe3dd37  dist-archive/dashcore-44e9cc9162b8.tar.gz
da2605634a2956e75383b45e641f4c6586b40e463af8ecfb47afaf338fec0fa2  riscv64-linux-gnu/dashcore-44e9cc9162b8-riscv64-linux-gnu-debug.tar.gz
3751e2fdc1657f8ef3e682655e53e2a623a52009a6a47188e9be5cf300aaf0b7  riscv64-linux-gnu/dashcore-44e9cc9162b8-riscv64-linux-gnu.tar.gz
a3ce72e5767290a1c9180b49721b8a3cf16dc515c17263085853dd8baecba33e  x86_64-apple-darwin/dashcore-44e9cc9162b8-x86_64-apple-darwin-debug.tar.gz
889cb5e721354c488b037daf4c008ebf906f86c33a8044dced19faa77f3cf059  x86_64-apple-darwin/dashcore-44e9cc9162b8-x86_64-apple-darwin.tar.gz
a5b9119efebc7334c121cbda53d0fbdd3b943322ff81d90f3584375b82aa9ef9  x86_64-apple-darwin/dashcore-44e9cc9162b8-x86_64-apple-darwin-unsigned.dmg
da51d6c3b27289a9c22118ecdd71f4204b2ed9cd19eada7d39cff9c39f800117  x86_64-apple-darwin/dashcore-44e9cc9162b8-x86_64-apple-darwin-unsigned.tar.gz
e46c1be4c01d5befba543f3b3157e82b9e8878606ece080d2457cc14bd75954c  x86_64-linux-gnu/dashcore-44e9cc9162b8-x86_64-linux-gnu-debug.tar.gz
8fba2bd2a6f4e260d1b513986e1bffd82b1fde5e9445006f7e683097bada81d1  x86_64-linux-gnu/dashcore-44e9cc9162b8-x86_64-linux-gnu.tar.gz
3f3b168cbd9d101279c76de273073ff104c505d32291833a1c0b840ba126592d  x86_64-w64-mingw32/dashcore-44e9cc9162b8-win64-debug.zip
2055716e3cf34bdab979cd9de346506503b4bb56db65ed84624ce21b38a36483  x86_64-w64-mingw32/dashcore-44e9cc9162b8-win64-setup-unsigned.exe
291daae578bed7045a5045e467989cd82d0fa3afbb5b6f425f6960d5780ca613  x86_64-w64-mingw32/dashcore-44e9cc9162b8-win64-unsigned.tar.gz
bb9318f7cb4757d9c63df881f3bcac99cb61c2696013d1b7a6d5e696e42e0b84  x86_64-w64-mingw32/dashcore-44e9cc9162b8-win64.zip
```

**Review by UdjinM6 — APPROVED** [review]
utACK, guix failure is unrelated

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
