### PR TITLE
docs: Several more suggestions

### PR DESCRIPTION
**Pull request by thephez**
These don't need to be in 0.16.0.0, but maybe nice for the GH release text. @bcarrollaz Please take a look

### CODE REVIEW

**Review by bcarrollaz — APPROVED** [review]

**Comment by UdjinM6** [comment]
Will consider them for GH release page announcement. Thanks! 👍

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
utACK

We decided to actually merge this too :)

**Pull request merged**
