### PR TITLE
fix: Resolve warnings in Guix GitHub workflow

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
see warnings in https://github.com/dashpay/dash/actions/runs/5462770856

## What was done?
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## How Has This Been Tested?
n/a

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by kittywhiskers — APPROVED** [review]
ACK

Works with CI

**Comment by UdjinM6** [comment]
15 vs 18 warnings before the patch. The rest of them are coming from `docker/setup-buildx-action@v1` I believe. If that's actually the case [2f9492c](https://github.com/dashpay/dash/pull/5478/commits/2f9492cff101c7ebb5f45ecd335ef3485ddce6b1) should fix remaining warnings.

**Comment by UdjinM6** [comment]
Ok, down to 5 warnings now. Bumping `docker/build-push-action` to fix them (hopefully).

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
