### PR TITLE
chore: merge master 18.1.1 back into develop, archive 18.1.1 release notes

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Why backport this to v18.2.x?

**Comment by UdjinM6** [comment]
I'm not 1005 sure but I _think_ we need this to re-align v18.2.x with v18.1.x/master or it would not be possible to fast-forward master on v18.2.1 release.

**Comment by PastaPastaPasta** [comment]
You're correct, I did have to merge this into my v18.2 bp branch in order to merge that branch into master

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
