### PR TITLE
UI: theme-dependent icons/images Step 2-5

### PR DESCRIPTION
**Pull request by crowning-**
There are now individual folders for icons and images for each wallet-theme, so adding new themes will be much easier in the future.

**Steps to add a new theme:**
* optionsdialog.cpp: add your new theme to the Options dialogue: ui->theme->addItem(QString("DASH-\<visible_theme_name\>"), QVariant("\<theme\>"));
* create CSS file: res/css/\<theme\>.css and do whatever CSS-magic you need to make the wallet look good
* create folders res/icons/\<theme\> and res/images/\<theme\> and copy your icons/images there. The file names must stay the same
* add resources to src/qt/dash.qrc and src/Makefile.qt.include

**Limitations:**
* For obvious reasons the icons for the executables cannot be made theme-dependent (res/icons/*.ico are always used)
* networkstyle.cpp and rpcconsole.cpp use static arrays for (some of) their icons. If someone finds a simple(!) way to make this theme dependent please do. If not I'll replace the arrays somewhere in the future
* helpmessagedialog.ui always uses (hardcoded) res/images/drkblue/about.png. I'll change that later, I think we can live with that for a while

Tested with Linux, OSX and Windows, builds fine with Gitian. As a simple test whether you're using my new coding or not  switch back to the traditional theme, the old and ugly Bitcoin-icons for the in/outgoing transactions are used there :-)

Feedback appreciated.

### CODE REVIEW

**Comment by crowning-** [comment]
Everything works fine now, from my point of view it's ready to merge.

If you want to see it _"in use"_, here's my test-implementation: https://github.com/crowning-/dash/tree/Crownium

**Comment by UdjinM6** [comment]
Tested and works as expected :+1: 

PS. Crownium theme is... o_O
:smile:

**Comment by crowning-** [comment]
It's...ahem...different :alien:

The kids like it, though...

**Comment by crowning-** [comment]
Missed that make_windows_icons.sh needs not only icons/bitcoin\*.ico but also icons/bitcoin\*.png in the res/icons folder.
Added them back there.

Now it's REALLY ready to merge :smile: 

_We apologize for the inconvenience..._

**Pull request merged**
