### PR TITLE
qt: Finetune RPCConsole

### PR DESCRIPTION
**Pull request by xdustinface**
See commit messages. 

### Preview
|Before|With this PR|
|-|-|
|Bildschirmfoto 2020-09-18 um 16 12 24|Bildschirmfoto 2020-09-18 um 16 11 49|
|Bildschirmfoto 2020-09-18 um 16 12 18|Bildschirmfoto 2020-09-18 um 16 11 44|

### CODE REVIEW

**Comment by UdjinM6** [comment]
pls drop a5b264d

**Comment by xdustinface** [comment]
> pls drop [a5b264d](https://github.com/dashpay/dash/commit/a5b264dcb4fcf7f1c182a505ad5fd3e992ed52fe)

Damn it happened again 😆 We really need to backport some stuff now to make building on catalina happy haha

**Review by UdjinM6 — APPROVED** [review]
Looks good and works as expected as far as I can tell.

Slightly tested ACK

**Comment by PastaPastaPasta** [comment]
utACK, images look good, will try to build and actually test later today

**Comment by UdjinM6** [comment]
Assuming `utACK` above was meant to be an approval and not a regular comment, merging

**Pull request merged**
