### PR TITLE
checkbox image for wallet themes

### PR DESCRIPTION
**Pull request by snogcel**

### CODE REVIEW

**Comment by crowning-** [comment]
A bit more information: this is the fix for https://github.com/dashpay/dash/issues/826

I already tested the pre-release :-) for Win and OSX, no issues so far.

The Gitian Linux build (which was the main reason for https://github.com/dashpay/dash/issues/826) will be tested later.

**Comment by UdjinM6** [comment]
Works nicely for me on mac :)
ACK squashed merge of 1a985cc

**Comment by UdjinM6** [comment]
btw fixes #805 also

**Comment by crowning-** [comment]
Gitian Linux build works as expected.

And yes, issue https://github.com/dashpay/dash/issues/805 is also fixed now :-)

Ready to merge.

**Pull request merged**
