### PR TITLE
iterator cleanup in several places

### PR DESCRIPTION
**Pull request by nmarley**
Please see individual commits. A few notes:

* this should be all Dash-specific code, so none of these should conflict w/Bitcoin PRs
* mostly uses `auto` and range-based `for`

### CODE REVIEW

**Comment by nmarley** [comment]
You're probably right. What would you suggest I use for a `std::map<int, CSporkMessage>` entry though (from the 1st commit for example)? Just `entry`, or `pair`, or ... ?

Or are you only suggesting this for the longer `it[A-Za-z]?` names?

**Comment by UdjinM6** [comment]
For simple cases like that `pair` would do it I guess. For `mapMasternodes` it's `mnpair` all over the place already, for `mMnbRecoveryGoodReplies` (which is a bit more code) could be `mnbreplypair` to give some context or smth like that.

**Comment by UdjinM6** [comment]
You can't do this
```
for (auto& pair : someMap) {
    auto key = mnpair.first;
    mapMasternodes.erase(key);
}
```
It's going to segfault.

**Comment by nmarley** [comment]
@UdjinM6 Works fine in my test.

Code: https://gitlab.com/nmarley/cpptest/blob/master/range-for-modify.cpp

Output: https://gist.github.com/nmarley/c28de321bd15d1205900b1cf9d595d2e

**Comment by UdjinM6** [comment]
> Code: https://gitlab.com/nmarley/cpptest/blob/master/range-for-modify.cpp

`The page could not be found or you don't have permission to view it.`

**Comment by nmarley** [comment]
@UdjinM6 Sorry, should be public now. And you're right, looks like this code was "working" because of some internal ordering of keys. Once I tried deleting element `13` instead, things got screwy.

I will go back and refactor (or revert) these. I was hoping to get rid of all the incrementing iterator `else` blocks this way. :/

**Comment by UdjinM6** [comment]
Well, if that was the goal, you could probably try smth like:
```
auto it = someMap.begin();
while (it != someMap.end()) {
    auto curr = it++;
    if (condition) {
        // do smth using curr
        someMap.erase(curr);
    }
}
```

**Comment by UdjinM6** [comment]
The problem with the approach above is that this way you _always_ create a copy, even if you don't need it, while with `else ++it;` you can avoid it (in some cases most of the time).

**Comment by nmarley** [comment]
Well, my idea was actually to invert the if / else condition such that I can `if (thing) { it++ ; continue; }` and remove the else block that way. But might do that in a separate refactor PR.

**Comment by nmarley** [comment]
I've reverted changes where I made the false assuption that a container being iterated over could be modified using range-based for, which isn't the case. Also rebased onto the latest `develop` and squashed all since I reverted most of the changes that I'd originally made.

**Comment by UdjinM6** [comment]
Pushed few suggestions to my repo, see individual commits:
- could use `const` refs in few more places 401be7bd961809f75af2ba713502877ecb1ebd8e
- some names are still confusing a6084bb0a9e552ed9be2c7cc1c5b68f44602d1ff
- use prefix `++` e4a4e59275f38d22320803577dfd81d1e68a0aca

**Comment by nmarley** [comment]
Just had one question on the rational for `++thing` vs `thing++`, but looks good, thanks! 👍

**Pull request merged**
