### PR TITLE
Add the public GPG key for Pasta for Gitian building

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Same as the key https://keybase.io/pasta

### CODE REVIEW

**Comment by UdjinM6** [comment]
@nmarley Good point!

**Comment by PastaPastaPasta** [comment]
see latest commit

**Comment by UdjinM6** [comment]
@PastaPastaPasta Now you have 2 files :) Should drop "gpg" file from git (`git add contrib/gitian-keys/pasta.gpg` and commit), not just from you local fs.

**Comment by PastaPastaPasta** [comment]
see latest

**Pull request merged**
