### PR TITLE
chore: Merge master 20.0.1 back into develop

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
`Check Merge Fast-Forward Only` action is failing on develop atm

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by ogabrielides — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Did you see the linter failure here?

**Comment by UdjinM6** [comment]
> Did you see the linter failure here?

introduced in https://github.com/dashpay/dash/pull/5712 (see https://gitlab.com/dashpay/dash/-/jobs/5555509052#L55)

**Comment by PastaPastaPasta** [comment]
Agreed; okay, merging

**Pull request merged**
