### PR TITLE
Partial Merge #10420: Add Qt tests for wallet spends

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Bump fee code was not included

5749a4882 Add Qt tests for wallet spends & bumpfee (Russell Yanofsky)

Tree-SHA512: 026785e7b5ab662f37029d0694916757e46e68bf10e1a7bf1e8538a36593ada0768c6cf3c810c66d65fad891c137fc8bb13904ed09ab3bcffd6cf43d09e48621
Signed-off-by: Pasta <pasta@dashboost.org>

Conflicts:
src/qt/test/wallettests.cpp
src/qt/transactionview.cpp

### CODE REVIEW

**Comment by UdjinM6** [comment]
Looks good, will require rebase after #3316 though.

**Comment by PastaPastaPasta** [comment]
Understandable

**Comment by UdjinM6** [comment]
Needs rebase

**Comment by PastaPastaPasta** [comment]
rebased

**Pull request merged**
