### PR TITLE
fix(qt): should use weighted mn count when calculating payments in Masternodes tab

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
Masternodes tab was showing UNKNOWN next payment for some enabled MNs

reported by @kxcd aka xkcd

## What was done?
ask for the maximum data available, let GetProjectedMNPayees crop it

## How Has This Been Tested?
run dash-qt, check the list on Masternodes tab

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by ogabrielides — APPROVED** [review]
utACK

**Review by ogabrielides — APPROVED** [review]
LGTM

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Comment by PastaPastaPasta** [comment]
I've been getting this crash. But only sometimes... I reproduced it like 3 times, then tried adding some more logs and couldn't reproduce anymore. Any ideas @UdjinM6 
https://github.com/dashpay/dash/blob/7f4288436ed9b5e374872836fcf51ebb5cbd09da/src/qt/masternodelist.cpp#L207
```
2023-04-06T05:23:36Z [mining_sql] AddToWallet 0bdfafd33a03ea981a20a8e3574131fd637b3d77c4232927af8c94911b6c2b22  
2023-04-06T05:23:36Z New outbound peer connected: version: 70227, blocks=863211, peer=0 (full-relay)
2023-04-06T05:23:36Z Posix Signal: Segmentation fault: 11
   0#: (0x100F73010) stacktraces.cpp         - HandlePosixSignal(int)
   1#: (0x1A5BFB2A4) <unknown-file>          - ???
   2#: (0x100A0737C) masternodelist.cpp:207  - ???
   3#: (0x100A0737C) masternodelist.cpp:207  - ???
   4#: (0x100A06BEC) masternodelist.cpp:161  - ???
   5#: (0x1016C780C) <unknown-file>          - ???
   6#: (0x1016CB1DC) <unknown-file>          - ???
   7#: (0x1016C1B4C) <unknown-file>          - ???
   8#: (0x10177A930) <unknown-file>          - ???
   9#: (0x10177BC88) <unknown-file>          - ???
  10#: (0x1016A921C) <unknown-file>          - ???
  11#: (0x1016E3C98) <unknown-file>          - ???
  12#: (0x1012F73DC) <unknown-file>          - ???
  13#: (0x100A2D00C) sendcoinsdialog.cpp:545 - ???
  14#: (0x100A279FC) sendcoinsdialog.cpp:92  - SendCoinsDialog::SendCoinsDialog(bool, QWidget*)
Posix Signal: Segmentation fault: 11
   0#: (0x100F73010) stacktraces.cpp         - HandlePosixSignal(int)
   1#: (0x1A5BFB2A4) <unknown-file>          - ???
   2#: (0x100A0737C) masternodelist.cpp:207  - ???
   3#: (0x100A0737C) masternodelist.cpp:207  - ???
   4#: (0x100A06BEC) masternodelist.cpp:161  - ???
   5#: (0x1016C780C) <unknown-file>          - ???
   6#: (0x1016CB1DC) <unknown-file>          - ???
   7#: (0x1016C1B4C) <unknown-file>          - ???
   8#: (0x10177A930) <unknown-file>          - ???
   9#: (0x10177BC88) <unknown-file>          - ???
  10#: (0x1016A921C) <unknown-file>          - ???
  11#: (0x1016E3C98) <unknown-file>          - ???
  12#: (0x1012F73DC) <unknown-file>          - ???
  13#: (0x100A2D00C) sendcoinsdialog.cpp:545 - ???
  14#: (0x100A279FC) sendcoinsdialog.cpp:92  - SendCoinsDialog::SendCoinsDialog(bool, QWidget*)
[1]    41029 abort      ./src/qt/dash-qt --testnet --nowallet --wallet="mining_sql" --printtoconsole 
```

**Pull request merged**
