### PR TITLE
bump to 0.12.1.3

### PR DESCRIPTION
**Pull request by schinzelh**
Bumpiddy bump :)

### CODE REVIEW

**Comment by UdjinM6** [comment]
I'd like to have #1364 in first, which is still waiting for review/test btw ;)

**Comment by schinzelh** [comment]
Nevertheless we should bump the version first, as this branch is not 0.12.1.2 anymore :)

**Comment by schinzelh** [comment]
Bitcoin us doing 0.12.1.99's afaik, to mark the dev branch as WIP.

**Comment by schinzelh** [comment]
In Java/Maven world we used 0.12.1.3-SNAPSHOT as WIP marker...

**Pull request merged**
