### PR TITLE
fix(tests): a couple of fixes for dynamically_add/update functions

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
should hopefully fix some sporadic ci test failures (like https://gitlab.com/dashpay/dash/-/jobs/4052206622#L1962)

## What was done?
tweaked dynamically_add/update functions to make checks more consistent and avoid some edge cases, pls see individual commits

## How Has This Been Tested?
`feature_llmq_hpmn.py` and `feature_dip3_v19.py` still work locally, let's see if ci is now (constantly) happy about these too...

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by ogabrielides — APPROVED** [review]
LGTM (Let's wait for CI)

**Comment by UdjinM6** [comment]
there were more issues https://gitlab.com/dashpay/dash/-/jobs/4054105603#L2002 (but at least it failed on `assert_equal` and not in some random place with `UnboundLocalError` so that was a progress anyway :) ), pushed more fixes

**Comment by ogabrielides** [comment]
CI is not happy :(

**Comment by ogabrielides** [comment]
@UdjinM6 `feature_llmq_is_retroactive.py` looks broken now

**Comment by UdjinM6** [comment]
@ogabrielides I know, thanks. it's still a draft after all ;)

**Review by ogabrielides — APPROVED** [review]
LGTM

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
