### PR TITLE
[v0.14.0.x] Backport pending PRs

### PR DESCRIPTION
**Pull request by codablock**
These are all currently pending PRs marked with `backport-candidate-14.0.x`

### CODE REVIEW

**Comment by UdjinM6** [comment]
Travis failed due to some network issues while trying to pull dependencies it seems.

**Comment by codablock** [comment]
Yepp...and https://github.com/dashpay/dash/pull/3011/commits/0410259dd51fbe83d38b5f55df8abd44fd94c7a9 was actually supposed to fix these types of failures, but even with retrying 3 times it failed...

**Comment by codablock** [comment]
Added d2ff63e8d3273383a8dc8f74e6c8b24fe5ea8324 but left everything else as it is. Needs re-ACK now.

**Comment by PastaPastaPasta** [comment]
UTACK again, all commits match original prs

**Pull request merged**
