### PR TITLE
backport: bitcoin#20346, #20495, #20577, #20787, #20890, bitcoin-core/gui#109, gui#116, gui#138, gui#148

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Just regular bitcoin backports, mostly from v21-v22

## What was done?
 - bitcoin-core/gui#116
 - bitcoin/bitcoin#20346
 - bitcoin-core/gui#109
 - bitcoin-core/gui#138
 - bitcoin/bitcoin#20577
 - bitcoin/bitcoin#20890
 - bitcoin/bitcoin#20787
 - bitcoin/bitcoin#20495
 - bitcoin-core/gui#148

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by knst** [comment]
> Merge https://github.com/bitcoin/bitcoin/pull/20282: wallet: change upgradewallet return type to be a…

should I drop this one as a breaking rpc and keep it for v21?

**Comment by PastaPastaPasta** [comment]
> > Merge [bitcoin#20282](https://github.com/bitcoin/bitcoin/pull/20282): wallet: change upgradewallet return type to be a…
> 
> should I drop this one as a breaking rpc and keep it for v21?

I'd drop; open new PR with that change

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merge via merge commit; whitespace only diff

**Pull request merged**
