### PR TITLE
chore(rpc): adjust field type in getwalletinfo help

### PR DESCRIPTION
**Pull request by thephez**
## Issue being fixed or feature implemented
Help reported incorrect field type 

## What was done?
Change field from string to num

## How Has This Been Tested?
Tested locally

## Breaking Changes
N/A

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by knst — APPROVED** [review]
utACK

CI fails seems due to docker's infrastracture down
ERROR: Job failed: failed to pull image "docker:20.10.20-dind" with specified policies [always]: Error response from daemon: Get "https://registry-1.docker.io/v2/library/docker/manifests/sha256:0ff6ef3a97db28ff24e753179097770de480cd77c5ee24a9b5e9c937ad7b889a": EOF (manager.go:203:10s)

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by ogabrielides — APPROVED** [review]
utACK

**Pull request merged**
