### PR TITLE
backport: Misc backports 18

### PR DESCRIPTION
**Pull request by Munkybooty**

### CODE REVIEW

**Comment by Munkybooty** [comment]
I've been working on fixing alot of errors that i've had but now i'm at a standstill as i'm not sure how to handle this linker error

**Comment by UdjinM6** [comment]
linter complains `The subject line of commit hash ba42f8c85af7cc89af7cab5b8ed5ddf0d73d2b5c is followed by a non-empty line. Subject lines should always be followed by a blank line.`

**Comment by UdjinM6** [comment]
pls see 85ad99fb6b

**Review by UdjinM6 — DISMISSED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Pull request merged**
