### PR TITLE
Do not check old legit nodes for watchdogs

### PR DESCRIPTION
**Pull request by UdjinM6**
Should not check old legit nodes for whatchdogs (otherwise there will be a split during migration)

(+added more log output in debug mode)

### CODE REVIEW

**Comment by UdjinM6** [comment]
That's one time migration issue only, I don't think it needs specific spork. Or are we talking about disabling whatchdog check also for future migrations (why?)?

PS. github is not showing reviews as new comments in PR list now so you have to click through to find out... 😞

**Comment by tgflynn** [comment]
Then how about tying it to the SUPERBLOCK spork ?  In other words ignore WATCHDOG_EXPIRED state (treat as ENABLED) for masternode payments when spork 9 is not active.

**Comment by tgflynn** [comment]
> That's one time migration issue only, I don't think it needs specific spork.

It seems like the same thing could be said about superblocks, but we do have a spork for that.

**Comment by UdjinM6** [comment]
Re tying to SPORK_9_SUPERBLOCKS_ENABLED: So the question is do we want to check for watchdogs from new nodes during migration? My guess was yes, we do, to make sure that it's indeed works as designed _before_ flipping the switch for superblocks.

Re superblocks are one time migration issue: Well... it's not true, iirc we had issues with superblocks when we had to turn them off for a while. I would agree however that watchdogs (and mnverify) could also have some unforeseen outcomes and become a non-one time issue when we would like to have a switch for them (at least at first migration) because they affect mn list and that can end badly but that's kind of separate issue from what I was fixing here (still worth looking into though).

**Comment by tgflynn** [comment]
After thinking about this some more I don't think this PR really solves the problem.  There could be upgraded nodes which don't have sentinel running which will be paid by old nodes but not by new ones even with this PR so you could still have a fork due to that.

I think that adding a new spork is probably the best solution.  I'll discuss this with Evan at today's meeting.

Note also that the original primary purpose of watchdog wasn't really to prevent masternodes from being paid but rather so sentinel would have an accurate count of how many sentinel nodes are voting for quorum purposes.

**Comment by UdjinM6** [comment]
> There could be upgraded nodes which don't have sentinel running which will be paid by old nodes but not by new ones even with this PR so you could still have a fork due to that.

Hmm, true. So probably the answer to
> Re tying to SPORK_9_SUPERBLOCKS_ENABLED: So the question is do we want to check for watchdogs from new nodes during migration? My guess was yes, we do, to make sure that it's indeed works as designed before flipping the switch for superblocks.

is "no" then and code should be `if(nProtocolVersion > 70103 && sporkManager.IsSporkActive(SPORK_10_MASTERNODE_PAY_UPDATED_NODES)) {` (i.e. check for watchdogs only if it's a new node AND it's not a migration period)?

**Comment by tgflynn** [comment]
Also this will break watchdog as an indication of the number of running sentinels, which is its primary purpose.  This type of check should be done in deciding whether to pay a masternode not for controlling the state.

**Comment by UdjinM6** [comment]
That's actually a very good point. I agree. 👍

**Pull request closed without merging**
