### PR TITLE
Improve CHDChain

### PR DESCRIPTION
**Pull request by UdjinM6**
Pls see individual commits. This also fixes an issue I mentioned in #4122.

### CODE REVIEW

**Review by xdustinface — DISMISSED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Why is b5a3a174bbbeab1d1ed4a6e96a18f6658d1d031c needed / desireable?

**Comment by UdjinM6** [comment]
@PastaPastaPasta some my other local changes were using it but it violates https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account (`Software should prevent a creation of an account if a previous account does not have a transaction history`) it seems... dropped it.

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
