### PR TITLE
backport: bitcoin-core/gui#29, gui#123, #164, gui#256, gui#309, gui#313, gui#329, gui#331, gui#333, gui#346, gui#393

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Gui related backports from bitcoin v22

## What was done?
See commits

## How Has This Been Tested?
Run unit/functional tests

See also: 

right menu

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by knst** [comment]
It seems as all GUI changes in this PR doesn't really worth to be mentioned in the Release notes, maybe except quick access for "online/offline" switch from peer button, but I am open for suggestions 
@UdjinM6 @PastaPastaPasta @thephez

**Review by thephez — COMMENTED** [review]
On the console screen, these still don't look like buttons for me. I thought one of these PRs changed that?
image

**Comment by knst** [comment]
> On the console screen, these still don't look like buttons for me. I thought one of these PRs changed that?

That's right, we have our own style by "css", so, these changes in backport doesn't actually changed style of buttons, just unified code with bitcoin. They doesn't look nice as rectangle buttons here I think, should we change it?

**Comment by thephez** [comment]
> > On the console screen, these still don't look like buttons for me. I thought one of these PRs changed that?
> 
> That's right, we have our own style by "css", so, these changes in backport doesn't actually changed style of buttons, just unified code with bitcoin. They doesn't look nice as rectangle buttons here I think, should we change it?

I don't mind them the way they are. But I'm a horrible judge of good ui/ux :smile:

**Comment by UdjinM6** [comment]
LGTM but gui346 shouldn't be partial imo - we update translations all at once so there won't be another `backport gui#346`

**Comment by knst** [comment]
> LGTM but gui346 shouldn't be partial imo - we update translations all at once so there won't be another backport gui#346

Indeed, removed "partial" mark

**Review by UdjinM6 — APPROVED** [review]
light ACK 6431f71b3a16339d8a88f3ac123cd9a6a057ae42

**Review by PastaPastaPasta — APPROVED** [review]
utACK 6431f71b3a16339d8a88f3ac123cd9a6a057ae42

**Pull request merged**
