### PR TITLE
tests: Fix `feature_llmq_simplepose.py` and `feature_llmq_signing.py`

### PR DESCRIPTION
**Pull request by UdjinM6**
Pls see individual commits

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
@UdjinM6 what's up with https://gitlab.com/dashpay/dash/-/jobs/838891056 and https://gitlab.com/dashpay/dash/-/jobs/838890842 ?

**Comment by PastaPastaPasta** [comment]
Restarting tests again on CI. If they pass, then I think this PR is probably good to go

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

nit: Title only refers to `feature_llmq_simplepose.py` but `feature_llmq_signing.py` is also affected here.

**Pull request merged**
