### PR TITLE
fix: dash is no more pretending being a 'libdashbls'

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented

It resolves: https://github.com/dashpay/dash/issues/5270

## What was done?
It is still workaround, but it should works more reliable that previous solution.

## How Has This Been Tested?
Using project awhile - not changed to dashbls yet.

## Breaking Changes
No breaking changes

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by ogabrielides — APPROVED** [review]
LGTM

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
I am pretty sure I agree with KW and this should be filed to the bps-signatures repo

**Comment by kittywhiskers** [comment]
Since https://github.com/dashpay/bls-signatures/pull/76 has been merged, the subtree can be updated.

**Comment by PastaPastaPasta** [comment]
@knst please update the subtree instead of this patch like this

**Comment by knst** [comment]
superseeded by https://github.com/dashpay/dash/pull/5466

**Pull request closed without merging**
