### PR TITLE
rpc: Fix filtering in `masternode winners`

### PR DESCRIPTION
**Pull request by UdjinM6**
Was broken by https://github.com/dashpay/dash/commit/44706dc88acf2eab07695f5093bda31ab278d2bf#diff-244e87df3ed336aadc56ec7c8fc521954751f3c3f66b3eb3832bcbcc87996c51L807

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Can you describe the bug a bit more? How would you feel about writing a regression test?

**Comment by UdjinM6** [comment]
The filtering logic was basically dropped in the commit I linked to, so `filter` param had no effect.

**Comment by PastaPastaPasta** [comment]
> The filtering logic was basically dropped in the commit I linked to, so `filter` param had no effect.

Gotcha, `How would you feel about writing a regression test?`

**Review by PastaPastaPasta — APPROVED** [review]
utACK (if you don't want to write regression test)

**Comment by UdjinM6** [comment]
> How would you feel about writing a regression test?

[Ok](http://www.nooooooooooooooo.com/) but et's maybe add it after #3863?

**Comment by PastaPastaPasta** [comment]
> `http://www.nooooooooooooooo.com/`

How DARE you link me to a non-https site... Terrible!

**Pull request merged**
