### PR TITLE
Backports 0.17 pr8

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Rebased cleanly on develop, haven't ran tests or built it, so might be ready for review might not be :)

**Comment by UdjinM6** [comment]
PRs 13119-13079 were already backported via #3539, pls rebase

**Comment by PastaPastaPasta** [comment]
rebased

**Comment by PastaPastaPasta** [comment]
cherry-picked and squashed

**Pull request merged**
