### PR TITLE
Introduce ONLY_PRIVATESEND coin type to select fully mixed coins only

### PR DESCRIPTION
**Pull request by UdjinM6**
This should make it a bit clearer IMO.

Note: ONLY_DENOMINATED will NOT return fully mixed coins now

### CODE REVIEW

**Comment by 10xcryptodev** [comment]
The check on this line could be removed https://github.com/dashpay/dash/blob/d56138cdc987d896a6226d60143767ddb0eec3a8/src/wallet/wallet.cpp#L3311 because is already done inside AvailableCoins

**Comment by UdjinM6** [comment]
@10xcryptodev good catch! 👍 fixed

**Comment by UdjinM6** [comment]
@PastaPastaPasta yeah, makes sense... any suggestions? smth like 82a78e7683?

**Comment by PastaPastaPasta** [comment]
Makes sense, can you elaborate a bit on the intention/what caused you to want this diff?

**Comment by UdjinM6** [comment]
@PastaPastaPasta the idea was that coins that are ready to be mixed and coins that are ready to be spent via PS are in fact two different sets of coins thus we should have different types for them It just makes PS code a bit cleaner and easier to follow IMO.

**Pull request merged**
