### PR TITLE
rpc: Fix inconsistencies in gobject_prepare and gobject_submit 

### PR DESCRIPTION
**Pull request by xdustinface**
The parameter description for some parameter declare them as `numeric` e.g. https://github.com/dashpay/dash/blob/b3c830686758886aa9d026a3c07ac119709cc20d/src/rpc/governance.cpp#L129
However they get fetched witch `get_str()` like in here https://github.com/dashpay/dash/blob/b3c830686758886aa9d026a3c07ac119709cc20d/src/rpc/governance.cpp#L160
Providing numbers there throws an RPC error prior to this PR because of a type check https://github.com/dashpay/dash/blob/b3c830686758886aa9d026a3c07ac119709cc20d/src/univalue/lib/univalue_get.cpp#L99-L100
7104550 Using `ParseInt32V`, `ParseInt64V` and `getValStr` fixes this issue with backwards compatibility i.e. it accepts integer strings and just integers.

62e7689 Adjusts some parameter namings

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — COMMENTED** [review]
it'd be really nice if you could write up a few tests around this!

**Comment by xdustinface** [comment]
@PastaPastaPasta I agree, there is a need for tests in the governance parts of the code but that exceeds the scope of this PR, no? Added a note about missing tests to the backlog. I realised this issue while i was writing tests for dash related ZMQ handler.. will open a PR for that soon which covers at least the minimal usage of those two commands.

**Review by PastaPastaPasta — APPROVED** [review]
ACK, tested creating a proposal on testnet

**Pull request merged**
