### PR TITLE
[Wallet] Fix build warnings for wallet.cpp

### PR DESCRIPTION
**Pull request by Mast3rMind**
Fix warning in wallet.cpp when building.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Thanks! 👍 

Technically OK but I'm not sure if this is going to cause issues for upcoming backports due to possible merge conflicts. @codablock

**Comment by Mast3rMind** [comment]
I pulled #1770 and #1842 locally then merged the two with this fix applied without issue.

**Comment by codablock** [comment]
@Mast3rMind It's more about the upcoming backports, which is huge pile of hundrets of PRs. But don't worry, it's just 2 lines, should be easy to fix if any conflicts come up :)

**Comment by UdjinM6** [comment]
@codablock ok, cool

@Mast3rMind we do not merge into master, pls rebase on `develop`

**Comment by Mast3rMind** [comment]
@UdjinM6 okay my bad.

**Pull request closed without merging**
