### PR TITLE
backport: bitcoin#20182 ci: Build with --enable-werror by default, and document exceptions

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
As discovered in #5957:

Jobs tsan/ubsan fails with backport bitcoin#20182

it fails, because both tsan and ubsan jobs use clang but all other jobs use gcc. Somehow, after configure there are set incorrect options:

```
clang++-16 -std=c++17 -c -pipe -static-libstdc++ -O1   -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_LIBCPP_DEBUG=1 -I/builds/dashpay/dash/depends/x86_64-pc-linux-gnu/include/  conftest.cpp
```

`clang` doesn't support `-static-llibstdc++` which is supposed to be gcc-only, it cause this failure:
```
clang: error: argument unused during compilation: '-static-libstdc++' [-Werror,-Wunused-command-line-argument]
```

This failure make `autoconf` to think that clang doesn't support `-Werror` and fails with this error. So, you can't activate this flag.

## What was done?
Backport bitcoin#20182 and related fixes to make it works

## How Has This Been Tested?
CI now succeed with bitcoin#20182. It means, that -Werror activated for clang; also there are not warnings such as:
```
clang: error: argument unused during compilation: '-static-libstdc++' [-Werror,-Wunused-command-line-argument]
```
https://gitlab.com/dashpay/dash/-/jobs/6494328698

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
8d0da3d2016102b7de9034ec33b93012f3e585e7 looks good but I don't like dropping `check-symbols` from CI in following commits. Let's maybe try to fix it by using `-static-libstdc++` properly: 05a857efce63db8f9e31dac0bdffe976502e854b should help, CI https://gitlab.com/UdjinM6/dash/-/pipelines/1237445880.

**Comment by knst** [comment]
> https://github.com/dashpay/dash/commit/8d0da3d2016102b7de9034ec33b93012f3e585e7 looks good but I don't like dropping check-symbols from CI in following commits. Let's maybe try to fix it by using -static-libstdc++ properly: https://github.com/dashpay/dash/commit/05a857efce63db8f9e31dac0bdffe976502e854b should help, CI https://gitlab.com/UdjinM6/dash/-/pipelines/1237445880.

Check new version of branch, please:
 - symbol-check in CI enabled
 - linux.mk is original without any extra params
 - tested both version - with static and non-static libstdc++

**Comment by knst** [comment]
> @[knst](https://github.com/knst) knst [force-pushed](https://github.com/dashpay/dash/compare/751cdb3c263587ee7f3d15648272e4e481bae6eb..a47635baade5414f6e597f9af4a071905a2cbc53) the bp-v22-p2 branch from[ 751cdb3 ](https://github.com/dashpay/dash/commit/751cdb3c263587ee7f3d15648272e4e481bae6eb)to a47635b

I accidentally rebased on the top of `develop` which I didn't plan to do. 

This [commit](https://github.com/dashpay/dash/pull/5958/commits/a47635baade5414f6e597f9af4a071905a2cbc53) contains new/changed code

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has began to build this PR tagged as v21.0.0-devpr5958.a47635ba. A new comment will be made when the image is pushed.

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v21.0.0-devpr5958.a47635ba. The image should be on dockerhub soon.

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]

**Pull request merged**
