### PR TITLE
bump .python-version

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Any objection? It's really annoying for me on m1, because I need continually delete the .python-version file so that pyenv uses my global version. For it not to be annoying for m1 users, it needs to be at least 3.9(earlier versions of python aren't installable on m1), but I figured why not latest? idk. I think this should only affect people using pyenv

### CODE REVIEW

**Comment by kittywhiskers** [comment]
My global Python version on my macOS 11 install is 3.7 (for Tensorflow support) the last time I checked and some tests were already borked due to a [change in behaviour in macOS Big Sur and above](https://stackoverflow.com/a/63609524). Apple Silicon support [has been implemented](https://bugs.python.org/msg392734) on 3.8.10 and higher, so I would suggest setting it to the _minimum_ supported version (3.8.10 or 3.9) rather than going for the latest (3.10)

**Review by kittywhiskers — COMMENTED** [review]
My global Python version on my macOS 11 install is 3.7 (for Tensorflow support) the last time I checked and some tests were already borked due to a [change in behaviour in macOS Big Sur and above](https://stackoverflow.com/a/63609524). Apple Silicon support [has been implemented](https://bugs.python.org/msg392734) on 3.8.10 and higher, so I would suggest setting it to the _minimum_ supported version (3.8.10 or 3.9) rather than going for the latest (3.10)

**Comment by PastaPastaPasta** [comment]
> 

Why do we care that tensor flow has some borked tests with newer versions? Isn't this the whole point of pyenv? to have multiple environments depending on the project? If you don't have 3.10.2 simply `pyenv install 3.10.2` and that fixes it? if you're using system python, then it doesn't care about .python-version file right?

**Review by kittywhiskers — APPROVED** [review]
utACK

**Review by Munkybooty — APPROVED** [review]
Quite a Robust Change, took a while to review, utACK

**Review by UdjinM6 — DISMISSED** [review]
🤷‍♂️ 
utACK

**Comment by PastaPastaPasta** [comment]
Yeah I think I've maybe seen this before... I'm not sure it's cause, but you can see from the step prior that there are no potential conflicts even. Maybe that is what causes the error idk. Anyhow, I don't think that's a blocker to merge this PR (please for the love of dash :D )

**Review by UdjinM6 — APPROVED** [review]

**Pull request merged**
