### PR TITLE
V0.12.0.x merge btc010&dash_master

### PR DESCRIPTION
**Pull request by UdjinM6**
Merged latest Bitcoin 0.10 branch fixes (but ignored translation and release notes) and then Dash master branch (also fixed new trailing spaces in few places) on top of it.

### CODE REVIEW

**Comment by crowning-** [comment]
Builds fine (Linux) and at least my commits seem to work properly.
Initial problems:

- first start: blockchain corrupt message -> rebuild doesn't work
- second start: no error message, but wallet doesn't sync at all
- deleted blocks/ blockhain/ peers.dat : still doesn't sync, not a single block. I'm the only v0.12.0.x peer right now, guess it doesn't talk to old peers (or just bans them).
- some minor UI issues because some Qt objects seems to have changed.

I'll be on the road today, but will have a closer look tomorrow and will take care of the UI stuff.

**Comment by UdjinM6** [comment]
v0.12 itself is broken now, apply https://github.com/dashpay/dash/pull/332 also to fix it.

**Comment by crowning-** [comment]
Works fine with https://github.com/dashpay/dash/pull/332 :+1: 

I'll wait until your commits are merged before I add the UI stuff.

**Comment by UdjinM6** [comment]
Cool, I'll merge them then. Thanks!

**Pull request merged**
