### PR TITLE
backport: Merge bitcoin#20406, 21370, 21395, 21007, 20040, 21418, 21447, 20197, 21613,  21602

### PR DESCRIPTION
**Pull request by vijaydasmp**
bitcoin backports

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 @knst  @PastaPastaPasta please review

**Review by UdjinM6 — APPROVED** [review]
utACK

**Comment by vijaydasmp** [comment]
Hello @PastaPastaPasta please review

**Comment by vijaydasmp** [comment]
Hello @knst @PastaPastaPasta please review

**Review by knst — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK 7574fd1144733380b08c3f87e0a60eb12ac88680

**Pull request merged**
