### PR TITLE
instantsend: Ignore IS while reindexing/loading blocks from file, bail out early when IS is off

### PR DESCRIPTION
**Pull request by UdjinM6**
Please see individual commits.

Extracted from #3970, ~based on #3984 atm~

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
NACK de8192e857d6f33d59f50465ac11a457b5c84359

We really only call these functions from places where we already check if IS is enabled or not. Additionally, nothing about IS being disabled really prohibits these functions from doing their job. If anything, these checks just add additional overhead and should probably be avoided.

**Comment by UdjinM6** [comment]
My idea was to kind of guard the access to db with these checks (the overhead is tiny compared to db reads/writes I think) but it does _look like_ we have it all covered in other places atm, even though it takes some jumping back and forth through the code to figure it out. Dropped most of them and only ket the one in `HandleFullyConfirmedBlock` for now.

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
