### PR TITLE
Fix bug in GetNextMasternodeForPayment

### LINKED ISSUE #2788: RPC - masternode current kills Core
### Describe the issue
`masternode current` causes Dash Qt to close immediately

#### If so, please list the steps to reproduce below:
1. Run `masternode current`

### Actual behaviour
Qt closes immediately

### What version of Dash Core are you using?
Current develop branch: https://github.com/dashpay/dash/commit/591b0185c5f576b3bb2d7a04b16d7914729e57a6

### Any extra information that might be useful in the debugging process.
Nothing in `debug.log`, but I think we're going out of bounds here on the index (1 minus 9 :scream: ) https://github.com/dashpay/dash/blob/develop/src/rpc/masternode.cpp#L252. `masternode winner` passes through that same function and it works fine.

### PR DESCRIPTION
**Pull request by UdjinM6**
Fixes #2788

### CODE REVIEW

**Comment by thephez** [comment]
Slightly-tested ACK

**Comment by codablock** [comment]
I assume the crash was only happening on `develop` and not on 0.13.x?

**Comment by UdjinM6** [comment]
@codablock yes, it was introduced recently with the removal of legacy code.

**Comment by RoushanArshid** [comment]
can anyone please tell me any address or link to get faucets for my dashcoin testnet address

**Pull request merged**
