### PR TITLE
Masternode broadcast's and ping's GetHash method fix

### PR DESCRIPTION
**Pull request by btcsoft**
We at btcsoft explored your sources in an effort to write our java implementation of DASH protocol for wallets. We've found a place in the code that raised our concern. That's GetHash() methods of CMasternodeBroadcast and CMasternodePing classes. It uses 
```C++
Hash(BEGIN(...), END(...))
``` 
structures that casts objects to byte arrays. I'm not an C++ expert but as far as I know that's very platform dependent, i.e. code compiled on Windows 32x and Ubuntu 64x gcc will produce different result (not even mentioning data endinnesses of different architectures). That might introduce a problem in a protocol when "problematic" nodes will calculate it's own hash of message and store it once again in a "seen" vector and broadcast message to the network once again. Also it introduces a complication in different programming languages implementations (e.g. java) which will be forced to mimic C++ (on some isolated platform) way to store objects in memory.
Keeping in mind that v0.12 will introduce severe protocol changes I think it's a good time to slip that little fix in: calculate those hashes like bitcoin core developers did with core coin objects - using serialization streams.

Regards,
Michael Kulikov, Btcsoft lead developer
adios@btcsoft.com
http://btcsoft.com/

### CODE REVIEW

**Comment by UdjinM6** [comment]
Wow, good find! :+1: 
Thank you!

@evan82 I tested on mac and ubuntu and can confirm this. We have the same problem with CFinalizedBudgetVote and CBudgetVote also (because of vin), fix in https://github.com/dashpay/dash/pull/358

@crowning- that might be actually the root of increased bandwidth we were looking for!

**Comment by crowning-** [comment]
Indeed a very good find :thumbsup:

Will be interesting to see how much the number of messages is reduced by this.

**Comment by evan82** [comment]
Great find! I'll go around and correct the rest of the hashing functions. Thanks so much!

**Comment by btcsoft** [comment]
Great! Thanks for quick response.

**Pull request merged**
