### PR TITLE
Show BIP9 progress in getblockchaininfo

### PR DESCRIPTION
**Pull request by codablock**
I couldn't find a way to figure out the current progress of BIP9 deployments with Dash Core, so I hope this helps others as well.

### CODE REVIEW

**Comment by UdjinM6** [comment]
I like the idea in general but I'd like to propose a couple of patches:
17fb6f2e26c43941c34cc86cc0e06e0e41641abe - to make it look more consistent with the rest of the code
cc9523e2e959c17302b66051f56721a91bcefbde - an additional (internal) check that we are not counting blocks for some another state
478c25df28ab3ab5e12db972f61cf74095b0b7c1 - to match rpc help (`between 0 and 1`)

**Comment by UdjinM6** [comment]
Might also be a good idea to add a couple of tests in `versionbits_tests.cpp`.

**Comment by UdjinM6** [comment]
ok, I guess you can ignore the first two :)

**Comment by codablock** [comment]
added the last commit

**Pull request merged**
