### PR TITLE
backport: Merge bitcoin#20613,20617,20569,20668,20686

### PR DESCRIPTION
**Pull request by vijaydasmp**

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 , please review

**Comment by knst** [comment]
#20605 seems included in other PR: https://github.com/dashpay/dash/pull/5492

**Comment by vijaydasmp** [comment]
> [bitcoin#20605](https://github.com/bitcoin/bitcoin/pull/20605) seems included in other PR: #5492

removed 20605

**Review by knst — DISMISSED** [review]
LGTM

**Review by UdjinM6 — CHANGES_REQUESTED** [review]

**Review by UdjinM6 — APPROVED** [review]
utACK

re recent rebase: pls note https://github.com/dashpay/dash/pull/5514

**Comment by vijaydasmp** [comment]
> utACK
> 
> re recent rebase: pls note #5514
Sure , noted

**Review by knst — CHANGES_REQUESTED** [review]
Seems as fixes related to signet accidentally went with wrong [commit ](https://github.com/dashpay/dash/pull/5502/commits/9bcc54e86d4902f076d1506cbca3b91202d3ba94):
Instead 'bitcoin#20668' being fixed fuzz-related backport "bitcoin#20686" got them.

otherwise LGTM

**Comment by vijaydasmp** [comment]
> Seems as fixes related to signet accidentally went with wrong [commit ](https://github.com/dashpay/dash/pull/5502/commits/9bcc54e86d4902f076d1506cbca3b91202d3ba94): Instead '[bitcoin#20668](https://github.com/bitcoin/bitcoin/pull/20668)' being fixed fuzz-related backport "[bitcoin#20686](https://github.com/bitcoin/bitcoin/pull/20686)" got them.
> 
> otherwise LGTM

Corrected the error

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
