### PR TITLE
Backports 0.17 pr26

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Let's drop 49a9d02 and mark 11637 as DNM instead + ~see https://github.com/UdjinM6/dash/commit/83430d8352~ ~not sure why but linter is still unhappy~ 1f67eb6b16 (?)

**Comment by PastaPastaPasta** [comment]
Yeah, I guess that makes sense :D done

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
