### PR TITLE
depends: Update Qt download url

### PR DESCRIPTION
**Pull request by OlegGirko**
Download URL for Qt 5.7 has changed for some reason.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Thanks for the patch but it doesn't seem to really fix the issue - the new folder is just an empty one, see https://download.qt.io/new_archive/qt/5.7/. We might need to consider prioritising qt backports and migrating to 5.9.x asap. @PastaPastaPasta

**Comment by OlegGirko** [comment]
That's weird. It was there yesterday.

**Comment by xdustinface** [comment]
>  the new folder is just an empty one

Can't confirm this, i see `5.7.0` and `5.7.1` in there, so seems like things changed  

> We might need to consider prioritising qt backports and migrating to 5.9.x asap

But i still agree with this :)

**Review by UdjinM6 — DISMISSED** [review]
Looks like it was repopulated with files again. Tried it and it works as expected, hashes match. Re (temporary) empty folder: there is a related issue in qt bug tracker  https://bugreports.qt.io/browse/QTQAINFRA-3944. 

ACK

**Comment by xdustinface** [comment]
@UdjinM6 Re your ACK: This PR currently wants to go into `master`. @OlegGirko should rebase on `develop` first.

**Comment by UdjinM6** [comment]
@xdustinface oh, good catch! 👍

**Comment by OlegGirko** [comment]
OK, rebased on `develop`.

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
