### PR TITLE
Merge remaining bits of #11824: Block ActivateBestChain to empty validationinterface queue

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by codablock** [comment]
Just a few minor stuff that got lost: 65ddd34b21f614850f561ecc7f5c250c6fa69586
Most white space stuff or ordering of locks which were fixed by you in the past. The ordering is not really more correct in the bitcoin version, but this way we reduce conflicts in the future.

**Comment by UdjinM6** [comment]
@codablock Whitespace changes are kind of unrelated (but I'm fine with fixing it here). `cs_main` changes however revert a fix we backported earlier, should not be applied IMO. pls see https://github.com/dashpay/dash/pull/3300#issuecomment-577395263

**Comment by codablock** [comment]
@UdjinM6 Ah I see, I thought these were fixes pre-11824.

**Comment by codablock** [comment]
fyi, test failure is unrelated and fixed in https://github.com/dashpay/dash/pull/3378

**Pull request merged**
