### PR TITLE
refactor: remove circular dependency governance/object over governance/classes

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
This PR is preparation for bitcoin#19668, otherwise impossible to make lock annotations for CGovernanceManager properly.

## What was done?
1. object mn_sync and peerman is pass to many methods of CGovernanceManager instead passing it to constructor.
2. methods of class CSuperblockManager moved to CGovernanceManager where they belongs to.
3. removed `CSuperblock::GetGovernanceObject` which makes a lot of mess with annotations of `govman.cs`

And minor relevant improvements: moved ScopedLockBool from header to implementation, added multiple `const` for methods, added one more file `flat-database.h` to non-backported list

## How Has This Been Tested?
Run unit and functional tests.

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by UdjinM6** [comment]
Not sure I understand the reason for 7bb236e4613fbc932b760c4e4a8e04bc4ebb9658. Why would we want this?

**Comment by knst** [comment]
> Not sure I understand the reason for https://github.com/dashpay/dash/commit/7bb236e4613fbc932b760c4e4a8e04bc4ebb9658. Why would we want this?

This commit aims 2 reasons:
 - break circular dependency over PeerManager (net_processing) same as in this PR: https://github.com/dashpay/dash/pull/6292
 - CGovernanceManager's constructor accepts not a reference, but the unique_ptr (`const std::unique_ptr<CMasternodeSync>& mn_sync);`). It happens due to order of objects initialization: CGovernanceManager is init before CMasternodeSync, but it requires CMasternodeSync. To fix this order of initialization, better to pass `mn_sync` when it's really need rather then keep "unique_ptr" somewhere inside class, which can be in valid state or invalid state and changed at any moment back to nullptr...  

1st one (break circular dependency over PeerManager) is not done yet, that's just a preparartion
2nd one is compete here. Need to do something similar with `const std::unique_ptr<CDeterministicMNManager>& dmnman` later one.

This commit can be move to own PR **in theory**, or even be split to 2 commits (CMasternodeSync, PeerManager), but I'd prefer to don't do it to avoid multiple conflicts resolving

**Comment by knst** [comment]
> How about https://github.com/dashpay/dash/commit/05a717bd0dab90545e44e99f160b72601c47e859 instead?

That looks good, I replaced my commit to this one; changes related to PeerManager will go to other PR

**Review by PastaPastaPasta — COMMENTED** [review]
generally LGTM 2e368329826c9cd7fbd287266b848df509e4e590

**Review by UdjinM6 — APPROVED** [review]
utACK 2e368329826c9cd7fbd287266b848df509e4e590

**Review by PastaPastaPasta — APPROVED** [review]
utACK https://github.com/dashpay/dash/commit/2e368329826c9cd7fbd287266b848df509e4e590

**Pull request merged**
