### PR TITLE
remove hardcoded `strDarksendPoolDummyAddress`

### PR DESCRIPTION
**Pull request by UdjinM6**
- use "" account address
- remove `collateralPubKey` and `SetCollateralAddress()` from darksend and create `dummyScriptPubkey` and `InitDummyScriptPubkey()` in masternodeman
- initialize `dummyScriptPubkey` before loading cache otherwise MNs could be removed because of the invalid tx

### CODE REVIEW

**Comment by schinzelh** [comment]
Wow, `strDarksendPoolDummyAddress` -  a blast from the past :)

**Comment by schinzelh** [comment]
Hmm, it seems disablewallet.py test gets stuck with these changes

https://travis-ci.org/dashpay/dash/jobs/133772479#L2708
https://travis-ci.org/dashpay/dash/jobs/133772477#L3097

**Comment by UdjinM6** [comment]
@schinzelh Not sure, travis hangs sometimes for no reason.
Anyway, fixed a bug in commit and pushed again, let's see if this can be reproduced.

**Comment by UdjinM6** [comment]
Wrapped "setup PrivateSend" step with ENABLE_WALLET and fDisableWallet (), should be ok now.
It doesn't make sense to have DS or IS without wallet anyway and we need wallet functions for MN and governance iirc. Correct me if I'm wrong pls.
@evan82

**Comment by UdjinM6** [comment]
Ignore the message above :D 
I think I came up with a way better solution - we could just generate a random address instead of using one from the wallet, see https://github.com/dashpay/dash/pull/828/files#diff-3eacbdb2557a3591cfc3764cd73bd2abR634 I also added debug.log output for this new address and corresponding private key so that user always was aware https://github.com/dashpay/dash/pull/828/files#diff-3eacbdb2557a3591cfc3764cd73bd2abR643.

**Comment by schinzelh** [comment]
ACK https://github.com/dashpay/dash/pull/828/commits/3881103b8579087dad71d703c19405f802fca7c2

**Pull request merged**
