### PR TITLE
Remainder of Manual RPC tracker

### PR DESCRIPTION
**Pull request by Munkybooty**

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
4c93796e875b93d47d5a4c68044f8d6e2a6f670b: not sure where it comes from, should backport 18499 instead
aada044: doesn't seem to be doing what it says in the commit message

**Comment by Munkybooty** [comment]
From the looks of it e8c2f56 may have been previously backported

**Comment by UdjinM6** [comment]
> From the looks of it [e8c2f56](https://github.com/dashpay/dash/commit/e8c2f56c79656db9547c3e72473f7b2e38cd48d4) may have been previously backported

yes, I mean it doesn't make sense to have this commit, should be dropped imo.

basically this PR could be turned into `backport #18499: rpc: Make rpc documentation not depend on call-time rpc args` (with an addition of bf354d6dbb to be complete)

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
