### PR TITLE
Make PS Buttons not react to spacebar (#1766)

### LINKED ISSUE #1766: "Start Mixing" shouldn't react to space bar
When Dash Core is freshly started, the "Start Mixing" button has focus and thus pressing space by mistake immediately tries to start mixing. This happened to me when I was starting Dash and then started typing somewhere else while it was loading. When Dash Core got to the foreground, I pressed space (as I was in the middle of typing a sentence).

I'd suggest to make "Start Mixing" not react on space or at least not get focus on startup.

### PR DESCRIPTION
**Pull request by PaulieD**
Wow, this one was a lot harder then it looks... I just want to say publicly that I hate qt, so much stuff that based on the documentation should have worked didn't. At least it is a simple fix in the end.

I'd like to call out to @nmarley and point out that there are no tabs in this one, no trailing spaces, etc. I'm getting better 😉 Also, I learned how to squash commits, thanks @UdjinM6 for pointing me in that direction! 

Oh yeah, and this fixes #1766.

Testing it, everything works well. Space bar doesn't seem to do anything. I am slightly worried about `privateSendAuto` only because I can't tell what it does, and don't know if the space might be triggering it now. But it also doesn't actually look to be a button, at least not one that I see anywhere, and I have seen no ill effects from it.

### CODE REVIEW

**Comment by nmarley** [comment]
> I'd like to call out to @nmarley and point out that there are no tabs in this one, no trailing spaces, etc. I'm getting better 😉 Also, I learned how to squash commits, thanks @UdjinM6 for pointing me in that direction!

:) My only comment is that this should ideally be a 5 line change -- in the "Files Changed" view, ideally there won't be a red line at all (for this specific one) and only 5 green background lines (the reason is that you have changed indention of one of the braces un-necessarily).

**Comment by nmarley** [comment]
Great! 👍 

But ah, now I see you've force-pushed a change! I know that @schinzelh suggested this w/squashing a few days ago, but it's generally (in my experience) not the best for collaboration because then we don't have a history of what happened -- and as @UdjinM6 pointed out, this can be done via GitHub's squash commits, which we now use. So I'd encourage you to not squash once history has been shared / reviewed -- as an example, my comment doesn't make sense without seeing your previous commit.

Now for the code, looks much better. :) I'd still recommend spacing out the `//PrivateSend` so there's a space after the `//` because that's cleaner, and I'd recommend making your comment an entire sentence. These aren't really "required" and more aesthetic guidelines, but I'm trying to guide you to what I would consider "better practice". :)

I hope you see from all this feedback that I'm not trying to critique you un-necessarily, but help you grow as a developer.

**Comment by UdjinM6** [comment]
>But it also doesn't actually look to be a button, at least not one that I see anywhere

https://github.com/dashpay/dash/blob/develop/src/qt/forms/overviewpage.ui#L585

> I am slightly worried about privateSendAuto only because I can't tell what it does

https://github.com/dashpay/dash/blob/develop/src/qt/overviewpage.cpp#L580

Btw, I can't reproduce the initial issue on macos (10.13.5). Is it OS-specific one? If so, which OS can you reproduce it on?

**Comment by PaulieD** [comment]
The initial issue was space pressing the button on startup, as in after it loads and you haven't clicked on dash-qt yet. I have confirmed the issue exists on windows 10 and Ubuntu. It shouldn't be os specific but maybe it is. This PR goes one step further then just making it not react on startup, but not react ever. For example on the old version, if you clicked "Start Mixing" then hit the space bar, it would then stop mixing. Possibly different w/ an encrypted wallet. Didn't test w/ that.

**Comment by PaulieD** [comment]
@UdjinM6 I think something is messed up w/ `privateSendAuto` 

Clicking it calls `DoAutomaticDenominating(CConnman& connman, bool fDryRun=false)` the comment on that method is `/// Passively run mixing in the background according to the configuration in settings`
However, the button's text is `Try Mix` and the toolTip is "Try to manually submit a PrivateSend request"

In addition, clicking this button doesn't appear to actually do anything. it is possible the `DoAutomaticDenominating` function is messed up?

**Comment by UdjinM6** [comment]
Hmm..... true, this button doesn't actually do anything anymore. `DoAutomaticDenominating` function is kind of fine but conditions inside of it won't let you do what button tooltip says without setting `privateSendClient.fEnablePrivateSend = true;` (and back to `false` after it's done). These "Try mix" and "Reset" buttons were meant to be "debug" buttons in earlier versions and I don't know if anyone is using them today at all. We do not show them in "simple" mode already and should probably think about dropping them completely. But that's smth for a separate PR. 

Having said this, I think we still should keep this PR consistent and fix all 4 buttons even if we are going to drop one or two of them later. Well, unless the other PR (to drop unused buttons) is the one to be merged first and I don't think we are there (yet).

**Pull request merged**
