### PR TITLE
backport: Merge bitcoin #20530,20221,20556,19832

### PR DESCRIPTION
**Pull request by vijaydasmp**

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 , please review

**Review by knst — APPROVED** [review]
LGTM

_note for futher backports: #20566 is partial due to missing #20403_

**Comment by UdjinM6** [comment]
20530 should also be partial imo because of missing changes in `src/txrequest.cpp` (introduced in 19988)

**Comment by knst** [comment]
> 20530 should also be partial imo because of missing changes in src/txrequest.cpp (introduced in 19988)

I don't agree, because we have a linter now: `test/lint/extended-lint-cppcheck.sh` will be triggered by CI and changes will be merged after all - not like a separate backport but together with bitcoin#19988

Moreover, when 19988 will be merged (by new updated version) - you can't merge remaining part of 20530 as a spare changes -> because these changes forced to be included in 19988 by linter.

**Review by UdjinM6 — APPROVED** [review]
makes sense, utACK then

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
