### PR TITLE
Refactor CDarkSendSigner

### PR DESCRIPTION
**Pull request by UdjinM6**
Error messages in `SignMessage()` and `GetKeysFromSecret()` don't really help too much since there is only one way these functions can ever fail. Having localized error message in `VerifyMessage()` also do not help too much (and actually is annoying) since the only place it can be visible is debug.log. So changing these functions accordingly and also making sure that every caller gets proper debug.log output etc.

### CODE REVIEW

**Comment by tgflynn** [comment]
Why are we changing localized error messages to non-localized ?

**Comment by UdjinM6** [comment]
@tgflynn Because they are technical and only shown in debug.log. Simplified localized messages are provided for UI only in places where this functions are called.

Reason: I went through tons of user's debug.log files helping them to resolve their issues (or find network problems) and I would like to make debug.log messages as non-localized as possible tbh because having all kind of hieroglyphs there doesn't help to find/resolve issues imo.  Some initial messages are fine to be localized probably: they are easily identifiable, they only occur once at wallet start and they provide some info general user can understand. Deeply technical messages should not be localized imo.

**Comment by tgflynn** [comment]
utACK

**Comment by schinzelh** [comment]
utACK https://github.com/dashpay/dash/pull/948/commits/b130c3286a9df0c364b12f32a774f123fefb618c - i agree that error messages in debug.log should be unlocalized for better traceability

**Pull request merged**
