### PR TITLE
refactor: Add (and use) queueAndMaybePushInv helper

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Does this change behavior, or is it a pure refactor? And if so, please explain how it changes behavior

**Comment by UdjinM6** [comment]
@PastaPastaPasta It shouldn't change network related behaviour. It adds more logging (for `BCLog::NET` category i.e. debug mode only) for non-block invs though.

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
