### PR TITLE
refactor: Drop some unused code

### PR DESCRIPTION
**Pull request by xdustinface**

### CODE REVIEW

**Comment by xdustinface** [comment]
The new commit 0768803 also drops `nodeId` parmeter in some places where it was just used in logs but that should be fine?

**Comment by UdjinM6** [comment]
Pls see https://github.com/UdjinM6/dash/commits/pr3919 for a couple of suggestions

**Comment by xdustinface** [comment]
@UdjinM6 Picked 6fa44429ddf2fef9903332e7eb0c472cd61e3bc7. The other two also make sense but maybe better in a seperate PR since it exceeds the "drop unused" topic a bit, no? :D

**Review by UdjinM6 — DISMISSED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
