### PR TITLE
Merge bitcoin#14771: test: Add BOOST_REQUIRE to getters returning optional

### PR DESCRIPTION
**Pull request by 5tefan**
Merges bitcoin/bitcoin#14771: test: Add BOOST_REQUIRE to getters returning optional

fa21ca09a8 test: Add BOOST_REQUIRE to getters returning optional
            (MarcoFalke)

Pull request description:

  Usually the returned value is already checked for equality, but for
sanity we might as well require that the getter successfully returned.

### CODE REVIEW

**Comment by 5tefan** [comment]
There's a second component of bitcoin#14771, which seems to be adding `NODISCARD`. It looks like Dash is generally not adding `NODISCARD` nor the `[[nodiscard]]` attribute.

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
> It looks like Dash is generally not adding `NODISCARD` nor the `[[nodiscard]]` attribute.

Yeah, it's rare but we do have it in a few places e.g. https://github.com/dashpay/dash/blob/develop/src/evo/deterministicmns.h#L511. I think this part should be backported as well (NOTE: pls use `[[nodiscard]]` instead of `NODISCARD`).

**Review by UdjinM6 — APPROVED** [review]
👍 

utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
