### PR TITLE
feat: Implement caching in `CalcCbTxMerkleRootQuorums`

### PR DESCRIPTION
**Pull request by UdjinM6**
Somehow these loops are the heaviest part here. Improve it by an order of magnitude (in the long run) by caching few stuff and skipping these loops most of the time (quorums do not change that often).

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Can you take a look at this? 7176b9b77fae527379ff2fd8c8f266085fff8815 and apply that / that kind of idea?

**Comment by UdjinM6** [comment]
> Can you take a look at this? [7176b9b](https://github.com/dashpay/dash/commit/7176b9b77fae527379ff2fd8c8f266085fff8815)

I like it 👍 but I'd rather keep this PR focused - it's pretty much trivial when you exclude whitespaces https://github.com/dashpay/dash/pull/4952/files?w=1

> it's much safer, especially as we are both adding and removing the hashes

We only remove hashes in the loop below the optimised one (for commitments that are about to be mined, not for the already mined ones) so there should be no difference imo.

Let's do all the suggested stuff in the follow-up PR #4954

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Comment by PastaPastaPasta** [comment]
nit: fuzz build not happy?

**Pull request merged**
