### PR TITLE
Backports 0.16 pr2

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
builds and tests pass locally

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
cherry-picked, can squash once review is done I'd say

**Comment by PastaPastaPasta** [comment]
@codablock can you review?

**Comment by UdjinM6** [comment]
Looks good IMO 👍  (cherry-picked commits match the ones in my branch and I have no additional suggestions atm)

**Comment by codablock** [comment]
@PastaPastaPasta can you rebase and remove bitcoin#7609 instead of doing the revert at the end?

**Comment by PastaPastaPasta** [comment]
Removed and squashed.... Somehow #10303 (backported already) got into the branch so I had to force push again to remove it

**Pull request merged**
