### PR TITLE
privatesend: Increase max participants to 20

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
This adds a new spork which will change the maximum number of participants from 5 to 20 (the theoretical limit based on tx size limit should be around 60). This should increase the general privacy of privatesend when there is sufficient liquidity on the network. In the case that there is insufficient liquidity, privacy is the same as it is today, with a minimum number of participants of 3 (actually 2 on devnet/testnet once this spork is activated to make it easier to test mixing).

If there's a better way to do this, let me know

### CODE REVIEW

**Comment by xdustinface** [comment]
Is there any reason to not increase it even more if you say the theoretical maximum should be around 60?

**Comment by PastaPastaPasta** [comment]
The more participants you have I assume the more problems you might have. That'll require more connection slots etc. It might be fine to do so, but imo would require more research and I don't expect that this will be getting maxed out on mainnet at this point so no trouble capping it at 20

**Comment by xdustinface** [comment]
utACK, At this point i can't attest that this doesn't break anything in the PS process but the min/max increase itself with the spork looks good to me.

**Comment by PastaPastaPasta** [comment]
backported in https://github.com/dashpay/dash/pull/3670

**Pull request merged**
