### PR TITLE
immer: update source tree to 609d1958fc588f0b73f25c7c3b0c8b78f084c983

### PR DESCRIPTION
**Pull request by kittywhiskers**
Requires https://github.com/dashpay/dash/pull/4268

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Linter fails

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see 1bcbf341885cd114dc375191714028e30f4ee317, LGTM otherwise

**Comment by PastaPastaPasta** [comment]
How was this PR created?

**Comment by kittywhiskers** [comment]
While not the exact commands I've run, this should do the job (untested):

```bash
# Clone what you need
git clone https://github.com/dashpay/dash -b develop
wget https://github.com/arximboldi/immer/archive/refs/tags/v0.6.2.zip
unzip v0.6.2.zip
# Get rid of existing immer source tree
cd dash
rm -rf src/immer/
# Copy the contents of the archive
cp -R ../immer-0.6.2/immer ./src/
# Do not acknowledge changes in file permissions
git config core.fileMode false
# Commit changes
git commit -Am "immer: update source tree to arximboldi/immer@609d195"
# Add Udjin's branch
git remote add udjin https://github.com/UdjinM6/dash
git fetch udjin
git cherry-pick 1bcbf34
# Squash Udjin's commit with the previous commit
# using interactive rebase (user involvement necessary)
git rebase -i HEAD~2
```

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
