### PR TITLE
Qt: Remove old themes

### PR DESCRIPTION
**Pull request by nmarley**
This is split out from #3000 and removes all except the "light" theme in preparation for a bit more extensive refresh. This refresh moves images and layout around and won't work with the current theme layout.

### CODE REVIEW

**Comment by UdjinM6** [comment]
This basically leaves us with one single theme again and what it means is that we don't have to care about themes for any kind of images at all now and thus we can "squash" things like this https://github.com/UdjinM6/dash/commit/721288ed2203eedaf79948c9840e61f4af6dd185. Also, we can finally cleanup some legacy `drkblue` mess https://github.com/UdjinM6/dash/commit/06e1f59a2a235ccc406c38dea0f4fd6b1d03868b.

And I would actually keep the `Traditional` theme - it requires almost no additional code and no images after the "squashing" commit, so it's very lightweight (https://github.com/UdjinM6/dash/commit/b190fd8bd4a89d396d3bdf4ed931f281de19742a) but it can be very useful for people running qt wallets in weird environments (some exotic linux distros, crazy small resolutions etc.). I know that at least some people were actually using this theme at some point.

**Comment by codablock** [comment]
Big fan of removing the themes mess as proposed by UdjinM6 :+1:

**Comment by nmarley** [comment]
Agree on removing themes and cleaning up drkblue. Traditional seems to still work so don't mind either way on that one. FF'ed to 06e1f59a2a235ccc406c38dea0f4fd6b1d03868b.

**Comment by UdjinM6** [comment]
Travis failed due to some (unrelated) `apt-get` timeout issues.

**Pull request merged**
