### PR TITLE
backport: merge bitcoin#27479, #27230, #25251, partial #22934, #23383, #24792, #26691, #27445 (secp256k1 update)

### PR DESCRIPTION
**Pull request by kwvg**
## Motivation

As mentioned in https://github.com/dashpay/dash-issues/issues/7, [bitcoin#27479](https://github.com/bitcoin/bitcoin/pull/27479) is an important backport required in establishing the cryptographic foundation needed for BIP324 support. This pull request, therefore, performs out-of-order updates of the `secp256k1` subtree and its API use till [bitcoin#27479](https://github.com/bitcoin/bitcoin/pull/27479).

## Additional information

* Depends on https://github.com/dashpay/dash/pull/5574
* "trivial: add header for std::array instantiation" needed to mitigate build failure for macOS targets ([build](https://gitlab.com/dashpay/dash/-/jobs/5182422817#L1717))
* "ci: don't re-use config.cache when running configure script" needed to mitigate build failures ([build](https://gitlab.com/dashpay/dash/-/pipelines/998322957), [build](https://gitlab.com/dashpay/dash/-/pipelines/1014987384))

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
I don't love that most of the commits are partials..

**Review by UdjinM6 — COMMENTED** [review]
one issue, LGTM otherwise

**Review by UdjinM6 — APPROVED** [review]
squashed 9b74ac11fb into 26691

utACK

**Comment by UdjinM6** [comment]
rebased from GH GUI to fix `Merge Fast-Forward Only` check

**Comment by UdjinM6** [comment]
force-pushed to resolve merge conflicts

**Review by UdjinM6 — APPROVED** [review]
self-utACK :D

**Review by ogabrielides — APPROVED** [review]
ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit; I don't love the partials

**Pull request merged**
