### PR TITLE
V0.12.0.x Process Budget only to/from valid Peers.

### PR DESCRIPTION
**Pull request by thelazier**
For your consideration..

### CODE REVIEW

**Comment by schinzelh** [comment]
Before merging this, please introduce a method to reduce code duplication - we have four identical code blocks which do excactly the same.

**Comment by thelazier** [comment]
I'm running fine with these latest fix on testnet for now, please feel free to close the request if you don't need. Thanks :sunglasses:

**Comment by UdjinM6** [comment]
@thelazier this https://github.com/dashpay/dash/pull/412/files#diff-2e2ff25b7bc057a741bf93c35ae3b624R812 and this https://github.com/dashpay/dash/pull/412/files#diff-2e2ff25b7bc057a741bf93c35ae3b624R62 are ok but for later I would prefer even more general implementation, see my https://github.com/dashpay/dash/pull/413

As for other bugfixes like https://github.com/dashpay/dash/pull/412/files#diff-2e2ff25b7bc057a741bf93c35ae3b624R42 - nice catch! but wrong PR :wink: I don't like mixing all kind of unrelated stuff in one place, please open new PRs for those fixes and give a little bit more description maybe

**Comment by thelazier** [comment]
Thanks @UdjinM6 , I'm not sure about the catch as well if it will be same solution as @evan82 expected or not so I will close this and will not open another PR for the other bugfixes.

**Comment by UdjinM6** [comment]
Ahh.. you're right actually, there is no bug, I fixed my comment... I probably need to sleep more :confused: 
Anyway thanks for looking into code :+1:

**Pull request closed without merging**
