### PR TITLE
chore: blockchain updates for v20.1: chainparams, seeds

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Part of release process to update seeds and chainparams: https://github.com/dashpay/dash/blob/develop/doc/release-process.md

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by knst** [comment]
there's something wrong with tor on my machine, it says all onions' hosts are unavailable. @UdjinM6 @PastaPastaPasta please help to validate them

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Looks mostly ok, one issue, see below. Also, what about testnet?

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
:D

**Review by UdjinM6 — APPROVED** [review]
utACK (verified blockhashes etc. in chainparams)

**Review by PastaPastaPasta — APPROVED** [review]
utACK; rebased to change commit names a bit

**Pull request merged**
