### PR TITLE
feat: bump protocol version to distinguish v21 from v20.1

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
See commit

## Breaking Changes
None really; will require MNs to upgrade in order to not be banned

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by knst** [comment]
@pankcuf be ready for protocol version bump in mobile applications

**Comment by pankcuf** [comment]
> @pankcuf @HashEngineering @Syn-McJ be ready for protocol version bump in mobile applications
What ETA's for Testnet/Mainnet?

**Comment by PastaPastaPasta** [comment]
Please see https://github.com/dashpay/dash/issues/6082: more or less, July 29th

**Review by UdjinM6 — APPROVED** [review]
utACK (to merge close to release maybe?)

**Pull request merged**
