### PR TITLE
tests: Fix a couple of rare mnsync issues

### PR DESCRIPTION
**Pull request by UdjinM6**
Pls see individual commits.

### CODE REVIEW

**Review by xdustinface — CHANGES_REQUESTED** [review]
I guess adding 8d88d9b makes sense then here.

**Review by xdustinface — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
