### PR TITLE
Update rpc auth script

### PR DESCRIPTION
**Pull request by charlesrocket**
Backport rpc token script from bitcoin

### CODE REVIEW

**Comment by UdjinM6** [comment]
Hmmm...
1. why, is smth broken? we try to avoid backporting stuff in no order unless it fixes some serious bug or adds a very needed feature to make it easier to backport lots of PRs (e.g. the whole 0.15->0.16 transition) at once or at least in just a few attempts without having to deal with tons of merge conflicts.
2. what PR does this backports exactly?
3. needs rebase, probably based on an outdated commit atm

**Comment by charlesrocket** [comment]
having issues with the old script running from homebrew env, looking for the actual bad string(s), but I am guessing theres a few since upstream has several PRs fixing it (like `#` in rpc pass). will confirm asap

**Comment by charlesrocket** [comment]
3. I went with the master first, but it was conflicting with version configs, so I thought one is better than 6 :) this is probably parallel PR

**Comment by charlesrocket** [comment]
@PastaPastaPasta should I open this after `0.13` release or isolate formatting in current PR?

**Comment by charlesrocket** [comment]
will reopen

**Pull request closed without merging**
