### PR TITLE
Fix sign mismatch warnings in GCC.

### PR DESCRIPTION
**Pull request by Duality-CDOO**
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=193080913

### CODE REVIEW

**Comment by nmarley** [comment]
Isn't this an upstream (vendored) dependency from Bitcoin? Have they solved this in their repo yet? (Meaning, if they have, we could just backport that commit / PR instead.)

**Comment by UdjinM6** [comment]
Agree with @nmarley - leveldb is submodule-like inclusion and this PR, #2349 and most of #2347 should be submitted to leveldb repo.

**Comment by Duality-CDOO** [comment]
Can we update LevelDB to 1.20?

**Comment by UdjinM6** [comment]
I doubt we can switch to google/leveldb repo as it misses some bitcoin specific code afaik but we can backport PRs that were merged in bitcoin repo itself to re-align with it https://github.com/bitcoin/bitcoin/commits/master/src/leveldb. It's only a handful of PRs as far as I can see.

**Comment by Duality-CDOO** [comment]
Yeah do that, I have just looked and https://github.com/bitcoin/bitcoin/commit/47f3e8c74d390139967cc40e37cf5b433f0b0f9f#diff-ca4dbb87b4472b26c1537348d904ea8b would  then be included and fix this issue.

**Comment by UdjinM6** [comment]
Postponing these fixes till future backport packs. Closing.

**Pull request closed without merging**
