### PR TITLE
backport: merge bitcoin#22689, #23381, #22674, #23804, #24310, #24537, #24582, #24404, #25013, #25029, #25254, #25388 (mempool backports)

### PR DESCRIPTION
**Pull request by kwvg**
## Additional Information

* [bitcoin#23694](https://github.com/bitcoin/bitcoin/pull/23694) (backported in [dash#6256](https://github.com/dashpay/dash/pull/6256)) was backported before [bitcoin#22689](https://github.com/bitcoin/bitcoin/pull/22689) and therefore, the formatting changes in the former were not incorporated in the backport. This has been resolved by accommodating them in the latter.

* The fields deprecated in [bitcoin#22689](https://github.com/bitcoin/bitcoin/pull/22689) were originally deprecated in [bitcoin#12240](https://github.com/bitcoin/bitcoin/pull/12240) but not gated behind runtime arguments, the backport does so.

* This pull request includes multiple backports that include code specific to RBF (BIP 125) and SegWit, which have been removed due to Dash Core not supporting them, comments and documentation (like `doc/policy/packages.md`) have been amended to reflect this accordingly.

* When backporting [bitcoin#22674](https://github.com/bitcoin/bitcoin/pull/22674), a new constructor was introduced for submitting `MEMPOOL_ENTRY` `ResultType`, upstream this can be done trivially as it uses function overloading ([source](https://github.com/bitcoin/bitcoin/pull/22674/files#diff-d3c243938494b10666b44404a27af7d84b44a72b85a27431e0c89e181462ca6eR198-R204)) but as Dash Core doesn't accept 
`replaced_txns`, there is no opportunity to differentiate arguments.
  * This was resolved by accepting `ResultType` as an argument but always passing `MEMPOOL_ENTRY` as the argument ([source](https://github.com/dashpay/dash/pull/6499/commits/71b26232074ae308f86ab685f5f57ec47a7ef0e9#diff-d3c243938494b10666b44404a27af7d84b44a72b85a27431e0c89e181462ca6eR232-R242))

* Unit tests like `package_witness_swap_tests` (introduced in [bitcoin#23804](https://github.com/bitcoin/bitcoin/pull/23804)) have been omitted due to functionality tested not being implemented in Dash Core. Subsequent backports that include modifications to these tests have mirrored similar omissions.

## Breaking Changes

* The top-level fee fields `fee`, `modifiedfee`, `ancestorfees` and `descendantfees` returned by RPCs `getmempoolentry`,`getrawmempool(verbose=true)`, `getmempoolancestors(verbose=true)` and `getmempooldescendants(verbose=true)` are deprecated and will be removed in the next major version (use `-deprecated=fees` if needed in this version). The same fee fields can be accessed through the `fees` object in the result. 

  **WARNING: deprecated fields `ancestorfees` and `descendantfees` are denominated in sats, whereas all fields in the `fees` object are denominated in DASH.**

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
utACK 578be36b897f48889241cefa3421a3ecf05e58fa

**Review by PastaPastaPasta — APPROVED** [review]
utACK 578be36b897f48889241cefa3421a3ecf05e58fa

**Comment by thephez** [comment]
Was there actually a change in `fee`, `modifiedfee`, `ancestorfees` and `descendantfees`? Per docs they have been deprecated since 0.17.0, but this PR says they are being deprecated now. :thinking:

**Comment by kwvg** [comment]
> The fields deprecated in https://github.com/bitcoin/bitcoin/pull/22689 were originally deprecated in https://github.com/bitcoin/bitcoin/pull/12240 but not gated behind runtime arguments, the backport does so.

@thephez, as mentioned in the PR description, they have been _de facto_ deprecated since 0.17 through the backport in [dash#3877](https://github.com/dashpay/dash/pull/3877) but this deprecation wasn't enforced, only expressed in documentation, until https://github.com/bitcoin/bitcoin/pull/22689 (included in this PR), where access to the deprecated RPCs are gated behind `-deprecatedrpc=fees`, which is in line with other deprecations like `-deprecatedrpc=addresses` (see https://github.com/bitcoin/bitcoin/pull/20286).

Functionally, the only difference is that programs that haven't been revised to use the newer fields will need to start Dash Core with that argument (at least until the deprecated logic is removed altogether and programs need to update themselves to use newer fields).

**Pull request merged**
