### PR TITLE
small cleanup in a few places

### PR DESCRIPTION
**Pull request by nmarley**
Please see individual commits. Removes unused code, comments, variables, etc.

Let's wait 'til 12.3 is released before any merge, but I've been itching to get this PR created for a while, so gonna go ahead and do that now.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Looks good 👍

I'd say it's safe to merge in 12.3 if you drop d7f876e for now.

**Comment by nmarley** [comment]
Per our discussion on another recent PR, we'd like to off on any more non-bug-fixes going in to 12.3, but did you have any specific concerns with commit d7f876e86336170f2d6d3f20b6af26bcd0dc2b18? Or is it just the potential for a bug b/c it's a little more complex?

**Comment by UdjinM6** [comment]
>off on any more non-bug-fixes

It's more like no-new-features-or-potential-changes-in-behaviour mode :)

d7f876e _looks_ fine but has a _potential_ to change the behaviour because it touches some actual code unlike others here.

**Comment by nmarley** [comment]
Yep, makes sense. Might as well get the others in, will revert d7f876e86.

**Pull request merged**
