### PR TITLE
Update static and dns seeds for mainnet and testnet

### PR DESCRIPTION
**Pull request by UdjinM6**
~Mainnet static seeds are 10% of active MNs plus 100 MNs running behind Tor. Testnet static seeds are all currently enabled MNs.~

Seeds are generated using updated scripts and instructions now. Onion seeds are not hardcoded but instead a few of them are listed in `tor.md` now with a note that they are hosted by one entity. 

Dropping `(test.)dnsseed.masternode.io` dns seeds because they are down atm.

### CODE REVIEW

**Comment by codablock** [comment]
nACK, as discussed in Slack. The way MNs were selected is suboptimal. Instead, we should update `makeseeds.py` to work with `protx list` instead and then use that list. The advantage is that we can filter for MNs owned by the same people or hosted in the same location (ASN filtering).

Please see ab47413f63977c583ae4c2c407426eedac123efb and 8656a6b3cdf69a36f35277cf9d63a746a9651eaf

**Comment by codablock** [comment]
Ah, and the list in https://github.com/dashpay/dash/commit/8656a6b3cdf69a36f35277cf9d63a746a9651eaf can be easily verified by using the protx list from block 1185168. Running `makeseeds.py` and `generate-seeds.py` with the resulting protx list should result in exactly the same list of IPs.

**Comment by codablock** [comment]
I forgot to run `generate-seeds.py`, which I've done in 8656a6b3cd now

**Comment by UdjinM6** [comment]
Rebased and reworked this using new script from #3235 with no manual intervention, tor nodes are in `tor.md` now. Updated PR description accordingly.

**Pull request merged**
