### PR TITLE
feat: calculate DISK_SNAPSHOTS at compile time

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
LLMQ_400_85 requires four days worth of LLMQs https://github.com/dashpay/dash/blob/master/src/llmq/params.h#L416

## How Has This Been Tested?
n/a

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Can we better document here what this value should be? Even better if we could add compile time checks on that; but that may be asking too much.

**Review by ogabrielides — APPROVED** [review]
utACK

**Review by knst — APPROVED** [review]
LGTM

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

Much better :)

**Pull request merged**
