### PR TITLE
Backport candidates to v0.15.x

### PR DESCRIPTION
**Pull request by UdjinM6**
And update release notes accordingly

### CODE REVIEW

**Comment by UdjinM6** [comment]
Added #3321 and #3322

**Comment by PastaPastaPasta** [comment]
Should the release notes (at https://github.com/dashpay/dash/pull/3323/files#diff-ef76fd6674f07db88c3422fdbf0bcf9fL73 ) be updated after #3321 ? I don't have a strong opinion either way, in fact I lean towards they don't need to be updated.

**Comment by UdjinM6** [comment]
@PastaPastaPasta Hmm... Might be a good point actually. Smth like `Nodes joining the network will now try to sync their mempool from other v0.15+ peers via the 'mempool' p2p message.`?

**Comment by PastaPastaPasta** [comment]
Sure

**Comment by UdjinM6** [comment]
Removed `backport-candidate-15.x ` label from corresponding PRs.

**Pull request merged**
