### PR TITLE
Backports 0.15 pr12

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by UdjinM6** [comment]
missing this part https://github.com/bitcoin/bitcoin/pull/9942/files#diff-ca74c4b28865382863b8fe7633a85cd6L853

**Comment by UdjinM6** [comment]
Looks good but could you squash 6545d37 into 56e6cb2 pls?

**Comment by UdjinM6** [comment]
Looks like `#include "policy/fees.h"` is missing in `validation.cpp`

**Comment by codablock** [comment]
@PastaPastaPasta See 4c89c2c79e39affa36caba974eccb294a0ab1094, this should fix the build errors.

**Comment by UdjinM6** [comment]
And `disconnect_ban.py` fails, not sure why yet.

**Comment by UdjinM6** [comment]
Pls see https://github.com/UdjinM6/dash/commit/a0c2f2a2574f29fe1b89f3fad661d53afedc398b

**Pull request merged**
