### PR TITLE
[UI] Rebranding: Darksend/InstantX changed to PrivateSend/InstantSend (UI+log)

### PR DESCRIPTION
**Pull request by crowning-**
**Update: ------------------------------------------------------------------------**
After some discussions there seems to be consensus that **"Darksend"** will be re-branded to **"PrivateSend"** and **"InstantX"** to **"InstantSend"**.

Reasoning: PrivateSend gets us aways from our dark side :-), and InstantSend is less technical and better to understand for 'normal' people.
Whatever 'normal' is :stuck_out_tongue_winking_eye:

References:
Discussion: https://www.dash.org/forum/threads/darksend-rebranding-discussion.8710/
Someone created a poll: https://www.dash.org/forum/threads/non-binding-wallet-terms-vote.8715/
**End of Update -----------------------------------------------------------------**

tungfa told me that **"Darksend"** will be re-branded to **"PrivacyProtect"**. This is a first result.
Please test and report back if I missed some occurrences.

**What's covered:**
1. labels, buttons and screen titles
2. tool-tips
3. text of log-messages

**What's not covered:**
1. log category, the category is still called "darksend"
2. RPC API + command-line/dash.conf options
3. network messages to other peers/nodes
4. refactoring of classes containing Darksend in the name
5. I think I remember that somewhere's a thread created called darksend
6. translations

I can do 1. and 2. later if wanted, 3. + 4. is for someone who REALLY is bored :-)

Overview-screen looks like this now:
pp

### CODE REVIEW

**Comment by UdjinM6** [comment]
Thanks for looking into this!

However, now with that done in code it looks like this DS->PP transition is not going to be that easy to implement and it looks messy tbh (imo)... Maybe it would be a better idea to get rid of any technology name at all in UI/logs/rpc(?) and replace it with smth more general like simply "mixing", "mixed", "private" etc.

And few side notes:
- having darksend + privacyprotect together all over the place in code is confusing imo and I think almost everything in "What's not covered" need to be implemented too sooner or later
- if you mean "change _ds_ part to _pp_" in messages like dsq, dsa etc in number 3 of "What's not covered" then I guess this can be done later once we have something else that bumps protocol for a better reason than just rebranding ;) (or keep it as it is if we decide to go with general names)

**Comment by crowning-** [comment]
@UdjinM6 I think the main problem is the mixing button, I think I'll change it to "Start Mixing" and be done with it.
The other places are IMO okay-ish, but if one of you wants specific changes just speak up :-)

And, yes, I meant exactly those messages.

(on the other hand, we live in a "Design-Driven" world, so I wouldn't be TOO surprised if one day someone somewhere on this planet changes a protocol because the protocol-messages need a re-branding. 
Aaaargh, shoot me...)

**Comment by crowning-** [comment]
@UdjinM6 @schinzelh : somewhere during the last big Bitcoin-merge parts of https://github.com/dashpay/dash/pull/612 got lost (here: no theme-dependent splash-screens).
I've fixed this with https://github.com/dashpay/dash/pull/760/commits/67214d997166fa3ed2a0f5efec1b587dcb9f8675. 

However, some things are still not there, e.g. the theme-dependent tx_input/tx_inout/tx_whatever icons (they show up fine on the 'Transactions' page, but the bigger ones on the 'Overview' page are gone). The resources are all there

I don't have any local working repositories of my changes  any more, so I can't easily diff through the files. Something seems to be changed in TransactionTableModel but I cannot find what..I guess it's just TOO obvious to be found by myself :-/

**Comment by UdjinM6** [comment]
b61849c is a step in the right direction ;) I guess tungfa already sent you an image with few more changes so we all should be on the same page now.

Re issues with splash screen:
67214d9 has nothing to do with current PR and should be removed imo.
Yes, I removed splash_tesnet.png-s because bitcoin now uses NetworkStyle to rotate colors for different networks instead of having multiple files. You are right though, there is a bug with splash screen theme specifically which I hope should be fixed by #761. I'm not sure about tx_whatever icons though, I don't see any issues. (Let's continue in #761 if you still have any issues after applying that patch).

**Comment by crowning-** [comment]
@evan82 @schinzelh , it's ready to merge now, from the UI and log point of view Darksend is Privatesend now and InstantX is InstantSend.

**Pull request merged**
