### PR TITLE
V0.12.0.x Bump version to 0.12.0.60

### PR DESCRIPTION
**Pull request by schinzelh**
I'll do another release to have #959 included

### CODE REVIEW

**Comment by UdjinM6** [comment]
ok, I hope we don't miss anything else :)

utACK

**Comment by schinzelh** [comment]
I hear you :-)

**Comment by tgflynn** [comment]
Maybe it would be a good idea to create a checklist for what needs to change when checkpoints are updated, also for bumping the release version.

**Comment by crowning-** [comment]
utACK

**Pull request merged**
