### PR TITLE
backport: trivial 2024 06 04

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
Batch of trivial backports

## What was done?
Trivial backports

## How Has This Been Tested?
Built; haven't ran tests

## Breaking Changes
Didn't see any

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
tests failed, reverting/dropping 22817 (50e34fb) helps

**Comment by UdjinM6** [comment]
Hmm... Looks like `wallet_multisig_descriptor_psbt.py` is broken too. Drop 22067 (2ce0367) and 23303 (c5860fd) for now maybe?

**Review by PastaPastaPasta — COMMENTED** [review]
self-review utACK

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
