### PR TITLE
psclient: initialize base class in copy ctor

### PR DESCRIPTION
**Pull request by nmarley**
This addresses compiler warnings by explicitly initializing base class.

### CODE REVIEW

**Comment by gladcow** [comment]
Why we have the "dummy" copy constructor here instead of normal one? This class is used as vector element,  so we can have some errors that are really difficult to debug because of this.

**Comment by nmarley** [comment]
@gladcow I don't know, @UdjinM6 wrote that part. I'm just trying to fix compiler warnings right now, and this one is pretty loud b/c it's in several places in the build output.

**Comment by UdjinM6** [comment]
> I don't know, @UdjinM6 wrote that part

🙈

**Comment by nmarley** [comment]
Closing in favor of #2305

**Pull request closed without merging**
