### PR TITLE
Introduce SPORK_23_QUORUM_POSE

### PR DESCRIPTION
**Pull request by UdjinM6**
This splits SPORK_21_QUORUM_ALL_CONNECTED into two which should let us control node connectivity and quorum PoSe independently.

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
What quorums does PoSe work for if spork 23 is on?

**Comment by UdjinM6** [comment]
@PastaPastaPasta same rules as for `SPORK_21_QUORUM_ALL_CONNECTED`, see `EvalSpork`.

**Comment by PastaPastaPasta** [comment]
How does it work if Spork 23 is enabled, but spork 21(concentrated recovery) is disabled?

**Comment by UdjinM6** [comment]
@PastaPastaPasta I don't understand your question... what do you mean exactly?

**Comment by UdjinM6** [comment]
I mean, PoSe uses its own short living probe connections which have nothing to do with regular intra-quorum connections, if that was your question. It should work just fine with spork21 off.

**Comment by PastaPastaPasta** [comment]
> I mean, PoSe uses its own short living probe connections which have nothing to do with regular intra-quorum connections, if that was your question. It should work just fine with spork21 off.

This was my understanding, but wanted to clarify that and make sure

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
