### PR TITLE
QScrollBar Fix

### PR DESCRIPTION
**Pull request by snogcel**
Related to: https://github.com/darkcoin/darkcoin/pull/303

Very interesting bug here, didn't realize a trace was left behind even though the buttons themselves were styled away. This is an alternative fix that should theoretically kill the bug while keeping the current style intact

Tnx for the tag @crowning- :-)

### CODE REVIEW

**Comment by crowning-** [comment]
Morning :-)

You need to implement the same for the horizontal scrollbars. 

But I have a question: is it usability/styleguide wise allowed or preferable to have the scroll buttons removed?
Even Windows 8.1 still shows them...

**Comment by snogcel** [comment]
Evening :-)

Good call, completely forgot that the Command-line Options window used a horizontal scroll. Latest commit should cover that but...

You do raise a good point. These scroll bars were implemented before I put more elegant arrow icons elsewhere in the UI. I personally never use Scroll Buttons, but perhaps others do -- give me the weekend and I can whip together some nicer looking ones using the same arrows ;-)

**Comment by crowning-** [comment]
I've closed https://github.com/darkcoin/darkcoin/pull/303 ( my fork needs some cleanup anyway) , so feel free to go crazy with your arrows :-)

**Comment by snogcel** [comment]
Much nicer looking arrows now included in latest commit :-)

image

image

Tests out fine in Linux, and I would assume on Windows & Mac however I don't have the means to test on those platforms presently.

**Comment by crowning-** [comment]
I'll build and test it on Windows today after work and will report back.

**Comment by crowning-** [comment]
Doesn't build with Gitian....the new arrows are missing in the resources of the Qt-makefile.

I've fixed it and have created a pull-request in your repository, see https://github.com/snogcel/darkcoin/pull/1

Once this is included in your pull-request here I'll test again

**Comment by snogcel** [comment]
@crowning- tnx for having a look, your pull-request has been merged

**Comment by UdjinM6** [comment]
Compiles for me on Mac OS! :+1:

**Comment by crowning-** [comment]
Builds now with Gitian and looks on Windows as expected....good work :thumbsup:

@evan82 , it's ready to merge.

**Pull request merged**
