### PR TITLE
Remove spork 15, 16, 20

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
These sporks had no code usage. See https://github.com/dashpay/dash/blob/master/doc/release-notes.md#sporks which talks about these sporks being removed in a later version

### CODE REVIEW

**Comment by thephez** [comment]
@quantumexplorer @hashengineering Can you confirm that the mobile wallets are not using these spork values anymore (especially the IS-related ones)? I know in the past some "unused" sporks were kept around longer than Core needed them due to how the mobile wallets were using them.

**Comment by 10xcryptodev** [comment]
@PastaPastaPasta https://github.com/dashpay/dash/blob/master/doc/release-notes.md#sporks should be changed in this PR too?

**Comment by thephez** [comment]
> @PastaPastaPasta https://github.com/dashpay/dash/blob/master/doc/release-notes.md#sporks should be changed in this PR too?

Release notes are typically updated in a standalone PR shortly before releases (e.g. #3283).

**Comment by PastaPastaPasta** [comment]
I tagged this for 0.17, imo if you are 3 major versions behind that's on you. But if we want to support old versions when possible like this, we can close this PR

**Comment by UdjinM6** [comment]
Yep, it's kind of a common rule IMO that everything on p2p level since the last hard-fork should be backwards compatible, at least for regular nodes. No need to disrupt someones day-to-day operations when there is no serious reason to do so, especially given the fact that it might require updating some backend software to be compatible with rpc changes etc. And we won't save much by not relaying these 3 sporks, so IMO we have no reason to push people.

**Comment by UdjinM6** [comment]
I just checked sporks code while working on some other changes and it looks like we do NOT have anything that would prevent nodes from relaying unknown sporks! 🙈 Believe it or not, from `spork.cpp` history it looks like we never actually had it at all, we just check `nTimeSigned` and a sig and if everything is ok we relay it further. Which means that ALL nodes are aware of ALL sporks, they just don't understand some but they don't really care. I'm not sure where this shared confusion that sporks which are not in the list aren't relayed came from but we can actually drop sporks right when we drop the logic behind them, no need to wait for the next major release/hard-fork. Release notes were misleading it seems, this should be good to merge even in 0.16.

**Comment by HashEngineering** [comment]
The android app still depends on these sporks, but it looks like that the rest of the network will propagate them anyways, even if 0.16 doesn't send them out.  We will update the android app to no longer use 15, 16 and 20 and assume that they are ON.

**Pull request merged**
