### PR TITLE
Moves CMinerPolicyEstimator and CBlockAverage class definitions to header.

### PR DESCRIPTION
**Pull request by CryptoDJ**
Class definitions should not be in the implementation (.cpp) file.

### CODE REVIEW

**Comment by schinzelh** [comment]
close & reopen for CI test trigger

**Comment by schinzelh** [comment]
Regarding https://github.com/cryptodeveloper/dash/commit/1757e90cc73876c5c1216be045e853ca7738d7e0 : it seems the CMinerPolicyEstimator and CBlockAverage code is old and not used anyway. Bitcoin is removing this code with hhttps://github.com/bitcoin/bitcoin/commit/b649e0395464a659f4b3485ec71d28dc95ba48bd which got merged into Bitcoin 0.11.0

As we are going to merge Bitcoin 0.11.0 soon, I'd rather not mess around with this as it is creating more conflicts

**Comment by UdjinM6** [comment]
@schinzelh I agree, keeping in mind further upstream merges we'd better leave this part of a code untouched
@CryptoDJ thanks for your efforts anyway!

**Comment by CryptoDJ** [comment]
Makes sense.  Thanks

**Pull request closed without merging**
