### PR TITLE
Guix Build for Generalized ehf

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
 - _Why is this change required? What problem does it solve?_
 - _If it fixes an open issue, please link to the issue here._

## What was done?
  _Describe your changes in detail_

## How Has This Been Tested?
  _Please describe in detail how you tested your changes._

  _Include details of your testing environment, and the tests you ran
to see how your change affects other areas of the code, etc._

## Breaking Changes
  _Please describe any breaking changes your code introduces_

## Checklist:
  _Go over all the following points, and put an `x` in all the boxes that apply._
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has began to build this PR tagged as v20.1.0-devpr5857.f6be08ed. A new comment will be made when the image is pushed.

**Comment by DashCoreAutoGuix** [comment]
Guix Automation has completed; a release should be present here: https://github.com/dashpay/dash-dev-branches/releases/tag/v20.1.0-devpr5857.f6be08ed. The image should be on dockerhub soon.

**Comment by knst** [comment]
New devnet paulaner.
Before activation EHF spork:
```
getblockchaininfo:
    "v20": {
      "type": "bip9",
      "bip9": {
        "status": "active",
        "start_time": 1661990400,
        "timeout": 9223372036854775807,
        "ehf": false,
        "since": 360
      },
      "height": 360,
      "active": true
    },
    "mn_rr": {
      "type": "bip9",
      "bip9": {
        "status": "defined",
        "start_time": 1661990400,
        "timeout": 9223372036854775807,
        "ehf": true,
        "since": 0
      },
      "active": false
    }
sporks:
  "SPORK_24_TEST_EHF": 4070908800
```

**Comment by knst** [comment]
`SPORK_24_TEST_EHF` has been activated:
```
getblockchaininfo:
    "mn_rr": {
      "type": "bip9",
      "bip9": {
        "status": "started",
        "bit": 10,
        "start_time": 1661990400,
        "timeout": 9223372036854775807,
        "ehf": true,
        "ehf_height": 5865,
        "since": 5880,
        "statistics": {
          "period": 120,
          "threshold": 80,
          "elapsed": 5,
          "count": 5,
          "possible": true
        }
      },
      "active": false
```
EHF signal is generated, signed, submitted in mempool and mined:
```
dash-cli getblockhash 5865
0000004f3dca3fb168238f03d9581bb42b34af78cfa35246144991f5b9ed944c
```

```
getrawtransaction 30a3bb7304a3cffafd70fb07f5d3dee95db37e7b0209a8a5598ffe927e4b68f8
0300070000000000000082010a57d4bad3e0b054ad2b465e40fc7e5175adb0e7fdac6736d2f77a69acd40000008e4a6a1112c38d3bb95ebc8057ea2c97aa3dee27e7685fc98553e13239e9cbbd6d64d6455046c534348e3374eedd12080176c179d88e0d5399df9343ec8275770707406c3baff429a1c03747a9026eaea3a2bae8bdfcb50b9fdc2184ac662d7c
```

some relevant logs:
```
CEHFSignalsHandler::HandleNewRecoveredSig Special EHF TX is created hash=30a3bb7304a3cffafd70fb07f5d3dee95db37e7b0209a8a5598ffe927e4b68f8
```
and
```
2024-02-16T07:44:43Z IsValidMNActivation: set MnEHF for bit=10 is valid
2024-02-16T07:44:43Z IsValidMNActivation: set MnEHF for bit=10 is valid
2024-02-16T07:44:43Z CEHFSignalsHandler::HandleNewRecoveredSig Special EHF TX is created hash=30a3bb7304a3cffafd70fb07f5d3dee95db37e7b0209a8a5598ffe927e4b68f8
2024-02-16T07:44:43Z CEHFSignalsHandler::HandleNewRecoveredSig -- AcceptToMemoryPool failed: txn-already-in-mempool
2024-02-16T07:50:16Z IsValidMNActivation: set MnEHF for bit=10 is valid
...
2024-02-16T07:50:16Z IsValidMNActivation: set MnEHF for bit=10 is valid
2024-02-16T07:50:16Z CMNHFManager::ProcessBlock: add mnhf bit=10 block:0000004f3dca3fb168238f03d9581bb42b34af78cfa35246144991f5b9ed944c number of known signals:0
2024-02-16T07:50:16Z IsValidMNActivation: set MnEHF for bit=10 is valid
2024-02-16T07:50:16Z IsValidMNActivation: set MnEHF for bit=10 is valid
```

So far so good; waiting MN_rr be activated

**Comment by knst** [comment]
```
    "mn_rr": {
      "type": "bip9",
      "bip9": {
        "status": "locked_in",
        "start_time": 1661990400,
        "timeout": 9223372036854775807,
        "ehf": true,
        "ehf_height": 5865,
        "since": 6000,
        "activation_height": 6120
      },
      "active": false
    }
```

`mn_rr` is locked_in, expecting activation in ~100 blocks from now

**Comment by knst** [comment]
somewhere at block 6157:
```
    "mn_rr": {
      "type": "bip9",
      "bip9": {
        "status": "active",
        "start_time": 1661990400,
        "timeout": 9223372036854775807,
        "ehf": true,
        "ehf_height": 5865,
        "since": 6120
      },
      "height": 6120,
      "active": true
    }
```

mn_rr is activated since 6120
at this height:
```
  "cbTx": {
    "version": 3,
    "height": 6159,
    "merkleRootMNList": "9fc484bcce468ec725047c702fe2d4dd3e70e305d3a9537740a80e4d2f42ea1c",
    "merkleRootQuorums": "2c4cd9ad74b0c0f11a12b6c6f89c4391172f7af5d611ddcadf9cad4037c63cc7",
    "bestCLHeightDiff": 0,
    "bestCLSignature": "a28a12537170df3ac32da6778a3442f71b8be3ebe02474c8e8093b0807104ed223efb782b0884d3bd9121021e2ff62e407bbf2299bfcda29c0f69a5185a815e4ec2a4c73422677dba44226d4434420ddf41f8392e46e6332d173ce063f12294c",
    "creditPoolBalance": 45.00000000
  },
```

40 blocks * 1.125 = 45 dash in creditPoolBalance.

So far so good, changes from https://github.com/dashpay/dash/pull/5824 seems working as expected

**Comment by knst** [comment]
Continue in https://github.com/dashpay/dash/pull/5824

**Pull request closed without merging**
