### PR TITLE
Suppress Warning

### PR DESCRIPTION
**Pull request by Duality-CDOO**

### CODE REVIEW

**Comment by Duality-CDOO** [comment]
If that is the case then you can close it and it can be upstreamed instead. I just keep seeing the warning and thought it best to nutrilise it whilst it was in the forefront of my mind.

**Comment by UdjinM6** [comment]
Since this is only a tiny part of a much bigger and focused commit ("Minimal code changes to allow msvc compilation"), I would avoid merging this to avoid conflicts/confusion in the future. But thanks for looking into it anyway!

**Comment by Duality-CDOO** [comment]
No problem. I will let you guys do what you want with this PR, close or earmark it for later.

**Comment by UdjinM6** [comment]
Ok, closing in fav of the backporting the original PR in full sometime in the future either as a separate one or as a part of a larger/general upstream backport (e.g. to align with btc 0.16+).

**Pull request closed without merging**
