### PR TITLE
revert #3036, #2911, #1879, #1432: revert dashification of filenames

### PR DESCRIPTION
**Pull request by kittywhiskers**
## Why?

As we're planning to support multiple build systems, remaining inline with their origin projects are a priority and surface-level filename rebranding serves as a quick and easy way to cause merge conflicts. We aim to remedy that. **No logic or user-visible strings have been changed (outside of documentation)**

Some filenames in the codebase will have the Dash branding, others don't. Only sources file that have a tendency to undergo change or are used by files that tend to undergo change were considered for the revert

## Why not?

We now have an inconsistent naming scheme, despite being named `bitcoinconsensus`, it will still output the `libdashconsensus` library

### CODE REVIEW

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge assuming it passes CI

**Review by PastaPastaPasta — DISMISSED** [review]
re-utACK

**Comment by UdjinM6** [comment]
> We now have an inconsistent naming scheme, ...

yeah... not sure I like it

> despite being named bitcoinconsensus, it will still output the libdashconsensus library

this exact example is 1. not true and 2. it's a shared lib which is a bit more complex case, see dbc0474634

also, see few trivial fixes a9b9c2d209

**Comment by UdjinM6** [comment]
pls rebase to include #4957

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
