### PR TITLE
qt: More asset cleanup

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by xdustinface** [comment]
What exactly is 2b62e90b5d87056c07bb58a4cb95ca07fd0cf98f doing?

**Comment by UdjinM6** [comment]
@xdustinface https://github.com/dashpay/dash/pull/1688

**Review by xdustinface — APPROVED** [review]
ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
