### PR TITLE
locks: Only lock mempool.cs when needed in cleanup

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
"potential deadlock" https://gitlab.com/dashpay/dash/-/jobs/1031617457#L63

**Comment by UdjinM6** [comment]
You could _probably_ do smth like https://github.com/UdjinM6/dash/commit/579624f964a80cd9c4942af6203430f4ea3d3b89?w=1 instead _if_ holding `cs`/`cs_main` locks the whole time isn't really required here (should be fine imo but I'm not 100% sure).

**Comment by PastaPastaPasta** [comment]
Why'd you move `lastCleanupTime = GetTimeMillis();`?

**Comment by UdjinM6** [comment]
Because when `cs` was held the whole time there was no way for another thread to go past this part. With `cs` not being held `lastCleanupTime` should be updated asap (it acts kind of as a locking mechanism itself here). Could use a `static bool` (running = true/false) instead of moving `lastCleanupTime`, would probably be a cleaner solution indeed.

**Comment by xdustinface** [comment]
Wouldn't it just make sense to just leave it as it is because this locking anyway only runs once every 30 seconds?

**Pull request closed without merging**
