### PR TITLE
Reorganize Dash Specific code into folders

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
creates privatesend folder for all privatesend related files, governance folder, and masternode folder respectively. Adjusts old code into the kindof modern standard, see evo folder, bls folder, etc. Additionally, renamed instantx files to instantsend

### CODE REVIEW

**Comment by codablock** [comment]
What about one common subfolder for all dash specific stuff, with subfolders for the specific subsystems? So it would be `src/dash/llmq/*.h/.cpp` for example.

**Comment by UdjinM6** [comment]
@codablock I think it would make sense if there would be no/less injections of Dash-specific code in other modules but since it's not the case the way it's done in this PR atm is ok-ish IMO.

**Comment by UdjinM6** [comment]
Needs rebase.

**Comment by PastaPastaPasta** [comment]
rebased

**Comment by PastaPastaPasta** [comment]
rebased

**Comment by UdjinM6** [comment]
`No rule to make target 'privatesend.h'` - missed few lines on `Makefile.am` it seems

**Comment by UdjinM6** [comment]
```
llmq/quorums.cpp:18:10: fatal error: masternode-sync.h: No such file or directory
 #include "masternode-sync.h"
```
https://travis-ci.org/dashpay/dash/jobs/532932722#L2371

**Comment by PastaPastaPasta** [comment]
Building locally, passing tests with flying colors

**Pull request merged**
