### PR TITLE
[PrivateSend] Performance tweak for MN-exclusion list

### PR DESCRIPTION
**Pull request by crowning-**
I think it's inefficient to build a vector with ALL Masternodes, shuffle them and then loop over all to find one not in the exclusion vector.

My change builds a vector with all not-excluded Masternodes and shuffles that vector  instead.
When there's lots of Masternodes and lots of excluded Masternodes this is much more efficient because that vector is much smaller.

Not a dramatic improvement, but IMO one worth trying.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Well, I'm not that much convinced tbh. 

shuffle
```
template <class RandomAccessIterator, class RandomNumberGenerator>
  void random_shuffle (RandomAccessIterator first, RandomAccessIterator last,
                       RandomNumberGenerator& gen)
{
  iterator_traits<RandomAccessIterator>::difference_type i, n;
  n = (last-first);
  for (i=n-1; i>0; --i) {
    swap (first[i],first[gen(i+1)]);
  }
}
```

x - number of entries to exclude
y - number of masternodes

Current code:
1. loop to fill vector (1..y)
2. shuffle (y)
3. loop through (1..y)
3.1 inner loop (1..x)
3.2. not found in excluded? **return**
i.e. in the worst case scenario when every first x masternodes match elements of vecToExclude it means that we break on every of 1..x step from inner loop and after doing (x+1)th step of outer loop we should be 100% able to return the answer. Which gives us this:
`loop(y) + shuffle(y) + loop( (1+x+1)*(x+1)/2 )`

Your code:
1. loop (1..y)
1.1. inner loop (1..x)
1.2 not found in excluded? add
2. shuffle (y - x) and **return**
i.e. no matter how elements and masternodes are sorted it's the same loop with the same kind of break as above but after x steps of outer loop you need to finish it, so it's another (y-x) steps of outer loop each x steps long + shuffle. Which gives us this:
`loop( (1+x)*x/2 + (y-x)*x ) + shuffle(y-x)`

Even though there is one more loop in current code, we exit early (right after first candidate was found) while in you code you have to continue and keep looping in that double loop till the end.

Say we have 4000 masternodes, we need to exclude 100 of them and we are extremely unlucky (first 100 masternodes match elements of vecToExclude):
- loop(4000) + shuffle(4000) + loop((1+100+1)*(100+1)/2 == 5 151)
- loop(((1+100)*100/2 == 5 050 + (4000-100)*100) == 395 050) + shuffle(3900)
So it's 13k vs 399k cycles even when it's the worst case for current code.

But let's take this to extreme. We keep vecMasternodesUsed at 90% max of masternode count, so say it's completely full and we need to exclude 4000*0.9=3600 and we are extremely unlucky again (first 3600 masternodes match elements of vecToExclude). You can do the math but it's ~6.5m vs ~7.92m cycles.

So, unless I'm missing smth in code or math above, I doubt that there is any improvement in this. Not to mention that we still should have pretty good chances to find the first one on avg a bit quicker than for the worst case scenario I used in examples above.

**Comment by tgflynn** [comment]
How much effect does the runtime of this code have on that of the overall mixing process ?

It can certainly be made much more efficient.

**Comment by UdjinM6** [comment]
Not sure if it slows down that much and I doubt anyone have mixed to that kind of numbers. One simple improvement that can be made is basically limit vecMasternodesUsed by some large enough number in addition to existing "90% of vMasternodes" limit. 1000 Masternodes as a max would be enough imo.

**Comment by tgflynn** [comment]
I can submit a PR that should speed it up just by using more efficient data structures but testing is problematic.  I don't have much experience with private send and when I try to use it seems to remain stuck at 20% for a long time, even now that we have a number of 70202 masternodes.

**Comment by UdjinM6** [comment]
Reviewing this gave me an idea how to easily optimize current code, see #1056 :)

**Comment by tgflynn** [comment]
#1057 should speed up FindRandomNotInVec by up to 100x when the number of MN's to exclude is large.  (log2(1000) ~ 10).

Unfortunately I'm unable to test this because PS is staying stuck for me at 20%, with or without this change.

**Comment by UdjinM6** [comment]
@tgflynn heh, nice :)

**Comment by crowning-** [comment]
Even when this is obsolete now (thanks @tgflynn :thumbsup:), because I couldn't find a reliable source how std::random_shuffle _really_ performs I just measured both versions and plotted the result:
findrandomnotinvec

It's a factor of about 2, fortunately it grows linear and not quadratic as I have feared before my tests.

I'll test Tim's implementation and close this PR later.

**Comment by tgflynn** [comment]
Interesting chart but I don't understand how FindRandomNotInVec can get faster when the number of excluded masternodes increases.

**Comment by tgflynn** [comment]
I guess it must be because the shuffling time dominates, so your version is faster for a large enough exclusion vector.  It would be interesting to see the results for your version using a set instead of the vector.

**Comment by tgflynn** [comment]
If the runtime's dominated by shuffle then using a set probably won't help very much.  I'm not sure why that's the case since shuffle should be O(n).  I wonder if it's the random number generation that's slow.

**Comment by crowning-** [comment]
Yep, the shuffling performance was (at least for me) the big question and I only found imprecise (sometimes even contradicting) information. Maybe it depends on the underlying OS/compiler implementation. 

> It would be interesting to see the results for your version using a set instead of the vector.

That's what I'm doing right now :-)
I'll let it run over night and report back tomorrow.

Depending on the result I'll
> ... I wonder if it's the random number generation that's slow.

do some investigations here.

It's not really THAT important, but I'm curious now...

**Comment by UdjinM6** [comment]
@crowning- wow, that's really surprising. 👍

**Comment by crowning-** [comment]
@tgflynn , your assumption was spot on!

1. FindRandomNotInSet shows the exact same behavior:
findrandomnotinset-getrandint

2. Curious cat that I am I replaced the random number generator `GetRandInt` with the standard `rand()` call. Not only is it 10x faster, but as you predicted the duration goes (slightly, not visible in this overview graph) down for increasing numbers of excludes nodes:
findrandomnotinset-rand


Conclusion: for a `std::random_shuffle` with slow random number generator my algorithm is faster, with a faster random number generator the original algorithm, especially when used with a set instead of a vector, is faster. And the random number generator makes the biggest difference.

I think for our purpose (we're not encrypting stuff here) using rand() is the way to go.

**Comment by tgflynn** [comment]
@crowning- There appears to be a discrepancy between your results and @UdjinM6's with the default PRNG.  Can you explain how you made your measurements ?  Thanks.

**Comment by crowning-** [comment]
Sure:
```
CMasternode *CMasternodeMan::FindRandomNotInVec(std::vector<CTxIn> &vecToExclude, int nProtocolVersion)
{
    LOCK(cs);

    nProtocolVersion = nProtocolVersion == -1 ? mnpayments.GetMinMasternodePaymentsProto() : nProtocolVersion;

    int nCountEnabled = CountEnabled(nProtocolVersion);
    int nCountNotExcluded = nCountEnabled - vecToExclude.size();

    LogPrintf("CMasternodeMan::FindRandomNotInVec -- %d enabled masternodes, %d masternodes aren't yet exluded\n", nCountEnabled, nCountNotExcluded);
    if(nCountNotExcluded < 1) return NULL;

    // fill a vector of pointers
    std::vector<CMasternode*> vpMasternodesShuffled;
    std::vector<CMasternode*> vpMasternodesShuffled1;
    bool fExclude;

    // Quick'n'Dirty performance measurement
    boost::chrono::duration<double> duration_new;
    boost::chrono::duration<double> duration_old;
    boost::chrono::high_resolution_clock::time_point start = boost::chrono::steady_clock::now();
    boost::chrono::high_resolution_clock::time_point end = start;

    BOOST_FOREACH(CMasternode &mn, vMasternodes) {

        if(mn.nProtocolVersion < nProtocolVersion || !mn.IsEnabled()) continue;
        fExclude = false;
        BOOST_FOREACH(CTxIn &txinToExclude, vecToExclude) {
            if(mn.vin.prevout == txinToExclude.prevout) {
                fExclude = true;
                break;
            }
        }
        // Not in the exclude list -> add it 
        if(!fExclude)
            vpMasternodesShuffled1.push_back(&mn);
    }

    if(vpMasternodesShuffled1.size() > 0){
        // Shuffle the resulting vector of Masternodes
        std::random_shuffle(vpMasternodesShuffled1.begin(), vpMasternodesShuffled1.end(), GetRandInt);

        // If we have non-excluded Masternodes, return the first one from the vector
        // The shuffling guarantees that it's a random one
 //       return vpMasternodesShuffled1.front();

        end = boost::chrono::high_resolution_clock::now();
        duration_new = end - start;
    }

    start = boost::chrono::high_resolution_clock::now();
    end = start;

    BOOST_FOREACH(CMasternode &mn, vMasternodes) {
        vpMasternodesShuffled.push_back(&mn);
    }

    // shuffle pointers
    std::random_shuffle(vpMasternodesShuffled.begin(), vpMasternodesShuffled.end(), GetRandInt);


    // loop through
    BOOST_FOREACH(CMasternode* pmn, vpMasternodesShuffled) {
        if(pmn->nProtocolVersion < nProtocolVersion || !pmn->IsEnabled()) continue;
        fExclude = false;
        BOOST_FOREACH(CTxIn &txinToExclude, vecToExclude) {
            if(pmn->vin.prevout == txinToExclude.prevout) {
                fExclude = true;
                break;
            }
        }
        if(fExclude) continue;
        // found the one not in vecToExclude
        LogPrint("masternode", "CMasternodeMan::FindRandomNotInVec -- found, masternode=%s\n", pmn->vin.prevout.ToStringShort());
        // end = boost::chrono::system_clock::now();
        end = boost::chrono::high_resolution_clock::now();
        duration_old = end - start;
        printf("Duration Old: %f sec | New: %f sec | Diff(old-new): %f sec | Masternodes: %ld (Excluded: %ld)\n", 
                duration_old.count(), duration_new.count(), duration_old.count() - duration_new.count(), vMasternodes.size(), vecToExclude.size());
        return pmn;
    }

    LogPrint("masternode", "CMasternodeMan::FindRandomNotInVec -- failed\n");
    return NULL;
}
```

The only difference to the 'real' code is that I disabled the return statement for the first one to get a measurement of the second one.

**Comment by crowning-** [comment]
BTW, I'm running my original test (code from above) with a v0.12.0.59 client on main-net right now and the numbers seem indeed   go more into the direction @UdjinM6 's result, albeit after about 20 iterations (thus 20 excluded nodes) it's to early to draw conclusions.

This obviously shows that other (more critical changes) should always be tested in both networks.

**Comment by UdjinM6** [comment]
@crowning- see patch in https://github.com/dashpay/dash/pull/1057#issuecomment-250956463 - there is also a piece of code to get this vector filled quickly without actual mixing.

**Comment by crowning-** [comment]
So, I've let it run on main-net until about 450 excluded nodes were reached, and indeed the graph for main-net is quite different (same sourcecode as posted above):
findrandomnotinvec-getrandint-mainnet

Obviously the number of nodes on testnet is too low for significant measurements.
If nothing else, we've learned this at least.

Shall I close this PR or do we test some more things?

**Comment by UdjinM6** [comment]
Thanks for testing 👍 As I mentioned in https://github.com/dashpay/dash/pull/1057#issuecomment-250956463 turned out that this implementation is way too slow and your new benchmark is proving that too. I'm not sure about #1057 either since we are talking about improvement most of which comes from using faster rand rather then faster/additional data structures (i.e. using such data structures makes almost no difference but instead it slightly complicates things). Anyway, let's continue discussion there from now.

**Pull request closed without merging**
