### PR TITLE
bug: should use txidCollateral to calculate confirmations

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by UdjinM6** [comment]
note: all Travis jobs failed because of mismatching (?) dependencies, build should not fail because of the code changes

**Comment by schinzelh** [comment]
Yeah, it's related to the Travis changes they did a month ago - I guess we'll need to backport #1133

**Comment by schinzelh** [comment]
Restarting the builds, seems to work now

**Comment by schinzelh** [comment]
Turned out it was deprecated download paths, fixed with https://github.com/dashpay/dash/pull/1219

**Comment by UdjinM6** [comment]
rebased to make sure only win64 fails as in #1219

**Comment by schinzelh** [comment]
The failing Win64 may be related to https://github.com/bitcoin/bitcoin/pull/7891

**Comment by UdjinM6** [comment]
rebased on top of #1220 , waiting for travis...

**Pull request merged**
