### PR TITLE
trivial: remove unneeded lock

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Signed-off-by: pasta <pasta@dashboost.org>

### CODE REVIEW

**Comment by xdustinface** [comment]
Seems like #4016 is taking care of this already?

**Comment by PastaPastaPasta** [comment]
There's no presumption in my mind that #4016 is going to get merged. It may be a good while if it does get merged. Might as well just merge this PR and we'll see what happens with 4016 in the next while

**Review by UdjinM6 — APPROVED** [review]
utACK

I don't mind merging this and rebasing #4016 (it's still a draft anyway)

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
