### PR TITLE
backport: bitcoin#18867, #19247, #19222, #18363, #18190, #18393, partial #18047, #18314, #19143 (fuzzing harness backports: part 3)

### PR DESCRIPTION
**Pull request by kittywhiskers**
### Depends on

* https://github.com/dashpay/dash/pull/4829

### CODE REVIEW

**Review by PastaPastaPasta — DISMISSED** [review]
utACK for merging via merge commit
utACK for merging via merge commit

**Comment by thephez** [comment]
> utACK for merging via merge commit utACK for merging via merge commit

@PastaPastaPasta Thanks for reviewing. Your response was a little vague though. My only question is, could you let us know if you will utACK this for merging via a merge commit? :trollface:

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Can't compile:
```
In file included from test/fuzz/addition_overflow.cpp:7:
./test/fuzz/util.h:265:13: error: no matching function for call to 'AdditionOverflow'
        if (AdditionOverflow((uint64_t)fuzzed_file->m_offset, random_bytes.size())) {
            ^~~~~~~~~~~~~~~~
./test/fuzz/util.h:131:20: note: candidate template ignored: deduced conflicting types for parameter 'T' ('unsigned long long' vs. 'unsigned long')
[[nodiscard]] bool AdditionOverflow(const T i, const T j) noexcept
                   ^
./test/fuzz/util.h:276:13: error: no matching function for call to 'AdditionOverflow'
        if (AdditionOverflow(fuzzed_file->m_offset, n)) {
            ^~~~~~~~~~~~~~~~
./test/fuzz/util.h:131:20: note: candidate template ignored: deduced conflicting types for parameter 'T' ('long long' vs. 'long')
[[nodiscard]] bool AdditionOverflow(const T i, const T j) noexcept
                   ^
2 errors generated.
```
dropping 60aa00a590 helps

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
