### PR TITLE
Fix PS/IS/Balance display in SendCoinsDialog

### PR DESCRIPTION
**Pull request by spencerlievens**
screen shot 2017-11-29 at 15 13 06

Did the same in Dynamic. See the example above.

### CODE REVIEW

**Comment by UdjinM6** [comment]
???

Mind sharing screenshots before/after pls?

**Comment by spencerlievens** [comment]
OK, let me build Dash as it stands, grab a screenshot, then I will build with my changes and provide both screenshots.

**Comment by spencerlievens** [comment]
**Before**
screen shot 2017-11-29 at 15 54 57

**After
screen shot 2017-11-29 at 15 54 10
**

**Comment by UdjinM6** [comment]
Thanks! That's interesting... How to reproduce the issue? What OS/resolution is this?

**Comment by UdjinM6** [comment]
Ah, I see.. it's traditional GUI scheme....

**Comment by UdjinM6** [comment]
Pushed a much simpler patch (da547b9) to #1741 . I'd prefer to keep `.ui` untouched and fix GUI formatting via `.css`.

**Comment by spencerlievens** [comment]
https://github.com/dashpay/dash/pull/1158/files 

Looks like I already fixed it before, I just didn't see the traditional theme issues at the time.

@UdjinM6 :P

**Pull request closed without merging**
