### PR TITLE
fix: Faster feature_llmq_rotation.py + introduction of llmq_devnet_dip0024

### PR DESCRIPTION
**Pull request by ogabrielides**
This PR includes:

- Introduction of new llmq_type: `llmq_devnet_dip0024` similar to `llmq_devnet`. The reason is because  deployments on small devnets are done with `llmqinstantsenddip0024=llmq_devnet` thus the value of `keepOldConnections` is not aligned with rotation logic (`2 x signingActiveQuorumCount`)
- Faster `feature_llmq_rotation.py` test by reducing the number of masternodes and by removing one cycle (~40% faster on my machine)

### CODE REVIEW

**Review by UdjinM6 — DISMISSED** [review]
nit: You could probably call it `LLMQ_DEVNET_DIP0024` to be more self-describing (and match `LLMQ_TEST_DIP0024` we have for regtest).

utACK

**Comment by ogabrielides** [comment]
@UdjinM6 Updated to llmq_devnet_dip0024 + adjusted parameters for smaller devnets.

**Review by UdjinM6 — DISMISSED** [review]
utACK

**Comment by UdjinM6** [comment]
@ogabrielides pls rebase and tweak `llmq_devnet_dip0024` to have
```
        .useRotation = true,
```
and
```
        .dkgMiningWindowStart = 12, // signingActiveQuorumCount + dkgPhaseBlocks * 5 = after finalization
        .dkgMiningWindowEnd = 20,
```

**Comment by UdjinM6** [comment]
Also, let's maybe split this PR into 2: 1. introduction of `LLMQ_DEVNET_DIP0024` (this one, v18, `backport-candidate-18.x`) and 2. faster `feature_llmq_rotation.py` (new PR, v18.1)?

**Comment by ogabrielides** [comment]
@UdjinM6 If on testnet at least one block with nVersion commitment was mined then we must not change mining window for rotation.
As in RC6, quorumCycleMiningStartHeight = quorumCycleStartHeight + 5 x dkgPhaseBlocks + 1.
So basically we need to add + 1 in all dkgMiningWindowStart of rotated llmqTypes

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Comment by UdjinM6** [comment]
> @UdjinM6 If on testnet at least one block with nVersion 2 commitment was mined then we must not change mining window for rotation. As in RC6, quorumCycleMiningStartHeight = quorumCycleStartHeight + 5 x dkgPhaseBlocks + 1. So basically I added + 1 in all dkgMiningWindowStart of rotated llmqTypes

Hmm, dip0024 is not active on testnet yet. And even if it would be active I'd rather fork testnet instead of introducing an arbitrary off-by-one in llmq params and bringing this to mainnet.

**Comment by ogabrielides** [comment]
@UdjinM6 All right you convinced me :). Re-adjusted the params

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
