### PR TITLE
feat(rpc): masternode status and count RPCs adjusted for HPMNs

### PR DESCRIPTION
**Pull request by ogabrielides**
## What was done?

-  `masternode status` now returns the type as well
-  `masternode count` now returns in addition total and total enabled MNs per type.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by thephez — COMMENTED** [review]
Concept ACK

**Comment by ogabrielides** [comment]
@PastaPastaPasta @UdjinM6 Enriched `feature_llmq_hpmn.py`.
\Pasta mode on
dandy!
\Pasta mode off

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge. I love when I don't even have to ask for tests 😀

**Comment by thephez** [comment]
> utACK for squash merge. I love when I don't even have to ask for tests grinning

You could just make a new GH action to do it for you :smile:

**Pull request merged**
