### PR TITLE
Deprecate masternodeaddr

### PR DESCRIPTION
**Pull request by UdjinM6**
i.e. remove dash.conf-started remote masternode support

### CODE REVIEW

**Comment by schinzelh** [comment]
@crowning- masternode.conf is deployed on control wallet only usually, so I see no reason to remove masternodeprivkey.

**Comment by crowning-** [comment]
@schinzelh my v0.12.1.x Masternode on testnet (dashd-only) still has the example masternode.conf deployed. Will this change in the future?

**Comment by UdjinM6** [comment]
Empty masternode.conf is always generated if there is none but I would avoid using it for hot masternode. Basically in any setup:
"hot" wallet/masternode == `dash.conf` + `masternode=1` + `masternodeprivkey=<asdasdadad>`
"cold" wallet/control node == `masternode.conf`

**Comment by schinzelh** [comment]
Yep, that's my default setup for hosting.

Hosted node has dash.conf parameters while I send masternode.conf to the customer. Node40 does the same.

**Pull request merged**
