### PR TITLE
backport: bitcoin#23723, 23547, 24153, 23591

### PR DESCRIPTION
**Pull request by vijaydasmp**
backporting

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6, requesting review

**Comment by UdjinM6** [comment]
re 23002 "Make descriptor wallets by default": Do we have everything prepared for this @knst?

**Comment by knst** [comment]
> re 23002 "Make descriptor wallets by default": Do we have everything prepared for this @knst?

Basically, everything is ready https://github.com/dashpay/dash-issues/issues/59 except mnemonics for descriptor wallets, which is quite important IMO.

**But, we should not merge 23002 yet, because that's a breaking changes, at least not before v22 is branched-out.**

Also, there's couple useful follow-ups must be done:
 - remove "experimental" hint from Qt's interface
 - remove the extra requirement for `load_on_startup` flagfrom `createwallet` rpc, which has been introduced due to RPCinterface changes (see https://github.com/dashpay/dash/pull/6095)

@vijaydasmp could you exclude 23002 from this PR, please?

**Comment by vijaydasmp** [comment]
Sure

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 @knst , dropped 23002

**Review by UdjinM6 — APPROVED** [review]
utACK 073d6d6b2a6eb2741fe461884574c671858e6cda

**Review by knst — APPROVED** [review]
utACK 073d6d6b2a6eb2741fe461884574c671858e6cda

**Pull request merged**
