### PR TITLE
port RPC credentials script from Bitcoin

### PR DESCRIPTION
**Pull request by charlesrocket**
Current script is broken (parsing conflicts?), it's useful for k8/docker/etc env to get it fixed.

### CODE REVIEW

**Comment by UdjinM6** [comment]
What do you mean by "broken"? What's the issue exactly?

**Comment by charlesrocket** [comment]
@UdjinM6 can't get it working in homebrew. im writing new formulae since i've lost some data i had along #2464, plus need to add new dependencies for evo. would it make a difference if i post logs from 0.12.3 base?

**Comment by UdjinM6** [comment]
Last changes to `rpcuser.py` were made mid 2018, so I guess logs for `0.12.3.x` branch should be ok.

**Comment by charlesrocket** [comment]
@UdjinM6 homebrew moved to Azure env after #2464, now need to figure out the way with travis. But have a feeling I'm almost there https://github.com/charlesrocket/homebrew-dash

**Comment by UdjinM6** [comment]
Hmm, ok. Well, I don't see how failures in your build might be connected to rpcuser/rpcauth tbh, feels more like c++11 requirement isn't met.

Also, pls note that stable (`master`) is now 0.13.1 and we actually build dependencies like qt/boost/etc. instead of installing them, so you have to specify correct prefix in `./configure`. See https://github.com/dashpay/dash/blob/master/doc/build-generic.md for more info.

**Comment by charlesrocket** [comment]
@UdjinM6 That is not the output I am looking for yet, current build fails are due switch to Azure, I'm figuring out the approach with travis at the moment.

**Pull request closed without merging**
