### PR TITLE
Merge bitcoin/0.12 + few fixes

### PR DESCRIPTION
**Pull request by UdjinM6**
“why?” https://github.com/bitcoin/bitcoin/blob/0.12/doc/release-notes.md#notable-changes

What's inside:
- Merge all commits from remote-tracking branch 'bitcoin/0.12' and refactor code to match new structures/functions/arguments
- Refactor keepass to use evhttp (need testing)
- Move most hardcoded mainnet/testnet magic numbers to consensus part of chainparams, get rid of most `if(Params().NetworkIDString() == CBaseChainParams::MAIN)` and alike to unify formulas. Further improvements will require testnet restart (see TODO notes in changed code) so I'm keeping few things as they are till then.
- There is no more `AcceptableInputs`, `AcceptToMemoryPool`/`AcceptToMemoryPoolWorker` have `fDryRun` parameter instead
- Fix `consensus.nSubsidyHalvingInterval` (210000 -> 210240)
- Replace hardcoded 9999 with `Params(CBaseChainParams::MAIN).GetDefaultPort()`
- Replace all hardcoded network message strings with `NetMsgType::` constants, log unknown commands (`net` debug category only)
- UI fixes:
 - Refactor tools menu signals/slots, add more keyboard shortcuts
 - Refactor sync progress to use signals, remove lock from masternode count label updates
 - Fix icons in tx list to preserve our ui styles, fix about/cmd-line help dialog
 - Get rid of the new warning icon and use old text label instead
 - Update overview screen ds rounds/amount/progress when settings changed (we were already sending signals but connectors in overview screen were missing)
- Quick fix for testnet - we reeeeally should restart it one day, it’s broken (see https://github.com/UdjinM6/dash/commit/29b1af2bb1bbdc3aa88de8f5016c2dcedd677fc7 and TODO in https://github.com/UdjinM6/dash/commit/e8d9aabb62c17625bbf146151d7a93a0ffde33f5)
- Add note about `GetBlockSubsidy` using previous height, changed var names accordingly
- Add few more debug messages for `masternode` category
- Move historical bitcoin release notes to appropriate subfolder

Few notes/todos:
- RBF is set to `false` by default (shall we remove RBF completely?)
- I can’t compile on linux without `--disable-hardening` yet, it complains about x11 crypto (but as a side effect of `--disable-hardening` (?) - ubuntu recognize dash-qt as an executable again so maybe we should consider this as a default option?)
- new keepass integration code need to be tested
- gitian build is probably broken too, haven’t tested yet
- release notes should be updated

### CODE REVIEW

**Comment by schinzelh** [comment]
Many thanks, I'll do some local build tests first to see if gitian/travis broke.

**Comment by evan82** [comment]
Yay, thanks!

**Comment by schinzelh** [comment]
@UdjinM6 i have fixed the issue with --disable-hardening: x11 crypto was compiled without fPIC support, which made Dash client linking fail.

I've commited the fix to 12.1 branch - can you retest on your side as well?

**Comment by UdjinM6** [comment]
@schinzelh Bingo! :+1:

**Comment by schinzelh** [comment]
Gitian/Bamboo almost working again, only Windows build has i minor issue

`/usr/bin/x86_64-w64-mingw32-windres -DWINDRES_PREPROC -i qt/res/dash-qt-res.rc -o qt/res/dash-qt-res.o
/usr/bin/x86_64-w64-mingw32-windres: can't open icon file `icons/bitcoin.ico': No such file or directory
/usr/bin/x86_64-w64-mingw32-windres: preprocessing failed.
make[2]: *** [qt/res/dash-qt-res.o] Error 1
make[2]: Leaving directory `/home/travis/build/dashpay/dash/dash-x86_64-w64-mingw32/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/dashpay/dash/dash-x86_64-w64-mingw32/src'
make: *** [all-recursive] Error 1
`

**Comment by thelazier** [comment]
Hope #700 help solving minor issue.

**Comment by schinzelh** [comment]
@thelazier thanks, that solved it, gitian builds working now again.

Travis is still failing due to some broken unittests, needs some more work.

**Pull request merged**
