### PR TITLE
Remove assertion from ~LockedPageManager

### PR DESCRIPTION
**Pull request by crowning-**
References: 
- https://dashtalk.org/threads/v12-testing-thread.5484/page-48#post-58668
- https://github.com/dashpay/dash/pull/395

Bitcoin solution: 
- https://github.com/bitcoin/bitcoin/pull/6144

### CODE REVIEW

**Comment by UdjinM6** [comment]
I would prefer ```git cherry-pick 881027a``` instead of creating yet another commit from scratch to have a nice history :)
smth like that https://github.com/UdjinM6/dash/commit/05b31b7110651373c53051c9cb79d95bc7243aaf

**Comment by crowning-** [comment]
Didn't know the cherry-pick option...I'll try that.

**Comment by UdjinM6** [comment]
@crowning- add bitcoin as a remote,  fetch it and then cherry-pick

**Comment by crowning-** [comment]
I already tried that:
```
git remote add upstream https://github.com/bitcoin/bitcoin.git
fatal: remote upstream already exists.
```
No, I've never added it before...
Anyway, a direct
```
git fetch https://github.com/bitcoin/bitcoin.git
```
did the job.

The commit looks a bit odd now because no file was changed, but I guess we can live with that.

**Comment by UdjinM6** [comment]
errr... I thought of replacing you commit with cherry-pick, not adding it to yours actually
smth like this (using ```stash``` is optional - it should save your current work if you have smth uncommitted):
```
git stash
git reset --hard HEAD^
git cherry-pick 881027a
git push crowning- HEAD -f
git stash apply
```
since now you now have 2 commits already:
```git reset --hard HEAD^``` should actually be done twice or replaced with ```git reset --hard HEAD~2```

**Pull request closed without merging**
