### PR TITLE
backport: Merge bitcoin#21902, 22187, 21795, 22902,(followup) 19940, 22121, 21353, 21936

### PR DESCRIPTION
**Pull request by vijaydasmp**
backport: Merge bitcoin#21902, 22187, 21795, 22902,(followup) 19940, 22121, 21353, 21936

### CODE REVIEW

**Review by UdjinM6 — DISMISSED** [review]
LGTM, utACK

**Review by UdjinM6 — DISMISSED** [review]
utACK

**Comment by PastaPastaPasta** [comment]
Please do not have an empty pull request description.

**Review by PastaPastaPasta — APPROVED** [review]
utACK 2b2a78e72bd05917bf2b4b2ab69949b69b519309, rebase looks good.

**Review by UdjinM6 — APPROVED** [review]
re-utACK

**Comment by vijaydasmp** [comment]
Hi @PastaPastaPasta , req

**Review by knst — APPROVED** [review]
utACK

**Pull request merged**
