### PR TITLE
thread safe rand

### PR DESCRIPTION
**Pull request by UdjinM6**
This reuses idea/code for `InsecureRand` class from a non-merged PR by @tgflynn.

### CODE REVIEW

**Comment by tgflynn** [comment]
I think the best way to fix insecure_rand would be for each thread to have its own InsecureRand object.  That requires using thread local storage, which is platform dependent.  I think boost provides an interface for tls but I'm not sure there are any examples of its use in the current dash code.

The only other way I see to fix it is to protect it with a mutex, but that might be quite inefficient.

**Comment by UdjinM6** [comment]
I think creating InsecureRand object for each thread is an overkill. Reading random bytes once in a while should provide enough randomness with low performance impact, for loops this is done outside + actual use of math inside of it which again should not hurt.

**Comment by tgflynn** [comment]
My problem with this PR is that your new implementation of GetInsecureRand is calling the slow secure RNG on each call.

The changes to masternode.cpp and wallet.cpp, which do not use GetInsecureRand, look fine.

However I'm not sure about the effect of using the slower method in darksend.cpp.

Also are there other places this function is used ?

**Comment by UdjinM6** [comment]
Well, "slow" is kind of relative - it's still quite fast if you don't run it like thousands times in a row and for such cases I moved that out of the loop. Remember when we did our last optimization for shuffling? That was 10ms vs 2 ms for a loop over thousands items iirc, so I think calling it just a few times in a row should be perfectly fine.

**Comment by tgflynn** [comment]
OK, but then why not just use the GetRand or GetRandInt functions which already exist and do essentially the same thing ?

**Comment by UdjinM6** [comment]
Hmm... they don't quite do the same thing but, I agree, should be comparable in terms of performance. So, you mean that we should get rid of GetInsecureRand completely and replace all its calls (besides loops and shuffling) back to GetRandInt simply to avoid any possible confusion? Well, this makes sense imo, will do.

**Comment by tgflynn** [comment]
Yes, that would seem to make sense, while keeping InsecureRand for the places you use it explicitly.

**Pull request merged**
