### PR TITLE
feat: drop hard-coded restrictions for platform-user

### PR DESCRIPTION
**Pull request by knst**
## What was done?
Hard-coded restrictions for platform-user are superseeded by whitelist feature.
Splits from https://github.com/dashpay/dash/pull/6100

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
It deprecates old command line argument `-platform-user` and special hard-coded logic related to `platform-user`

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — DISMISSED** [review]
utACK 765294ce10e0bb83de94124e96ca0c65724303fd

**Review by UdjinM6 — APPROVED** [review]
utACK fcf143ecbdc3ad65bfb9bcf517362118606a1924

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
NACK for v21.1; while I find it incredibly unlikely anyone is using this, it is a public API and this would be a breaking change... As such, we should likely do a 2 cycle, deprecation followed by removal. In practice, I think taking into consideration the unlikely-ness that anyone is using this, and the fact that we can instead tell them to use rpcwhitelist to replicate functionality, I think it'll be okay to drop in v22. But not before then, also needs release notes :)

**Comment by knst** [comment]
Closed in favor of https://github.com/dashpay/dash/pull/6209 for v22.
To re-open for v23!

**Pull request closed without merging**
