### PR TITLE
Remove FEEFILTER code

### PR DESCRIPTION
**Pull request by codablock**
Until we clarify if https://jasonc.me/blog/bitcoin-bip-133-double-spends-bch
is really a problem for us.

### CODE REVIEW

**Comment by codablock** [comment]
As discussed in Slack, it would be better to completely remove the FEEFILTER code. I'll do this now and rename the PR accordingly.

**Comment by codablock** [comment]
Updated the PR to completely remove the FEEFILTER code

**Comment by codablock** [comment]
@UdjinM6 Sorry, missed these 2. Fixed and force pushed :)

**Comment by UdjinM6** [comment]
Needs rebase

**Comment by gladcow** [comment]
utACK

**Comment by UdjinM6** [comment]
This one was caused by cmctblock merge, so was a trivial one. Fixed via github GUI.

**Pull request merged**
