### PR TITLE
llmq:: Return const reference in GetLLMQParams() and move it out of CLLMQUtils

### PR DESCRIPTION
**Pull request by xdustinface**

### CODE REVIEW

**Review by UdjinM6 — DISMISSED** [review]
utACK

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
NACK df567cc0b97b37dd32276d222aa44f4e8a7c5469 

GetLLMQParams imo is more descriptive and better name imo

**Comment by xdustinface** [comment]
Its so redundant.. `llmq::CLLMQUtils::GetLLMQParams` contains 3x LLMQ. Don't you think `llmq::CLLMQUtils::GetParams` is still descriptive enough due to namespace wrapping class (2x LLMQ)? Actually now that i think more about it, i would probably prefer to make it even shorter and move it out of `CLLMQUtils` so thats it's only `llmq::GetParams`.

**Comment by PastaPastaPasta** [comment]
I'd be fine moving it out of CLLMQUtils, but GetParams makes it sound like it'll return a `CChainParams` object, instead of a `Consensus::LLMQParams` object which ofc isn't the case

**Comment by xdustinface** [comment]
> I'd be fine moving it out of CLLMQUtils, but GetParams makes it sound like it'll return a `CChainParams` object, instead of a `Consensus::LLMQParams` object which ofc isn't the case

I don't know.. i agree, if you look only at the method name it would not be obvious what kind of params you will get in return. But there is still the namespace and i (personally) don't feel like there is any risk for confusion  with `llmq::` prefix and surrounding context. Actually, at the end it doesn't matter a lot and im fine either way 🙈 buuut i just like the shorter a bit more.. sooo it seems like we are in a deadlock now and @UdjinM6 needs to fix it haha.. do you just want to pick one? 😄 I assume you will be also fine with moving it out of `CLLMQUtils`?

```
llmq::GetParams()
llmq::GetLLMQParams()
```

**Comment by xdustinface** [comment]
Hmm okay i just realised that it is indeed not very obvious if you are using it inside the `llmq` namespace where the prefix isn't even required! Sooo i guess then it should be one of where i now would vote for the shorter again rather.. 😄

```
llmq::CLLMQUtils::GetParams()
llmq::GetLLMQParams()
```

**Comment by UdjinM6** [comment]
I think `llmq::GetLLMQParams()` should be fine

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
