### PR TITLE
Fix Hot Masternode

### PR DESCRIPTION
**Pull request by thelazier**
Revert to use same value as master branch.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Hmm.. I'm not sure what this fixes and why https://github.com/dashpay/dash/blob/v0.12.0.x/src/activemasternode.cpp#L81

**Comment by schinzelh** [comment]
Thats strange, in master this is set to true:

https://github.com/dashpay/dash/blob/master/src/activemasternode.cpp#L81

In the end it prevents masternodes to be started locally

**Comment by UdjinM6** [comment]
yes, in master it's `true` but https://github.com/dashpay/dash/pull/706

**Comment by UdjinM6** [comment]
Ahh... I see now. So for local MN start it's an exceptional case which is the opposite to the natural way it was designed... hmm.. ok, let's make that change but we need to remove `pnode->Release();` at line 93 too then.

**Comment by thelazier** [comment]
if pnode-release() need to remove, should we revert the pnode line as well? so it will be back to master branch version.

**Comment by UdjinM6** [comment]
Yes, I think that makes sense.

**Comment by UdjinM6** [comment]
ACK 56adee2

**Comment by UdjinM6** [comment]
On another note - I think we should make hot masternodes redundant one day and clean up the code. But for now - it's ok.

**Comment by schinzelh** [comment]
Maybe we should deprecate hot nodes anyway, as it is nuts to have $7000 online 24/7

**Pull request merged**
