### PR TITLE
[WIP] Backport multiwallet functionality

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
To Backport:

1. https://github.com/bitcoin/bitcoin/pull/8775 (Done)
2. https://github.com/bitcoin/bitcoin/pull/8776 (Done)
3. https://github.com/bitcoin/bitcoin/pull/8774 (Done)
4. https://github.com/bitcoin/bitcoin/pull/8694
and more https://github.com/bitcoin/bitcoin/projects/2#card-205279

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Above commits backport https://github.com/bitcoin/bitcoin/pull/8775

**Comment by PastaPastaPasta** [comment]
Above commits backport bitcoin#8775

**Comment by PastaPastaPasta** [comment]
backports https://github.com/bitcoin/bitcoin/pull/8774

**Comment by PastaPastaPasta** [comment]
Closing in favor of just doing backports in order etc

**Comment by adneerav** [comment]
Hello @luke-jr ,

Is there any way where we can increase the number of wallets to be in loaded state at same time.As rightnow its like if I load wallet more than 100 or 150 daemon is getting crashed/stopped. I am trying to load/unload wallet dynamically using RPC.

What i tried is incraesing the `set_lk_max_lockers` to 400000 and also added 
`set_lg_regionmax 1048576` But still same things I am facing. 

Reflink for above setup : https://docs.oracle.com/cd/E17276_01/html/api_reference/C/set_lk_max_lockers_parameter.html
https://bitcoin.stackexchange.com/a/70737

So is there any way or configuration or any changes which can increase and allow more number of wallets to be loaded ?

**Comment by nmarley** [comment]
Hey @adneerav , it appears that your comment may have been intended for the Bitcoin repo (since luke-jr is more of a contributor there rather than for Dash). If you have a feature request for Dash, please create a new issue rather than posting to this one which is for something else.

Thanks!

**Pull request closed without merging**
