### PR TITLE
remove unused pindex from IsValidLocally, fix cs_main in rpc

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by tgflynn** [comment]
nACK

You can remove the argument but not the lock, because of this:

https://github.com/dashpay/dash/blob/v0.12.1.x/src/governance-object.cpp#L570

**Comment by UdjinM6** [comment]
Ah, true, missed it...

**Comment by UdjinM6** [comment]
I guess I still can remove few of them though, reopening...

**Comment by tgflynn** [comment]
utACK

**Pull request merged**
