### PR TITLE
backport: Merge bitcoin#20468, 20568, 20606

### PR DESCRIPTION
**Pull request by vijaydasmp**

### CODE REVIEW

**Comment by vijaydasmp** [comment]
Hello @UdjinM6 , please review

**Review by knst — CHANGES_REQUESTED** [review]
NACK: bitcoin#20830 should be done only after bitcoin#18267 backported.
We don't have "signet" now.

**Comment by vijaydasmp** [comment]
> NACK: [bitcoin#20830](https://github.com/bitcoin/bitcoin/pull/20830) should be done only after [bitcoin#18267](https://github.com/bitcoin/bitcoin/pull/18267) backported. We don't have "signet" now.

Backporting  [bitcoin#18267](https://github.com/bitcoin/bitcoin/pull/18267)

**Comment by vijaydasmp** [comment]
> NACK: [bitcoin#20830](https://github.com/bitcoin/bitcoin/pull/20830) should be done only after [bitcoin#18267](https://github.com/bitcoin/bitcoin/pull/18267) backported. We don't have "signet" now.

dropped [bitcoin#20830](https://github.com/bitcoin/bitcoin/pull/20830) for now

**Comment by vijaydasmp** [comment]
Hello @knst   please review

**Comment by knst** [comment]
why 20568 is partial? I don't see any missing changes... 

otherwise LGTM

**Comment by vijaydasmp** [comment]
> why 20568 is partial? I don't see any missing changes...
> 
> otherwise LGTM

agree, removed partial

**Review by knst — APPROVED** [review]
LGTM

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
