### PR TITLE
chore: bump `dashbls` subtree to 1.3.0

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented
bump `dashbls` subtree to 1.3.0

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Review by knst — APPROVED** [review]
utACK

I tried to bump `dashbls` myself from `main` - got same diff as in this PR.

**Review by kittywhiskers — APPROVED** [review]
utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Review by ogabrielides — APPROVED** [review]
utACK

**Pull request merged**
