### PR TITLE
Change copyright from 2015 to 2016

### PR DESCRIPTION
**Pull request by crowning-**
If everyone used COPYRIGHT_YEAR we should be done with that.

### CODE REVIEW

**Comment by jonathancross** [comment]
FYI: All errors seem to be relates to SSL, so they are caused by an unrelated change made to the codebase / dependencies.

**Comment by crowning-** [comment]
@jonathancross thanks :thumbsup:

I actually wanted to fix the Travis builds last weekend (there are some more issues to fix, we're using Travis for just 2 weeks, so it's all new and the errors are not related to recent commits) but got sick and have to go through my backlog first...

**Comment by UdjinM6** [comment]
need to change configure.ac too

**Comment by schinzelh** [comment]
I am still in the process of fixing the unit tests, so please ignore Travis output for the moment

**Comment by crowning-** [comment]
@UdjinM6 : Done.

**Comment by UdjinM6** [comment]
Should work nicely now but... how about squashing 3 commits into 1 to keep history a bit cleaner? :wink:

**Comment by crowning-** [comment]
Squashed to 1 commit

**Comment by UdjinM6** [comment]
:+1:

**Comment by jonathancross** [comment]
Cheers @crowning- Hope you get the Travis errors worked out.  :-)

**Comment by schinzelh** [comment]
@jonathancross Travis is doing fine now :-)

https://travis-ci.org/dashpay/dash/builds/105901646

**Comment by jonathancross** [comment]
@schinzelh Good to know, cheers!

**Pull request merged**
