### PR TITLE
Implement bip69

### PR DESCRIPTION
**Pull request by UdjinM6**
BIP69 https://github.com/kristovatlas/bips/blob/master/bip-0069.mediawiki

### CODE REVIEW

**Comment by crowning-** [comment]
@kristovatlas said:
> For example, if an attacker can patch a victim’s HD wallet client to order inputs 
> and outputs based on the bits of a master private key

Dunno if that's Kristov's idea, but it's brilliant :thumbsup:

BTW, @UdjinM6 , where can I add those tags to my pull-requests?

**Comment by UdjinM6** [comment]
@crowning- screen shot 2015-08-22 at 2 59 45

**Comment by crowning-** [comment]
@UdjinM6 : not for me, seems to be a repository-permission feature:
tags

**Comment by kristovatlas** [comment]
> Dunno if that's Kristov's idea, but it's brilliant :thumbsup:

IIRC credit for this observation goes to @SergioDemianLerner

**Pull request closed without merging**
