### PR TITLE
Fix Qt UI High DPI scaling

### LINKED ISSUE #2959: UI scale problem on HiDPI monitor
UI unuseable on 4k monitor. some element got scaled 2x, some don't.

### PR DESCRIPTION
**Pull request by akshaynexus**
closes #2959

### CODE REVIEW

**Comment by akshaynexus** [comment]
After looking at the suggestion on the original issue,maybe I'll need to adjust the css to use pt instead of px aswell to get the scaling working .

**Comment by akshaynexus** [comment]
Closing pr for now,since the css needs to be changed for it to be scalable.Will reopen once its done

**Comment by nmarley** [comment]
Have you checked if this is an issue after https://github.com/dashpay/dash/pull/3217 was merged?

**Comment by akshaynexus** [comment]
Nope,thanks for that info,was trying to see why my change didn't do much.Will look into that pr

**Pull request closed without merging**
