### PR TITLE
Add Qt GUI refresh w/branding updates

### PR DESCRIPTION
**Pull request by nmarley**
Align Qt wallet better with new style guidelines and consistent branding

Removes old non-default themes due to brittle design (they don't play well with new redesign)

Remove small 3 buttons underneath PS button
- The try and reset buttons are not necessary
- The PS info modal is still available via the help menu

This is an alternative to #2204

Please see individual commits for more granular info on changes.

### CODE REVIEW

**Comment by UdjinM6** [comment]
`+68 −7,547` - nice :)

**Comment by UdjinM6** [comment]
Few notes:
- should run `contrib/devtools/optimize-pngs.py` to shrink new images a bit (`Total reduction: 98903 bytes`);
- should drop `images/light/about.png` because it's no longer used after f924607;
- would prefer the old "remove.png" icon (the one used in Console tab, the new one looks weird there imo).

All these changes in one commit https://github.com/UdjinM6/dash/commit/ad784aa4dcb1ca7468ce7c87d5f09fa43c756287

Could also adjust `masternodes.png` icon to match new style while at it I guess.

**Comment by nmarley** [comment]
Added your commit, thanks @UdjinM6 . I've reached out to Suba to help w/the MN icon, and he said he found some more that he missed, so will wait for a patch from him (should be pretty quick).

**Comment by PastaPastaPasta** [comment]
General overview below as of https://github.com/dashpay/dash/pull/3000/commits/33d0fee13777f667135ac51afcab2908a1a07b7d

sync page
Overview
send page
receive page
request payment

**Comment by codablock** [comment]
Screens from Light-HiRes theme on a HiDPI monitor.

Please note that in all screens multiple of the bottom right icons are missing:
image

Text very often overlaps or wraps strangely.  Table columns are too small very often, but I assume this is not in the scope of this PR.

image
Selection_020
Selection_021
Selection_022

**Comment by nmarley** [comment]
Rebased onto latest develop and force-pushed newest changes.

**Comment by nmarley** [comment]
I've rebased this after splitting out the extra themes removal and re-grouped into new commits (the old commit history was kind of a mess).

Should be ready for review and testing now.

**Comment by codablock** [comment]
- 8ed6afc99f9c82be56fa3e57e27b6c52684efb53 I can't see what's changed/updated here
- ea3d6f5d9a2bd400b7fd47046714f8ff21e85721 Most icons are without transparancy now
- src/qt/res/icons/address-book.png
  This seems to be the wrong icon (doesn't look like an address book) and also is missing transparancy
- src/qt/res/icons/tx_inout.png, tx_input.png, tx_output.png
  I liked the older ones much better. With the new ones it's less clear what they mean. Left and right is easier associated with incoming/outgoing while up/down gives some room for more interpretations (balance gone up?).
  Also, the in+out icon has much smaller arrows then the individual ones, which is strange

**Comment by UdjinM6** [comment]
Why 2df07ff? It's not needed imo (splash image colors are adjusted automagically).

**Comment by nmarley** [comment]
@UdjinM6 re: https://github.com/dashpay/dash/commit/2df07ff7d30664e0f18ad2dfbeb85ec602ef6245, I didn't know why it was removed in 3141 so assumed it should not have been.

@iamsuba Can you help answer these questions about icons that @codablock asked above?

**Comment by iamsuba** [comment]
@codablock  @nmarley 

> Most icons are without transparancy now
 **Yes, they are. There was a reason I went with non-transparent icons. I don't remember exactly why. I will try doing transparent icons and see the issues.**

> src/qt/res/icons/address-book.png
> This seems to be the wrong icon (doesn't look like an address book) and also is missing transparancy
**I will update to a new icon.**

> src/qt/res/icons/tx_inout.png, tx_input.png, tx_output.png
> I liked the older ones much better. With the new ones it's less clear what they mean. Left and right is easier associated with incoming/outgoing while up/down gives some room for more interpretations (balance gone up?).
**The icons where done this way to make is consistent with the dishpan and native wallet redesign icons, where we are using simple up and down arrows.**

> Also, the in+out icon has much smaller arrows then the individual ones, which is strange
**The sizes are different because, the same icons are used in the transaction history pages. these sizes make it look good on transaction history pages but not in homepage. I guess we could resize the icons to be smaller.**

**Comment by nmarley** [comment]
Transparency has been fixed in icons now, directions fixed and sizes should be correct.

@UdjinM6 I reverted the testnet splash screen commit

@codablock As for your question about https://github.com/dashpay/dash/commit/8ed6afc99f9c82be56fa3e57e27b6c52684efb53, I _believe_ this is where UdjinM6 ran the optimize images script, but I can't say for sure. I picked this from an old commit of his as the base for this work. But that's what it looks like since the file size is reduced for all these.

**Comment by UdjinM6** [comment]
Ah, yes, we must run new images through `mogrify` (to fix nasty error messages) and `optimize-pngs.py` (to reduce image size). The later has to be fixed first though https://github.com/UdjinM6/dash/commit/d8f6ed7d793476c661a6db9f9497a5470df4f54b, we missed it in #3141 🙈 Changes for this PR would be https://github.com/UdjinM6/dash/commit/301121f475b4eb91febe57c0b6deca463c14210f and https://github.com/UdjinM6/dash/commit/5d927284dc63ac1083276ce1565e20d301ae4bd1 accordingly.

I'm still not happy with the new "remove" icon tbh https://github.com/dashpay/dash/pull/3000#issuecomment-505168279. I tried to make the icon in Console tab a bit larger https://github.com/UdjinM6/dash/commit/1e283140109c97bafd4f91fca2b0462392923fcd and it's a bit better that way IMO but it's still weird. I would probably copy the old one into some new file and use it in Console instead. Or maybe we could use a more general delete/remove icon like a trashcan or smth that would fit in both places instead?

**Comment by nmarley** [comment]
@UdjinM6 Cherry-picked your changes except for the last one, I didn't see where this remove.png was showing up on the debug console 'til now. I agree the old one looks better there, restored the old remove icon as `console_remove.png`.

**Comment by jhodges10** [comment]
@codablock need me to test hires? I've got 4k screens.

**Pull request merged**
