### PR TITLE
Allow compilation with `--disable-wallet`

### LINKED ISSUE #1732: `--disable-wallet` has no effect
Hi there,

I'm trying to build dash from source. I don't need wallet functionality, only `dashd` with RPC access.

I'm getting this when trying to build with `./configure --disable--wallet` and 0.12.2.1:

```
In file included from ./wallet/walletdb.h:10:0,
                 from wallet/wallet.h:20,
                 from activemasternode.h:10,
                 from init.cpp:48:
./wallet/db.h:21:20: fatal error: db_cxx.h: No such file or directory
compilation terminated.
Makefile:5657: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/dash-build/dash-0.12.2.1/src'
Makefile:9434: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/dash-build/dash-0.12.2.1/src'
make: *** [all-recursive] Error 1
Makefile:656: recipe for target 'all-recursive' failed
ERROR: Service 'dash' failed to build: The command '/bin/sh -c make -j$(nproc)' returned a non-zero code: 2
```

It seems like dash is still looking for libdb4.8++. Is this expected behavior? Are you guys able to reproduce?

### PR DESCRIPTION
**Pull request by UdjinM6**
Should fix #1732, please test.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Thanks! Wasn't failing on my mac but I was able to reproduce this on Ubuntu... Should be fixed by 2b4ade7 , pls try again

**Comment by gladcow** [comment]
ACK. I've compiled it,  have started dashd and have posted several rpc calls,  all is working now (Ubuntu 17)

**Comment by UdjinM6** [comment]
Rebased to fix merge conflict in `rpc/mining.cpp` (few `include`s were overlapping)

**Comment by gladcow** [comment]
ACK

**Comment by UdjinM6** [comment]
I figured out that we can also (finally) re-enable Travis build with no wallet which was disabled for almost 2 years now 🙈 Trying to do so revealed more references that had to be fixed which in their turn required quite a few other files to be fixed too. Organized these changes in 2 new commits, groped by the initially fixed reference. 3rd commit is simply removing `#` and re-enabling an additional build this way. As a result we should see 1 more job in Travis now and (hopefully) all of them should be ✅. Pls review (again) and build/test locally as well.

**Comment by gladcow** [comment]
ACK, have builded it locally, synced with net, call several rpc methods, wallet rpc calls are not available,  other calls works correctly, GUI client hasn't wallet-related tabs,  all is correct.

**Comment by thelazier** [comment]
ACK, have builded it locally, running as masternode on testnet , working fine.

**Pull request merged**
