### PR TITLE
Open "Peers list" page when clicking on connections icon in status bar

### PR DESCRIPTION
**Pull request by crowning-**
I always wondered why the Bitcoin wallet does NOT offer this obvious action for that little connection icon down in the status bar...

### CODE REVIEW

**Comment by crowning-** [comment]
Sorry for the commit spam at the end, I moved bitcoingui.cpp to the wrong folder :-/

**Comment by UdjinM6** [comment]
Button works for me but tooltip background is transparent now and looks weird imo
screen shot 2015-05-19 at 2 06 52

**Comment by crowning-** [comment]
Seems to be an OSX thing (again), Linux looks 'normal'.
tooltip

I'll check and report back when the OSX-build is fixed.

**Comment by crowning-** [comment]
Hi @UdjinM6 ,
right now I can't build OSX binaries, so could you please test if my latest commit (https://github.com/crowning-/dash/commit/34a205b9a6362b13f247f10a48e047427fd409a7) fixes the problem?

**Comment by UdjinM6** [comment]
screen shot 2015-05-20 at 20 34 34
on mac os it's yellow...... :)
I found another fix (I hope), give me a sec

**Comment by crowning-** [comment]
Longest sec ever :-)  ...in the meantime I found out that the OSX tooltips are "lightgoldenrodyellow" and installed the build-environment for the native OSX wallet so I don't have to rely on Gitian which half of the time fails...much faster this way :-)

**Comment by crowning-** [comment]
I built it on both OSX and Linux and it looks fine :thumbsup:

Ready to merge :-)

**Pull request merged**
