### PR TITLE
Backport More P2P

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
this builds on #3414 and will be rebased once that is merged. This is a number of PRs which prepare us for a couple of critical backports, namely the v2 message protocol once that comes out as well as the separation between wallet and node code in #10244

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
I am unable to reproduce these test failures locally

**Comment by UdjinM6** [comment]
There is a merge conflict because of https://github.com/dashpay/dash/pull/3450/commits/d23536453400b07ad8fd8d54024b6b1a6ee9b73d - that this https://github.com/dashpay/dash/pull/3415/commits/29eada80a70b01921c7260bc01745262e3fdbf26#diff-6becc62f79dca411ca82cc6c57b76030R77 (in 14733) should be bumped to `3` while doing so to make tests pass. Moreover it looks like 14024 (which 14733 relies on too btw) requires _at least_ 13022, probably more. Depending on how many more PRs need to be backported I guess it might be a good idea to just drop these two and backport them later with other required PRs in correct order.

**Comment by PastaPastaPasta** [comment]
I'm gonna delay this until 0.16 is branched.

**Comment by PastaPastaPasta** [comment]
Just so I don't forget, when I force-pushed two days ago, dropped14024 and 14733.

**Comment by PastaPastaPasta** [comment]
rebased on develop

**Comment by PastaPastaPasta** [comment]
test failure likely unrelated

**Pull request merged**
