### PR TITLE
merge bitcoin#16240...21526: assumeutxo project backports (part 2)

### PR DESCRIPTION
**Pull request by kittywhiskers**
## Additional Notes

* Depends on https://github.com/dashpay/dash/pull/4704

### CODE REVIEW

**Comment by UdjinM6** [comment]
19204 is partial, right? + pls see 1decd2f3bc2ffb62d12652b21494686bd7627fb6 and a08afba9ab8748eacedf3c9a0c1b916bed5a36b2

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Comment by UdjinM6** [comment]
ping @PastaPastaPasta

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

**Pull request merged**
