### PR TITLE
Backports 0.16 pr1-2: almost trivial

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Comment by UdjinM6** [comment]
Looks good imo 👍Ideally, we should apply similar fixes to Dash-specific code too but I'm not sure if we should do it here or in some follow-up PR instead - `throw() -> noexcept` would be a trivial/compact find-and-replace fix for example, `const` - no so much.

**Comment by codablock** [comment]
We should at least do the `throw() -> noexcept` as part of this PR. The const thing is not that important IMHO.

**Comment by codablock** [comment]
BTW, test failures are all unrelated to this PR. I'll create a PR to fix them.

**Comment by PastaPastaPasta** [comment]
added throw() -> noexcept

**Comment by PastaPastaPasta** [comment]
also rebased on develop

**Comment by PastaPastaPasta** [comment]
squashed https://github.com/dashpay/dash/pull/3262/commits/2983a5f2f0dfeed41c53d9009641ae9463874f52 into 10965

**Pull request merged**
