### PR TITLE
backport: bitcoin#21373, #21377, #21681, #21714, #21749, #21792, #21814, #21874, #21884, bitcoin-core/gui#284

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Regular batch of backports from bitcoin v22

## What was done?
Implemented new commandline argument `-bip147height` for RegTest.
Backports:

 - bitcoin/bitcoin#21377
 - bitcoin/bitcoin#21792
 - bitcoin-core/gui#284
 - bitcoin/bitcoin#21714
 - bitcoin/bitcoin#21373
 - bitcoin/bitcoin#21814
 - bitcoin/bitcoin#21681
 - bitcoin/bitcoin#21874
 - bitcoin/bitcoin#21884
 - bitcoin/bitcoin#21749

## How Has This Been Tested?
Run unit/functional tests

## Breaking Changes
n/a

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]

**Review by UdjinM6 — APPROVED** [review]
utACK

**Comment by knst** [comment]
> p2p_timeouts.py                                     | ✖ Failed  | 13 s

restarted - p2p_timeouts.py fails intermittently

**Comment by UdjinM6** [comment]
Looks good but needs another rebase to fix tests

**Review by PastaPastaPasta — APPROVED** [review]
utACK 7cc77f3a30cd79fec39f9340d3fea0333500beca

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
