### PR TITLE
depends: Add sodium to depends

### LINKED ISSUE #4168: Build Error on Ubuntu 20.04 With Release 0.17.0.2
I cloned the repo and was able to build the depends directory successfully. 

I then cd .. to the dash directory and ran ./autogen.sh and ./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu --with-incompatible-bdb

I get to this point and receive the following error:

  CXXLD    libdashconsensus.la
/usr/bin/ld: /home/alt/dash/depends/x86_64-pc-linux-gnu/share/../lib/libbls-dash.a(libsodium_la-randombytes.o): relocation R_X86_64_PC32 against symbol `randombytes_sysrandom_implementation' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status

### PR DESCRIPTION
**Pull request by UdjinM6**
~Should probably~ fix #4168

### CODE REVIEW

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Comment by UdjinM6** [comment]
Closing in fav of #4176

**Comment by zikarad** [comment]
Could hash of libsodium-1.0.18-stable.tar.gz be reviewed?
I can see this sha256sum:
32be348b1b7f5dd7bb890f2c867351ece5d478a3e7d2d324cbfd4aa261e71317  libsodium-1.0.18-stable.tar.gz
instead of
~~3c240fcd414189492d7c7dc12d2cf48f67bf04142ce2f60b620adb5bac6ca732~~

**Comment by UdjinM6** [comment]
> libsodium-x.y.z-stable.tar.gz is the source code of x.y.z with bug fixes, security fixes and minor improvements immediately backported from the next version being currently in development. These additions over the point release are guaranteed to never change the behavior or API. Version x.y.z-stable is always fully compatible with version x.y.z. New features or breaking changes will never be introduced in a stable set of changes. libsodium-x.y.z-stable.tar.gz is an automated daily copy of the stable branch in the Git repository.

https://download.libsodium.org/libsodium/releases/README.html

Another reason why #4176 is a better solution :)

**Pull request closed without merging**
