### PR TITLE
Removed some unneeded code in deterministicmns

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Signed-off-by: pasta <pasta@dashboost.org>

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
NACK

I thought about it when I was preparing #3722 and the thing is that dmn diff upgrade was included in v0.15 (released Feb 2020) and imo it's too early to remove this.

**Comment by PastaPastaPasta** [comment]
So you think this should wait for 0.18?

**Comment by UdjinM6** [comment]
I can't say the exact version, it just feels too early to remove it (in less than 1y since the release). Let's get back to this idea mid next year or so. v0.17 might be good too if it isn't released by that time, otherwise these changes should go into v0.18+ I think.

**Comment by ogabrielides** [comment]
@PastaPastaPasta @UdjinM6 This one can be closed since the cleanup already took place in #5113

**Pull request closed without merging**
