### PR TITLE
build: remove cmake from list of packages

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
Seems as `cmake` package is not needed anymore so far as `immer` moved inside src/ directory.
`immer` is integrated to our Makefile.am and do not requires extra call of cmake as it used to be.

## What was done?
Removed cmake from list of packages and removed package `cmake.mk`

## How Has This Been Tested?
Tested build with HEAD - succeed.
After that reverted to the old revision that have `immer` package (85d6cadbfad77844a393e4db3dc71ed6a5234c8b).
Failed as expected:
```
make: *** No rule to make target 'cmake', needed by '/home/knst/projects/dash/depends/built/x86_64-pc-linux-gnu/bls-dash/bls-dash-1.2.0-6213882c069.tar.gz'.  Stop.
```

## Breaking Changes
No breaking changes

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by kittywhiskers — DISMISSED** [review]
utACK

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see 3dd39a96c596682d96aa820f2b87f0f4c7e6663f

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
