### PR TITLE
Refactor `masternodebroadcast`

### PR DESCRIPTION
**Pull request by UdjinM6**
Refactor `masternodebroadcast` to serialize/decode/relay multiple masternodes at once as discussed in #741 

Update:
35 dummy masternodes hexified/decoded/relayed on testnet without any issues for me

### CODE REVIEW

**Comment by thelazier** [comment]
Agree that relaying own created broadcast is fine to just do relay with out check Input again.
Just in case that , Wallet owner create broadcast message and send to masternode service.
Masternode service will try to relay for customer without checking input. This will result the relay node to be ban from network if the Input is already spent while the command will show successful relay.
How about additional param to force check input before relay ?

**Comment by UdjinM6** [comment]
Masternode service? I was thinking that wallet owner send it himself just from another wallet (which is online)... though bunning yourself is not a good idea too.. maybe you were actually right and we should spend some time/cpu verifying mnbs before relaying them, shouldn't really be the big impact unless there are 100s of them I guess. Or we can add additional switch ("safe", default 0?) to rpc command to enforce additional checks on user request.

**Comment by thelazier** [comment]
Thank you for your understanding :sunglasses:

**Comment by UdjinM6** [comment]
I _tried_ to implement such switch. I grabbed the part of `ProcessMessage` for mnb and moved it to a new function `CheckMnbAndUpdateMasternodeList` (yeah, I know it's not the best name but I can't find a better one). Made few other adjustments but I don't think I broke smth... And still, results are strange - only 1/3 of my dummy masternodes appeared as pre-enabled using "safe" method.

**Comment by UdjinM6** [comment]
omg, I think I found a bug thanks to @thelazier !

I have all my dummy masternodes on one tdash address and we are not hashing vin at all! Because i was signing them _almost at the same time_ and with _the same private key_ many of them had _the same hash_ as their "neighbors" and were actually ignored by the network (which was not obvious without "safe" mode).
Same thing happens now for those who do `start-<mode>` on mainnet and have the same setup (many MNs on one dash address).

Solution: added `vin` in `GetHash()` for `CMasternodeBroadcast`.

**Comment by thelazier** [comment]
Glad I can help, :sunglasses:

**Comment by evan82** [comment]
Wow, good stuff!

**Pull request merged**
