### PR TITLE
chainlocks: Another attempt to fix deadlocks

### PR DESCRIPTION
**Pull request by UdjinM6**
```
POTENTIAL DEADLOCK DETECTED
Previous lock order was:
 cs_main  llmq/quorums_chainlocks.cpp:139
 (1) cs  llmq/quorums_chainlocks.cpp:139
 cs_vNodes  net.cpp:3662
 (2) cs_inventory  ./net.h:1085
Current lock order is:
 pnode->cs_sendProcessing  net.cpp:2854
 cs_main  net_processing.cpp:3946 (TRY)
 mempool.cs  net_processing.cpp:4183
 (2) pto->cs_inventory  net_processing.cpp:4183
 pto->cs_filter  net_processing.cpp:4233
 (1) cs  llmq/quorums_chainlocks.cpp:87
```

This deadlock was introduced in https://github.com/dashpay/dash/pull/3962, fixed in https://github.com/dashpay/dash/pull/3972 and re-indroduced in https://github.com/dashpay/dash/pull/3990/ 🙈

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
How do you check these? Can we lint for this?

**Comment by UdjinM6** [comment]
> How do you check these?

By compiling with `DEBUG_LOCKORDER` https://github.com/dashpay/dash/blob/master/doc/developer-notes.md#development-tips-and-tricks and running on testnet

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
