### PR TITLE
[Trivial] Fix indentation in test_dash.cpp

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
based on #3310

### CODE REVIEW

**Comment by codablock** [comment]
needs rebase

**Comment by PastaPastaPasta** [comment]
Due to the fact that we renamed it to test_dash any changes to test_bitcoin automatically are conflicts(this is at least what I experienced in my backporting). When I backported changes to test_bitcoin I had to do it manually.

**Comment by UdjinM6** [comment]
I tend to agree with @PastaPastaPasta on that one tbh... Indentation here won't be fixed until 0.19, plus this file should not be touched _that_ often in following backports really. IMO it's ok-ish to fix it now.

**Comment by codablock** [comment]
@PastaPastaPasta `-Xrename-threshold=20%` as git argument helps in such cases when cherry picking commits that involve files that we have internally renamed. There is also the rename from `test_bitcoin.cpp` -> `setup_common.cpp` which will happen in one of the future versions, and this one will be a candidate for many conflicts.

**Pull request closed without merging**
