### PR TITLE
refactor: implement c++23 inspired ToUnderlying

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
Avoid lots of static_cast's from enums to underlying types. Communicate intention better

## What was done?
implement c++23 inspired ToUnderlying, then see std::to_underlying and https://en.cppreference.com/w/cpp/types/underlying_type; Then, we use this instead of static_casts for enums -> underlying type

## How Has This Been Tested?
make check

## Breaking Changes
None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
I'm really confused why this build fails... Please help 🙈

**Comment by UdjinM6** [comment]
> I'm really confused why this build fails... Please help 🙈

`git add src/util/underlying.h` ;)

**Comment by PastaPastaPasta** [comment]
> > I'm really confused why this build fails... Please help 🙈
> 
> 
> 
> `git add src/util/underlying.h` ;)

Oh 🙈 I'll do that tonight 😂

**Comment by knst** [comment]
LGTM, but let's add [these](https://github.com/knst/dash/commit/7fbc8d054a258b615a7cca80fba8235ccb30fe25) also and may be [this](https://github.com/knst/dash/commit/4c9d7a78a4aed9e0ff25e6b353b39c185569cdcd)

**Comment by UdjinM6** [comment]
linter complains
```
A new circular dependency in the form of "llmq/debug -> llmq/dkgsessionhandler -> llmq/debug" appears to have been introduced.
A new circular dependency in the form of "llmq/debug -> llmq/dkgsessionhandler -> llmq/dkgsession -> llmq/debug" appears to have been introduced.
```

**Comment by knst** [comment]
utACK

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK

**Pull request merged**
