### PR TITLE
merge bitcoin#14209, #13878, #14192, #17086: logging and filesystem updates

### PR DESCRIPTION
**Pull request by kittywhiskers**
### Disclosure:

Includes patches 6f5f2e6d0e24b2f49d8198a5972edf2e40c74760, 49e69beb695cbd544c8bee972737156adbc813ff and backport #17086 (144bf39039541cf9fc61deae4489fd0c8f8ad85c) by UdjinM6

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
Build fails. Please fix

**Comment by kittywhiskers** [comment]
Build fail due to test failure, not reproducible on macOS

**Comment by PastaPastaPasta** [comment]
I am unable to reproduce these build failures locally. Build works and tests pass fully

**Review by PastaPastaPasta — DISMISSED** [review]
utACK, however we need to figure out why CI isn't happy... Unit tests are happy locally. @UdjinM6 hopefully you have an idea?

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
pls see https://github.com/UdjinM6/dash/commits/pr4199

**Comment by kittywhiskers** [comment]
Title has been updated to include Udjin's backport, thanks for figuring it out!

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK (assuming CI is going to be happy)

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
